PewterCity_Mart_hns_MapScripts::
	.byte 0

PewterCity_Mart_EventScript_Youngster::
	msgbox PewterCity_Mart_Text_Youngster, MSGBOX_NPC
	end

PewterCity_Mart_EventScript_Nerd::
	msgbox PewterCity_Mart_Text_SuperNerd, MSGBOX_NPC
	end

PewterCity_Mart_Text_Youngster:
	.string "Salut! Regarde mon LÉVIATOR!\p"
	.string "Je l'ai élevé depuis MAGICARPE.\n"
	.string "Je n'en reviens pas de sa force.$"

PewterCity_Mart_Text_SuperNerd:
	.string "Il y avait un vieil homme bizarre\n"
	.string "qui vendait des MAGICARPE.\p"
	.string "Il disait que celles du LAC\n"
	.string "COLÈRE étaient excellentes.$"

