gText_ApprenticeChallenge0::
	.string "Euh, je suis l'apprenti de {STR_VAR_1}, nº {STR_VAR_2}.\n"
	.string "Cette tension m'attire...$"

gText_ApprenticeChallenge1::
	.string "Je suis l'apprenti\n"
	.string "de {STR_VAR_1}, nº {STR_VAR_2}! Nous voilà!$"

gText_ApprenticeChallenge2::
	.string "Je suis l'apprenti nº {STR_VAR_2} de\n"
	.string "{STR_VAR_1}! Vas-y, mesure-toi à moi!$"

gText_ApprenticeChallenge3::
	.string "Euh… Je suis l'apprenti de {STR_VAR_1}, nº {STR_VAR_2}…\n"
	.string "Quelqu'un comme moi peut gagner?$"

gText_ApprenticeChallenge4::
	.string "Je suis l'apprenti de {STR_VAR_1}, nº {STR_VAR_2}!\n"
	.string "Je t'autorise à me défier!$"

gText_ApprenticeChallenge5::
	.string "Je suis terriblement occupé, mais\n"
	.string "je suis aussi l'apprenti de {STR_VAR_1}, nº {STR_VAR_2}.$"

gText_ApprenticeChallenge6::
	.string "Je suis l'apprenti de {STR_VAR_1}, nº\n"
	.string "{STR_VAR_2}. Ravi de te rencontrer!$"

gText_ApprenticeChallenge7::
	.string "Je suis l'apprenti de {STR_VAR_1},\n"
	.string "nº {STR_VAR_2}. Puis-je commencer?$"

gText_ApprenticeChallenge8::
	.string "Hii! Je suis l'apprenti de {STR_VAR_1},\n"
	.string "nº {STR_VAR_2}! Je ferai de mon mieux!$"

gText_ApprenticeChallenge9::
	.string "Yeeha! Je suis\n"
	.string "l'apprenti de {STR_VAR_1}, nº {STR_VAR_2}! En garde!$"

gText_ApprenticeChallenge10::
	.string "Je suis l'apprenti nº 1 000 de {STR_VAR_1}!\n"
	.string "Mais non, le nº {STR_VAR_2}! C'est parti!$"

gText_ApprenticeChallenge11::
	.string "Ouais, je suis l'apprenti de\n"
	.string "{STR_VAR_1}, nº {STR_VAR_2}! Que le rock commence!$"

gText_ApprenticeChallenge12::
	.string "Youpi-yaouh! Je suis ce qu'on\n"
	.string "appelle l'apprenti de {STR_VAR_1}, nº {STR_VAR_2}!$"

gText_ApprenticeChallenge13::
	.string "Kof! Je suis l'apprenti de {STR_VAR_1},\n"
	.string "nº {STR_VAR_2}. Ravi de te rencontrer! Kof!$"

gText_ApprenticeChallenge14::
	.string "C'est vraiment stressant\n"
	.string "ici… Je suis l'apprenti nº {STR_VAR_2} de {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Je suis l'apprenti de {STR_VAR_1}, nº {STR_VAR_2},\n"
	.string "et ce n'est pas un mensonge.$"

gText_ApprenticePleaseTeach0::
	.string "Tu es… {PLAYER}? Oh!\n"
	.string "Snif… Bouhou…\p"
	.string "Oh! P-pardon… Je suis si\n"
	.string "nerveux que j'en pleure…\p"
	.string "Je m'appelle {STR_VAR_1} et je\n"
	.string "t'admire beaucoup, {PLAYER}.\p"
	.string "Je… Je rêvais de te rencontrer un\n"
	.string "jour pour te parler des POKéMON.\p"
	.string "S'il te plaît, {PLAYER}!\n"
	.string "Apprends-moi tout sur les POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… Mais…\n"
	.string "Sniff… S'il\p"
	.string "te plaît! Je\n"
	.string "t'en supplie!$"

gText_ApprenticeWhichLevelMode0::
	.string "Vraiment? C'est vraiment\n"
	.string "super sympa de ta part!\p"
	.string "Oh… Je suis désolé… Ce\n"
	.string "sont des larmes de joie…\p"
	.string "Hum… J'ai une question sur\n"
	.string "la TOUR DE COMBAT.\p"
	.string "Qu'est-ce que je dois\n"
	.string "ou le niveau ouvert?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}? Ouin!!! Oh! Je\n"
	.string "suis désolé! Ce\p"
	.string "sont des larmes\n"
	.string "de joie… Je suis\l"
	.string "si heureux de te\p"
	.string "connaître! Sniff…\n"
	.string "Je te remercie!\l"
	.string "Reviens me voir!$"

gText_ApprenticePleaseTeach1::
	.string "Waouh! Tu es {PLAYER}, non?\n"
	.string "Tout le monde parle\p"
	.string "de toi! Je m'appelle\n"
	.string "{STR_VAR_1}! Et je suis un\p"
	.string "DRESSEUR! Dis, {PLAYER}… Tu\n"
	.string "pourrais m'apprendre\l"
	.string "deux ou trois trucs?$"

gText_ApprenticeRejectTeaching1::
	.string "Pourquoi? Oh, s'il te\n"
	.string "plaît! S'il te plaît!\l"
	.string "Apprends-moi des trucs!$"

gText_ApprenticeWhichLevelMode1::
	.string "Génial! Je vais commencer\p"
	.string "par une question sur la\n"
	.string "TOUR DE COMBAT. Tu crois\p"
	.string "que je devrais choisir\n"
	.string "niveau 50 ou plutôt niveau libre?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}? D'accord! Je vais\n"
	.string "choisir ça! J'espère qu'on\p"
	.string "se reverra, j'ai encore\n"
	.string "plein de trucs à apprendre!$"

gText_ApprenticePleaseTeach2::
	.string "Tu ne serais pas {PLAYER}, par\n"
	.string "hasard? Moi, c'est {STR_VAR_1}. Je veux\p"
	.string "devenir DRESSEUR, mais je ne\n"
	.string "sais pas quoi faire… Comme tu\p"
	.string "es célèbre, eh bien… Je\n"
	.string "pensais que tu pourrais\p"
	.string "{PLAYER}, peux-tu me donner un conseil?$"

gText_ApprenticeRejectTeaching2::
	.string "Mais… Je veux vraiment\p"
	.string "devenir DRESSEUR! Je suis\n"
	.string "sûr que tu ne me crois pas…\p"
	.string "Allez… Tu peux me conseiller?$"

gText_ApprenticeWhichLevelMode2::
	.string "Merci! Voici ma première\n"
	.string "question! Dans la TOUR DE\p"
	.string "COMBAT, tu peux choisir\n"
	.string "entre niveau 50 et niveau\p"
	.string "libre… Qu'est-ce que je\n"
	.string "devrais choisir, d'après toi?$"

gText_ApprenticeLevelModeThanks2::
	.string "{STR_VAR_1}? Compris! Si j'ai\n"
	.string "d'autres\p"
	.string "questions, je\n"
	.string "reviendrai te demander conseil!$"

gText_ApprenticePleaseTeach3::
	.string "Non… Je n'arrive pas à y\n"
	.string "croire. Si on m'avait dit que\p"
	.string "j'allais rencontrer {PLAYER}, je ne\n"
	.string "l'aurais pas cru! Dis, tu es {PLAYER},\p"
	.string "n'est-ce pas? Je n'arrive pas\n"
	.string "à y croire! En général, quand\p"
	.string "j'ai autant de chance, il\n"
	.string "m'arrive une catastrophe\l"
	.string "après. Qu'est-ce que ce sera,\p"
	.string "cette fois-ci!?! Mais j'oublie\n"
	.string "mes bonnes manières! Je\p"
	.string "m'appelle {STR_VAR_1}. Enchantée! Il n'y a\n"
	.string "pas grand chose à dire sur moi.\p"
	.string "Je n'ai rien d'exceptionnel… Ma\n"
	.string "vie est tellement banale que ça\p"
	.string "t'ennuierait, de toute façon…\n"
	.string "Pour une fois qu'un truc\l"
	.string "intéressant m'arrive… {PLAYER}, tu\p"
	.string "voudrais bien me donner quelques\n"
	.string "conseils? Je suis sûre que tu vas\p"
	.string "refuser, mais ça ne coûte rien de\n"
	.string "C'est mon conseil?$"

gText_ApprenticeRejectTeaching3::
	.string "Je le savais, bah… Je\p"
	.string "suppose que je ne suis\n"
	.string "pas assez intéressante\p"
	.string "pour toi… Rien ne te fera\n"
	.string "changer d'avis… N'est-ce\p"
	.string "pas? Non. Je ne peux pas\n"
	.string "abandonner comme ça! S'il\p"
	.string "te plaît, tu veux bien me\n"
	.string "donner quelques conseils?$"

gText_ApprenticeWhichLevelMode3::
	.string "Vraiment? C'est si gentil!\n"
	.string "C'est le plus beau jour de ma\l"
	.string "vie! Je suis si heureuse… J'ai\p"
	.string "une question sur la TOUR DE\n"
	.string "COMBAT… C'est tout bête, mais je\p"
	.string "n'arrive pas à choisir entre\n"
	.string "niveau 50 et niveau libre. Tu me\p"
	.string "conseilles quoi? Je comprendrais\n"
	.string "que tu ne veuilles pas répondre…$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? D'accord! Mais tu penses\n"
	.string "que j'ai mes chances? Je suis\l"
	.string "sûre que je vais perdre… Peu\p"
	.string "importe, je ferai de mon\n"
	.string "mieux. On verra bien… Je t'ai\p"
	.string "fait perdre ton temps, tu dois\n"
	.string "avoir un tas de choses à faire.$"

gText_ApprenticePleaseTeach4::
	.string "Oh! Super, {PLAYER}{KUN}! J'ai beaucoup\p"
	.string "entendu parler de toi!\n"
	.string "Quel DRESSEUR! Je\p"
	.string "m'appelle {STR_VAR_1}! Je suis ta\n"
	.string "copine, maintenant! Au fait,\p"
	.string "tu savais? Tout ce qu'on\p"
	.string "nous apprend à l'ECOLE DE\n"
	.string "DRESSEURS, ça ne sert à rien\l"
	.string "dans la ZONE DE COMBAT… Je\p"
	.string "voudrais bien que tu me donnes\n"
	.string "quelques trucs. Tu veux bien?$"

gText_ApprenticeRejectTeaching4::
	.string "Pourquoi tu ne veux pas!?! Tu es\n"
	.string "célèbre, alors tu ne veux pas\l"
	.string "t'abaisser à me parler, c'est ça?$"

gText_ApprenticeWhichLevelMode4::
	.string "Bon, j'ai quelque chose à te\n"
	.string "demander. Donne-moi ton avis.\p"
	.string "Tu sais, il y a niveau 50 et\n"
	.string "niveau libre dans la TOUR DE\p"
	.string "COMBAT. Je ne sais pas quoi\n"
	.string "pour moi, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Tu me conseilles {STR_VAR_1}?\n"
	.string "Super, merci! Comme\p"
	.string "c'est ta décision, ce\n"
	.string "sera de ta faute si je\l"
	.string "perds, {PLAYER}{KUN}! Non,\p"
	.string "sérieusement. Je te fais\n"
	.string "entièrement confiance. Salut!$"

gText_ApprenticePleaseTeach5::
	.string "Bonjour! Tu es {PLAYER}{KUN}? C'est ça?\n"
	.string "Moi, je m'appelle {STR_VAR_1}. Je suis un\l"
	.string "TRIATHLETE, mais je fais aussi\p"
	.string "des combats de POKéMON. J'aime\n"
	.string "aussi travailler, faire la\p"
	.string "sieste, prendre des cours de\n"
	.string "danse de salon… Du coup, il me\p"
	.string "reste très peu de temps pour\n"
	.string "les POKéMON. Je voudrais te\p"
	.string "proposer quelque chose! Je\p"
	.string "pense qu'on ne s'est pas\n"
	.string "rencontrés par hasard. {PLAYER}{KUN}, tu\l"
	.string "La sagesse avec moi si souvent?$"

gText_ApprenticeRejectTeaching5::
	.string "S'il te plaît! J'ai vraiment\n"
	.string "besoin de quelqu'un comme toi\l"
	.string "pour me guider et me motiver, {PLAYER}{KUN}!\p"
	.string "Sincèrement, j'ai besoin de toi!$"

gText_ApprenticeWhichLevelMode5::
	.string "Merci! Ton soutien\n"
	.string "me sera précieux! Tu\p"
	.string "connais la TOUR DE\n"
	.string "COMBAT, non? Il y a\l"
	.string "niveau 50 et niveau\p"
	.string "libre. Lequel me\n"
	.string "conviendrait le mieux?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}? C'est compris. J'irai\n"
	.string "dès que j'aurai le\p"
	.string "temps! Je vais être en\n"
	.string "retard au travail. Je me sauve!$"

gText_ApprenticePleaseTeach6::
	.string "Je n'y crois pas! Ne me dis\n"
	.string "pas que tu es {PLAYER}!?!\p"
	.string "Incroyable! Je m'appelle {STR_VAR_1}.\n"
	.string "Je suis contente de te\p"
	.string "rencontrer! {PLAYER}, tu as une\n"
	.string "force incroyable, tu sais? On\p"
	.string "ne parle plus que de toi,\p"
	.string "ici! Oh! J'ai une idée. Je\n"
	.string "vais te demander conseil, {PLAYER}! Je\l"
	.string "suis sûre que tu peux\p"
	.string "m'aider! C'est une bonne idée,\n"
	.string "non? Bon, tu me donnes un conseil?$"

gText_ApprenticeRejectTeaching6::
	.string "Tu veux te faire passer pour\n"
	.string "quelqu'un de méchant, mais je ne\l"
	.string "Tu veux dire bien, n'est-ce pas?$"

gText_ApprenticeWhichLevelMode6::
	.string "Youpi! Je savais que tu\n"
	.string "avais un cœur gros comme ça,\p"
	.string "{PLAYER}! Que vais-je bien pouvoir\n"
	.string "te demander… Ça y est, je\p"
	.string "sais! Roulement de tambour!\n"
	.string "Voici ma question. Je veux\p"
	.string "me battre dans la TOUR DE\n"
	.string "COMBAT. Que me conseilles-tu?\p"
	.string "Niveau 50 ou niveau libre?\n"
	.string "Lequel est le mieux pour moi?$"

gText_ApprenticeLevelModeThanks6::
	.string "Ah, oui? {STR_VAR_1}, tu penses?\n"
	.string "Merci, je suivrai ton\l"
	.string "conseil! Bon, c'est\p"
	.string "tout ce que j'avais à\n"
	.string "te demander, je crois.\p"
	.string "Mais on se reverra\n"
	.string "sûrement! Merci encore!$"

gText_ApprenticePleaseTeach7::
	.string "Je te prie de m'excuser…\n"
	.string "Serais-tu par hasard {PLAYER}? Je\p"
	.string "m'appelle {STR_VAR_1} et je suis\n"
	.string "enchantée de faire ta\p"
	.string "connaissance! Je suis une fan,\n"
	.string "tu sais? Ça fait très\p"
	.string "longtemps que je suis tes\p"
	.string "exploits… … … … … … … Euh…\n"
	.string "J'espère que je n'abuse pas, je ne\p"
	.string "veux pas te forcer, mais… Est-ce\n"
	.string "que je peux être ton apprentie, {PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Oh! … … … … … … … … …\p"
	.string "… … … Désolée, je\n"
	.string "n'ai pas bien entendu,\p"
	.string "tu peux répéter? S'il\n"
	.string "te plaît! Dis-moi que\p"
	.string "tu acceptes de me\n"
	.string "prendre comme apprentie!$"

gText_ApprenticeWhichLevelMode7::
	.string "Oh! Ça me fait plaisir! Je ne\p"
	.string "veux pas te faire perdre ton\n"
	.string "temps, donc je me dépêche. J'ai\p"
	.string "prévu de relever le défi de la\n"
	.string "TOUR DE COMBAT très bientôt. Mais\p"
	.string "il y a deux niveaux et je ne sais\p"
	.string "pas lequel choisir… Lequel me\n"
	.string "Niveau 50 ou Niveau ouvert?$"

gText_ApprenticeLevelModeThanks7::
	.string "Tu me conseilles {STR_VAR_1}? Très\n"
	.string "bien, tu dois avoir\p"
	.string "raison! Merci, {PLAYER}. Je\n"
	.string "savais que je pouvais\l"
	.string "compter sur toi. A bientôt!$"

gText_ApprenticePleaseTeach8::
	.string "Comment? {PLAYER}! Et tu me parles?\n"
	.string "A moi!?! Oh… Quelle chance!\l"
	.string "Moi, je m'appelle {STR_VAR_1}! Je\p"
	.string "viens de devenir DRESSEUR!\n"
	.string "Quel honneur de te parler,\p"
	.string "{PLAYER}. Si je m'attendais à ça…\n"
	.string "Et si j'en profitais pour\p"
	.string "te demander un service, {PLAYER}?\n"
	.string "Bon, j'ose… Est-ce que je\p"
	.string "peux être ton apprentie?\n"
	.string "Apprends-moi tout ce que tu sais!$"

gText_ApprenticeRejectTeaching8::
	.string "Oh… Je viens d'être\n"
	.string "rejetée par {PLAYER}… Quelle\l"
	.string "expérience! Mais je t'en\p"
	.string "prie, {PLAYER}! Dis-moi que tu\n"
	.string "acceptes, cette\p"
	.string "fois-ci! Accorde-moi ton aide!$"

gText_ApprenticeWhichLevelMode8::
	.string "Ouiiiii! {PLAYER} a dit oui! {PLAYER} a dit\n"
	.string "oui! Je ne vais pas en\p"
	.string "dormir de la nuit… Merci!\n"
	.string "Merci!!! Bon, j'ai une\p"
	.string "question à te poser! Dans la\p"
	.string "TOUR DE COMBAT, je dois plutôt\n"
	.string "choisir niveau 50 ou niveau libre?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}, d'accord! Je\n"
	.string "choisirai ça, puisque\l"
	.string "tel est ton conseil!\p"
	.string "J'espère que tu m'en\n"
	.string "donneras encore plein!$"

gText_ApprenticePleaseTeach9::
	.string "Waouh! On dirait… Tu ne\n"
	.string "serais pas… {PLAYER}{KUN}? Le célèbre\l"
	.string "DRESSEUR? On dirait que c'est\l"
	.string "mon jour de chance! Bonjour,\p"
	.string "au fait! Je m'appelle {STR_VAR_1}! Je\p"
	.string "cherchais justement quelqu'un\n"
	.string "pour tout m'enseigner sur les\p"
	.string "POKéMON. Et qui est-ce que je\n"
	.string "vois arriver? Eh bien, {PLAYER}{KUN}! C'est\p"
	.string "le destin! Tu ne peux pas\n{PLAYER}{KUN}"
	.string "Laissez-moi apprentie sous vous!$"

gText_ApprenticeRejectTeaching9::
	.string "Quoi?!? Je sais, tu es\n"
	.string "quelqu'un d'important… Tu veux\p"
	.string "te faire prier un peu… S'il te\n"
	.string "plaît, ce serait un tel honneur!$"

gText_ApprenticeWhichLevelMode9::
	.string "Oui, excellente réponse! Ça\n"
	.string "me fait sacrément plaisir! Si\p"
	.string "on commençait par un conseil\n"
	.string "sur la TOUR DE COMBAT?\p"
	.string "Qu'est-ce que tu me\n"
	.string "Niveau 50 ou Niveau ouvert?$"

gText_ApprenticeLevelModeThanks9::
	.string "Oh, {STR_VAR_1}! Je prends! Je\n"
	.string "vais faire des\l"
	.string "progrès avec toi!\p"
	.string "Tu seras mon mentor,\n"
	.string "OK? Hasta la vista!$"

gText_ApprenticePleaseTeach10::
	.string "Tu es, {PLAYER}{KUN}, non? La police te\n"
	.string "cherche partout! … … …\p"
	.string "Mais non, je rigole! Je\n"
	.string "m'appelle {STR_VAR_1}. Je suis le\p"
	.string "MAÎTRE POKéMON. Je suis\n"
	.string "ici incognito… Mais non, je\l"
	.string "rigole! Je suis plus doué\p"
	.string "pour les blagues que pour\n"
	.string "les combats… Tu voudrais\p"
	.string "être le professeur d'un\n"
	.string "petit boute-en-train comme moi?$"

gText_ApprenticeRejectTeaching10::
	.string "Tu ne veux pas? Oh, tout le monde\n"
	.string "me rejette, c'est l'histoire de\p"
	.string "ma vie… Je fais des blagues pour\n"
	.string "masquer ma tristesse, mais… je\p"
	.string "suis très seul… Ha, ha, ha, je\p"
	.string "rigole!!! Bon, vas-y! Sois mon\n"
	.string "Mon maître POKéMON?$"

gText_ApprenticeWhichLevelMode10::
	.string "Youpi! Pour te remercier, je\n"
	.string "vais t'offrir un bateau!\p"
	.string "Bien sûr, je rigole! Je te\n"
	.string "remercie, en tout cas… Tu\p"
	.string "sais, il y a niveau 50 et\n"
	.string "niveau libre dans la TOUR DE\p"
	.string "COMBAT. Entre les deux, mon\n"
	.string "cœur balance… Lequel tu me\p"
	.string "Pouvez-vous me décider, maître?$"

gText_ApprenticeLevelModeThanks10::
	.string "{STR_VAR_1}? Merci, je vais choisir\n"
	.string "l'autre, alors! Mais non,\p"
	.string "je rigole… Je vais suivre\n"
	.string "ton conseil! Merci!\p"
	.string "J'espère que tu m'apprendras\n"
	.string "encore plein d'autres choses!$"

gText_ApprenticePleaseTeach11::
	.string "Ohé, matelot! C'est le salut\n"
	.string "salut des marins,\p"
	.string "moussaillon! Je m'appelle\n"
	.string "{STR_VAR_1}, le MARIN chantant! Je\p"
	.string "sais tout sur toi, mais\n"
	.string "cela va de soi! Voyons\p"
	.string "voir… {PLAYER}{KUN}, tu te prénommes,\n"
	.string "pour les POKéMON, tu te\l"
	.string "passionnes! Tu es encore\p"
	.string "bien jeune, mon petit! A ton\n"
	.string "âge, tout est permis! Tu\p"
	.string "sais, aujourd'hui… tu es le\n"
	.string "dixième DRESSEUR avec qui je\l"
	.string "parle, pardi! Solennellement,\p"
	.string "je te le demande… Sois mon\n"
	.string "mentor, j'ai tant à apprendre!$"

gText_ApprenticeRejectTeaching11::
	.string "Mais! J'ai besoin de\n"
	.string "toi! Je suis sûr que\p"
	.string "tu me fais marcher!\n"
	.string "Accepte, s'il te plaît!$"

gText_ApprenticeWhichLevelMode11::
	.string "Oui! {PLAYER} a dit oui! Voici une\n"
	.string "question. Je suis ouvert\p"
	.string "à toute suggestion! C'est\n"
	.string "à propos de la TOUR DE\p"
	.string "COMBAT. Disons que j'ai\n"
	.string "l'embarras du choix! Niveau\p"
	.string "50 et niveau libre? Que me\n"
	.string "conseilles-tu de choisir?$"

gText_ApprenticeLevelModeThanks11::
	.string "{STR_VAR_1}, tu dis? C'est un bon\n"
	.string "conseil, pardi! Tes\p"
	.string "conseils me sont précieux, {PLAYER}!\n"
	.string "Toi, tu as l'esprit belliqueux!$"

gText_ApprenticePleaseTeach12::
	.string "Qui va là? Mais c'est {PLAYER}!\n"
	.string "Que faire? Te parler, au\l"
	.string "risque de t'importuner?\p"
	.string "Mon choix est fait! {PLAYER},\n"
	.string "pourquoi ce regard\p"
	.string "surpris? Tu te demandes\n"
	.string "qui je suis? {STR_VAR_1}, c'est mon\l"
	.string "nom. Et la guitare, c'est\p"
	.string "ma passion! Tu m'as\n"
	.string "compris? Oui, tu m'as\p"
	.string "compris! C'est mon jour de\n"
	.string "chance, alors je me lance! {PLAYER},\p"
	.string "laisse-moi être ton apprenti!\n"
	.string "Je n'ai pas encore assez appris!$"

gText_ApprenticeRejectTeaching12::
	.string "Si ta réponse est non, je\n"
	.string "repose ma question! {PLAYER},\p"
	.string "laisse-moi être ton apprenti!\n"
	.string "Je n'ai pas encore assez appris!$"

gText_ApprenticeWhichLevelMode12::
	.string "Ça, c'est bon! Je peux\n"
	.string "te poser une autre\p"
	.string "question? Ma question\n"
	.string "portera… sur la TOUR DE\p"
	.string "COMBAT! Des deux choix\n"
	.string "proposés, lequel dois-je accepter?$"

gText_ApprenticeLevelModeThanks12::
	.string "Tu dis {STR_VAR_1}? C'est ça\n"
	.string "que je choisirai!\p"
	.string "{PLAYER}, je dois y\n"
	.string "aller! Pense à moi!\p"
	.string "A bientôt, j'espère!$"

gText_ApprenticePleaseTeach13::
	.string "Hé, toi! Tu me fais un\n"
	.string "massage? J'ai les\p"
	.string "épaules contractées. Oui,\n"
	.string "toi! J'adore les\p"
	.string "massages! Ça me détend! Je\n"
	.string "m'appelle {STR_VAR_1}. Je fais du\l"
	.string "karaté, mais je ne suis\p"
	.string "pas en grande forme… J'ai\n"
	.string "donc décidé de me mettre\p"
	.string "aux combats de POKéMON. Tu\n"
	.string "es {PLAYER}{KUN}, non? Le MAÎTRE de la\p"
	.string "LIGUE POKéMON? Dis, tu veux\n"
	.string "bien me donner un conseil?$"

gText_ApprenticeRejectTeaching13::
	.string "Pourquoi? Ce ne sera\p"
	.string "pas long, juste un petit\n"
	.string "conseil… S'il te plaît!$"

gText_ApprenticeWhichLevelMode13::
	.string "Merci! Oh là là, je tousse…\n"
	.string "Il faut vite que je retrouve\p"
	.string "la forme… Je vais relever le\p"
	.string "défi de la TOUR DE COMBAT. Tu\n"
	.string "penses que je devrais\l"
	.string "choisir niveau 50 ou niveau libre?$"

gText_ApprenticeLevelModeThanks13::
	.string "D'accord, je vais choisir\n"
	.string "{STR_VAR_1}. Bon, j'y vais. Ça fait\p"
	.string "plaisir de pouvoir\n"
	.string "compter sur son mentor. Merci!$"

gText_ApprenticePleaseTeach14::
	.string "Euh… Hum… {PLAYER}{KUN}? Ne me fixe pas\n"
	.string "comme ça, tu me rends\p"
	.string "nerveux… Je m'appelle {STR_VAR_1}.\n"
	.string "J'ai un peu honte de le\p"
	.string "dire, mais les ruines…\p"
	.string "l'archéologie… c'est mon\n"
	.string "dada! J'ai aussi un peu honte\p"
	.string "d'avouer que je m'intéresse à\n"
	.string "la ZONE DE COMBAT. {PLAYER}{KUN}, tu as\p"
	.string "la réputation d'être un très\n"
	.string "bon DRESSEUR… Ce n'est pas\p"
	.string "mon habitude, mais je\n"
	.string "voudrais te poser une question.\p"
	.string "Bon, je me jette à l'eau. Tu\n"
	.string "veux bien devenir mon professeur?$"

gText_ApprenticeRejectTeaching14::
	.string "Je m'y attendais… Je ne\n"
	.string "supporte pas d'être humilié!\p"
	.string "Pardonne-moi d'insister. S'il\n"
	.string "te plaît, sois mon professeur!$"

gText_ApprenticeWhichLevelMode14::
	.string "Je te remercie… Ne me regarde\p"
	.string "pas droit dans les yeux, ça me\n"
	.string "met mal à l'aise. Je vais te\p"
	.string "poser une question, mais ne me\n"
	.string "regarde pas, d'accord? Dans\p"
	.string "la TOUR DE COMBAT, quel niveau\n"
	.string "tu me conseilles de choisir?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… C'est compris! Je\n"
	.string "vais essayer ça. J'espère\p"
	.string "que je vais y arriver!\n"
	.string "J'ai le trac rien que d'en\p"
	.string "parler… Merci, {PLAYER}{KUN}. J'espère\n"
	.string "qu'on va se revoir, tu es\l"
	.string "vraiment de bon conseil.$"

gText_ApprenticePleaseTeach15::
	.string "Tiens donc? Tu es {PLAYER}{KUN}, n'est-ce\n"
	.string "pas? Je me présente, mon nom\p"
	.string "est {STR_VAR_1}. Je me disais justement\p"
	.string "que Je voudrais apprendre\n"
	.string "avec un bon DRESSEUR. Alors,\p"
	.string "quelle chance de te voir! Tu\n"
	.string "es vraiment {PLAYER}{KUN}, non? Très\p"
	.string "bien. Permets-moi de te\n"
	.string "présenter mon souhait le plus\l"
	.string "cher. Puis-je être ton apprenti?$"

gText_ApprenticeRejectTeaching15::
	.string "Comment? Pourquoi\n"
	.string "refuses-tu? Je suis désolé\p"
	.string "d'avoir émis des doutes\n"
	.string "sur ton identité. Je te\p"
	.string "prie d'accepter mes excuses.\n"
	.string "Puis-je être ton apprenti?$"

gText_ApprenticeWhichLevelMode15::
	.string "C'est vrai? J'en suis tout à\n"
	.string "fait ravi! Tu ne sais pas ce\p"
	.string "que ça représente pour moi…\n"
	.string "J'ai besoin d'un conseil.\p"
	.string "Dans la TOUR DE COMBAT, que\n"
	.string "me conseilles-tu de choisir?\l"
	.string "Niveau 50 ou niveau libre?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}? Cela me surprend\n"
	.string "un peu. Je te\p"
	.string "remercie, c'est très\n"
	.string "aimable de ta part.\p"
	.string "J'espère ne pas\n"
	.string "avoir abusé de ton\p"
	.string "temps, surtout. À bientôt!$"

gText_ApprenticeWhatHeldItem0::
	.string "Sniff… Oh, {PLAYER}! C'est\n"
	.string "horrible, je n'arrive\p"
	.string "pas à me décider. Je ne\n"
	.string "sais pas quel objet je\p"
	.string "devrais faire porter à\n"
	.string "mon {STR_VAR_1}. Tu en penses\p"
	.string "quoi, {PLAYER}? Qu'est-ce que je\n"
	.string "devrais lui faire porter?$"

gText_ApprenticeHoldNothing0::
	.string "Vraiment? Tu penses que\n"
	.string "mon {STR_VAR_1} ne devrait rien porter?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Oh, d'accord. Je\n"
	.string "suis soulagé.\p"
	.string "Merci du conseil!$"

gText_ApprenticeThanksHeldItem0::
	.string "{STR_VAR_1}? J'ai cet objet,\n"
	.string "justement! Merci\p"
	.string "beaucoup! Bon, c'est\n"
	.string "décidé! Très bon\p"
	.string "choix! Je te remercie!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Comment? Tu te moques\p"
	.string "de moi… On m'a déjà\n"
	.string "recommandé {STR_VAR_1}, sniff… Tu\p"
	.string "veux peut-être dire que\n"
	.string "mon {STR_VAR_2} ne devrait rien porter?$"

gText_ApprenticeWhatHeldItem1::
	.string "Hé, mais c'est {PLAYER}!\n"
	.string "Justement, j'avais une\p"
	.string "question pour toi! Tu\n"
	.string "fais porter des objets à\p"
	.string "tes POKéMON? Moi, je\n"
	.string "voudrais mais… Quel objet\p"
	.string "serait bon pour {STR_VAR_1}? Tu as une idée?$"

gText_ApprenticeHoldNothing1::
	.string "Hein? Tu veux dire que mon\n"
	.string "{STR_VAR_1} ne devrait rien porter?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "D'accord, j'ai\n"
	.string "compris! Merci du conseil!$"

gText_ApprenticeThanksHeldItem1::
	.string "{STR_VAR_1}, tu dis? Je suis\n"
	.string "bien d'accord!\p"
	.string "Merci du conseil!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Oui, mais je sais déjà pour\n"
	.string "cet objet. Je voulais en\l"
	.string "connaître un autre. Ou tu\p"
	.string "veux dire que mon POKéMON ne\n"
	.string "devrait rien porter, cette fois?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, bonjour! Je voulais te\n"
	.string "parler de mon {STR_VAR_1}… Je veux\p"
	.string "lui faire porter un objet.\n"
	.string "Lequel tu me conseilles?$"

gText_ApprenticeHoldNothing2::
	.string "Mon {STR_VAR_1} ne doit rien\n"
	.string "porter, c'est ça?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "Compris! À\n"
	.string "bientôt!$"

gText_ApprenticeThanksHeldItem2::
	.string "{STR_VAR_1}? Compris! Je\n"
	.string "vais essayer de\p"
	.string "trouver cet\n"
	.string "objet! À bientôt!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "{STR_VAR_1}? Mais on m'en a déjà\n"
	.string "parlé, tu sais. Je\p"
	.string "voudrais que mon POKéMON\n"
	.string "porte un autre objet. Ou\p"
	.string "est-ce que tu veux dire que\n"
	.string "mon {STR_VAR_2} ne devrait rien porter?$"

gText_ApprenticeWhatHeldItem3::
	.string "Salut, {PLAYER}! Je suis désolée de\n"
	.string "te déranger… Je voudrais te\l"
	.string "poser une question. Je ne\p"
	.string "suis pas assez forte pour\n"
	.string "gagner les combats sans aide,\l"
	.string "alors je voudrais faire porter\p"
	.string "un objet à mon {STR_VAR_1}. Mais je ne\p"
	.string "sais pas quoi choisir. Dis, {PLAYER}… Tu\n"
	.string "pourrais me conseiller un objet?$"

gText_ApprenticeHoldNothing3::
	.string "Tu veux dire qu'il vaut mieux que\n"
	.string "Ce serait mieux sans un objet?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Je vois… Tu penses qu'il\n"
	.string "vaut mieux que je ne\l"
	.string "compte que sur moi. Je\p"
	.string "vais essayer! Merci beaucoup!$"

gText_ApprenticeThanksHeldItem3::
	.string "{STR_VAR_1}… D'accord. Je ne sais\n"
	.string "pas comment je vais\l"
	.string "trouver cet objet… Mais je\p"
	.string "le trouverai. Merci beaucoup!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "{STR_VAR_1}? Oh, mais… On m'a déjà\n"
	.string "parlé de ça… Peut-être\p"
	.string "que je ne l'ai pas\n"
	.string "utilisé correctement? Ou\p"
	.string "est-ce que tu veux dire que\n"
	.string "mon {STR_VAR_2} ne devrait rien porter?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}. J'ai quelque chose à te\n"
	.string "demander. Tu te souviens que\p"
	.string "tu m'avais dit quel POKéMON\n"
	.string "je devrais avoir? Maintenant,\p"
	.string "je voudrais savoir quel objet\n"
	.string "je devrais lui faire porter.\p"
	.string "Comme tu m'as bien\n"
	.string "conseillée la dernière fois,\p"
	.string "j'ai pensé que tu saurais! Quel\n"
	.string "objet tu me conseilles pour mon {STR_VAR_1}?$"

gText_ApprenticeHoldNothing4::
	.string "Ah, bon? Mon {STR_VAR_1} ne\n"
	.string "devrait porter aucun objet?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Si tu penses que c'est la\p"
	.string "meilleure solution, je te fais\n"
	.string "confiance. Comme c'est ta\l"
	.string "décision, ce sera ta faute si je\p"
	.string "perds, {PLAYER}{KUN}! Non, sérieusement. Je te\n"
	.string "fais entièrement confiance. Salut!$"

gText_ApprenticeThanksHeldItem4::
	.string "{STR_VAR_1}, hein? Pas mal. Je\n"
	.string "vais l'utiliser! Comme\p"
	.string "c'est ta décision, ce\n"
	.string "sera ta faute si je\l"
	.string "perds, {PLAYER}{KUN}! Non,\p"
	.string "sérieusement. Je te fais\n"
	.string "entièrement confiance. Salut!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "{STR_VAR_1}? Mais tu m'as déjà\n"
	.string "parlé de cet objet. Tu\l"
	.string "as oublié? A moins que tu\p"
	.string "ne veuilles dire que mon\n"
	.string "{STR_VAR_2} ne devrait rien porter?$"

gText_ApprenticeWhatHeldItem5::
	.string "Salut, {PLAYER}{KUN}! On a tous les deux\p"
	.string "beaucoup à faire, mais on\n"
	.string "n'arrête pas de se croiser! Le\p"
	.string "programme, aujourd'hui, c'est\n"
	.string "footing, ménage et repassage.\p"
	.string "Je n'ai pas eu le temps\n"
	.string "d'acheter quelque chose pour\p"
	.string "mon {STR_VAR_1}. Tu pourrais me conseiller\n"
	.string "un objet à faire porter à mon\l"
	.string "{STR_VAR_1}? Ça me ferait gagner du temps.$"

gText_ApprenticeHoldNothing5::
	.string "Tu crois qu'il vaut\n"
	.string "mieux que mon {STR_VAR_1} ne porte rien?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "C'est compris. Tant\n"
	.string "mieux, ça me fera\p"
	.string "gagner du temps. Merci du\n"
	.string "conseil! A la prochaine!$"

gText_ApprenticeThanksHeldItem5::
	.string "{STR_VAR_1}? C'est compris. Dès que\n"
	.string "j'aurai cinq minutes à moi,\l"
	.string "j'irai chercher cet objet. Je\p"
	.string "peux toujours compter sur\n"
	.string "toi. Merci! Et à la prochaine!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "{STR_VAR_1}? Mais je connais\n"
	.string "déjà, je voulais un\p"
	.string "autre objet. Tu crois\n"
	.string "qu'il vaut mieux que mon {STR_VAR_2}\l"
	.string "ne porte rien, c'est ça?$"

gText_ApprenticeWhatHeldItem6::
	.string "Salut, {PLAYER}! C'est moi! J'ai\n"
	.string "encore besoin de tes\l"
	.string "lumières! Eclaire ma\p"
	.string "lanterne… Bon, je me\n"
	.string "dépêche! Voici ma question…\p"
	.string "Je veux faire porter un objet\n"
	.string "à mon {STR_VAR_1}. Que me conseilles-tu?$"

gText_ApprenticeHoldNothing6::
	.string "Vraiment? Mon {STR_VAR_1} n'a pas\n"
	.string "besoin de porter d'objet, tu dis?$"

gText_ApprenticeThanksNoHeldItem6::
	.string "D'accord, je vais suivre ton\p"
	.string "conseil. C'est tout ce que\n"
	.string "je voulais savoir. Rien\p"
	.string "d'autre pour aujourd'hui! On\n"
	.string "se reverra ici, d'accord? Merci!$"

gText_ApprenticeThanksHeldItem6::
	.string "{STR_VAR_1}? C'est une super\n"
	.string "idée! Je vais\l"
	.string "essayer! C'est tout ce\p"
	.string "que je voulais savoir.\n"
	.string "Rien d'autre pour\p"
	.string "aujourd'hui! On se\n"
	.string "reverra ici, d'accord? Merci!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "{STR_VAR_1}? Mais tu m'as déjà\n"
	.string "parlé de cet objet! Tu\l"
	.string "as oublié? Tu te sens\p"
	.string "bien, {PLAYER}? Ah, tu veux\p"
	.string "dire que mon {STR_VAR_2} n'a pas\n"
	.string "besoin de porter un objet.$"

gText_ApprenticeWhatHeldItem7::
	.string "Bonjour, {PLAYER}. J'espère que tu\n"
	.string "vas bien. Je peux te\p"
	.string "demander un conseil? J'ai\p"
	.string "remarqué que certains de\n"
	.string "mes adversaires font\l"
	.string "porter des objets à leurs\p"
	.string "POKéMON. Et ils m'ont tous\p"
	.string "battu… Alors, moi aussi, je\n"
	.string "voudrais que mon {STR_VAR_1} porte un\l"
	.string "objet. Tu me comprends,\p"
	.string "non? Je voudrais bien que tu\n"
	.string "choisisses un objet pour moi…$"

gText_ApprenticeHoldNothing7::
	.string "En d'autres termes… je\n"
	.string "n'ai pas besoin d'objet?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "C'est compris! Je vais\n"
	.string "continuer sans objet,\p"
	.string "alors. Merci, {PLAYER}. Je\n"
	.string "savais bien que je pouvais\l"
	.string "compter sur toi. A bientôt!$"

gText_ApprenticeThanksHeldItem7::
	.string "{STR_VAR_1}, vraiment? Je vais\n"
	.string "suivre ce conseil!\p"
	.string "Merci, {PLAYER}. Je savais\n"
	.string "bien que je pouvais\l"
	.string "compter sur toi. A bientôt!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Tu m'as déjà parlé de cet\n"
	.string "objet et je l'ai déjà. Tu\p"
	.string "veux dire que… mon\n"
	.string "POKéMON n'a pas besoin d'objet?$"

gText_ApprenticeWhatHeldItem8::
	.string "Hé, {PLAYER}! Quel plaisir\n"
	.string "de te voir!\p"
	.string "Justement, j'avais une\n"
	.string "petite question à te\p"
	.string "poser, {PLAYER}! Dis-moi quel\n"
	.string "objet mon {STR_VAR_1} devrait porter!$"

gText_ApprenticeHoldNothing8::
	.string "Comme c'est surprenant!\n"
	.string "Il ne devrait rien porter?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "C'est compris! Je vais\n"
	.string "continuer sans objet!\p"
	.string "J'espère que tu me\n"
	.string "donneras encore plein de conseils!$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}? C'est d'accord! Toi\p"
	.string "aussi, {PLAYER}, tu utilises cet\n"
	.string "objet? Je vais me le\p"
	.string "procurer le plus vite\n"
	.string "possible! J'espère que tu me\l"
	.string "donneras encore plein de conseils!$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "{STR_VAR_1}? Tu me l'as déjà\n"
	.string "recommandé. C'est le\p"
	.string "meilleur objet? Ou tu\n"
	.string "veux dire que mon {STR_VAR_2} ne\l"
	.string "devrait rien porter?$"

gText_ApprenticeWhatHeldItem9::
	.string "Bonjour, {PLAYER}{KUN}! J'ai un\n"
	.string "petit conseil à te\p"
	.string "demander en matière de\n"
	.string "POKéMON. Qu'est-ce que\p"
	.string "je dois faire porter à\n"
	.string "mon {STR_VAR_1}, d'après toi?\p"
	.string "Dis-le-moi, je te fais\n"
	.string "une confiance aveugle!$"

gText_ApprenticeHoldNothing9::
	.string "Ah, bon? Mon {STR_VAR_1} peut\n"
	.string "gagner sans objet?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Bueno! Je vais\n"
	.string "faire de mon mieux\p"
	.string "sans objet!\n"
	.string "Merci! Hasta la vista!$"

gText_ApprenticeThanksHeldItem9::
	.string "{STR_VAR_1}? Bueno! Je\n"
	.string "vais me\l"
	.string "servir de\p"
	.string "ça! Merci!\n"
	.string "Hasta la vista!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "{STR_VAR_1}? Tu m'en as déjà\n"
	.string "parlé, tu as\p"
	.string "oublié? Attends… Tu\n"
	.string "veux dire que mon {STR_VAR_2}\l"
	.string "peut gagner sans objet?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, il m'est arrivé un truc\n"
	.string "incroyable! Quand je me\p"
	.string "suis réveillé ce matin, mon\n"
	.string "POKéMON avait 10 PEPITES!\p"
	.string "Non, je rigole! Ha, ha,\n"
	.string "ha! Bon, le fait est que je\p"
	.string "ne connais rien aux objets.\n"
	.string "Je ne sais pas lesquels il\l"
	.string "faut faire porter aux\p"
	.string "POKéMON. Tu pourrais me dire\n"
	.string "ce que mon {STR_VAR_1} devrait porter?$"

gText_ApprenticeHoldNothing10::
	.string "Comment? Il ne doit rien\n"
	.string "porter? C'est ce que tu me dis?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Pas d'objet, d'après toi… Je\n"
	.string "vais lui en trouver un, alors!\p"
	.string "Je rigole, bien sûr que je\n"
	.string "vais suivre ton conseil!\p"
	.string "Merci! J'espère que tu\n"
	.string "Apprends-moi encore beaucoup!$"

gText_ApprenticeThanksHeldItem10::
	.string "{STR_VAR_1}? Je vais lui faire porter\n"
	.string "autre chose, alors! Je\p"
	.string "rigole, bien sûr que je vais\n"
	.string "suivre ton conseil! Merci!\p"
	.string "J'espère que tu m'apprendras\n"
	.string "encore plein d'autres choses!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Tu m'as déjà parlé de ça,\n"
	.string "non? Si, je me souviens…\p"
	.string "Tu n'as pas une autre idée?\p"
	.string "Ou alors, tu veux dire que\n"
	.string "mon {STR_VAR_2} ne doit rien porter?$"

gText_ApprenticeWhatHeldItem11::
	.string "Ohé, matelot! C'est le salut\n"
	.string "des marins, matelot! C'est\p"
	.string "moi, le MARIN chantant! C'est\n"
	.string "toujours un plaisir de te\l"
	.string "voir, soit dit en passant!\p"
	.string "J'ai une question sur les\n"
	.string "objets. Je compte sur toi, mon\p"
	.string "rouget! Mon {STR_VAR_1} doit porter un\n"
	.string "objet. Lequel me conseilles-tu?$"

gText_ApprenticeHoldNothing11::
	.string "Vraiment? Mon {STR_VAR_1}\n"
	.string "n'a pas besoin de\l"
	.string "porter un objet?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Je vais suivre ton conseil! Car\n"
	.string "ton intelligence est sans\p"
	.string "pareille! Tes conseils me sont\n"
	.string "{PLAYER}, ta parole que j'écoute toujours!$"

gText_ApprenticeThanksHeldItem11::
	.string "{STR_VAR_1}? Je vais l'utiliser! Te\n"
	.string "demander conseil était\l"
	.string "une bonne idée! Ton avis\p"
	.string "m'est précieux, {PLAYER}! Toi,\n"
	.string "tu as l'esprit belliqueux!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "{STR_VAR_1}, tu dis? Mais tu m'en\n"
	.string "as déjà parlé. Je veux\l"
	.string "quelque chose encore.\p"
	.string "Ou est-ce qu'il se\n"
	.string "pourrait… que mon POKéMON\l"
	.string "n'ait pas besoin d'objet?$"

gText_ApprenticeWhatHeldItem12::
	.string "Bonjour, {PLAYER}! Comme on se\n"
	.string "retrouve! Que faire? Te\p"
	.string "parler, au risque de\n"
	.string "t'importuner? Mon choix est\p"
	.string "fait! {PLAYER}, j'espère que tu ne te\n"
	.string "lasses pas de moi! En tout cas,\p"
	.string "moi, je ne me lasse pas de toi!\n"
	.string "Tu as une minute à m'accorder?\l"
	.string "J'aurais besoin d'un conseil.\p"
	.string "Je veux faire porter un objet à\n"
	.string "mon {STR_VAR_1}, mais je ne sais pas lequel\l"
	.string "choisir! Tu veux bien m'aider?$"

gText_ApprenticeHoldNothing12::
	.string "Mon {STR_VAR_1} n'a besoin de\n"
	.string "rien? Rien de rien?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Tu as un grand\n"
	.string "savoir-faire, alors c'est\p"
	.string "ce que je vais faire! {PLAYER},\n"
	.string "je dois y aller! Pense à\p"
	.string "moi! A bientôt, j'espère!$"

gText_ApprenticeThanksHeldItem12::
	.string "{STR_VAR_1}? Quel précieux\n"
	.string "conseil… A chaque fois,\p"
	.string "je m'émerveille! {PLAYER}, je\n"
	.string "dois y aller! Pense à\p"
	.string "moi! A bientôt, j'espère!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "{STR_VAR_1}? Ce nom ne m'est pas\n"
	.string "inconnu. Ce conseil, je\l"
	.string "l'ai déjà reçu! Mais se\p"
	.string "pourrait-il… que mon {STR_VAR_2}\n"
	.string "n'ait besoin de rien?\l"
	.string "Vraiment, rien de rien?$"

gText_ApprenticeWhatHeldItem13::
	.string "Aïe! Ouille! Je me suis cassé le\n"
	.string "bras, {PLAYER}{KUN}! Ne t'approche pas!\p"
	.string "J'essayais de faire porter des\n"
	.string "objets à mes POKéMON et je me\l"
	.string "suis fait mal au bras. Je pense\p"
	.string "qu'il est cassé. Je crois que\n"
	.string "j'ai besoin de ton aide en ce qui\p"
	.string "concerne les objets. {PLAYER}{KUN}, qu'est-ce\n"
	.string "C'est bon pour moi {STR_VAR_1} de tenir?$"

gText_ApprenticeHoldNothing13::
	.string "Ouille… Tu penses\p"
	.string "que mon {STR_VAR_1} ne\n"
	.string "devrait rien porter?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hum! Très bien. Etant donné\n"
	.string "que j'ai le bras cassé, ça\p"
	.string "m'arrange. Ça fait plaisir de\n"
	.string "pour de l'aide comme ça.$"

gText_ApprenticeThanksHeldItem13::
	.string "{STR_VAR_1}? Très bien. Mon bras va\n"
	.string "déjà mieux. Je vais donner\l"
	.string "cet objet à mon POKéMON. Ça\p"
	.string "fait plaisir de pouvoir\n"
	.string "compter sur quelqu'un. Merci!$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "{STR_VAR_1}? Non, non, tu m'en\n"
	.string "as déjà parlé… Tu te\p"
	.string "souviens? Tu n'as\n"
	.string "pas une meilleure\p"
	.string "idée? Oh, attends… Tu\n"
	.string "veux dire que mon {STR_VAR_2} ne\l"
	.string "devrait rien porter?$"

gText_ApprenticeWhatHeldItem14::
	.string "Hum… Euh… {PLAYER}{KUN}… Ne me regarde\n"
	.string "pas comme ça… Mes POKéMON\p"
	.string "ne portent aucun objet.\n"
	.string "Euh… Ça me gêne un peu…\p"
	.string "J'aurais besoin de ton\n"
	.string "aide. Je n'arrive pas à\p"
	.string "décider quel est le meilleur\n"
	.string "objet pour mon {STR_VAR_1}. {PLAYER}{KUN}, qu'est-ce\p"
	.string "que tu en penses? Quel\n"
	.string "objet je dois lui faire porter?$"

gText_ApprenticeHoldNothing14::
	.string "Oh… Tu penses que c'est\n"
	.string "mieux que mon {STR_VAR_1} ne porte rien?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… C'est entendu!\n"
	.string "J'oublie les objets,\p"
	.string "alors. Je n'arrive pas à le\n"
	.string "croire… Quel bonheur de\p"
	.string "parler avec toi! Merci, {PLAYER}{KUN}.\n"
	.string "J'espère qu'on va se revoir,\l"
	.string "tu es vraiment de bon conseil.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… {STR_VAR_1}? C'est entendu! Je\n"
	.string "vais essayer ça. Je\p"
	.string "n'arrive pas à le croire…\n"
	.string "Quel bonheur de parler\p"
	.string "avec toi! Merci, {PLAYER}{KUN}.\n"
	.string "J'espère qu'on va se revoir,\l"
	.string "tu es vraiment de bon conseil.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "Mais je le sais déjà, ça. Tu ne\p"
	.string "veux pas m'aider… Je vois. Je m'y\n"
	.string "attendais… Je ne supporte pas\p"
	.string "d'être humilié! Oh… Mais je me\n"
	.string "trompe peut-être. Tu veux dire\l"
	.string "mon {STR_VAR_2} n'avait pas d'objet?$"

gText_ApprenticeWhatHeldItem15::
	.string "Tiens… {PLAYER}{KUN}, n'est-ce pas? A\n"
	.string "moins que tu ne sois son\l"
	.string "sosie? Mais, si tu es\p"
	.string "vraiment {PLAYER}, je te présente\n"
	.string "mes excuses. Je ne voulais\l"
	.string "pas te mettre dans\p"
	.string "l'embarras. J'ai encore\n"
	.string "besoin de tes conseils\p"
	.string "avisés. J'ai avec moi mon {STR_VAR_1} et\n"
	.string "je souhaite lui faire porter un\p"
	.string "objet. Lequel me conseilles-tu?$"

gText_ApprenticeHoldNothing15::
	.string "Tu me conseilles de ne\n"
	.string "rien lui donner? Vraiment?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Je te remercie,\n"
	.string "c'est très aimable\p"
	.string "de ta part. À bientôt!$"

gText_ApprenticeThanksHeldItem15::
	.string "{STR_VAR_1}? Vraiment? Je\n"
	.string "te remercie,\p"
	.string "c'est très\n"
	.string "aimable de ta\p"
	.string "part. Je suis sûr\n"
	.string "que cela me sera\p"
	.string "très utile. À bientôt!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Mais, dis-moi… Ne\n"
	.string "m'aurais-tu pas déjà\p"
	.string "parlé de ça? N'aurais-tu\n"
	.string "pas un autre objet à me\p"
	.string "proposer? Ou peut-être\n"
	.string "veux-tu dire que mon {STR_VAR_2} ne\l"
	.string "doit rien porter? C'est cela?$"

gText_ApprenticeWhichMonFirst0::
	.string "Ah, {PLAYER}! J'ai un problème…\n"
	.string "Je veux commencer à\p"
	.string "faire des combats, mais\n"
	.string "je ne sais pas comment\p"
	.string "m'y prendre. Dans quel\n"
	.string "ordre dois-je placer mes\p"
	.string "POKéMON? Dis-moi, {PLAYER}. A\n"
	.string "ma place, quel POKéMON\l"
	.string "enverrais-tu en premier?$"

gText_ApprenticeMonFirstThanks0::
	.string "C'est mon {STR_VAR_1} qui doit aller\n"
	.string "au combat en premier?\p"
	.string "Aaah! Oh, je suis désolé!\n"
	.string "Ton aide me fait tellement\l"
	.string "chaud au cœur que ça me fait\p"
	.string "pleurer… Merci infiniment!$"

gText_ApprenticeWhichMonFirst1::
	.string "Super, {PLAYER}! Tu tombes bien, j'ai\n"
	.string "une question pour toi! D'après\p"
	.string "toi, lequel de mes POKéMON je\n"
	.string "dois envoyer au combat en premier?$"

gText_ApprenticeMonFirstThanks1::
	.string "Mon {STR_VAR_1}? Tu as\n"
	.string "raison. Je vais\p"
	.string "suivre ton conseil! Merci!$"

gText_ApprenticeWhichMonFirst2::
	.string "Salut, {PLAYER}! Il paraît qu'il faut\p"
	.string "bien choisir le POKéMON\n"
	.string "qu'on envoie en premier.\p"
	.string "Lequel de mes POKéMON je devrais\n"
	.string "envoyer en premier, d'après toi?$"

gText_ApprenticeMonFirstThanks2::
	.string "Mon {STR_VAR_1} devrait\n"
	.string "être le premier?\p"
	.string "D'acc! À bientôt!$"

gText_ApprenticeWhichMonFirst3::
	.string "Bonjour, {PLAYER}... je suis désolé\n"
	.string "de vous déranger encore une\l"
	.string "fois avec une autre question.\p"
	.string "J'ai si peu de confiance, je ne\n"
	.string "sais ce que je ferais sans toi, {PLAYER}.\p"
	.string "C'est peut-être une perte de\n"
	.string "temps pour moi de m'en\l"
	.string "décider quelque chose...\p"
	.string "Lequel de mes POKéMON dois-je\n"
	.string "D'abord dans une bataille?$"

gText_ApprenticeMonFirstThanks3::
	.string "Mon {STR_VAR_1}? C'est compris! C'est\n"
	.string "vraiment gentil de ta\p"
	.string "part de me conseiller\n"
	.string "comme ça! J'ai toujours\p"
	.string "peur que tu refuses de me\n"
	.string "parler, mais tu es super… Merci!$"

gText_ApprenticeWhichMonFirst4::
	.string "Oh, {PLAYER}{KUN}! C'est moi, tu me\n"
	.string "reconnais? Je suis contente de\l"
	.string "te voir! Je ne sais pas dans\p"
	.string "quel ordre placer mes POKéMON.\n"
	.string "Tu peux m'aider? Je ne te\p"
	.string "demande pas d'ordonner toute\n"
	.string "l'équipe, ce serait trop… Mais tu\p"
	.string "pourrais au moins me dire quel\n"
	.string "POKéMON pour moi?$"

gText_ApprenticeMonFirstThanks4::
	.string "Mon {STR_VAR_1}? Super! Comme\p"
	.string "c'est ta décision, ce\n"
	.string "sera ta faute si je\l"
	.string "perds, {PLAYER}{KUN}! Non,\p"
	.string "sérieusement. Je te fais\n"
	.string "entièrement confiance. Salut!$"

gText_ApprenticeWhichMonFirst5::
	.string "C'est {PLAYER}{KUN}! C'est encore la\n"
	.string "course aujourd'hui! Au\p"
	.string "programme: vélo, shopping et\n"
	.string "chorale. Je n'ai même pas\p"
	.string "encore eu le temps\n"
	.string "d'ordonner mon équipe POKéMON!\p"
	.string "Si on le faisait ensemble?\n"
	.string "Lequel je dois envoyer en premier?$"

gText_ApprenticeMonFirstThanks5::
	.string "D'accord, je m'en remets à ton\n"
	.string "jugement. Placer mon {STR_VAR_1} en premier\l"
	.string "ne devrait pas me prendre trop\p"
	.string "de temps! Ma copine m'attend, je\n"
	.string "dois y aller! Merci. À bientôt!$"

gText_ApprenticeWhichMonFirst6::
	.string "Bonjour, {PLAYER}! Tu es\n"
	.string "partout, toi! Comme\p"
	.string "d'habitude, j'ai besoin de\n"
	.string "ton aide! Cette fois-ci,\p"
	.string "ma question est sur mon\n"
	.string "équipe POKéMON. Quel\p"
	.string "POKéMON tu me conseilles\n"
	.string "d'envoyer en premier au combat?$"

gText_ApprenticeMonFirstThanks6::
	.string "Mon {STR_VAR_1}? Super! Je vais\n"
	.string "suivre ton conseil,\l"
	.string "comme d'habitude! Bon,\p"
	.string "c'est tout ce que\n"
	.string "j'avais à te demander,\p"
	.string "je crois. Mais on se\n"
	.string "reverra sûrement! Merci!$"

gText_ApprenticeWhichMonFirst7::
	.string "C'est gentil de t'arrêter\n"
	.string "pour discuter avec moi, {PLAYER}.\p"
	.string "Puisque tu es là… Je peux te\n"
	.string "poser une petite question?\p"
	.string "Je voudrais déterminer\n"
	.string "l'ordre de mes POKéMON. Je\p"
	.string "voudrais que tu me dises quel\n"
	.string "POKéMON je dois placer en premier.$"

gText_ApprenticeMonFirstThanks7::
	.string "{STR_VAR_1}? Parfait! C'est ce\n"
	.string "que je vais faire!\p"
	.string "Merci, {PLAYER}. Je savais\n"
	.string "que je pouvais\l"
	.string "compter sur toi. A bientôt!$"

gText_ApprenticeWhichMonFirst8::
	.string "Oh, {PLAYER}! Quel plaisir de te\n"
	.string "revoir! Je m'améliore aux\p"
	.string "combats POKéMON, tu sais!?!\n"
	.string "Je ne gagne pas toujours,\p"
	.string "car je ne sais jamais quel\n"
	.string "POKéMON envoyer en\p"
	.string "premier. {PLAYER}, tu dois m'aider!\p"
	.string "Dis-moi quel POKéMON je dois\n"
	.string "envoyer au combat en premier!$"

gText_ApprenticeMonFirstThanks8::
	.string "Je suis si heureuse…\p"
	.string "Sniff… Quel honneur,\n"
	.string "tu me fais {PLAYER}. C'est\p"
	.string "entendu, je vais\n"
	.string "envoyer {STR_VAR_1} en premier!\p"
	.string "J'espère que tu me\n"
	.string "donneras encore plein de conseils!$"

gText_ApprenticeWhichMonFirst9::
	.string "Bonjour, bonjour! {PLAYER}{KUN}, mon\n"
	.string "mentor! J'ai besoin de tes\l"
	.string "lumières. Voilà. J'ai\p"
	.string "trois POKéMON dans mon\n"
	.string "équipe. Jusque-là, ça va.\p"
	.string "Mais je voudrais les placer\n"
	.string "dans un certain ordre.\p"
	.string "C'est là que tu interviens,\n"
	.string "{PLAYER}{KUN}. A toi de choisir le\p"
	.string "premier POKéMON! Dis-le-moi, je\n"
	.string "te fais une confiance aveugle!$"

gText_ApprenticeMonFirstThanks9::
	.string "Mon {STR_VAR_1} doit être le\n"
	.string "premier? Compris, je\l"
	.string "vais de ce pas\p"
	.string "ordonner mes POKéMON!\n"
	.string "Merci! Hasta la vista!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, tu tombes bien! C'est une\n"
	.string "catastrophe… Mes trois\p"
	.string "POKéMON se battent en même\n"
	.string "temps! Non, je rigole! Ha, ha,\p"
	.string "ha! Tu sais bien que c'est\n"
	.string "impossible! Par contre, ce qui\p"
	.string "est vrai, c'est que Je\n"
	.string "voudrais savoir dans quel ordre\l"
	.string "placer mes POKéMON. Tu ne\p"
	.string "voudrais pas décider pour moi quel\n"
	.string "POKéMON je dois placer en premier?$"

gText_ApprenticeMonFirstThanks10::
	.string "Tu choisis mon {STR_VAR_1}? Mais tu\n"
	.string "es bête ou quoi? Je rigole,\p"
	.string "bien sûr que je vais\n"
	.string "suivre ton conseil! Merci!\p"
	.string "J'espère que tu me donneras\n"
	.string "encore plein de bons conseils!$"

gText_ApprenticeWhichMonFirst11::
	.string "Ohé, matelot! C'est le\n"
	.string "salut des marins,\p"
	.string "moussaillon! C'est moi, le\n"
	.string "MARIN chantant! J'ai une\l"
	.string "question pour toi, mon\p"
	.string "merlan! L'ordre des POKéMON en\n"
	.string "est le sujet. Je compte sur\p"
	.string "toi, mon rouget! Lequel de mes\n"
	.string "POKéMON doit se battre en premier?$"

gText_ApprenticeMonFirstThanks11::
	.string "Tant de sagesse! La foule\n"
	.string "est en liesse! Tes\p"
	.string "conseils me sont précieux, {PLAYER}!\n"
	.string "Toi, tu as l'esprit belliqueux!$"

gText_ApprenticeWhichMonFirst12::
	.string "Commen{PLAYER}t\n"
	.string "allez-vous?\p"
	.string "Qu'est-ce que je\n"
	.string "dois faire? Allez-y\l"
	.string "et demandez-moi?\l"
	.string "J'ai cela à demander!\p"
	.string "Vous devez décider, lequel de mes\n"
	.string "POKéMON est le premier à monter!\l"
	.string "Dans la bataille, je veux dire.$"

gText_ApprenticeMonFirstThanks12::
	.string "{STR_VAR_1}? Oui, très bonne\n"
	.string "idée! Je vais le faire\p"
	.string "sans hésiter! {PLAYER}, je\n"
	.string "dois y aller! Pense à\p"
	.string "moi! A bientôt, j'espère!$"

gText_ApprenticeWhichMonFirst13::
	.string "Aïe… Ouille… J'ai des crampes\n"
	.string "d'estomac, {PLAYER}{KUN}! C'est horrible!\p"
	.string "Ah… Ça a l'air de se calmer…\p"
	.string "Ça m'arrive quand je suis\n"
	.string "nerveux. Depuis des heures,\l"
	.string "j'essaie de décider d'un\p"
	.string "ordre pour mon équipe POKéMON…\n"
	.string "Je n'y arrive pas. Tu dois\p"
	.string "m'aider. {PLAYER}{KUN}, quel POKéMON je\n"
	.string "dois envoyer le premier au combat?$"

gText_ApprenticeMonFirstThanks13::
	.string "Hum, très bien. Mon {STR_VAR_1} sera\n"
	.string "le premier. Je vais le\p"
	.string "faire tout de suite et\n"
	.string "après j'irai manger. Ça\p"
	.string "fait plaisir de pouvoir\n"
	.string "compter sur quelqu'un. Merci!$"

gText_ApprenticeWhichMonFirst14::
	.string "Euh… Hum… {PLAYER}{KUN}? Ne me fixe\n"
	.string "pas comme ça, tu me\p"
	.string "rends nerveux… Hum… J'ai\n"
	.string "besoin de ton aide. Ça\p"
	.string "me gêne de te parler de\n"
	.string "ça, mais j'ai trois\p"
	.string "POKéMON et je ne sais pas\n"
	.string "comment les placer dans\l"
	.string "l'équipe. Quel POKéMON\p"
	.string "est-ce que je devrais\n"
	.string "envoyer au combat en premier?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… C'est d'accord! Je\n"
	.string "vais placer {STR_VAR_1} en premier.\p"
	.string "Ça devrait me permettre\n"
	.string "d'être plus serein lors\p"
	.string "des combats. Merci, {PLAYER}{KUN}.\n"
	.string "J'espère qu'on va se revoir,\l"
	.string "tu es vraiment de bon conseil.$"

gText_ApprenticeWhichMonFirst15::
	.string "Tiens… Es-tu vraiment {PLAYER}{KUN}? A\n"
	.string "moins que tu ne sois son\l"
	.string "sosie? Mais, si tu es\p"
	.string "vraiment {PLAYER}, je te présente\n"
	.string "mes excuses. Je ne voulais\l"
	.string "pas te vexer. J'ai encore\p"
	.string "besoin de tes conseils\p"
	.string "avisés. Je voudrais savoir\n"
	.string "lequel de mes POKéMON je\l"
	.string "devrait commencer par la bataille.$"

gText_ApprenticeMonFirstThanks15::
	.string "Mon {STR_VAR_1}… Tu ne te\n"
	.string "moques pas de moi? Je\p"
	.string "te remercie, c'est\n"
	.string "très aimable de ta\p"
	.string "part. Je vais suivre\n"
	.string "ton conseil et faire\p"
	.string "de mon mieux. À bientôt!$"

gText_ApprenticeWhichMon0::
	.string "Sniff… Oh, {PLAYER}! Tu tombes\n"
	.string "bien, je suis devant\p"
	.string "un vrai dilemme… Je ne\n"
	.string "sais pas quel POKéMON\p"
	.string "je devrais utiliser.\n"
	.string "Je n'arrive pas à\p"
	.string "choisir entre les\n"
	.string "POKéMON {STR_VAR_1} et {STR_VAR_2}… {PLAYER}, avec\p"
	.string "lequel tu penses que j'ai le\n"
	.string "plus de chances de gagner?$"

gText_ApprenticeMonThanks0::
	.string "Sniff… … Tu as raison!\n"
	.string "C'est tellement gentil\l"
	.string "de ta part de m'aider\p"
	.string "que ça me fait pleurer…\n"
	.string "Je vais de ce pas\p"
	.string "attraper un {STR_VAR_1}! Merci beaucoup!$"

gText_ApprenticeWhichMon1::
	.string "Super, {PLAYER}! Je suis\n"
	.string "content de te revoir,\l"
	.string "j'ai besoin de tes\p"
	.string "conseils! Je ne sais\n"
	.string "pas je si dois dresser\p"
	.string "mon {STR_VAR_1} ou mon {STR_VAR_2}… Lequel\n"
	.string "je devrais dresser, {PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Mon {STR_VAR_1}, tu penses? C'est\n"
	.string "lui que je vais dresser,\p"
	.string "alors! Merci du conseil!$"

gText_ApprenticeWhichMon2::
	.string "Salut, {PLAYER}! J'ai une\n"
	.string "question à te poser.\p"
	.string "Je me demande si je\n"
	.string "devrais dresser un {STR_VAR_1}\p"
	.string "ou un {STR_VAR_2}. Lequel est le\n"
	.string "plus fort, à ton avis?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1}? Bon, je te\n"
	.string "fais confiance!\p"
	.string "Je vais aller\n"
	.string "capturer un {STR_VAR_1},\p"
	.string "alors! À bientôt tard!$"

gText_ApprenticeWhichMon3::
	.string "Bonjour, {PLAYER}… Je suis sûre\p"
	.string "que tu m'as déjà oubliée,\n"
	.string "mais on se connaît… Mais\p"
	.string "bon, même si tu m'as\n"
	.string "oubliée… Je voudrais te\p"
	.string "poser une question. Je ne\n"
	.string "sais pas quel POKéMON\p"
	.string "dresser… J'hésite entre {STR_VAR_1} et {STR_VAR_2}.\n"
	.string "Je n'arrive pas à faire un\l"
	.string "choix… Je les aime tous les\p"
	.string "deux… {PLAYER}, dis-moi lequel des deux\n"
	.string "je dois dresser, s'il te plaît.$"

gText_ApprenticeMonThanks3::
	.string "Tu crois que\n"
	.string "j'arriverais à dresser\p"
	.string "un {STR_VAR_1} sauvage? Bon, je\p"
	.string "vais essayer! Enfin,\n"
	.string "il faut d'abord que\p"
	.string "j'en attrape un… Merci!$"

gText_ApprenticeWhichMon4::
	.string "Oh, {PLAYER}{KUN}! Je suis contente\n"
	.string "de te voir! Je voulais\p"
	.string "te parler, justement!\n"
	.string "Il faut que tu me\p"
	.string "dises quel POKéMON je\n"
	.string "dois dresser. Par\l"
	.string "exemple… Que penses-tu\p"
	.string "des POKéMON {STR_VAR_1} et {STR_VAR_2}?\n"
	.string "Lequel des deux tu préfères?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? Super! Comme c'est\p"
	.string "ta décision, ce sera\n"
	.string "ta faute si je perds,\l"
	.string "{PLAYER}{KUN}! Non, sérieusement.\p"
	.string "Je te fais\n"
	.string "entièrement confiance. Salut!$"

gText_ApprenticeWhichMon5::
	.string "Mais, c'est {PLAYER}{KUN}! Quel bon vent\n"
	.string "t'amène? Je veux me mettre\p"
	.string "sérieusement aux combats\n"
	.string "POKéMON, mais je ne sais pas\l"
	.string "encore quel POKéMON je vais\p"
	.string "dresser. Il paraît que {STR_VAR_1} est\n"
	.string "très fort. Mais {STR_VAR_2} me plaît bien\p"
	.string "aussi… Il faut que tu décides\n{PLAYER}{KUN}"
	.string "Lequel serait bon pour moi?$"

gText_ApprenticeMonThanks5::
	.string "D'accord. Je vais essayer\n"
	.string "de me libérer quelques\l"
	.string "heures pour capturer un {STR_VAR_1}.\p"
	.string "Dès que j'ai un souci, tu es\n"
	.string "là! Merci! À bientôt tard!$"

gText_ApprenticeWhichMon6::
	.string "Oh! Super, {PLAYER}! J'ai\n"
	.string "parlé de toi à toutes\p"
	.string "mes amies! Elles n'en\n"
	.string "revenaient pas… J'ai\p"
	.string "encore besoin de ton\n"
	.string "aide. Ça ne prendra\p"
	.string "qu'une minute! Il me\n"
	.string "faut ton avis. Voici ma\p"
	.string "question… Si tu devais\n"
	.string "dresser un POKéMON, tu\l"
	.string "choisirais un {STR_VAR_1} ou un {STR_VAR_2}?$"

gText_ApprenticeMonThanks6::
	.string "Tu choisirais un {STR_VAR_1}?\n"
	.string "Super! Je vais suivre\l"
	.string "ton conseil! Bon,\p"
	.string "c'est tout ce que\n"
	.string "j'avais à te demander, je\p"
	.string "crois. Mais on se\n"
	.string "reverra sûrement! Merci encore!$"

gText_ApprenticeWhichMon7::
	.string "Oh! {PLAYER}? Quel plaisir de te\n"
	.string "rencontrer! Depuis que\p"
	.string "je suis ton apprentie,\n"
	.string "j'ai repris confiance en\p"
	.string "moi. Je crois même que\n"
	.string "je suis prête à élever\p"
	.string "mon propre POKéMON! {PLAYER}, Je\n"
	.string "voudrais que tu\p"
	.string "choisisses un POKéMON pour\n"
	.string "moi. J'ai le choix entre {STR_VAR_1} et\l"
	.string "{STR_VAR_2}… Lequel m'irait le mieux?$"

gText_ApprenticeMonThanks7::
	.string "Le {STR_VAR_1}? Parfait!\n"
	.string "Merci, {PLAYER}. Je\p"
	.string "savais que je\n"
	.string "pouvais compter\l"
	.string "sur toi. A bientôt!$"

gText_ApprenticeWhichMon8::
	.string "{PLAYER}? Décidément, comme\n"
	.string "on se retrouve!\p"
	.string "Tiens, puisque tu es\n"
	.string "là, je vais en\p"
	.string "profiter. Tu peux me\n"
	.string "rendre un service, {PLAYER}?\p"
	.string "Choisis un POKéMON pour\n"
	.string "moi! J'hésite entre {STR_VAR_1} et {STR_VAR_2}.$"

gText_ApprenticeMonThanks8::
	.string "Waouh! Ça me fait\n"
	.string "plaisir, tu sais. C'est\l"
	.string "d'accord, je vais élever un\p"
	.string "{STR_VAR_1}. J'espère que tu me\n"
	.string "donneras encore plein de conseils!$"

gText_ApprenticeWhichMon9::
	.string "Hé, hé! {PLAYER}{KUN}, mon\n"
	.string "mentor! Je te\p"
	.string "cherchais, j'ai besoin\n"
	.string "de tes conseils\p"
	.string "éclairés! Quel POKéMON\n"
	.string "je devrais dresser, un {STR_VAR_1}\p"
	.string "ou un {STR_VAR_2}? Dis-moi, je te\n"
	.string "fais une confiance aveugle!$"

gText_ApprenticeMonThanks9::
	.string "Un {STR_VAR_1}! Je vais\n"
	.string "en capturer un\l"
	.string "en un tour de\p"
	.string "main! Merci!\n"
	.string "Hasta la vista!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, tu ne devineras jamais!\n"
	.string "J'ai capturé un POKéMON\p"
	.string "mirage! Mais non, ce\n"
	.string "n'est pas vrai! Ha, ha,\p"
	.string "ha! Tu as cinq minutes? Je\n"
	.string "voudrais te demander ton\l"
	.string "avis. Je ne sais pas quel\p"
	.string "POKéMON capturer. Si tu\n"
	.string "pouvais décider pour moi,\l"
	.string "ça m'arrangerait!\p"
	.string "J'hésite entre deux POKéMON.\n"
	.string "Lequel je dois choisir, {STR_VAR_1} ou {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "{STR_VAR_1}, tu dis? Je vais capturer\n"
	.string "l'autre, alors! Je rigole,\p"
	.string "bien sûr que je vais\n"
	.string "suivre ton conseil! Merci!\p"
	.string "J'espère que tu m'apprendras\n"
	.string "encore plein d'autres choses!$"

gText_ApprenticeWhichMon11::
	.string "Ohé, matelot! C'est le salut\n"
	.string "des marins, moussaillon! C'est\p"
	.string "moi, le MARIN chantant! J'ai\n"
	.string "une question pour toi, mon\p"
	.string "enfant. Les POKéMON en sont le\n"
	.string "sujet. Je compte sur toi, mon\p"
	.string "rouget! Je veux en capturer un,\n"
	.string "mais entre {STR_VAR_1} et {STR_VAR_2}, je ne sais\l"
	.string "lequel choisir! Qu'en penses-tu?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}? C'est décidé! C'est lui\n"
	.string "que je vais capturer! Tes\p"
	.string "conseils me sont précieux, {PLAYER}!\n"
	.string "Toi, tu as l'esprit belliqueux!$"

gText_ApprenticeWhichMon12::
	.string "Attention… Voici {PLAYER}!\p"
	.string "Mais que faire? Te\n"
	.string "parler, au risque de\p"
	.string "t'importuner? Mon choix\n"
	.string "est fait! Ça faisait\l"
	.string "longtemps, tu sais, que\l"
	.string "je te cherchais! Tu m'as\p"
	.string "compris? Oui, tu m'as\n"
	.string "compris! {STR_VAR_1}? {STR_VAR_2}? Quel\l"
	.string "dilemme! Lequel dois-je choisir?$"

gText_ApprenticeMonThanks12::
	.string "{STR_VAR_1}, tu dis? J'en\n"
	.string "suis ravi! {PLAYER}, je\p"
	.string "dois y aller!\n"
	.string "Pense à moi! A\p"
	.string "bientôt, j'espère!$"

gText_ApprenticeWhichMon13::
	.string "Oh, salut, {PLAYER}{KUN}... j'ai\n"
	.string "cette horrible migraine...\p"
	.string "J'ai dû m'inquiéter trop du genre\n"
	.string "de POKéMON que j'aurais dû lever.\p"
	.string ", les choses étant comme ça,\n"
	.string "Je veux que tu décides pour moi.\p"
	.string "{PLAYER}{KUN}, si je devais choisir\n"
	.string "entre le POKéMON {STR_VAR_1} et {STR_VAR_2},\l"
	.string "qui devrait-il être?$"

gText_ApprenticeMonThanks13::
	.string "{STR_VAR_1}? J'irai en capturer un dès\n"
	.string "que je me sentirai un peu\p"
	.string "mieux. Ça fait plaisir de\n"
	.string "pour de l'aide comme ça.$"

gText_ApprenticeWhichMon14::
	.string "Euh… Hum… {PLAYER}{KUN}? Ne me\n"
	.string "fixe pas comme ça, tu\p"
	.string "me rends nerveux…\n"
	.string "J'ai besoin d'un\l"
	.string "conseil. Ça me gêne de\p"
	.string "t'ennuyer avec ça, mais\n"
	.string "je ne sais pas quel\p"
	.string "POKéMON capturer. Lequel\n"
	.string "est le plus fort, {STR_VAR_1} ou {STR_VAR_2}?$"

gText_ApprenticeMonThanks14::
	.string "D'accord! Je vais\n"
	.string "capturer un {STR_VAR_1}. Avoir un\p"
	.string "POKéMON fort, choisi par\n"
	.string "toi, me donnera confiance\p"
	.string "lors des combats. Merci, {PLAYER}{KUN}.\n"
	.string "J'espère qu'on va se revoir,\l"
	.string "tu es vraiment de bon conseil.$"

gText_ApprenticeWhichMon15::
	.string "Tu ressembles beaucoup à\n"
	.string "{PLAYER}{KUN}… Mais… est-ce toi? Oh,\p"
	.string "désolé si je n'ai pas vu\n"
	.string "qui tu es tout de suite.\l"
	.string "J'ai justement un conseil\p"
	.string "à te demander. C'est au\p"
	.string "sujet du POKéMON que je\n"
	.string "veux utiliser. Des POKéMON {STR_VAR_1}\l"
	.string "et {STR_VAR_2}, lequel choisirais-tu?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}? Vraiment? Je te\n"
	.string "remercie, c'est\p"
	.string "très aimable de ta\n"
	.string "part. Je pense que\p"
	.string "tu as raison. C'est\n"
	.string "celui qui me convient\p"
	.string "le mieux. À bientôt!$"

gText_ApprenticeWhichMove0::
	.string "Oh, {PLAYER}! Sniff…\n"
	.string "Quel dilemme! Je\p"
	.string "n'arrive pas à\n"
	.string "choisir une\l"
	.string "capacité pour mon\p"
	.string "{STR_VAR_1}… S'il te plaît, {PLAYER}…\n"
	.string "Est-ce que tu\p"
	.string "peux décider pour\n"
	.string "moi? Pour mon {STR_VAR_1}, je\l"
	.string "dois choisir {STR_VAR_2} ou {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}? Sniff… Oh, je\n"
	.string "suis désolé, {PLAYER}! Je\p"
	.string "suis tellement\n"
	.string "ému que tu m'aies\l"
	.string "aidé à faire ce\p"
	.string "choix que je\n"
	.string "pleure… Sniff… Merci!$"

gText_ApprenticeWhichMove1::
	.string "Hé, {PLAYER}! J'ai encore\n"
	.string "besoin de toi! Je\p"
	.string "veux apprendre\n"
	.string "une capacité sympa\p"
	.string "à mon {STR_VAR_1}. J'aime\n"
	.string "autant {STR_VAR_2} que {STR_VAR_3}.\l"
	.string "Laquelle tu choisirais?$"

gText_ApprenticeMoveThanks1::
	.string "Tu préfères {STR_VAR_1}? Je vais lui\n"
	.string "enseigner cette capacité!\p"
	.string "J'espère qu'on se reverra, j'ai\n"
	.string "encore plein de trucs à apprendre!$"

gText_ApprenticeWhichMove2::
	.string "Bonjour, {PLAYER}! Je ne sais\n"
	.string "pas quelle capacité\l"
	.string "mon {STR_VAR_1} devrait\p"
	.string "apprendre. Tu vois,\n"
	.string "j'hésite entre {STR_VAR_2} et {STR_VAR_3}.\p"
	.string "Laquelle de ces deux\n"
	.string "capacités convient mieux à mon {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} est\n"
	.string "votre choix?\p"
	.string "Je vais tout de suite\n"
	.string "enseigner {STR_VAR_1} à mon POKéMON!\p"
	.string "A bientôt!$"

gText_ApprenticeWhichMove3::
	.string "Oh, {PLAYER}… Je suis\n"
	.string "désespérée! J'ai décidé\p"
	.string "de dresser un POKéMON,\n"
	.string "mais je ne sais pas\l"
	.string "quelle capacité lui\p"
	.string "apprendre… Je suis sûre\n"
	.string "que tu dois me trouver\p"
	.string "bête, {PLAYER}. Mais pour moi,\p"
	.string "c'est important… Dis, {PLAYER}.\n"
	.string "Tu pourrais choisir une\p"
	.string "capacité pour mon {STR_VAR_1}? En\n"
	.string "fait, j'hésite entre {STR_VAR_2} et {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "Je comprends!\p"
	.string "Mais sera-t-il même prêt à\n"
	.string "apprendre {STR_VAR_1} pour moi...\l"
	.string "Non! Je ferai de mon mieux!\p"
	.string "Je vous remercie!$"

gText_ApprenticeWhichMove4::
	.string "Oh, {PLAYER}{KUN}! Je me\n"
	.string "demandais\p"
	.string "quelle\n"
	.string "capacité je\p"
	.string "devrais\n"
	.string "enseigner à mon {STR_VAR_1}.\p"
	.string "Je n'arrive pas à\n"
	.string "me décider. Tu\l"
	.string "décides pour moi? {STR_VAR_2} ou {STR_VAR_3}?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? Super! Comme c'est\p"
	.string "ta décision, ce sera\n"
	.string "ta faute si ça rate,\l"
	.string "{PLAYER}{KUN}! Non, sérieusement.\p"
	.string "Je te fais\n"
	.string "entièrement confiance. Salut!$"

gText_ApprenticeWhichMove5::
	.string "Comment ça se fait que j'ai\n"
	.string "toujours un millier de choses\l"
	.string "à faire? Hé, {PLAYER}{KUN}! Ça va? J'ai\p"
	.string "déjà fait mon footing, nagé et\n"
	.string "fait à manger! La journée\p"
	.string "n'est pas finie! Si tu savais\p"
	.string "tout ce que j'ai encore à\n"
	.string "faire! Je n'ai même pas le temps\p"
	.string "de choisir une capacité pour mon\n"
	.string "{STR_VAR_1}! {STR_VAR_2} est pas mal, mais j'aime\p"
	.string "aussi {STR_VAR_3}. {PLAYER}{KUN}, choisis une de ces deux\n"
	.string "capacités pour moi, s'il te plaît!$"

gText_ApprenticeMoveThanks5::
	.string "D'accord. Je pense que\n"
	.string "j'arriverai à trouver un\l"
	.string "moment pour la lui enseigner.\p"
	.string "Je peux toujours compter sur\n"
	.string "toi. Merci! A la prochaine!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Encore toi! Je\n"
	.string "suis contente de te\l"
	.string "revoir, {PLAYER}! Tu vas\p"
	.string "pouvoir m'aider! Je\n"
	.string "voudrais te poser une\p"
	.string "question. La voici…\n"
	.string "Quelle capacité convient\l"
	.string "le mieux à mon {STR_VAR_1}? {STR_VAR_2} ou {STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ah! {STR_VAR_1}, tu dis? Je\n"
	.string "vais suivre ton\l"
	.string "conseil! Bon, c'est\p"
	.string "tout ce que j'avais à\n"
	.string "te demander, je crois.\p"
	.string "Mais on se reverra\n"
	.string "sûrement! Merci encore!$"

gText_ApprenticeWhichMove7::
	.string "Salut, {PLAYER}. Tu as l'air\n"
	.string "en pleine forme! Je\p"
	.string "voudrais te poser une\n"
	.string "question. C'est au\p"
	.string "sujet de mon {STR_VAR_1} adoré.\n"
	.string "Quelle est la capacité\l"
	.string "idéale pour mon petit {STR_VAR_1}, {STR_VAR_2} ou {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1}? D'accord! Je vais la\n"
	.string "lui apprendre tout de\p"
	.string "suite! Merci, {PLAYER}. Je\n"
	.string "savais que je pouvais\l"
	.string "compter sur toi. A bientôt!$"

gText_ApprenticeWhichMove8::
	.string "Eek! {PLAYER} Je t'ai\n"
	.string "encore rencontré!\p"
	.string "Chaque fois que j'ai besoin,\n"
	.string "tu es toujours là pour moi, {PLAYER}!\p"
	.string "Aujourd'hui, je veux que tu me\n"
	.string "recommandes un déménagement!\p"
	.string "Veuillez choisir un\n"
	.string "déménagement pour mon {STR_VAR_1}!\p"
	.string "Quel mouvement\n"
	.string "serait le mieux, {STR_VAR_2} ou {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Oh! Merci! Je vais lui\n"
	.string "enseigner {STR_VAR_1}! C'est un\l"
	.string "très bon choix!\p"
	.string "J'espère que tu me\n"
	.string "donneras encore plein de conseils!$"

gText_ApprenticeWhichMove9::
	.string "Bonjour, {PLAYER}{KUN}! Je vais\n"
	.string "encore te voler un\l"
	.string "conseil, aujourd'hui!\p"
	.string "Quelle capacité je dois\n"
	.string "enseigner à mon {STR_VAR_1}, d'après\p"
	.string "toi? Il me faut une capacité\n"
	.string "qui me permette de gagner à\p"
	.string "tous les coups! Je devrais\n"
	.string "choisir {STR_VAR_2} ou {STR_VAR_3}, d'après toi?$"

gText_ApprenticeMoveThanks9::
	.string "Va pour {STR_VAR_1}! Je vais lui\n"
	.string "enseigner ça en\l"
	.string "moins de temps qu'il\p"
	.string "ne faut pour le dire!\n"
	.string "Merci! Hasta la vista!$"

gText_ApprenticeWhichMove10::
	.string "Hé, {PLAYER}{KUN}, tu ne vas pas\p"
	.string "me croire! Mon\n"
	.string "POKéMON a appris six\p"
	.string "capacités d'un coup!\n"
	.string "Mais non, je rigole!\p"
	.string "Ha, ha, ha! En fait,\n"
	.string "je ne sais même pas\l"
	.string "quelle capacité je dois\p"
	.string "lui enseigner. Ce\n"
	.string "serait sympa si tu\p"
	.string "pouvais m'aider un peu. Je\n"
	.string "dois choisir {STR_VAR_2} ou {STR_VAR_3} pour mon {STR_VAR_1}?$"

gText_ApprenticeMoveThanks10::
	.string "D'accord, tu dis {STR_VAR_1}? Je vais\n"
	.string "lui enseigner l'autre, alors!\p"
	.string "Je rigole, bien sûr que je\n"
	.string "vais suivre ton conseil!\p"
	.string "Merci! J'espère que tu\n"
	.string "Apprends-moi encore beaucoup!$"

gText_ApprenticeWhichMove11::
	.string "Ohé, matelot! C'est le\n"
	.string "salut des marins,\p"
	.string "moussaillon! C'est moi, le\n"
	.string "MARIN chantant! car chanter,\p"
	.string "c'est bien tentant! J'ai une\n"
	.string "question sur les capacités.\p"
	.string "Je compte sur toi, mon\n"
	.string "rouget! A ton avis, il vaut\l"
	.string "mieux que j'enseigne {STR_VAR_2} ou {STR_VAR_3} à mon {STR_VAR_1}?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, tu dis? Je vais lui\n"
	.string "enseigner ça, pardi! Tes\p"
	.string "conseils me sont précieux, {PLAYER}!\n"
	.string "Toi, tu as l'esprit belliqueux!$"

gText_ApprenticeWhichMove12::
	.string "Mais, c'est {PLAYER}! Que\p"
	.string "faire? Te parler,\n"
	.string "au risque de\p"
	.string "t'importuner? Mon\n"
	.string "choix est fait! {PLAYER},\p"
	.string "j'ai encore besoin de\n"
	.string "ton avis! Tu m'as\p"
	.string "compris? Oui, tu m'as\n"
	.string "compris! Mon {STR_VAR_1}… Doit-il\l"
	.string "plutôt apprendre {STR_VAR_2} ou {STR_VAR_3}?$"

gText_ApprenticeMoveThanks12::
	.string "{STR_VAR_1}, tu dis? J'en\n"
	.string "suis ravi! {PLAYER}, je\p"
	.string "dois y aller!\n"
	.string "Pense à moi! A\p"
	.string "bientôt, j'espère!$"

gText_ApprenticeWhichMove13::
	.string "Cof, cof! Oh, {PLAYER}{KUN}…\n"
	.string "J'ai attrapé froid…\p"
	.string "La fièvre m'empêche\n"
	.string "de choisir une\p"
	.string "capacité pour mon\n"
	.string "POKéMON… Je crois bien\p"
	.string "que j'ai besoin de\n"
	.string "ton aide. {PLAYER}{KUN}, me\l"
	.string "conseilles-tu {STR_VAR_2} ou {STR_VAR_3} pour mon {STR_VAR_1}?$"

gText_ApprenticeMoveThanks13::
	.string "Cof! D'accord, {STR_VAR_1}. Dès que je\n"
	.string "serai guéri, je lui\p"
	.string "enseignerai. Ça fait plaisir de\n"
	.string "pour de l'aide comme ça.$"

gText_ApprenticeWhichMove14::
	.string "Euh… Hum… {PLAYER}{KUN}? Ne me\n"
	.string "fixe pas comme\p"
	.string "ça, tu me rends\n"
	.string "nerveux… J'ai\l"
	.string "besoin de toi, je\p"
	.string "crois… Ça me gêne…\n"
	.string "Je voudrais que\l"
	.string "tu m'aides à\p"
	.string "choisir une\n"
	.string "capacité. C'est pour\l"
	.string "mon {STR_VAR_1}. Tu choisirais {STR_VAR_2} ou {STR_VAR_3}?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… D'accord! Je vais\n"
	.string "essayer {STR_VAR_1}. J'espère que\p"
	.string "ça va marcher… Quel\n"
	.string "bonheur de parler avec\p"
	.string "toi! Merci, {PLAYER}{KUN}. J'espère\n"
	.string "qu'on va se revoir, tu es\l"
	.string "vraiment de bon conseil.$"

gText_ApprenticeWhichMove15::
	.string "Tiens? Tu ressembles à {PLAYER}{KUN}…\n"
	.string "La ressemblance est\p"
	.string "frappante. Serais-tu par\n"
	.string "hasard un sosie? Je suis\p"
	.string "confus, bien sûr que\n"
	.string "c'est toi. Je suis désolé\p"
	.string "d'avoir douté! J'ai\n"
	.string "justement un conseil à te\p"
	.string "demander. C'est au sujet\p"
	.string "de mon {STR_VAR_1}. Dois-je lui\n"
	.string "enseigner {STR_VAR_2} ou {STR_VAR_3}? Qu'en penses-tu?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}? C'est sûr? Je\n"
	.string "te remercie,\p"
	.string "c'est très\n"
	.string "aimable de ta\p"
	.string "part. Cela ne\n"
	.string "devrait pas poser de\p"
	.string "problème. À bientôt!$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… {PLAYER}? C'est {PLAYER}! Oh!\n"
	.string "Sniff… Ecoute… Dès que\l"
	.string "je me bats, je pleure…\p"
	.string "Je suis trop nerveux!\n"
	.string "Quand je gagne, Je\p"
	.string "voudrais arrêter de\n"
	.string "pleurer! Je devrais me\p"
	.string "détendre. Je sais, {PLAYER}! Si tu\n"
	.string "m'apprenais une phrase\l"
	.string "cool à dire quand je gagne?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1} Super, j'aime\p"
	.string "bien! Je suis sûr\n"
	.string "que ça va marcher!\p"
	.string "Oh… Je suis désolé…\n"
	.string "Je pleure de joie…\p"
	.string "Sniff… Merci\n"
	.string "infiniment, {PLAYER}! Je\p"
	.string "vais faire de mon\n"
	.string "mieux… En ton honneur,\p"
	.string "{PLAYER}! {PLAYER}… La prochaine\n"
	.string "fois… nous nous battrons!$"

gText_ApprenticePickWinSpeech1::
	.string "Salut, {PLAYER}! Justement, je\n"
	.string "voulais te poser une question!\p"
	.string "Quand je gagne un match, je ne\n"
	.string "sais jamais quoi dire. Tu\p"
	.string "n'aurais pas une expression ou\n"
	.string "une phrase que je pourrais dire?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1} C'est une super idée!\p"
	.string "La prochaine fois, je\n"
	.string "dirai ça! C'est gentil\p"
	.string "de m'aider! Je vais\n"
	.string "m'entraîner dur! Je\l"
	.string "veux te surprendre! La\p"
	.string "prochaine fois, on\n"
	.string "fera un combat, tu verras!$"

gText_ApprenticePickWinSpeech2::
	.string "Salut, {PLAYER}! Mes POKéMON\p"
	.string "et moi, on est gonflés\n"
	.string "à bloc! Mais il me\p"
	.string "manque une expression\n"
	.string "sympa à crier quand je\p"
	.string "gagne. Tu as une idée de\n"
	.string "ce que je pourrais dire?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1} Cool! Je prends! Je\p"
	.string "vais me battre et\n"
	.string "gagner! J'ai hâte\p"
	.string "d'utiliser ton\n"
	.string "expression! Qui sait,\p"
	.string "peut-être qu'un jour\n"
	.string "on se battra, {PLAYER}? Il\p"
	.string "faudra qu'on se\n"
	.string "rencontre dans un lieu de combat!$"

gText_ApprenticePickWinSpeech3::
	.string "Salut, {PLAYER}… Je suis désolée\n"
	.string "de te déranger, mais je\p"
	.string "suis désespérée… Même quand\n"
	.string "je gagne… Même quand je\l"
	.string "gagne, je ne sais pas quoi\p"
	.string "dire… Tu ne peux pas\n"
	.string "comprendre ce que je ressens,\p{PLAYER}"
	.string "{PLAYER}. Mais c'est important pour\p"
	.string "moi… Qu'est-ce que je\n"
	.string "Si je gagne une bataille?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1} C'est bien trouvé! Euh…\p"
	.string "Je ne suis pas sûre\p"
	.string "d'oser dire ça. Je suis\n"
	.string "trop timide… Je te\p"
	.string "promets d'essayer! Merci\p"
	.string "de m'avoir consacré un peu\n"
	.string "de ton temps, {PLAYER}… Je vais\p"
	.string "faire de mon mieux. Tu\p"
	.string "m'auras certainement oubliée\n"
	.string "dans quelques minutes, mais\l"
	.string "moi je ne t'oublierai pas!$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}! J'ai quelque chose à te\n"
	.string "dire. Je sais très bien que je ne\p"
	.string "suis pas toujours très polie ni\n"
	.string "très gentille… Alors quand je\p"
	.string "gagne un combat, j'ai peur qu'on\n"
	.string "me trouve arrogante. Je voudrais\p"
	.string "bien dire quelque chose de gentil\n"
	.string "à mon adversaire quand je gagne,\l"
	.string "mais je ne sais pas quoi! Je n'ai\p"
	.string "pas l'habitude de dire des\n"
	.string "Pouvez-vous me dire quelque chose?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1} Pas mal! C'est ce que je\p"
	.string "dirai dorénavant! Grâce à\n"
	.string "toi, je suis sûre de\p"
	.string "devenir super forte! Oh,\n"
	.string "j'ai dit une chose gentille!\l"
	.string "Je suis désolée pour toutes\p"
	.string "les fois où j'ai été un peu\n"
	.string "grossière avec toi. La\p"
	.string "prochaine fois, Je voudrais\n"
	.string "qu'on fasse un combat. À bientôt!$"

gText_ApprenticePickWinSpeech5::
	.string "J'ai toujours un millier de\n"
	.string "choses à faire! Je te cherchais, {PLAYER}{KUN}.\p"
	.string "Tu as l'air en forme. Je suis\n"
	.string "toujours en vadrouille, je tiens\p"
	.string "la forme aussi. Au programme\n"
	.string "d'aujourd'hui: combats,\p"
	.string "cartographie et pêche. Je n'arrête\n"
	.string "pas! Malgré tout, Je voudrais\l"
	.string "prendre le temps de saluer mon\p"
	.string "adversaire quand je gagne un\n"
	.string "combat. Tu as une idée de ce que\l"
	.string "et s'en aller? {PLAYER}{KUN}, aide-moi!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1} Merci, je peux bien\p"
	.string "prendre une seconde pour\n"
	.string "dire ça! Tu m'as\p"
	.string "beaucoup appris, je te\n"
	.string "remercie. Maintenant, il\p"
	.string "faut que je me concentre\n"
	.string "sur les combats. Merci\p"
	.string "pour tout, {PLAYER}{KUN}! Il faudra\n"
	.string "qu'on se batte, tous les deux!$"

gText_ApprenticePickWinSpeech6::
	.string "J'ai de la chance, en ce\n"
	.string "moment! Je suis contente de te\l"
	.string "voir, {PLAYER}! Bien sûr, j'ai une\p"
	.string "question à te poser… Alors\n"
	.string "voilà! Ma question est… Quand je\p"
	.string "gagne un combat, Je voudrais\n"
	.string "finir en beauté, genre star de\l"
	.string "Devrais-je le dire?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1} C'est… tout simplement\p"
	.string "magnifique! Tout à fait\n"
	.string "ce qu'il me faut! Dis\p"
	.string "donc, je pense que je fais\n"
	.string "des progrès. J'ai décidé\p"
	.string "de me consacrer à ma\n"
	.string "carrière de DRESSEUR.\p"
	.string "C'est grâce à toi, {PLAYER}.\p"
	.string "Peut-être qu'un jour nous\n"
	.string "aurons l'occasion de nous\p"
	.string "Merci pour tout!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}. Je suis si contente de\n"
	.string "te connaître! Grâce à toi,\p"
	.string "j'ai pleinement confiance en\n"
	.string "mes POKéMON. Mais j'ai un\p"
	.string "petit souci… Les DRESSEURS\p"
	.string "disent toujours quelque\n"
	.string "chose quand ils gagnent un\p"
	.string "combat. Moi aussi, Je\n"
	.string "voudrais faire ça, mais je ne\p"
	.string "sais pas quoi dire! Est-ce que\n"
	.string "tu as quelque chose à me suggérer?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1} J'aime beaucoup, merci!\p"
	.string "Ça m'a mise de bonne\n"
	.string "humeur! Je brûle\p"
	.string "d'impatience de dire ça!\p"
	.string "Malheureusement, je dois\n"
	.string "m'en aller, {PLAYER}… J'ai à\p"
	.string "faire! Je vais me battre\n"
	.string "sans relâche, mais jamais\p"
	.string "je ne t'oublierai. On se\n"
	.string "reverra peut être… À bientôt!$"

gText_ApprenticePickWinSpeech8::
	.string "Bonjour, {PLAYER}! Je suis toujours\n"
	.string "ravie de te voir! Je\p"
	.string "voudrais te poser une\n"
	.string "question, puisque tu es là!\p"
	.string "L'autre fois, j'ai gagné un\n"
	.string "combat. C'était grisant!\p"
	.string "J'étais tellement surprise que\n"
	.string "je n'ai pas su quoi dire! Tu\p"
	.string "as une réplique à me suggérer\n"
	.string "pour mes prochaines victoires, {PLAYER}?$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1} Superbe! Je vais dire\p"
	.string "ça! Je suis tellement\n"
	.string "heureuse! Merci! Tu as\l"
	.string "changé ma vie! A partir\p"
	.string "d'aujourd'hui, je\n"
	.string "consacrerai ma vie aux\p"
	.string "combats de POKéMON. Je\n"
	.string "te dois tout, {PLAYER}. Je ne te\p"
	.string "remercierai jamais assez!\n"
	.string "Il faut que je me sauve.\p"
	.string "Peut-être aurons-nous\n"
	.string "l'occasion de nous battre!$"

gText_ApprenticePickWinSpeech9::
	.string "Bonjour, {PLAYER}{KUN}! Tu sais, je\n"
	.string "vais bientôt me consacrer\p"
	.string "entièrement aux combats.\n"
	.string "Mais j'ai encore besoin\p"
	.string "d'un dernier petit\n"
	.string "conseil! Si jamais je\p"
	.string "gagne un combat, je ne\n"
	.string "saurai pas quoi dire à mon\l"
	.string "adversaire… Tu as une suggestion?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1} Ça me plaît, ça! J'ai\p"
	.string "hâte de gagner,\n"
	.string "maintenant! Juste pour\l"
	.string "pouvoir dire ça! Il est\p"
	.string "temps de se dire À\n"
	.string "bientôt… Merci pour\p"
	.string "tout! On se battra un\n"
	.string "jour, d'accord? Hasta la vista!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, écoute ça! A chaque\p"
	.string "fois que je gagne un\n"
	.string "combat, je fais un long\p"
	.string "discours! Mais non, je\n"
	.string "rigole! Ha, ha, ha! En\p"
	.string "fait, c'est l'inverse.\n"
	.string "Je ne sais jamais quoi\p"
	.string "dire. Tu ne voudrais pas\n"
	.string "me trouver quelque chose\l"
	.string "à dire à chaque victoire?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1} Ça ne va pas? Tu veux\p"
	.string "vraiment que je dise ça?!?\n"
	.string "Non, je plaisante! Je\p"
	.string "dirai ça à chaque\n"
	.string "victoire! Merci pour tout,\p"
	.string "tu m'as beaucoup appris\n"
	.string "depuis qu'on se connaît!\p"
	.string "Grâce à toi, j'ai compris\n"
	.string "ce qu'était un DRESSEUR. Je\p"
	.string "vais défier tous les\n"
	.string "DRESSEURS que je\p"
	.string "rencontrerai. Peut-être en\p"
	.string "feras-tu partie, qui sait? C'est\n"
	.string "Adieu, mon maître!$"

gText_ApprenticePickWinSpeech11::
	.string "Ohé, matelot! C'est le\n"
	.string "des marins, moussaillon!\p"
	.string "C'est moi, le MARIN\n"
	.string "chantant! J'ai une dernière\l"
	.string "question. Fais bien attention!\p"
	.string "Les victoires en sont le\n"
	.string "sujet. Je compte sur toi, mon\p"
	.string "rouget! Quand je gagne un\n"
	.string "D'une manière vraiment cool?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1} Crois-moi, je vais le dire,\p"
	.string "cela va sans dire! Tu sais,\n"
	.string "j'ai bien réfléchi… Aux\p"
	.string "POKéMON, je veux consacrer ma\n"
	.string "vie!!! Merci pour tous tes\p"
	.string "enseignements. Te connaître\n"
	.string "fut si enrichissant! Il est\p"
	.string "temps pour moi de lever\n"
	.string "l'ancre! Souhaite-moi bon voyage,\l"
	.string "C'est mon hommage!$"

gText_ApprenticePickWinSpeech12::
	.string "Bonjour, {PLAYER}! Comme on se\n"
	.string "retrouve! Que faire? Te\p"
	.string "parler, au risque de\n"
	.string "t'importuner? Mon choix\p"
	.string "est fait! {PLAYER}, tu m'as\n"
	.string "compris? Oui, tu m'as\l"
	.string "compris! Je veux ton avis!\l"
	.string "C'est à propos de mon cri\p"
	.string "de victoire. Que\n"
	.string "pourrais-je bien dire? Dans\l"
	.string "ma tête, c'est le\p"
	.string "Allez, je veux que tu le dises!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1} car tu me l'as suggéré,\p"
	.string "c'est ce cri de victoire\n"
	.string "que je vais utiliser! Je\p"
	.string "n'ai rien à te demander.\n"
	.string "Pour moi, tu en as déjà\p"
	.string "tellement fait. Peut-être que\n"
	.string "nous nous reverrons… Et\p"
	.string "alors, nous combattrons! A\p"
	.string "présent, je te prie de\n{PLAYER}"
	.string "m'excuser. {PLAYER}, je dois y aller!\p"
	.string "Pense à moi! Prends bien soin de\n"
	.string "Je t'aime!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, c'est horrible… Mon nez\n"
	.string "n'arrête pas de couler… J'essayais\p"
	.string "de trouver une belle phrase à\n"
	.string "proclamer en cas de victoire. Ça\p"
	.string "m'a tellement ému que je me suis\n"
	.string "mis à pleurer… Les vannes sont\p"
	.string "ouvertes! Je ne peux pas continuer\n"
	.string "comme ça. Je n'y arriverai pas\p"
	.string "sans toi, {PLAYER}{KUN}. Si je gagne un combat,\n"
	.string "Que devrais-je dire?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1} Que c'est beau…\p"
	.string "J'aime beaucoup! J'en\n"
	.string "ai les larmes aux yeux!\l"
	.string "Même si je pleure, que\p"
	.string "j'ai le nez qui coule,\n"
	.string "je dirai ça! Je n'ai\p"
	.string "plus rien à te demander,\n"
	.string "{PLAYER}{KUN}. Désormais, nous\p"
	.string "sommes rivaux! Ma vie a\n"
	.string "changé, grâce à toi… Merci!$"

gText_ApprenticePickWinSpeech14::
	.string "Euh… Hum… {PLAYER}{KUN}… Ne me fixe\n"
	.string "pas comme ça, tu me\p"
	.string "rends nerveux… J'ai\n"
	.string "besoin de toi… Pour la\p"
	.string "dernière fois! Ça me\n"
	.string "gêne de t'en parler…\p"
	.string "Je ne sais pas quoi\n"
	.string "dire quand je gagne. Tu\l"
	.string "n'aurais pas une idée?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1} Oh… D'accord! Je\p"
	.string "dirai ça quand je\n"
	.string "gagnerai! Enfin, si je\l"
	.string "ne suis pas trop\p"
	.string "nerveux… Merci, {PLAYER}{KUN}. Je dois\n"
	.string "te faire mes adieux. Ma\p"
	.string "vie de DRESSEUR\n"
	.string "commence. Et c'est grâce à toi, {PLAYER}{KUN}.$"

gText_ApprenticePickWinSpeech15::
	.string "Vous semblez être {PLAYER}{KUN}...\n"
	.string "Mais êtes-vous bien?\l"
	.string "Peut-être une DOLL intelligente {PLAYER}?\p"
	.string "Oh, non, non, non, ne\n"
	.string "t'inquiète pas! Si tu es bien\l"
	.string "réel, oublie ma grossièreté.\p"
	.string "Pas besoin d'être si en colère,\n"
	.string "est plus de votre bon conseil.\p"
	.string "Ça concerne un dicton.\p"
	.string "Plus précisément, que devrais-je\n"
	.string "dire si je gagne une bataille?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1} … … … … … … En cas\p"
	.string "de victoire… {STR_VAR_1}\n"
	.string "Sérieusement? Je te\p"
	.string "remercie, c'est\p"
	.string "très aimable de ta\p"
	.string "part. J'en ferai\n"
	.string "bon usage. C'est\p"
	.string "promis! Il me\n"
	.string "semble que je n'ai\p"
	.string "plus rien à te\n"
	.string "demander. Je dois\p"
	.string "voler de mes propres\n"
	.string "ailes, à présent! Merci\p"
	.string "pour tout! Je regrette\n"
	.string "d'avoir douté de toi.$"
