
#if IS_HNS
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue à la TENTE DE COMBAT!\p"
	.string "Je guide le TOURNOI K.O.!$"
#else
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue à la TENTE DE COMBAT\n"
	.string "DE FALLARBOR!\p"
	.string "Je guide le TOURNOI K.O.!$"
#endif

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Voulez-vous relever le défi du\n"
	.string "TOURNOI K.O.?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Nous attendrons votre prochain\n"
	.string "défi!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
#if IS_HNS
	.string "Dans la TENTE DE COMBAT : ARÈNE,\n"
#else
	.string "TENTE DE COMBAT DE FALLARBOR:\n"
#endif
	.string "se tient le TOURNOI K.O.\p"
	.string "Chaque participant engage une\n"
	.string "équipe de trois POKéMON.\p"
	.string "Ces trois POKéMON doivent être\n"
	.string "placés dans leur ordre de passage.\p"
	.string "Ils combattront un par un, dans\n"
	.string "l'ordre préalablement choisi.\p"
	.string "Une fois en combat, un POKéMON\n"
	.string "reste jusqu'à la fin de la manche.\p"
	.string "Si rien n'est décidé après trois\n"
	.string "tours, un jury vous départagera.\p"
	.string "Pour interrompre votre défi,\n"
	.string "veuillez sauvegarder la partie.\p"
	.string "Sans sauvegarde, vous ne pourrez\n"
	.string "pas reprendre votre défi.\p"
	.string "Si vous parvenez à battre\n"
	.string "trois DRESSEURS à la suite,\l"
	.string "vous recevrez un superbe prix.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Avant de vous conduire à la TENTE\n"
	.string "DE COMBAT, je dois sauvegarder.$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Deux niveaux sont proposés:\n"
	.string "Niveau 50 et Niveau Libre.\l"
	.string "Lequel choisissez-vous?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Très bien. Choisissez maintenant\n"
	.string "vos trois POKéMON.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Très cher challenger!\p"
	.string "Vous n'avez pas les trois POKéMON\n"
	.string "requis pour participer.\p"
	.string "Ils ne doivent pas non plus tenir\n"
	.string "des objets identiques.\p"
	.string "Les ŒUFS{STR_VAR_1}.\p"
	.string "Quand vous serez fin prêt,\n"
	.string "revenez nous voir.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Très cher challenger!\p"
	.string "Vous n'avez pas les trois POKéMON\n"
	.string "requis pour participer.\p"
	.string "Vous devez apporter trois espèces\n"
	.string "de POKéMON différentes.\p"
	.string "Ils ne doivent pas non plus tenir\n"
	.string "des objets identiques.\p"
	.string "Les ŒUFS{STR_VAR_1}.\p"
	.string "Quand vous serez fin prêt,\n"
	.string "revenez nous voir.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Je vais vous conduire à la\n"
	.string "TENTE DE COMBAT.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Très cher challenger!\p"
	.string "Vous n'avez pas sauvegardé avant\n"
	.string "d'éteindre, n'est-ce pas?\p"
	.string "C'est regrettable, mais cela vaut\n"
	.string "disqualification de votre défi.\l"
	.string "Quel dommage!\p"
	.string "Vous pouvez bien sûr en commencer\n"
	.string "un nouveau.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Splendide! Vous avez battu trois\n"
	.string "DRESSEURS à la suite!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Patientez pendant la sauvegarde.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Pour vos trois victoires de suite,\n"
	.string "nous vous offrons ce prix.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} reçoit le prix:\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh?\n"
	.string "Votre SAC semble plein.\p"
	.string "Libérez de la place et revenez\n"
	.string "chercher votre prix.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Merci beaucoup d'avoir participé!\p"
	.string "Patientez pendant la sauvegarde.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Nous attendrons votre prochain\n"
	.string "défi!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Nous attendions votre arrivée\n"
	.string "avec impatience.\p"
	.string "Avant d'entrer dans la TENTE DE\n"
	.string "COMBAT, je dois sauvegarder.$"

#if IS_HNS
VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue à la TENTE DE COMBAT!\p"
	.string "Ici, la confiance du DRESSEUR\n"
	.string "en ses POKéMON est testée.$"
#else
VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue à la TENTE DE COMBAT\n"
	.string "DE VERDANTURF!\p"
	.string "Ici, la confiance du DRESSEUR\n"
	.string "en ses POKéMON est testée.$"
#endif
VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
#if IS_HNS
	.string "Le défi PALAIS de la\n"
#else
	.string "Le défi VERDANTURF de la\n"
#endif
	.string "TENTE DE COMBAT vous tente?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
#if IS_HNS
	.string "Dans la TENTE DE COMBAT : PALAIS,\n"
#else
	.string "TENTE DE COMBAT DE VERDANTURF:\n"
#endif
	.string "une règle cruciale doit être\l"
	.string "respectée.\p"
	.string "Les DRESSEURS peuvent uniquement\n"
	.string "changer de POKéMON.\p"
	.string "Ils ne peuvent donner aucun autre\n"
	.string "ordre à leurs POKéMON.\p"
	.string "Les POKéMON agissent selon leur\n"
	.string "nature et combattent seuls.\p"
	.string "Vous devez leur faire confiance\n"
	.string "et veiller sur eux.\p"
	.string "Si vous avez l'honneur de battre\n"
	.string "trois DRESSEURS à la suite,\l"
	.string "nous vous offrirons un prix.\p"
	.string "Pour interrompre votre défi,\n"
	.string "veuillez sauvegarder la partie.\p"
	.string "Sans sauvegarde avant l'arrêt,\n"
	.string "vous serez disqualifié.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Revenez avec un cœur et des\n"
	.string "POKéMON plus forts.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Il existe deux difficultés:\n"
	.string "Niveau 50 et Niveau Libre.\l"
	.string "Laquelle choisissez-vous?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Soupir…\p"
	.string "Vous n'avez pas les trois POKéMON\n"
	.string "requis pour ce défi.\p"
	.string "Vous devez présenter trois espèces\n"
	.string "de POKéMON différentes.\p"
	.string "Ils ne doivent pas non plus tenir\n"
	.string "des objets identiques.\p"
	.string "Les ŒUFS{STR_VAR_1}.\p"
	.string "Quand vous serez fin prêt,\n"
	.string "revenez nous voir.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Soupir…\p"
	.string "Vous n'avez pas les trois POKéMON\n"
	.string "requis pour ce défi.\p"
	.string "Vous devez présenter trois espèces\n"
	.string "de POKéMON différentes.\p"
	.string "Ils ne doivent pas non plus tenir\n"
	.string "des objets identiques.\p"
	.string "Les ŒUFS{STR_VAR_1}.\p"
	.string "Quand vous serez fin prêt,\n"
	.string "revenez nous voir.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Bien. Choisissez maintenant vos\n"
	.string "trois POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Je dois sauvegarder avant de vous\n"
	.string "conduire à la TENTE DE COMBAT.$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Bien.\n"
	.string "Suivez-moi.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Ce fut un honneur d'assister aux\n"
	.string "exploits de vos POKéMON.\p"
	.string "Les résultats seront enregistrés.\n"
	.string "Veuillez patienter un instant.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Trois victoires de suite…\p"
	.string "Les liens qui unissent votre cœur\n"
	.string "à vos POKéMON sont forts et vrais.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Votre exploit sera enregistré.\n"
	.string "Veuillez patienter un instant.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Pour vos trois victoires de suite,\n"
	.string "nous vous offrons ce prix.$"


#if IS_HNS
SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue à la TENTE DE COMBAT!\p"
	.string "Je guide le TOURNOI COMBAT\n"
	.string "ÉCHANGE.$"
#else
SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue à la TENTE DE COMBAT\n"
	.string "DE POIVRESSEL!\p"
	.string "Je guide le TOURNOI COMBAT\n"
	.string "ÉCHANGE.$"
#endif


SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Voulez-vous relever le défi\n"
	.string "COMBAT ÉCHANGE?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
#if IS_HNS
	.string "Dans la TENTE DE COMBAT : USINE,\n"
#else
	.string "TENTE DE COMBAT DE POIVRESSEL:\n"
#endif
	.string "on dispute des COMBATS ÉCHANGE\l"
	.string "avec des POKéMON de location.\p"
	.string "On vous prêtera d'abord trois\n"
	.string "POKéMON réservés à cette épreuve.\p"
	.string "Avec ces POKéMON de location,\n"
	.string "vous livrerez un COMBAT SOLO.\p"
	.string "Après une victoire, vous pourrez\n"
	.string "échanger un POKéMON de location.\p"
	.string "Répétez combats et échanges.\n"
	.string "Trois victoires de suite vous\l"
	.string "vaudront un superbe prix.\p"
	.string "Pour interrompre votre défi,\n"
	.string "veuillez sauvegarder la partie.\p"
	.string "Sans sauvegarde avant l'arrêt,\n"
	.string "vous serez disqualifié.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Nous espérons vous revoir bientôt.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Quel niveau voulez-vous tenter?\n"
	.string "Niveau 50 ou Niveau 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Avant de commencer le défi,\n"
	.string "je dois sauvegarder. D'accord?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Bien. Je garderai vos POKéMON\n"
	.string "en sécurité pendant l'épreuve.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Par ici, s'il vous plaît.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Merci d'avoir participé!\p"
	.string "Je vous rends vos POKéMON contre\n"
	.string "nos POKéMON de location.\p"
	.string "Je dois aussi sauvegarder vos\n"
	.string "résultats. Veuillez patienter.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Je vous rends vos POKéMON contre\n"
	.string "nos POKéMON de location.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Félicitations!\n"
	.string "Trois victoires de suite!\p"
	.string "Je vous rends vos POKéMON contre\n"
	.string "nos POKéMON de location.\p"
	.string "Je dois aussi sauvegarder vos\n"
	.string "résultats. Veuillez patienter.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "Pour vos trois victoires de suite,\n"
	.string "nous vous offrons ce prix.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh?\n"
	.string "Vous n'avez pas assez de place.\p"
	.string "Libérez de la place dans votre SAC\n"
	.string "et revenez me voir.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Nous vous attendions!\p"
	.string "Avant de reprendre votre défi,\n"
	.string "je dois sauvegarder la partie.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Navré, mais vous n'avez pas\n"
	.string "sauvegardé avant de quitter.\p"
	.string "Vous êtes donc disqualifié de\n"
	.string "votre défi.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Nous vous rendons vos POKéMON.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} reçoit le prix:\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Règles du COMBAT ÉCHANGE.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quelle rubrique voulez-vous lire?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "En COMBAT ÉCHANGE, vous ne pouvez\n"
	.string "utiliser que trois POKéMON.\p"
	.string "En location comme en échange,\n"
	.string "votre équipe ne peut comprendre\l"
	.string "deux POKéMON de la même espèce.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Vous ne pouvez échanger qu'avec\n"
	.string "le DRESSEUR tout juste vaincu.\p"
	.string "Seuls les POKéMON utilisés par ce\n"
	.string "DRESSEUR peuvent être échangés.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Après chaque victoire, vous pouvez\n"
	.string "prendre un POKéMON de l'adversaire\l"
	.string "vaincu en échange d'un des vôtres.\p"
	.string "Aucun échange n'est possible avec\n"
	.string "le troisième DRESSEUR du tournoi.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Deux points sont à retenir lors\n"
	.string "d'un échange de POKéMON.\p"
	.string "D'abord, vous ne pouvez pas voir\n"
	.string "les stats du POKéMON que vous\l"
	.string "allez recevoir.\p"
	.string "Ensuite, vos POKéMON sont rangés\n"
	.string "selon l'ordre dans lequel vous les\l"
	.string "avez loués.\p"
	.string "Cet ordre ne change pas, même\n"
	.string "après un échange.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Tous les POKéMON de la TENTE DE\n"
	.string "COMBAT DE POIVRESSEL sont loués.\p"
	.string "Tous les POKéMON de location sont\n"
	.string "au niveau 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Voici les règles de la TENTE DE\n"
	.string "COMBAT DE VERDANTURF.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quelle rubrique voulez-vous lire?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "TENTE DE COMBAT DE VERDANTURF:\n"
	.string "les POKéMON doivent réfléchir et\l"
	.string "combattre seuls.\p"
	.string "À l'inverse des POKéMON sauvages,\n"
	.string "ceux qui vivent avec les humains\l"
	.string "agissent selon leur nature.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Selon sa nature, un POKéMON peut\n"
	.string "toujours préférer attaquer.\p"
	.string "Un autre peut préférer se protéger\n"
	.string "contre tout danger.\p"
	.string "Un autre encore peut aimer gêner\n"
	.string "ou dérouter ses adversaires.\p"
	.string "Selon sa nature, un POKéMON aura\n"
	.string "des capacités favorites qu'il sait\l"
	.string "bien utiliser.\p"
	.string "Il pourra aussi détester certaines\n"
	.string "capacités difficiles à utiliser.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Les capacités offensives infligent\n"
	.string "des dégâts directs à l'adversaire.\p"
	.string "Les capacités défensives servent\n"
	.string "à anticiper les attaques ennemies\l"
	.string "ou à récupérer des PV, notamment.\p"
	.string "Il existe aussi des capacités\n"
	.string "qui affaiblissent l'ennemi avec\l"
	.string "des altérations comme le poison ou\l"
	.string "la paralysie.\p"
	.string "Les POKéMON choisissent parmi ces\n"
	.string "trois catégories de capacités.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Sans les ordres de son DRESSEUR,\n"
	.string "un POKéMON peut mal utiliser\l"
	.string "certaines capacités.\p"
	.string "Un POKéMON maîtrise mal les\n"
	.string "capacités qu'il n'aime pas.\p"
	.string "S'il ne connaît que des capacités\n"
	.string "contraires à sa nature, il aura\l"
	.string "du mal à montrer son potentiel.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Selon sa nature, un POKéMON en\n"
	.string "difficulté peut user de capacités\l"
	.string "qui ne lui ressemblent pas.\p"
	.string "S'il agit bizarrement quand il\n"
	.string "est en danger, observez-le bien.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "Dans cette TENTE DE COMBAT, le\n"
	.string "niveau de vos adversaires s'adapte\l"
	.string "à celui de vos POKéMON.\p"
	.string "Toutefois, aucun DRESSEUR affronté\n"
	.string "n'aura aucun POKéMON sous niv. 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Voici les règles de la TENTE DE\n"
	.string "COMBAT DE VERDANTURF.$"

BattleTentLobby_Text_EarnedBattlePoints:
	.string "Vous gagnez {STR_VAR_1} POINTS DE COMBAT!$"
