PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "PAPA : Salut, {PLAYER} !\p"
	.string "J'ai reçu une BAIE très rare.\n"
	.string "J'aimerais te la donner.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Si tu vois des BAIES dans un sol\n"
	.string "meuble, tu peux les cueillir.\p"
	.string "Mais replante une BAIE au même\n"
	.string "endroit. C'est l'usage.\p"
	.string "Tiens, partageons celle-ci.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "À te voir, tu dois être un\n"
	.string "DRESSEUR, non ?\p"
	.string "Les DRESSEURS donnent souvent des\n"
	.string "BAIES à tenir aux POKéMON.\p"
	.string "À toi : cultiver les BAIES\n"
	.string "ou les utiliser.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "J'ai arrosé chaque jour.\n"
	.string "Elles ont donné plein de fleurs.\p"
	.string "Et aussi beaucoup de BAIES.\p"
	.string "Tiens !\n"
	.string "Elle est pour toi !$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Je vais tout faire pour obtenir\n"
	.string "des BAIES de différentes couleurs.\p"
	.string "Fais de ton mieux, toi aussi !$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Quelle couleur de BAIES vais-je\n"
	.string "chercher aujourd'hui ?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "J'adore la machine BERRY CRUSH,\n"
	.string "alors je collectionne les BAIES.\p"
	.string "Je t'en donne une, si tu veux.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Essaie la machine BERRY CRUSH\n"
	.string "avec tes amis.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Quelle BAIE faut-il planter ?\n"
	.string "Utiliser ou garder ses BAIES ?\p"
	.string "C'est amusant d'y réfléchir.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "Les BAIES grandissent au soleil.\p"
	.string "Nous les aidons à pousser en les\n"
	.string "arrosant régulièrement.\p"
	.string "C'est une preuve d'amour, non ?$"

Route120_Text_YesYouUnderstand:
	.string "Oui, oui.\n"
	.string "Tu comprends ce que je veux dire.\p"
	.string "Tu devrais prendre ceci.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… Mais fais-toi ta propre\n"
	.string "opinion, j'imagine…\p"
	.string "Tu peux prendre ceci.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Je crois que cette BAIE est rare.\n"
	.string "Cultive-la avec beaucoup d'amour.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Le MAÎTRE DES BAIES m'en donnera\n"
	.string "d'autres.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "À bien y réfléchir…\p"
	.string "Comme ce costume me va à ravir,\n"
	.string "la brise fraîche sied à la mer.\p"
	.string "Et toi, une BAIE te va à ravir…\p"
	.string "Pourquoi donc ?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "À bien y réfléchir…\p"
	.string "Parce que tu es DRESSEUR !$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "À bien y réfléchir…\p"
	.string "Comme la sobriété me va à ravir,\n"
	.string "les {POKEBLOCK}S vont aux POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Appelle-moi le MAÎTRE DES BAIES.\p"
	.string "Je rêve de couvrir le monde de\n"
	.string "belles fleurs. Je cultive donc des\l"
	.string "BAIES et j'en offre à tous.\p"
	.string "Tu en mérites une !$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Pourquoi être radin ?\n"
	.string "Prends-en une autre !$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Visite la boutique PRETTY PETAL\n"
	.string "près de RUSTBORO.\p"
	.string "Que les fleurs couvrent le monde !$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "J'ai fini pour aujourd'hui.\n"
	.string "Reviens un autre jour.\p"
	.string "Que les fleurs couvrent le monde !$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Mon mari excelle avec les BAIES,\n"
	.string "c'est le meilleur du monde.\p"
	.string "Il me rend si fière.\p"
	.string "Au fait, mon enfant, as-tu entendu\n"
	.string "un bon dicton récemment ?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah ! Quel dicton remarquable !\n"
	.string "Quelle inspiration !\p"
	.string "Je veux t'offrir ceci.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh ! Voilà un bon dicton.\n"
	.string "Tu es remarquable.\p"
	.string "Je veux t'offrir ceci.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Nos quatre petits-enfants doivent\n"
	.string "surpasser mon mari.\p"
	.string "Ma vie déborde de joie !$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Bonjour !\p"
	.string "Bienvenue chez PRETTY PETAL.\n"
	.string "Des fleurs dans le monde entier !$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, veux-tu parler des\n"
	.string "BAIES ?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Comment t'appelles-tu ?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Quel joli nom.\p"
	.string "{PLAYER}{KUN}, veux-tu parler des\n"
	.string "BAIES ?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Les BAIES poussent sur des arbres\n"
	.string "qui aiment les sols meubles.\p"
	.string "Après la cueillette des BAIES,\n"
	.string "replante-en une dans le sol.\p"
	.string "Une BAIE plantée germe vite,\n"
	.string "pousse, devient plante et fleurit,\l"
	.string "puis redonne des BAIES.\p"
	.string "Je veux voir le vaste monde\n"
	.string "rempli de fleurs magnifiques.\l"
	.string "C'est mon rêve.\p"
	.string "{PLAYER}{KUN}, plante des BAIES\n"
	.string "et couvre le monde de fleurs.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Les fleurs rendent les gens si\n"
	.string "heureux, tu ne trouves pas ?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Bonjour !\p"
	.string "Plus tu prends soin des fleurs,\n"
	.string "plus elles s'épanouissent.\p"
	.string "Tu aimeras t'en occuper, j'en suis\n"
	.string "sûre. Tiens, c'est pour toi.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Pendant la croissance des BAIES,\n"
	.string "arrose-les avec le WAILMERROSOIR.\p"
	.string "Oh, autre chose.\p"
	.string "Si tu ne cueilles pas les BAIES,\n"
	.string "elles finissent par tomber au sol.\l"
	.string "Mais elles germeront à nouveau.\p"
	.string "C'est incroyable, non ?\n"
	.string "Comme si elles voulaient vivre.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Je veux imiter mes grandes sœurs.\n"
	.string "Moi aussi, je cultive des fleurs !\p"
	.string "Tiens !\n"
	.string "C'est pour toi !$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Tu peux faire pousser une BAIE,\n"
	.string "ou la donner à un POKéMON.\p"
	.string "Il existe aussi une machine qui\n"
	.string "change les BAIES en bonbons\l"
	.string "pour POKéMON.\p"
	.string "Moi aussi, je veux des bonbons.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Salut, comment t'appelles-tu ?\p"
	.string "… … …  … … …  … … …\n"
	.string "D'accord. C'est joli !\p"
	.string "Moi, c'est KIRI.\p"
	.string "Mes parents ont choisi ce nom pour\n"
	.string "que je grandisse en bonne santé et\l"
	.string "avec bon cœur. Tel était leur vœu.\p"
	.string "Tu peux en prendre une.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI te donne aussi cette BAIE !\n"
	.string "Je l'aime vraiment beaucoup !$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Quel vœu se cache donc\n"
	.string "dans ton nom.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Printemps, été, automne et hiver.\p"
	.string "Naître au printemps fait-il aimer\n"
	.string "le printemps ? Et quand on naît en\l"
	.string "été, aime-t-on l'été ?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Alors KIRI est née en automne,\n"
	.string "car j'adore l'automne !\p"
	.string "Quelle saison aimes-tu ?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "Ce n'est pas grave…\p"
	.string "Je veux savoir tant de choses…$"
