gText_Birch_Welcome::
	.string "Salut ! Désolé pour l'attente !\p"
	.string "Bienvenue chez les POKéMON !\p"
	.string "Je m'appelle BIRCH.\p"
	.string "Tout le monde m'appelle PROFESSEUR\n"
	.string "POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Voici ce qu'on appelle un POKéMON.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ce monde abrite de nombreuses\n"
	.string "créatures appelées POKéMON.\p"
	.string "Nous vivons aux côtés des POKéMON,\n"
	.string "parfois comme de bons camarades,\l"
	.string "parfois comme des collègues.\p"
	.string "Parfois, nous faisons aussi équipe\n"
	.string "pour affronter d'autres groupes.\p"
	.string "Mais malgré cette proximité, nous\n"
	.string "ignorons beaucoup sur les POKéMON.\p"
	.string "Ils recèlent encore énormément\n"
	.string "de mystères.\p"
	.string "Pour percer leurs secrets,\n"
	.string "je mène sans cesse des recherches.\l"
	.string "C'est mon métier.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Et toi, qui es-tu ?$"

gText_Birch_BoyOrGirl::
	.string "Es-tu un garçon ?\n"
	.string "Ou bien une fille ?$"

gText_Birch_WhatsYourName::
	.string "Très bien.\n"
	.string "Comment t'appelles-tu ?$"

gText_Birch_SoItsPlayer::
	.string "Tu t'appelles {PLAYER}{KUN} ?$"

gText_Birch_YourePlayer::
	.string "Ah, d'accord !\p"
	.string "{PLAYER}{KUN}, tu vas emménager à\n"
	.string "LITTLEROOT, ma ville natale.\l"
	.string "Je comprends mieux !\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Alors, es-tu prêt ?\p"
	.string "Ton aventure est sur le point\n"
	.string "de commencer.\p"
	.string "Prends ton courage et pars vers\n"
	.string "un monde de rêves, d'aventures et\l"
	.string "d'amitiés avec les POKéMON !\p"
	.string "Je t'attendrai un peu plus tard.\n"
	.string "Viens me voir au LABO POKéMON.\p"
	.string "$"
