BerryBlender_Text_BlendWithTheBlendMaster:
	.string "MAÎTRE MIXEUR : Évidemment !\n"
	.string "Je suis le MAÎTRE MIXEUR !\p"
	.string "Mélange avec moi, et tu verras\n"
	.string "toute l'étendue de mon talent !$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "MAÎTRE MIXEUR : Hmm ! Tu veux donc\n"
	.string "voir mon talent à l'œuvre ?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmm !\p"
	.string "Tu es trop occupé, je vois !\p"
	.string "Mais n'aie crainte !\n"
	.string "Je serai ici toute la journée !\l"
	.string "Reviens vite après ta course !$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmm !\p"
	.string "Tu ne possèdes aucune BAIE !\p"
	.string "Je serai ici toute la journée !\n"
	.string "Reviens vite avec des BAIES !$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Bien sûr !\n"
	.string "Bien sûr !\p"
	.string "Au fait…\n"
	.string "Tu sais préparer des {POKEBLOCK}S\l"
	.string "avec des BAIES ?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmm !\p"
	.string "Mais c'est très simple !\p"
	.string "Quand la flèche du MIXEUR atteint\n"
	.string "ton repère, presse le Bouton A.\p"
	.string "C'est tout ce qu'il faut faire.\p"
	.string "Observe la précision avec laquelle\n"
	.string "j'appuie, et tu comprendras.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Parfait !\p"
	.string "Alors, commençons !\p"
	.string "Tous avec le MAÎTRE MIXEUR,\n"
	.string "faisons tourner le MIXEUR !$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmm !\p"
	.string "Tu ne sembles pas avoir de\n"
	.string "BOÎTE À {POKEBLOCK}S !\p"
	.string "Je serai ici toute la journée !\n"
	.string "Trouve la BOÎTE À {POKEBLOCK}S !$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmm !\p"
	.string "Ta BOÎTE À {POKEBLOCK}S est pleine !\p"
	.string "Je serai ici toute la journée !\n"
	.string "Utilise des {POKEBLOCK}S. Reviens !$"

BerryBlender_Text_WhoaAwesome:
	.string "Waouh !\n"
	.string "Génial !$"

BerryBlender_Text_WickedlyFast:
	.string "Une vitesse démoniaque !$"

BerryBlender_Text_WhatAnExpert:
	.string "Quel expert !$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Avec le MAÎTRE MIXEUR,\n"
	.string "on a créé de super {POKEBLOCK}S !$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Des yeux qui suivent la flèche\n"
	.string "avec une intensité mécanique…\p"
	.string "Une main qui presse le Bouton A\n"
	.string "avec une précision d'horloger…\p"
	.string "Ces qualités font toute la gloire\n"
	.string "du MAÎTRE MIXEUR.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Le MAÎTRE MIXEUR s'entraînerait\n"
	.string "au plus profond des montagnes.\p"
	.string "Parfois, il vient à NÉNUCRIQUE\n"
	.string "mixer des BAIES toute la journée.$"
