CableClub_Text_WelcomeWhichCableClubService:
	.string "Bienvenue au POKéMON CABLE\n"
	.string "CLUB.\p"
	.string "Quel service souhaitez-vous\n"
	.string "utiliser?$"

CableClub_Text_WhichService:
	.string "Quel service souhaitez-vous\n"
	.string "utiliser?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Échangez des POKéMON avec un ami\n"
	.string "via un câble Game Link GBA.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Affrontez un autre DRESSEUR\n"
	.string "via un câble Game Link GBA.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "RECORD CORNER à plusieurs joueurs\n"
	.string "via un câble Game Link GBA.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Ferme ce menu.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Pour un COMBAT DUO, il vous faut\n"
	.string "au moins deux POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Pour échanger, vous devez avoir\n"
	.string "au moins deux POKéMON sur vous.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "Un POKéMON tenant la BAIE\n"
	.string "{STR_VAR_1} ne peut être échangé.$"

gText_PleaseWaitForLink::
	.string "Veuillez patienter.\n"
	.string "… … Bouton B: Annuler$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Quand tous les joueurs sont prêts…\n"
	.string "Bouton A: Confirmer\l"
	.string "Bouton B: Annuler$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Connexion avec {STR_VAR_1} joueurs.\n"
	.string "Bouton A: Confirmer\l"
	.string "Bouton B: Annuler$"

gText_AwaitingLinkup::
	.string "Connexion en attente…\n"
	.string "… … Bouton B: Annuler$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Votre progression doit être sauvée\n"
	.string "avant la connexion. Sauvegarder?$"

CableClub_Text_PleaseEnter:
	.string "Veuillez entrer.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Je vous conduis à votre salle.$"

Text_SomeoneIsNotReadyToLink:
	.string "Quelqu'un n'est pas prêt.\p"
	.string "Revenez quand tout le monde\n"
	.string "aura terminé ses préparatifs.$"

Text_LinkErrorPleaseReset:
	.string "Désolé, erreur de connexion…\n"
	.string "Redémarrez et réessayez.$"

Text_PlayersMadeDifferentSelections:
	.string "Les partenaires semblent avoir\n"
	.string "fait des choix différents.$"

CableClub_Text_PleaseVisitAgain:
	.string "Revenez nous voir.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "Le nombre de participants est\n"
	.string "incorrect.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "Le mode COMBAT SOLO ne peut pas\n"
	.string "se jouer à {STR_VAR_1} joueurs.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "Le mode COMBAT DUO ne peut pas\n"
	.string "se jouer à {STR_VAR_1} joueurs.$"

CableClub_Text_NeedFourPlayers:
	.string "Il faut quatre joueurs pour jouer\n"
	.string "dans ce mode de combat.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Vérifiez le nombre de joueurs\n"
	.string "et recommencez.$"

Text_TerminateLinkConfirmation:
	.string "Quitter la salle coupe la liaison.\n"
	.string "Voulez-vous continuer?$"

Text_TerminateLinkPleaseWait:
	.string "Fin de la connexion…\n"
	.string "On va vous raccompagner hors de\l"
	.string "la salle. Veuillez patienter.$"

CableClub_Text_TooBusyToNotice:
	.string "Ce DRESSEUR est trop occupé pour\n"
	.string "vous remarquer…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "Génial! Vous avez vu la CARTE DE\n"
	.string "DRESSEUR de {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "Génial! Vous avez vu la CARTE DE\n"
	.string "DRESSEUR de {STR_VAR_1}!\p"
	.string "C'est une carte {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Prenez place et commencez\n"
	.string "votre combat.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Veuillez vous asseoir pour\n"
	.string "commencer l'échange.$"

RecordCorner_Text_ThanksForComing:
	.string "Merci d'être venu.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "La CARTE DE DRESSEUR\n"
	.string "sera écrasée.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "J'espère vous revoir!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Je suis vraiment désolée.\p"
	.string "Nous ne pouvons encore échanger\n"
	.string "avec des DRESSEURS d'une région\l"
	.string "lointaine…$"

CableClub_Text_OtherTrainerNotReady:
	.string "L'autre DRESSEUR n'est pas prêt.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Vous avez au moins un POKéMON\n"
	.string "qui ne peut pas participer.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Asseyez-vous et patientez.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} envoie un exemplaire\n"
	.string "de {STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Désolé, erreur de transmission.\p"
	.string "Mixage des données impossible avec\n"
	.string "Ruby ou Sapphire en japonais.\p"
	.string "Impossible de mixer à la fois\n"
	.string "Emerald japonais et Ruby/Sapphire\l"
	.string "d'une autre région.$"

CableClub_Text_AdapterNotConnected:
	.string "L'adaptateur sans fil n'est pas\n"
	.string "correctement branché.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Les participants doivent venir\n"
	.string "au comptoir d'accueil.$"

@ Unused
CableClub_Text_Hello:
	.string "Bonjour!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Veuillez patienter.$"

CableClub_Text_YouMayTradeHere::
	.string "Ici, vous pouvez échanger vos\n"
	.string "POKéMON avec un autre DRESSEUR.$"

CableClub_Text_YouMayBattleHere::
	.string "Ici, vous pouvez combattre avec\n"
	.string "vos amis.$"

CableClub_Text_CanMakeBerryPowder::
	.string "De deux à cinq DRESSEURS peuvent\n"
	.string "préparer du BERRY POWDER.$"

CableClub_Text_CanMixRecords::
	.string "Deux à quatre joueurs peuvent\n"
	.string "mixer leurs données.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "Guide des différents services du\n"
	.string "WIRELESS CLUB.$"

CableClub_Text_CancelSelectedItem::
	.string "Annule l'option choisie du MENU.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Quel mode de combat voulez-vous?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Revient à l'étape précédente.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Pour utiliser BERRY CRUSH, il vous\n"
	.string "faut au moins une BAIE.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Pour entrer dans l'UNION ROOM, il\n"
	.string "vous faut au moins deux POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Un POKéMON tenant la BAIE\n"
	.string "{STR_VAR_1} ne peut entrer ici.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Voici l'UNION ROOM du POKéMON\n"
	.string "WIRELESS CLUB.\p"
	.string "Malheureusement, votre adaptateur\n"
	.string "sans fil est mal branché.\p"
	.string "Revenez nous voir.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh…\n"
	.string "Excusez-moi!$"

CableClub_Text_PlayerIsWaiting:
	.string "On dirait que {STR_VAR_1} joue\n"
	.string "en ce moment.\l"
	.string "Allez-y!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Je peux vous expliquer les règles,\n"
	.string "si vous le souhaitez.\p"
	.string "Quel jeu dois-je présenter?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "POKéMON JUMP\p"
	.string "Faites sauter le POKéMON avec A\n"
	.string "au-dessus du FOUET LIANES.\p"
	.string "Seuls les petits POKéMON d'environ\n"
	.string "70 cm ou moins peuvent participer.\p"
	.string "Ceux qui nagent, creusent, volent\n"
	.string "sautent très mal.\p"
	.string "Ces POKéMON ne peuvent donc pas\n"
	.string "participer.\p"
	.string "Une belle surprise vous attend si\n"
	.string "tout le monde saute en rythme.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "DODRIO BERRY-PICKING\p"
	.string "Dirigez les trois têtes de DODRIO\n"
	.string "pour attraper les BAIES en chute.\p"
	.string "Pressez droite, haut ou gauche sur\n"
	.string "la croix {PLUS} pour bouger les têtes.\p"
	.string "Pour jouer à ce jeu, vous devez\n"
	.string "avoir un DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Pour jouer, adressez-vous au\n"
	.string "vieil homme près de moi.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Bonjour et bienvenue!\n"
	.string "Vous venez jouer par communication\l"
	.string "sans fil?\p"
	.string "Pouvez-vous patienter un peu?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "Très bien, à bientôt!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "Adaptateur sans fil débranché.\n"
	.string "Revenez après l'avoir branché!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "Très bien. À quel jeu voulez-vous\n"
	.string "jouer?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "Quel POKéMON voulez-vous\n"
	.string "inscrire?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Bien, tout est prêt.\n"
	.string "Ne vous laissez pas battre!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Vous partez déjà?\n"
	.string "Revenez bientôt!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Vous n'avez aucun POKéMON\n"
	.string "admissible…\p"
	.string "Voulez-vous savoir quels types de\n"
	.string "POKéMON peuvent participer?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "POKéMON JUMP accepte les POKéMON\n"
	.string "d'environ 70 cm ou moins.\p"
	.string "Les POKéMON incapables de sauter\n"
	.string "ne peuvent pas participer.\p"
	.string "Comme ceux qui ne font que\n"
	.string "nager, creuser ou voler.\p"
	.string "Voilà tout ce qu'il faut savoir.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "DODRIO BERRY-PICKING est réservé\n"
	.string "aux DODRIO.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Pouvez-vous reprendre depuis le\n"
	.string "début, s'il vous plaît?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Bienvenue au DIRECT CORNER du\n"
	.string "POKéMON WIRELESS CLUB.\p"
	.string "Ici, vous pouvez communiquer\n"
	.string "directement avec vos amis.\p"
	.string "Dans quelle salle voulez-vous\n"
	.string "entrer?$"

CableClub_Text_TradePokemon:
	.string "Voulez-vous échanger des POKéMON?$"

CableClub_Text_PlayWhichBattleMode:
	.string "Quel mode de combat voulez-vous\n"
	.string "choisir?$"

CableClub_Text_AccessRecordCorner:
	.string "Voulez-vous accéder au\n"
	.string "RECORD CORNER?$"

CableClub_Text_UseBerryCrush:
	.string "Voulez-vous utiliser le système\n"
	.string "BERRY CRUSH?$"

CableClub_Text_ExplainBattleModes:
	.string "Il existe trois modes de combat.\p"
	.string "Le COMBAT SOLO oppose 2 DRESSEURS\n"
	.string "ayant chacun au moins un POKéMON.\p"
	.string "Chaque DRESSEUR envoie un seul\n"
	.string "POKéMON au combat à la fois.\p"
	.string "Le COMBAT DUO oppose 2 DRESSEURS\n"
	.string "avec au moins deux POKéMON chacun.\p"
	.string "Chaque DRESSEUR envoie deux\n"
	.string "POKéMON au combat à la fois.\p"
	.string "Le COMBAT MULTI réunit 4 DRESSEURS\n"
	.string "ayant chacun au moins un POKéMON.\p"
	.string "Chaque DRESSEUR envoie un seul\n"
	.string "POKéMON au combat à la fois.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Décidez lequel de vous deux sera\n"
	.string "le LEADER.\p"
	.string "L'autre joueur devra alors choisir\n"
	.string "JOIN GROUP.$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Décidez lequel de vous quatre sera\n"
	.string "le GROUP LEADER.\p"
	.string "Les autres joueurs devront choisir\n"
	.string "JOIN GROUP.$"

CableClub_Text_ChooseGroupLeader:
	.string "Décidez lequel d'entre vous sera\n"
	.string "le GROUP LEADER.\p"
	.string "Les autres joueurs devront choisir\n"
	.string "JOIN GROUP.$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Bienvenue dans l'UNION ROOM du\n"
	.string "POKéMON WIRELESS CLUB.\p"
	.string "Ici, vous pouvez communiquer avec\n"
	.string "d'autres DRESSEURS, même certains\l"
	.string "que vous ne connaissez pas.\p"
	.string "Voulez-vous entrer dans la SALLE?$"

CableClub_Text_UnionRoomInfo:
	.string "Les DRESSEURS dans l'UNION ROOM\n"
	.string "sont les joueurs à proximité qui\l"
	.string "sont aussi entrés dans la SALLE.\p"
	.string "Vous pouvez y faire toutes sortes\n"
	.string "de choses, comme vous saluer.\p"
	.string "Vous pouvez inscrire deux POKéMON\n"
	.string "niv. 30 max. pour un combat solo.\p"
	.string "Vous pouvez discuter en groupe\n"
	.string "de deux à cinq personnes.\p"
	.string "Vous pouvez proposer un POKéMON\n"
	.string "à l'échange.\p"
	.string "Voulez-vous entrer dans la SALLE?$"

CableClub_Text_EnjoyUnionRoom:
	.string "Amusez-vous bien dans\n"
	.string "l'UNION ROOM.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Bonjour!\n"
	.string "Je m'appelle TEALA.\p"
	.string "C'est votre première visite ici\n"
	.string "à cet étage.\p"
	.string "Je vais vous montrer le système\n"
	.string "de communication sans fil.\p"
	.string "Commençons par visiter cet étage\n"
	.string "de notre CENTRE POKéMON.\p"
	.string "Par ici, s'il vous plaît.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "Le dernier étage compte deux\n"
	.string "salles.\p"
	.string "D'abord, celle de gauche.\n"
	.string "C'est l'UNION ROOM.\p"
	.string "Elle vous relie aux DRESSEURS\n"
	.string "proches qui sont aussi entrés dans\l"
	.string "l'UNION ROOM.\p"
	.string "Avec eux, vous pouvez discuter,\n"
	.string "combattre et échanger.\p"
	.string "Ensuite, la salle de droite est\n"
	.string "le DIRECT CORNER.\p"
	.string "Vous pouvez échanger ou combattre\n"
	.string "avec vos amis.\p"
	.string "Sans adaptateur sans fil branché,\n"
	.string "vous pouvez encore vous relier\l"
	.string "par câble Game Link GBA.\p"
	.string "Dans ce cas, rendez-vous dans\n"
	.string "le DIRECT CORNER.\p"
	.string "Profitez bien du système de\n"
	.string "communication sans fil.$"

CableClub_Text_AskAboutLinking:
	.string "Bonjour, {PLAYER}!\p"
	.string "C'est moi, TEALA, l'hôtesse de\n"
	.string "l'étage du CENTRE POKéMON.\p"
	.string "Avez-vous une question sur la\n"
	.string "connexion?$"

CableClub_Text_ExplainWirelessClub:
	.string "Voici comment fonctionne\n"
	.string "du POKéMON WIRELESS CLUB.\p"
	.string "Le dernier étage compte\n"
	.string "deux salles.\p"
	.string "D'abord, celle de gauche.\n"
	.string "C'est l'UNION ROOM.\p"
	.string "Elle vous relie aux DRESSEURS\n"
	.string "proches qui sont aussi entrés dans\l"
	.string "l'UNION ROOM.\p"
	.string "Avec eux, vous pouvez discuter,\n"
	.string "combattre et échanger.\p"
	.string "Ensuite, la salle de droite est\n"
	.string "le DIRECT CORNER.\p"
	.string "Vous pouvez échanger ou combattre\n"
	.string "avec vos amis.\p"
	.string "Parfois, vous ne trouverez pas vos\n"
	.string "amis dans l'UNION ROOM ni dans\l"
	.string "le DIRECT CORNER.\p"
	.string "Dans ce cas, rapprochez-vous\n"
	.string "de vos amis.\p"
	.string "Sans adaptateur sans fil branché,\n"
	.string "vous pouvez encore vous relier\l"
	.string "par câble Game Link GBA.\p"
	.string "Dans ce cas, rendez-vous dans\n"
	.string "le DIRECT CORNER.\p"
	.string "Profitez bien du système de\n"
	.string "communication sans fil.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "Profitez bien du système de\n"
	.string "communication sans fil.$"
