Text_PictureBookShelf:
	.string "Des albums illustrés de POKéMON.$"

Text_BookShelf:
	.string "Il est rempli de livres variés.$"

Text_PokemonCenterBookShelf:
	.string "Des magazines POKéMON !\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"

Text_Vase:
	.string "Ce vase semble très cher…\n"
	.string "Tu regardes à l'intérieur…\p"
	.string "Mais il est vide.$"

Text_EmptyTrashCan:
	.string "C'est vide.$"

Text_ShopShelf:
	.string "Les rayons débordent de produits\n"
	.string "dérivés POKéMON.$"

Text_Blueprint:
	.string "Un plan, peut-être ?\n"
	.string "C'est bien trop compliqué !$"
