@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "Je m'occupe de la PENSION.\p"
	.string "Je prends soin des précieux\n"
	.string "POKéMON des DRESSEURS.\p"
	.string "Si tu veux nous confier un\n"
	.string "POKéMON, parle à ma femme.$"

DayCare_Text_DoYouWantEgg::
	.string "Ah, te voilà !\p"
	.string "En élevant tes POKéMON, nous avons\n"
	.string "eu une sacrée surprise !\p"
	.string "Tes POKéMON avaient un ŒUF !\p"
	.string "Nous ignorons d'où il vient,\n"
	.string "mais tes POKéMON l'avaient.\p"
	.string "Tu le veux, n'est-ce pas ?$"

DayCare_Text_YourMonIsDoingFine::
	.string "Ah, te voilà ! Ravi de te voir.\n"
	.string "Ton {STR_VAR_1} va très bien.$"

DayCare_Text_IllKeepIt::
	.string "Dans ce cas, je le garde.\n"
	.string "Merci !$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "Tu n'as pas de place pour lui…\n"
	.string "Reviens après en avoir fait.$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER} reçoit l'ŒUF de\n"
	.string "l'homme de la PENSION.$"

DayCare_Text_TakeGoodCareOfIt::
	.string "Prends-en bien soin.$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "Pour reprendre un POKéMON,\n"
	.string "adresse-toi à ma femme.$"

DayCare_Text_YourMonsAreDoingFine::
	.string "Ah, te voilà ! Ton {STR_VAR_1} et\n"
	.string "{STR_VAR_2} vont très bien.$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "Je vais vraiment le garder.\n"
	.string "C'est bien ce que tu veux ?$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "Je m'occupe de la PENSION.\p"
	.string "Nous pouvons élever tes POKéMON.\p"
	.string "Veux-tu nous en confier un ?$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "Quel POKéMON devons-nous élever\n"
	.string "pour toi ?$"

DayCare_Text_WellRaiseYourMon::
	.string "Bien, nous élevons {STR_VAR_1}\n"
	.string "quelque temps.\p"
	.string "Reviens le chercher plus tard.$"

DayCare_Text_WeCanRaiseOneMore::
	.string "Nous pouvons élever deux POKéMON.\p"
	.string "Veux-tu nous en confier\n"
	.string "un autre ?$"

DayCare_Text_HusbandWasLookingForYou::
	.string "Mon mari te cherchait.$"

DayCare_Text_FineThenComeAgain::
	.string "Oh, très bien.\n"
	.string "Reviens nous voir.$"

DayCare_Text_NotEnoughMoney::
	.string "Tu n'as pas assez d'argent…$"

DayCare_Text_TakeOtherOneBackToo::
	.string "Veux-tu aussi reprendre l'autre\n"
	.string "POKéMON ?$"

DayCare_Text_ComeAgain::
	.string "Très bien.\n"
	.string "Reviens nous voir.$"

DayCare_Text_GoodToSeeYou::
	.string "Ah, te voilà !\n"
	.string "Ravi de te voir.\p"
	.string "Tes POKéMON se portent forcément\n"
	.string "à merveille !$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "Ton {STR_VAR_1} a progressé de\n"
	.string "{STR_VAR_2} niveaux.$"

DayCare_Text_YourPartyIsFull::
	.string "Ton équipe POKéMON est complète.\n"
	.string "Fais de la place puis reviens.$"

DayCare_Text_TakeBackWhichMon::
	.string "Quel POKéMON veux-tu reprendre ?$"

DayCare_Text_ItWillCostX::
	.string "Pour reprendre {STR_VAR_1},\n"
	.string "tu dois payer ¥{STR_VAR_2}.$"

DayCare_Text_HeresYourMon::
	.string "Parfait !\n"
	.string "Voici ton POKéMON.$"

DayCare_Text_TookBackMon::
	.string "{PLAYER} reprend {STR_VAR_1} à\n"
	.string "la femme de la PENSION.$"

DayCare_Text_YouHaveJustOneMon::
	.string "Oh ? Mais tu n'as qu'un seul\n"
	.string "POKéMON.\p"
	.string "Reviens une autre fois.$"

DayCare_Text_TakeYourMonBack::
	.string "Veux-tu reprendre ton POKéMON ?$"

DayCare_Text_WhatWillYouBattleWith::
	.string "Si tu me confies ce POKéMON,\n"
	.string "avec qui vas-tu combattre ?\p"
	.string "Reviens une autre fois.$"

DayCare_Text_Huh::
	.string "Hein ?$"
