EventTicket_Text_ShowOldSeaMap:
	.string "Le ferry pour POIVRESSEL est…\p"
	.string "Pardon ?\n"
	.string "Peut-on rejoindre ce lieu ?\p"
	.string "Quelqu'un pourra mieux t'aider.\n"
	.string "Un instant.$"

EventTicket_Text_ThatPass:
	.string "Le ferry pour POIVRESSEL est…\p"
	.string "Oh ?\n"
	.string "Ce PASSE…$"

EventTicket_Text_ShowEonTicket:
	.string "Dis, c'est toi qui as apporté\n"
	.string "ce curieux PASSE ?\p"
	.string "Tu cherches une minuscule île\n"
	.string "perdue loin au sud.\p"
	.string "Nul ne sait ce que nous trouverons\n"
	.string "une fois là-bas, matelot.\l"
	.string "J'en frissonne d'avance !\p"
	.string "Tout le monde à bord !$"

#if IS_HNS
EventTicket_Text_SouthernIslandSailBack:
	.string "Eh bien, matelot, il n'y a rien à\n"
	.string "faire sur cette île oubliée.\p"
	.string "Et si nous rentrions à OLIVILLE ?$"
#else
EventTicket_Text_SouthernIslandSailBack:
	.string "Eh bien, matelot, il n'y a rien à\n"
	.string "faire sur cette île oubliée.\p"
	.string "On rentre à NÉNUCRIQUE ?$"
#endif 


EventTicket_Text_SailHome:
	.string "Très bien !\n"
	.string "Rentrons à la maison !$"

EventTicket_Text_AsYouLike:
	.string "Comme tu veux.$"

SouthernIsland_Interior_Text_Sign:
	.string "Les rêves sont une autre réalité.\n"
	.string "Ne l'oubliez jamais…$"

SouthernIsland_Exterior_Text_Sign:
	.string "Quand les souvenirs s'effacent,\n"
	.string "on les grave dans son cœur…$"
