EventTicket_Text_ShowOldSeaMap:
	.string "The ferry to SLATEPORT is…\p"
	.string "I beg your pardon?\n"
	.string "Can we sail to this place on the map?\p"
	.string "I know someone who will help you better.\n"
	.string "Please wait.$"

EventTicket_Text_ThatPass:
	.string "The ferry to SLATEPORT is…\p"
	.string "Oh?\n"
	.string "That PASS…$"

EventTicket_Text_ShowEonTicket:
	.string "Aye, mate, are you the one who brought\n"
	.string "that mighty odd PASS?\p"
	.string "I'll tell you, you're trying to reach a\n"
	.string "tiny spit of an island far in the south.\p"
	.string "There's no telling what we'll encounter\n"
	.string "once we reach there, aye.\l"
	.string "That shivers my timbers!\p"
	.string "All aboard!$"

#if IS_HNS
EventTicket_Text_SouthernIslandSailBack:
	.string "Eh bien, matelot, il n'y a rien à\n"
	.string "faire sur cette île oubliée.\p"
	.string "Et si nous rentrions à OLIVILLE ?$"
#else
EventTicket_Text_SouthernIslandSailBack:
	.string "Eh bien, matelot, il n'y a rien à\n"
	.string "faire sur cette île oubliée.\p"
	.string "On rentre à NÉNUCRIQUE ?$"
#endif 


EventTicket_Text_SailHome:
	.string "Très bien !\n"
	.string "Rentrons à la maison !$"

EventTicket_Text_AsYouLike:
	.string "Comme vous voulez.$"

SouthernIsland_Interior_Text_Sign:
	.string "Les rêves sont une autre réalité.\n"
	.string "Ne l'oubliez jamais…$"

SouthernIsland_Exterior_Text_Sign:
	.string "Quand les souvenirs s'effacent,\n"
	.string "on les grave dans son coeur…$"
