EventTicket_Text_OldSeaMapTooFar:
	.string "Que se passe-t-il, petit ?\p"
	.string "C'est donc toi qui possèdes\n"
	.string "une vieille carte abîmée ?\p"
	.string "Fais voir.\n"
	.string "… … … … … …\p"
	.string "Eh bien, c'est vraiment très loin.\n"
	.string "J'ai peur de ne pouvoir t'aider…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "MARCO : Attendez un instant !\p"
	.string "Pourquoi refuser d'aider quelqu'un\n"
	.string "à qui je dois tant ?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, je suis navré.\p"
	.string "Tu es venu demander mon aide,\n"
	.string "et nous avons failli te refuser.\p"
	.string "Laisse-moi réparer cette erreur.\p"
	.string "Nous partons sur-le-champ !\p"
	.string "Trouvons l'île indiquée sur\n"
	.string "cette VIEILLECARTE !$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "Tu as apporté cet étrange\n"
	.string "ticket ?\p"
	.string "Tu veux rejoindre une île\n"
	.string "extrêmement lointaine.\p"
	.string "Nul ne sait ce qui nous y attend…\p"
	.string "Rien que d'y penser, mon sang de\n"
	.string "marin ne fait qu'un tour !\p"
	.string "Monte à bord, petit !$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "Le CAP. MARCO est parfois très\n"
	.string "lunatique…\p"
#if IS_HNS
	.string "Veux-tu rentrer à OLIVILLE ?$"
#else
	.string "Veux-tu rentrer à NÉNUCRIQUE ?$"
#endif

BirthIsland_Harbor_Text_SailorReturn:
	.string "Cette île a une drôle de forme !\n"
#if IS_HNS
	.string "Veux-tu rentrer à OLIVILLE ?$"
#else
	.string "On rentre à NÉNUCRIQUE ?$"
#endif

EventTicket_Text_OddTicketsWhereTo:
	.string "C'est toi qui as apporté ces\n"
	.string "étranges tickets ?\p"
	.string "… … …Hmm.\p"
	.string "Ils mènent à des îles\n"
	.string "extrêmement lointaines.\p"
	.string "Nul ne sait ce qui nous y attend,\n"
	.string "ni ce qui peut s'y produire.\p"
	.string "Rien que d'y penser, mon sang de\n"
	.string "marin ne fait qu'un tour !\p"
	.string "Monte à bord, petit !\n"
	.string "Où allons-nous d'abord ?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Tu… Tu as entendu ?\n"
	.string "Ce grondement des profondeurs.\p"
	.string "Tu crois que c'est sans danger ?\n"
	.string "On devrait peut-être partir ?$"

FarawayIsland_Entrance_Text_Sign:
	.string "L'écriture s'efface, comme si elle\n"
	.string "datait d'il y a très longtemps…\p"
	.string "…bre, le 6\n"
	.string "Si un humain… revient ici…\l"
	.string "un jour… qu'il ait bon cœur…\l"
	.string "…vec cet espoir, je pars…$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"
