gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LABORATOIRE POKéMON DU PROF. CHEN$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Créer un guide complet de tous\n"
	.string "les POKéMON du monde…\p"
	.string "Tel était mon rêve!$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le PROF. CHEN n'en a peut-être\n"
	.string "pas l'air, mais c'est un expert.\p"
	.string "De nombreux DRESSEURS POKéMON\n"
	.string "l'estiment énormément.$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sa famille et ses amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le PROF. CHEN vivrait avec ses\n"
	.string "petits-enfants NINA et {RIVAL}.$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sa famille et ses amis?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il paraît que CHEN s'intéresse\n"
	.string "beaucoup à toi, mon enfant.\p"
	.string "Ce vieux schnock était jadis fort\n"
	.string "et séduisant.\p"
	.string "Mais c'était il y a des lustres.\n"
	.string "Il n'est plus que l'ombre d'avant.$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le PROF. CHEN aura bientôt sa\n"
	.string "propre émission de radio.\p"
	.string "Elle s'appellera LE SÉMINAIRE\n"
	.string "POKéMON DU PROF. CHEN.$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Montre ton POKéMON à NINA: elle\n"
	.string "saura s'il est attaché à toi.\p"
	.string "Parfois, elle acceptera même de\n"
	.string "le bichonner.$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mais la personne que les POKéMON\n"
	.string "préfèrent, c'est NINA, je crois.$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Elle bichonnait les POKéMON avec\n"
	.string "douceur… Un véritable petit ange.\p"
	.string "Cette fillette s'appelait…\n"
	.string "NINA, il me semble.$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sa famille et ses amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le PROF. CHEN vivrait avec ses\n"
	.string "petits-enfants NINA et {RIVAL}.$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}NINA, de BOURG PALETTE, boit du\n"
	.string "THÉ chaque jour.\p"
	.string "Elle va au CENTRE COMMERCIAL DE\n"
	.string "CÉLADOPOLE pour en acheter.$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La grande gagnante du CONCOURS\n"
	.string "du printemps: NINA CHEN,\l"
	.string "de BOURG PALETTE!$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ARÈNE POKéMON D'ARGENTA\n"
	.string "CHAMPION: PIERRE\l"
	.string "Le DRESSEUR dur comme le roc!$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ma volonté de fer se reflète\n"
	.string "jusque dans mes POKéMON.\p"
	.string "Ils sont tous durs comme la roche\n"
	.string "et d'une ténacité sans faille.\p"
	.string "Eh oui, tous mes POKéMON sont\n"
	.string "de type ROCHE!$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il y a peu de DRESSEURS POKéMON\n"
	.string "sérieux par ici.\p"
	.string "Ce sont surtout des amateurs,\n"
	.string "comme les CHASSEURS D'INSECTES.\p"
	.string "Mais PIERRE, de l'ARÈNE D'ARGENTA,\n"
	.string "n'est pas du tout comme eux.$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PIERRE a la classe, pas seulement\n"
	.string "parce qu'il est fort.\p"
	.string "Je veux devenir un CHAMPION\n"
	.string "aussi aimé et respecté que lui.$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Bonjour! Je cherche des fossiles\n"
	.string "sous le MONT SÉLÉNITE.\p"
	.string "PIERRE, de l'ARÈNE D'ARGENTA,\n"
	.string "vient parfois m'aider.$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PIERRE rit rarement, mais une fois\n"
	.string "lancé, impossible de l'arrêter.$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ARÈNE POKéMON D'AZURIA\n"
	.string "CHAMPIONNE: ONDINE\l"
	.string "La sirène au caractère d'acier!$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ma stratégie: l'offensive totale\n"
	.string "avec des POKéMON de type EAU!$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ONDINE est une DRESSEUSE qui ne\n"
	.string "cessera jamais de progresser.\p"
	.string "Elle ne perdra pas contre toi!$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Les bons DRESSEURS et les POKéMON\n"
	.string "EAU abondent dans les environs.\p"
	.string "On dit qu'ONDINE, de l'ARÈNE\n"
	.string "D'AZURIA, s'entraîne ici.$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ce cap est un lieu de rendez-vous\p"
	.string "très prisé. ONDINE, la CHAMPIONNE,\n"
	.string "en attend beaucoup.$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}On dit qu'ONDINE admire LORELEI,\n"
	.string "membre du CONSEIL 4.$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ARÈNE POKéMON DE CARMIN SUR MER\n"
	.string "CHAMPION: MAJOR BOB\l"
	.string "L'Américain électrique!$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je te le dis, petit: les POKéMON\n"
	.string "ÉLECTRIK m'ont sauvé à la guerre!$"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}À l'armée, le MAJOR BOB était mon\n"
	.string "supérieur, et il était sévère.\p"
	.string "Il ne nous ménageait pas.$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}À l'armée, le MAJOR BOB était déjà\n"
	.string "réputé pour sa prudence.$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le MAJOR BOB a installé lui-même\n"
	.string "les pièges de l'ARÈNE.\p"
	.string "Il a placé des doubles verrous.$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le MAJOR BOB aurait été pilote\n"
	.string "quand il vivait en Amérique.\p"
	.string "L'électricité de ses POKéMON\n"
	.string "alimentait son avion.$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ARÈNE POKéMON DE CÉLADOPOLE\n"
	.string "CHAMPIONNE: ERIKA\l"
	.string "La princesse amie de la nature!$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}J'étudie l'art de la composition\n"
	.string "florale.\p"
	.string "Mes POKéMON sont exclusivement\n"
	.string "de type PLANTE.$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ERIKA, la CHAMPIONNE, est calme,\n"
	.string "mais tout le monde la connaît ici.$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Dans notre ARÈNE, nous n'utilisons\n"
	.string "que des POKéMON PLANTE.\p"
	.string "Pourquoi? Ils servent aussi à nos\n"
	.string "compositions florales!$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je ne collectionnerais jamais des\n"
	.string "POKéMON sans charme.$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La rumeur dit qu'en regardant dans\n"
	.string "l'ARÈNE DE CÉLADOPOLE, on voit\l"
	.string "souvent ERIKA somnoler.$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ARÈNE POKéMON DE PARMANIE\n"
	.string "CHAMPION: KOGA\l"
	.string "Le maître ninja du poison$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tremble devant l'horreur rampante\n"
	.string "des POKéMON de type POISON!$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Même vaincu, je poursuivrai mon\n"
	.string "entraînement selon les préceptes\l"
	.string "de KOGA, mon maître ninja.$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sa famille et ses amis?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mon père est le CHAMPION de cette\n"
	.string "ville.\p"
	.string "Je m'entraîne à manier les POKéMON\n"
	.string "POISON aussi bien que lui.$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}KOGA connaîtrait parfaitement la\n"
	.string "médecine.\p"
	.string "Il prépare même des remèdes pour\n"
	.string "soigner ses POKéMON.$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le PARC SAFARI est immense, tu ne\n"
	.string "trouves pas?\p"
	.string "KOGA, le CHAMPION de PARMANIE,\n"
	.string "vient parfois y patrouiller.\p"
	.string "Grâce à lui, nous pouvons jouer\n"
	.string "ici en toute sécurité.$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ARÈNE POKéMON DE SAFRANIA\n"
	.string "CHAMPIONNE: MORGANE\l"
	.string "La maîtresse des POKéMON PSY!$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tu connais la CHAMPIONNE de\n"
	.string "SAFRANIA?\p"
	.string "Elle utilise des POKéMON de type\n"
	.string "PSY, pas vrai?$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}J'ai des dons psychiques depuis\n"
	.string "mon enfance.\p"
	.string "Tout a commencé quand une cuillère\n"
	.string "que je lançais s'est tordue.$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je déteste combattre, mais si tu\n"
	.string "insistes, tu verras mes pouvoirs!$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}On dit que MORGANE communique avec\n"
	.string "ses POKéMON sans parler, même\l"
	.string "pendant les combats.$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MORGANE vient d'écraser le MAÎTRE\n"
	.string "du KARATÉ voisin.$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ARÈNE POKéMON DE CRAMOIS'ÎLE\n"
	.string "CHAMPION: AUGUSTE\l"
	.string "Le maître des quiz enflammés!$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mes POKéMON ardents sont féroces\n"
	.string "et brûlants!\p"
	.string "Ils incinèrent tous leurs rivaux!$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Notre CHAMPION, AUGUSTE, s'est un\n"
	.string "jour perdu dans les montagnes.\p"
	.string "La nuit venue, un oiseau POKéMON\n"
	.string "enflammé est apparu.\p"
	.string "Sa lueur a permis à AUGUSTE de\n"
	.string "redescendre sain et sauf.$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}À CRAMOIS'ÎLE, AUGUSTE est\n"
	.string "un sacré original.\p"
	.string "Il vivait sur l'île bien avant\n"
	.string "la construction du LABO.$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sa famille et ses amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}C'est une photo d'AUGUSTE et de\n"
	.string "M. FUJI.\p"
	.string "Ils posent côte à côte avec un\n"
	.string "large sourire.$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}AUGUSTE n'ôterait ses lunettes\n"
	.string "noires que pour inventer de\l"
	.string "nouvelles questions.$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je suis LORELEI du CONSEIL 4.$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Personne ne me surpasse avec des\n"
	.string "POKéMON de glace.$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Où cette personne est-elle née?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Une grande DRESSEUSE a grandi sur\n"
	.string "cette île.\p"
	.string "Même toi, tu dois la connaître.\n"
	.string "C'est LORELEI du CONSEIL 4!$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Connue pour son style logique,\n"
	.string "calculé et glacial, LORELEI cache\l"
	.string "un secret étonnant!$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Savais-tu que LORELEI possède une\n"
	.string "foule de poupées en peluche?\p"
	.string "À chaque retour sur FOUR ISLAND,\n"
	.string "sa collection s'agrandit!$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Son LOKHLASS serait celui de son\n"
	.string "enfance.\p"
	.string "Capturé à ICEFALL CAVE, dit-on.\n"
	.string "si je ne me trompe pas.\p"
	.string "Ce POKéMON ne l'a peut-être jamais\n"
	.string "quittée depuis.$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je suis ALDO du CONSEIL 4!$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}J'ai vécu et me suis entraîné avec\n"
	.string "mes POKéMON COMBAT!$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ALDO aurait rejoint le CONSEIL 4\n"
	.string "pour assouvir son désir ardent\l"
	.string "d'affronter les meilleurs.$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mon aîné ALDO vient parfois aux\n"
	.string "THERMES.\p"
	.string "Il y soigne ses plaies et celles\n"
	.string "de ses POKéMON.$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il fait partie du CONSEIL 4.\n"
	.string "Il s'appelle ALDO.\p"
	.string "Il est reparti déçu en apprenant\n"
	.string "qu'il n'y avait plus de\l"
	.string "BONBONS RAGE.$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sa famille et ses amis?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Même ALDO…\n"
	.string "Il s'est autrefois entraîné avec\l"
	.string "un certain BRAWLY.$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je suis AGATHA du CONSEIL 4.$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Les POKéMON SPECTRE d'AGATHA sont\n"
	.string "d'une force terrifiante.$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Cette vieille dame s'emporte aussi\n"
	.string "au quart de tour.\p"
	.string "Un rien suffit à faire hurler\n"
	.string "cette femme effrayante.$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Dans leur jeunesse, AGATHA et le\n"
	.string "PROF. CHEN rivalisaient pour\l"
	.string "devenir le meilleur DRESSEUR.$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sa famille et ses amis?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il paraît que CHEN s'intéresse\n"
	.string "beaucoup à toi, mon enfant.\p"
	.string "Ce vieux schnock était jadis fort\n"
	.string "et séduisant.\p"
	.string "Mais c'était il y a des lustres.\n"
	.string "Il n'est plus que l'ombre d'avant.$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Prenez AGATHA, par exemple.\p"
	.string "Elle détient le record du membre\n"
	.string "le plus âgé du CONSEIL 4.$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je dirige le CONSEIL 4.\p"
	.string "Appelle-moi PETER, le DRESSEUR de\n"
	.string "dragons.$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tu sais, les dragons sont des\n"
	.string "POKéMON mythiques.\p"
	.string "Durs à capturer et à élever, mais\n"
	.string "leur puissance est sans égale.\p"
	.string "Ils sont presque indestructibles.\n"
	.string "Aucune ruse ne peut les vaincre.$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il défend la justice!\n"
	.string "Il est cool et passionné!\l"
	.string "PETER est le meilleur!$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Un client nommé PETER vient nous\n"
	.string "voir de temps en temps.\p"
	.string "Il achète toujours des capes.\p"
	.string "Je me demande s'il en a beaucoup\n"
	.string "d'identiques chez lui.$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sa famille et ses amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le grand-père de PETER serait\n"
	.string "l'ancien d'un célèbre clan de\l"
	.string "maîtres dragons.$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sa famille et ses amis?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}D'après ce qu'on m'a dit, PETER a\n"
	.string "une cousine CHAMPIONNE D'ARÈNE\l"
	.string "dans une lointaine région.$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Après tout, LEO est un POKéMANIAC\n"
	.string "connu dans le monde entier.\p"
	.string "Il a aussi inventé le système de\n"
	.string "stockage POKéMON sur PC.$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LEO possède beaucoup de POKéMON!\n"
	.string "Il en collectionne de très rares!$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}C'est mon petit-fils!\p"
	.string "Il a toujours aimé collectionner,\n"
	.string "même quand il était enfant!$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LEO est un POKéMANIAC: il aime\n"
	.string "toutes les espèces.\p"
	.string "Apparemment, le premier qu'il a\n"
	.string "capturé était un ABRA.$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sa famille et ses amis?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LEO vient de DOUBLONVILLE, où vit\n"
	.string "encore sa famille.\p"
	.string "Il paraît que cette ville est très\n"
	.string "animée et festive.$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Apparemment, LEO ne supporte\n"
	.string "vraiment pas le lait.$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il est vraiment très gentil.\p"
	.string "Il recueille les POKéMON\n"
	.string "abandonnés ou orphelins.$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ce vieux est entré tout droit dans\n"
	.string "notre REPAIRE.\p"
	.string "Puis il s'est mis à nous accuser\n"
	.string "de maltraiter les POKéMON.\p"
	.string "Alors on en discute calmement,\n"
	.string "entre adultes.$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MAGAZINE DES FANS DE POKéMON\n"
	.string "Grand tirage mensuel!\p"
	.string "Le bulletin de participation est…\p"
	.string "Parti! Il a été découpé.\n"
	.string "Quelqu'un a déjà dû participer.$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Une rumeur raconte…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il paraît que M. FUJI n'est pas\n"
	.string "originaire d'ici non plus.$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sa famille et ses amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}C'est une photo d'AUGUSTE et de\n"
	.string "M. FUJI.\p"
	.string "Ils posent côte à côte avec un\n"
	.string "large sourire.$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Rédaction: Le timide M. FUJI a\n"
	.string "refusé toutes nos interviews.\p"
	.string "Cet homme bienveillant est aimé\n"
	.string "et respecté à LAVANVILLE.$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La TEAM ROCKET capture des POKéMON\n"
	.string "partout dans le monde.\p"
	.string "Ces outils sont essentiels à la\n"
	.string "bonne marche de nos activités.\p"
	.string "J'en suis le chef, GIOVANNI!$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Son type de POKéMON préféré?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ces voyous qui ont pris notre\n"
	.string "immeuble…\p"
	.string "Leur BOSS disait rechercher des\n"
	.string "POKéMON puissants.$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le BOSS de la TEAM ROCKET est\n"
	.string "terriblement cruel!\p"
	.string "Pour lui, les POKéMON ne sont que\n"
	.string "des outils à exploiter.$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Bienvenue dans mon repaire!\p"
	.string "J'y resterai jusqu'à ce que la\n"
	.string "TEAM ROCKET retrouve sa gloire.$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ça alors! GIOVANNI était le\n"
	.string "CHAMPION de JADIELLE?$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sa famille et ses amis?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Toi… Tu n'es pas l'enfant de\n"
	.string "GIOVANNI, si?\p"
	.string "Non, impossible. Son enfant a\n"
	.string "les cheveux rouges.$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. CHEN$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: PROF. CHEN\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pourquoi tes POKéMON luttent-ils\n"
	.string "avec tant d'ardeur pour toi?\p"
	.string "Parce qu'ils voient tout l'amour\n"
	.string "et toute la confiance que tu\l"
	.string "places en eux.\p"
	.string "Ne l'oublie jamais.$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}NINA$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: NINA\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pendant mes paisibles pauses thé,\n"
	.string "thé, tu es devenu très doué et\l"
	.string "puissant.\p"
	.string "J'espère que tu resteras un bon\n"
	.string "rival pour mon petit frère.$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PIERRE$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: PIERRE\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Notre vaste monde compte sûrement\n"
	.string "bien des DRESSEURS redoutables.\p"
	.string "Continuons tous les deux à nous\n"
	.string "entraîner et à progresser!$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ONDINE$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: ONDINE\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je vais continuer à m'entraîner\n"
	.string "dans cette ARÈNE.\p"
	.string "Une fois plus forte, j'aimerais\n"
	.string "partir sur les routes.$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MAJOR BOB$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: MAJOR BOB\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hé, petit!\n"
	.string "Notre combat m'a électrisé!\p"
	.string "J'ignorais qu'il existait des\n"
	.string "DRESSEURS aussi braves que toi.\p"
	.string "Tu m'as obligé à revoir mon\n"
	.string "jugement!$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: ERIKA\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je suis ravie qu'il existe de bons\n"
	.string "DRESSEURS comme toi.\p"
	.string "Le savoir suffit à m'inspirer et\n"
	.string "me pousse à redoubler d'efforts.\p"
	.string "Reviens me voir, je t'en prie.\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: KOGA\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Toi et moi devons viser toujours\n"
	.string "plus haut et travailler dur pour\l"
	.string "relever nos défis.\p"
	.string "Je dois aller entraîner ma fille.$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MORGANE$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: MORGANE\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}L'amour que tu portes à tes\n"
	.string "POKéMON…\p"
	.string "Même mes pouvoirs psychiques n'ont\n"
	.string "jamais pu surpasser cette force.$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AUGUSTE$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: AUGUSTE\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mes POKéMON FEU!\n"
	.string "Ils deviendront encore plus forts!\p"
	.string "Et maintenant, un quiz: combien\n"
	.string "existe-t-il de POKéMON FEU?$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LORELEI$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: LORELEI\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je tenais à te remercier pour ton\n"
	.string "aide.\p"
	.string "Mais cela n'a rien à voir avec nos\n"
	.string "combats.\p"
	.string "La prochaine fois, prends garde!$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ALDO$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: ALDO\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}J'ai éprouvé moi-même la force\n"
	.string "prodigieuse de tes POKéMON et toi.\p"
	.string "La prochaine fois, je devrais\n"
	.string "t'apprendre à t'entraîner.$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: AGATHA\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En vieillissant, ne te ramollis\n"
	.string "surtout pas comme ce vieux CHEN!\p"
	.string "Imite-moi: combats sans cesse!$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PETER$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: PETER\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}J'envisage de retourner dans ma\n"
	.string "ville natale.\p"
	.string "Je veux reprendre l'entraînement\n"
	.string "de mes POKéMON DRAGON.\p"
	.string "J'aimerais t'inviter chez moi\n"
	.string "un jour.$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LEO$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: LEO\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Salut! CELIO n'a dit que du bien\n"
	.string "de toi.\p"
	.string "Ça m'a fait plaisir à entendre.\p"
	.string "Si tu captures un POKéMON rare,\n"
	.string "viens me le montrer. Promis?$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}M. FUJI$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: M. FUJI\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Au lieu de souhaiter seulement le\n"
	.string "bonheur de tes POKéMON…\p"
	.string "…Accepterais-tu de souhaiter le\n"
	.string "bonheur de tous les POKéMON?$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: GIOVANNI\n"
	.string "À: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je n'ai rien à te dire.\n"
	.string "Absolument rien.\p"
	.string "Je vais uniquement me consacrer à\n"
	.string "mon propre perfectionnement.$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "BOURG PALETTE$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "LABORATOIRE$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "LABORATOIRE$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "JADIELLE$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "LABORATOIRE$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "LABORATOIRE$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "WATER LABYRINTH$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "JADIELLE$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "MANOIR DE CÉLADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "ARGENTA$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "ARÈNE D'ARGENTA$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "ARGENTA$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "ROUTE 4$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "MONT SÉLÉNITE$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "MUSÉE D'ARGENTA$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "AZURIA$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "ARÈNE D'AZURIA$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "ARÈNE D'AZURIA$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "ÎLES ÉCUME$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "CAP AZURIA$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "AZURIA$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "ARÈNE DE CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "ARÈNE DE CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "ARÈNE DE CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "ARÈNE DE CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "CÉLADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "ARÈNE DE CÉLADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "ARÈNE DE CÉLADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "ARÈNE DE CÉLADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "ARÈNE DE CÉLADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "MANOIR DE CÉLADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "ARÈNE DE PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "ARÈNE DE PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "PARC SAFARI$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "THREE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "ARÈNE DE SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "ARÈNE DE SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "ARÈNE DE SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "ARÈNE DE CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "ARÈNE DE CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "ARÈNE DE CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "RESORT GORGEOUS$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "FIVE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "EMBER SPA$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "TWO ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "SEVAULT CANYON$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "PLATEAU INDIGO$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "PLATEAU INDIGO$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "SEVEN ISLAND$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "SIX ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "CENTRE COMMERCIAL$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "PLATEAU INDIGO$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "PLATEAU INDIGO$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "AZURIA$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "AZURIA$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "LAVANVILLE$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "TOUR POKéMON$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "LAVANVILLE$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "LAVANVILLE$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "ARÈNE DE CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "REPAIRE ROCKET$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "SYLPHE SARL$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "SYLPHE SARL$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "ARÈNE DE JADIELLE$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "ARÈNE DE JADIELLE$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "ROCKET WAREHOUSE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "PROF. CHEN$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "ASSISTANT$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "ASSISTANT$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "ASSISTANT$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "FEMME$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "VIEILLE DAME$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "PIERRE$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "JEUNE HOMME$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "GARÇON$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "ONDINE$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "LUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "JEUNE HOMME$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "DAME$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "MAJOR BOB$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "DWAYNE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "LOLA$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "TAMIA$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "KOGA$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "KIRK$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "CHARINE$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "JEUNE HOMME$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "MORGANE$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "MORGANE$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "TYRON$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "AUGUSTE$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "DEREK$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "FEMME$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "VIEIL HOMME$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "FILLETTE$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "VIEILLE DAME$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "ALDO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "ALDO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "KARATÉKA$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "FEMME$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "KARATÉKA$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "KARATÉKA$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "KARATÉKA$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "VIEILLE DAME$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "PETER$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "PETER$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "FEMME$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "FILLETTE$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "JEUNE HOMME$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "PETIT GARÇON$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "VIEIL HOMME$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "FILLETTE$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "TEAM ROCKET$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "MAGAZINE$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "SCIENTIFIQUE$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "SCIENTIFIQUE$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "GIDEON$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "JOURNAL POKéMON\p"
	.string "Dossier: ARÈNE D'ARGENTA\n"
	.string "CHAMPION PIERRE!\p"
	.string "PIERRE rit rarement, mais une fois\n"
	.string "lancé, impossible de l'arrêter.$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "JOURNAL POKéMON\p"
	.string "Dossier: ARÈNE D'AZURIA\n"
	.string "CHAMPIONNE ONDINE!\p"
	.string "On dit qu'ONDINE admire LORELEI,\n"
	.string "membre du CONSEIL 4.$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "JOURNAL POKéMON\p"
	.string "Dossier: ARÈNE DE CARMIN SUR MER\n"
	.string "CHAMPION MAJOR BOB!\p"
	.string "Le MAJOR BOB aurait été pilote\n"
	.string "quand il vivait en Amérique.\p"
	.string "L'électricité de ses POKéMON\n"
	.string "alimentait son avion.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "JOURNAL POKéMON\p"
	.string "Dossier: ARÈNE DE CÉLADOPOLE\n"
	.string "CHAMPIONNE ERIKA!\p"
	.string "La rumeur dit qu'en regardant dans\n"
	.string "l'ARÈNE DE CÉLADOPOLE, on voit\l"
	.string "souvent ERIKA somnoler.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "JOURNAL POKéMON\p"
	.string "Dossier: ARÈNE DE PARMANIE\n"
	.string "CHAMPION KOGA!\p"
	.string "KOGA connaîtrait parfaitement la\n"
	.string "médecine.\p"
	.string "Il prépare même des remèdes pour\n"
	.string "soigner ses POKéMON.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "JOURNAL POKéMON\p"
	.string "Dossier: ARÈNE DE SAFRANIA\n"
	.string "CHAMPIONNE MORGANE!\p"
	.string "On dit que MORGANE communique avec\n"
	.string "ses POKéMON sans parler, même\l"
	.string "pendant les combats.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "JOURNAL POKéMON\p"
	.string "Dossier: ARÈNE DE CRAMOIS'ÎLE\n"
	.string "CHAMPION AUGUSTE!\p"
	.string "AUGUSTE n'ôterait ses lunettes\n"
	.string "noires que pour inventer de\l"
	.string "nouvelles questions.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "JOURNAL POKéMON\p"
	.string "Dossier spécial:\n"
	.string "LORELEI DU CONSEIL 4!\p"
	.string "Connue pour son style logique,\n"
	.string "calculé et glacial, LORELEI cache\l"
	.string "un secret étonnant!$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "JOURNAL POKéMON\p"
	.string "Dossier spécial:\n"
	.string "ALDO DU CONSEIL 4!\p"
	.string "ALDO aurait rejoint le CONSEIL 4\n"
	.string "pour assouvir son désir ardent\l"
	.string "d'affronter les meilleurs.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "JOURNAL POKéMON\p"
	.string "Dossier spécial:\n"
	.string "AGATHA DU CONSEIL 4!\p"
	.string "Dans leur jeunesse, AGATHA et le\n"
	.string "PROF. CHEN rivalisaient pour\l"
	.string "devenir le meilleur DRESSEUR.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "JOURNAL POKéMON\p"
	.string "Dossier spécial:\n"
	.string "PETER DU CONSEIL 4!\p"
	.string "Le grand-père de PETER serait\n"
	.string "l'ancien d'un célèbre clan de\l"
	.string "maîtres dragons.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "JOURNAL POKéMON\p"
	.string "Dossier: le PROF. CHEN,\n"
	.string "chercheur POKéMON!\p"
	.string "Le PROF. CHEN vivrait avec ses\n"
	.string "petits-enfants NINA et {RIVAL}.$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "C'est un JOURNAL POKéMON vieux de\n"
	.string "plusieurs années…\p"
	.string "JOURNAL POKéMON\n"
	.string "Spécial CONCOURS!\p"
	.string "La grande gagnante du CONCOURS\n"
	.string "du printemps: NINA CHEN,\l"
	.string "de BOURG PALETTE!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "JOURNAL POKéMON\p"
	.string "Dossier spécial:\n"
	.string "M. FUJI de la MAISON POKéMON!\p"
	.string "Rédaction: Le timide M. FUJI a\n"
	.string "refusé toutes nos interviews.\p"
	.string "Cet homme bienveillant est aimé\n"
	.string "et respecté à LAVANVILLE.$"
