Trade_Text_LookingForMonWannaTradeForMon::
	.string "Je cherche le POKéMON\n"
	.string "{STR_VAR_1}!\p"
	.string "Tu veux l'échanger contre mon\n"
	.string "{STR_VAR_2} ?$"

Trade_Text_AwwOhWell::
	.string "Oooh !\n"
	.string "Bon, tant pis…$"

Trade_Text_WhatThatsNoMon::
	.string "Quoi ?\n"
	.string "Ce n'est pas {STR_VAR_1} !$"

Trade_Text_HeyThanks::
	.string "Hé, merci !$"

Trade_Text_IsntMyOldMonGreat::
	.string "Mon {STR_VAR_2} est formidable !$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "Bonjour ! Aurais-tu par hasard\n"
	.string "un {STR_VAR_1} ?\p"
	.string "Veux-tu l'échanger contre\n"
	.string "mon {STR_VAR_2} ?$"

Trade_Text_WellIfYouDontWantTo::
	.string "Bon, si tu ne veux pas…$"

Trade_Text_ThisIsntMon::
	.string "Hmm ?\n"
	.string "Ce n'est pas un {STR_VAR_1}.\p"
	.string "Pense à moi si tu en trouves un.$"

Trade_Text_Thanks::
	.string "Merci !$"

Trade_Text_HasTradedMonGrownStronger::
	.string "Le {STR_VAR_2} échangé est-il\n"
	.string "est-il devenu plus fort ?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "Salut !\n"
	.string "Tu as un {STR_VAR_1} ?\p"
	.string "Tu veux l'échanger contre mon\n"
	.string "{STR_VAR_2} ?$"

Trade_Text_ThatsTooBad::
	.string "Quel dommage.$"

Trade_Text_ThisIsNoMon::
	.string "…Ce n'est pas {STR_VAR_1}.\p"
	.string "Si tu en trouves, viens me voir.$"

Trade_Text_ThanksYoureAPal::
	.string "Merci, tu es un vrai pote !$"

Trade_Text_HowIsMyOldMon::
	.string "Mon {STR_VAR_2} va bien ?\n"
	.string "Mon {STR_VAR_1} va très bien !$"
