LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Ici, c'est le COIN LOTO POKéMON.\p"
	.string "Chaque client du GRAND MAGASIN\n"
	.string "peut tirer un TICKET LOTO POKéMON.\p"
	.string "Si son numéro correspond à l'ID\n"
	.string "de l'un de tes POKéMON,\l"
	.string "tu recevras un superbe cadeau.\p"
	.string "Veux-tu tirer un TICKET LOTO\n"
	.string "POKéMON ?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Reviens demain, s'il te plaît.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Reviens nous voir !$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Choisis un TICKET LOTO.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "Le numéro du TICKET est {STR_VAR_1}.\p"
	.string "Je dois vérifier ce numéro\n"
	.string "pour voir s'il correspond à l'ID\l"
	.string "d'un de tes POKéMON. Un instant.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Félicitations !\p"
	.string "Dans ton équipe, l'ID du POKéMON\n"
	.string "{STR_VAR_1} correspond à celui\l"
	.string "du TICKET LOTO !$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Félicitations !\p"
	.string "Dans ton PC, l'ID du POKéMON\n"
	.string "{STR_VAR_1} correspond à celui\l"
	.string "du TICKET LOTO !$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Je suis désolée.\n"
	.string "Aucun numéro ne correspond.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Deux chiffres correspondent : tu\n"
	.string "gagnes le troisième prix !\l"
	.string "Tu remportes {STR_VAR_1} !$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Trois chiffres correspondent : tu\n"
	.string "gagnes le deuxième prix !\l"
	.string "Tu remportes {STR_VAR_1} !$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Quatre chiffres correspondent : tu\n"
	.string "gagnes le premier prix !\l"
	.string "Tu remportes {STR_VAR_1} !$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Incroyable ! Les cinq chiffres\n"
	.string "correspondent !\p"
	.string "Tu décroches le gros lot !\n"
	.string "Tu remportes {STR_VAR_1} !$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Oh ?\n"
	.string "Tu n'as pas de place pour ça.\p"
	.string "Fais de la place dans ton SAC et\n"
	.string "préviens-moi.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER} ?\n"
	.string "Oui, je t'attendais.\p"
	.string "Voici le prix que nous gardions\n"
	.string "pour toi.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Reviens nous voir !$"
