MatchCall_WildBattleText1::
	.string "Salut, {PLAYER}{KUN}! C'est {STR_VAR_1}. J'ai\n"
	.string "vu un {STR_VAR_2}, il y a peu.\p"
	.string "Mais impossible de\n"
	.string "l'attraper! J'étais à\p"
	.string "deux doigts de réussir,\n"
	.string "pourtant! Bon, À bientôt!$"

MatchCall_WildBattleText2::
	.string "Bonjour, {PLAYER}{KUN}. C'est .\n"
	.string "Il n'y a pas très\p"
	.string "longtemps, j'ai\n"
	.string "essayé d'attraper un\p"
	.string "{STR_VAR_1}. Mais il s'est\n"
	.string "enfui! Tu parles que\p"
	.string "j'ai été déçue! À bientôt!$"

MatchCall_WildBattleText3::
	.string "Salut, {STR_VAR_2}! C'est moi, {PLAYER}. Je\n"
	.string "viens d'essayer\p"
	.string "d'attraper un {STR_VAR_1}, mais je\n"
	.string "l'ai raté. C'est rageant,\p"
	.string "j'étais à deux doigts d'y\p"
	.string "arriver! Bon, ça m'a gâché\n"
	.string "la journée… Bon, à plus!$"

MatchCall_WildBattleText4::
	.string "Allô, {STR_VAR_2}{PLAYER}? Ici {KUN}.\n"
	.string "Bonjour! Tu\p"
	.string "connais le POKéMON\n"
	.string "{STR_VAR_1}? J'ai failli en\p"
	.string "attraper un… Je\n"
	.string "pensais vraiment\p"
	.string "l'avoir! Si j'en\n"
	.string "revois un, je ne le\p"
	.string "louperai pas! Bon, à plus!$"

MatchCall_WildBattleText5::
	.string "Salut, {STR_VAR_2}{PLAYER}! {KUN} à\n"
	.string "l'appareil. Alors, des\l"
	.string "nouveaux POKéMON? Moi,\p"
	.string "j'ai failli en attraper\n"
	.string "un récemment, mais il\p"
	.string "s'est enfui. Bon, à plus!$"

MatchCall_WildBattleText6::
	.string "Salut, {STR_VAR_1}{PLAYER}. Ici {KUN}. Tu as\n"
	.string "attrapé des POKéMON?\l"
	.string "Récemment, j'en ai\p"
	.string "presque eu un, mais il\n"
	.string "m'a filé entre les\p"
	.string "doigts! Bon, à bientôt!$"

MatchCall_WildBattleText7::
	.string "{STR_VAR_1}{PLAYER}, c'est toi? Salut, {KUN}\n"
	.string "à l'appareil. Tu sais\p"
	.string "quoi? Je n'arrive\n"
	.string "pas à attraper de {STR_VAR_1}…\p"
	.string "Sacré nom d'un chien!\n"
	.string "Il n'y a rien à faire!$"

MatchCall_WildBattleText8::
	.string "Ça va, {STR_VAR_2}{PLAYER}? C'est {KUN}. Tu\n"
	.string "attrapes beaucoup\p"
	.string "de POKéMON en ce\n"
	.string "moment? J'ai failli\p"
	.string "en attraper un\n"
	.string "récemment, mais j'ai\p"
	.string "échoué. Je ne baisse\n"
	.string "pas les bras! A bientôt!$"

MatchCall_WildBattleText9::
	.string "Salut, {STR_VAR_1}{PLAYER}! C'est {KUN}!\n"
	.string "Alors, tu agrandis\p"
	.string "ta collection de\n"
	.string "POKéMON? J'en ai\p"
	.string "par-dessus la tête\n"
	.string "des POKéMON! Ils\p"
	.string "m'échappent tous! À bientôt!$"

MatchCall_WildBattleText10::
	.string "Coucou, {STR_VAR_1}{PLAYER}… C'est moi, {KUN}.\n"
	.string "Je voulais te dire…\p"
	.string "J'ai failli attraper\n"
	.string "un {STR_VAR_1}… Mais je l'ai\p"
	.string "laissé filer… Il faut\p"
	.string "que je persévère, je\n"
	.string "sais. A bientôt, j'espère.$"

MatchCall_WildBattleText11::
	.string "{STR_VAR_2}{PLAYER}? Bonjour, c'est {KUN}.\n"
	.string "Comment ça va? J'ai\l"
	.string "essayé d'attraper\p"
	.string "un {STR_VAR_1} sauvage, mais\n"
	.string "il a filé! Je\p"
	.string "perds un peu confiance…$"

MatchCall_WildBattleText12::
	.string "Bonjour, {STR_VAR_2}{PLAYER}. C'est {KUN}. Tu\n"
	.string "attrapes toujours des\l"
	.string "POKéMON? J'essaie de\p"
	.string "m'y mettre, mais c'est\n"
	.string "loin d'être facile!\p"
	.string "Les POKéMON sont malins!$"

MatchCall_WildBattleText13::
	.string "Bonjour, {STR_VAR_1}{PLAYER}! C'est {KUN} qui\n"
	.string "appelle! Tu as de\l"
	.string "nouveaux POKéMON? J'ai\p"
	.string "moi-même essayé, mais ce\n"
	.string "fut un échec, je dois\p"
	.string "dire. Les POKéMON sont malins!$"

MatchCall_WildBattleText14::
	.string "Bonjour, {STR_VAR_1}{PLAYER}, comment\n"
	.string "vas-tu? C'est {KUN}. Je\p"
	.string "viens d'essayer\n"
	.string "d'attraper un joli\p"
	.string "petit {STR_VAR_1}. Mais il s'est\n"
	.string "enfui! Crois-moi, j'ai\p"
	.string "été déçue! À bientôt!$"

MatchCall_WildBattleText15::
	.string "Bonjour, {STR_VAR_2}! Ici {PLAYER}! Je\n"
	.string "pense me mettre à\p"
	.string "attraper des POKéMON,\n"
	.string "tu sais. Mais le\p"
	.string "problème, c'est que je\n"
	.string "n'en vois aucun! C'est\p"
	.string "étrange, non? Bon, je\n"
	.string "te laisse. À bientôt!$"

MatchCall_NegativeBattleText1::
	.string "Salut, {STR_VAR_1}{PLAYER}! C'est {KUN}. J'ai\n"
	.string "essayé de me battre\p"
	.string "contre un autre\n"
	.string "DRESSEUR, mais j'ai\p"
	.string "perdu. J'étais très\n"
	.string "déçu, tu sais. Bon, salut!$"

MatchCall_NegativeBattleText2::
	.string "Bonjour, {STR_VAR_1}{PLAYER}. C'est {KUN}. J'ai\n"
	.string "affronté quelqu'un\p"
	.string "d'autre après notre\n"
	.string "combat. J'ai été pas mal,\p"
	.string "mais j'ai perdu. Je ferai\n"
	.string "mieux la prochaine fois.$"

MatchCall_NegativeBattleText3::
	.string "Salut, {STR_VAR_1}! C'est moi, {PLAYER}.\n"
	.string "Je viens de perdre\p"
	.string "un combat. Je suppose\p"
	.string "que mon équipe n'est\n"
	.string "pas encore au point!$"

MatchCall_NegativeBattleText4::
	.string "Salut, {STR_VAR_1}. {PLAYER} à l'appareil.\n"
	.string "J'ai refait un combat\p"
	.string "hier, mais je n'en suis\n"
	.string "pas sorti vainqueur. Je\p"
	.string "dois entraîner mon\n"
	.string "équipe davantage. Bon, à plus!$"

MatchCall_NegativeBattleText5::
	.string "Salut, {STR_VAR_1}! {PLAYER} à\n"
	.string "l'appareil. Tout se\p"
	.string "passe bien? J'ai fait\p"
	.string "quelques combats, mais\n"
	.string "je n'ai pas gagné\p"
	.string "souvent. Je ne suis pas\n"
	.string "encore au point! Bon, à plus!$"

MatchCall_NegativeBattleText6::
	.string "Salut, {STR_VAR_1}. Ici {PLAYER}. Tout\n"
	.string "va comme tu veux? Je\p"
	.string "mets toute mon énergie\p"
	.string "au combat, mais je\n"
	.string "perds souvent. Je ne\p"
	.string "suis pas encore dans\n"
	.string "l'esprit. Bon, à bientôt!$"

MatchCall_NegativeBattleText7::
	.string "Ici {STR_VAR_1}. Comment ça se\n"
	.string "passe? J'ai perdu\p"
	.string "un combat hier. Je\n"
	.string "n'arrête pas d'y\p"
	.string "penser. Il faut que\n"
	.string "je me reprenne… Salut!$"

MatchCall_NegativeBattleText8::
	.string "Ça va, {STR_VAR_1}{PLAYER}? C'est {KUN}.\n"
	.string "Comment vont tes\p"
	.string "POKéMON? J'ai perdu\n"
	.string "un combat, Récemment.\p"
	.string "Je ne baisse pas les\n"
	.string "bras! Bon, à bientôt!$"

MatchCall_NegativeBattleText9::
	.string "Salut, {STR_VAR_1}{PLAYER}! C'est {KUN}! Dis\n"
	.string "donc, j'ai quelque\p"
	.string "chose à te dire! J'ai\n"
	.string "fait un combat de\p"
	.string "POKéMON hier et j'ai\n"
	.string "perdu au dernier moment.\p"
	.string "Qu'est-ce que c'est frustrant!$"

MatchCall_NegativeBattleText10::
	.string "Coucou, {STR_VAR_1}{PLAYER}… C'est moi, {KUN}.\n"
	.string "J'ai fait un combat\p"
	.string "aujourd'hui. Mais j'ai\n"
	.string "perdu… Mes POKéMON ne\p"
	.string "sont pas encore au top\n"
	.string "niveau. A bientôt, j'espère.$"

MatchCall_NegativeBattleText11::
	.string "{STR_VAR_1}{PLAYER}? Bonjour, c'est {KUN}.\n"
	.string "Comment vont tes\l"
	.string "POKéMON? Moi, je viens de\p"
	.string "perdre un combat. C'est\p"
	.string "pas la joie… Bon, À bientôt!$"

MatchCall_NegativeBattleText12::
	.string "Bonjour, {STR_VAR_1}{PLAYER}. C'est {KUN}.\n"
	.string "Tu continues les\l"
	.string "combats? Je perds\p"
	.string "souvent ces derniers\n"
	.string "temps. Je dois renforcer\p"
	.string "mon équipe! A bientôt.$"

MatchCall_NegativeBattleText13::
	.string "Bonjour, {STR_VAR_1}{PLAYER}! C'est {KUN} qui\n"
	.string "appelle! J'espère que\p"
	.string "tu te portes bien. J'ai\p"
	.string "fait un combat tout\n"
	.string "récemment. Prends-en de\p"
	.string "la graine, {STR_VAR_1}{PLAYER}! Il faut\n"
	.string "garder la forme! À bientôt!$"

MatchCall_NegativeBattleText14::
	.string "Bonjour, {KUN}{PLAYER}. C'est {KUN}.\n"
	.string "Tout se passe comme\p"
	.string "tu veux? Tu sais,\p"
	.string "tu devrais rentrer\n"
	.string "chez toi de temps\p"
	.string "en temps. À bientôt!$"

MatchCall_PositiveBattleText1::
	.string "Salut, {STR_VAR_1}{PLAYER}! C'est {KUN}.\n"
	.string "J'ai combattu\p"
	.string "contre un autre\n"
	.string "DRESSEUR et j'ai\p"
	.string "gagné! Mon {STR_VAR_1} s'est\n"
	.string "vraiment démené! C'est super!$"

MatchCall_PositiveBattleText2::
	.string "Salut, {STR_VAR_2}{PLAYER}! C'est\n"
	.string "{KUN}! J'ai gagné\p"
	.string "un combat hier,\n"
	.string "c'était super!$"

MatchCall_PositiveBattleText3::
	.string "Salut, {STR_VAR_1}! C'est moi,\n"
	.string "{PLAYER}. Ça va, les\l"
	.string "combats? Moi, j'en ai\p"
	.string "fait un Récemment et\n"
	.string "mon {STR_VAR_1} a été épatant!\p"
	.string "Si on refait un\n"
	.string "combat, je ne perdrai pas, {STR_VAR_2}!$"

MatchCall_PositiveBattleText4::
	.string "Salut, {PLAYER}. C'est {PLAYER}.\n"
	.string "J'ai fait un\p"
	.string "combat, aujourd'hui.\n"
	.string "J'ai gagné, mais de\p"
	.string "justesse! Mon {STR_VAR_1} a été\n"
	.string "super, en tout cas.$"

MatchCall_PositiveBattleText5::
	.string "Salut, {STR_VAR_2}{PLAYER}! {KUN} à\n"
	.string "l'appareil. Comment va\p"
	.string "la vie? Toujours à faire\n"
	.string "des combats? Tiens, j'en\p"
	.string "ai gagné un récemment\n"
	.string "grâce à mon {STR_VAR_1}! La\p"
	.string "prochaine fois, c'est toi\n"
	.string "que je battrai! Bon, à plus!$"

MatchCall_PositiveBattleText6::
	.string "Salut, {STR_VAR_2}{PLAYER}. Ici {KUN}.\n"
	.string "Comment va? Pour\p"
	.string "moi tout baigne,\p"
	.string "je viens de gagner\n"
	.string "un combat. Si\p"
	.string "jamais on se\n"
	.string "recroise, je ne perdrai pas!$"

MatchCall_PositiveBattleText7::
	.string "{STR_VAR_1}{PLAYER}? Ici {KUN}. J'adore\n"
	.string "mon {STR_VAR_1}, il vient\p"
	.string "juste de me faire\n"
	.string "gagner! J'ai hâte\p"
	.string "de refaire un\n"
	.string "combat contre toi.$"

MatchCall_PositiveBattleText8::
	.string "Ça va, {STR_VAR_2}{PLAYER}? C'est {KUN}.\n"
	.string "J'espère que tu vas\p"
	.string "bien. Tu sais, je\n"
	.string "viens de gagner un\p"
	.string "combat! Mon {STR_VAR_1} a été\n"
	.string "brillant! Il fallait que\p"
	.string "je te le dise! À bientôt!$"

MatchCall_PositiveBattleText9::
	.string "Salut, {STR_VAR_2}{PLAYER}! C'est {KUN}!\n"
	.string "Comment vont tes\p"
	.string "POKéMON? Nous, on\n"
	.string "vient de gagner un\p"
	.string "combat! Mon {STR_VAR_1} a été\n"
	.string "absolument spectaculaire.\p"
	.string "Quel dommage que tu\n"
	.string "n'aies pas vu ça! À bientôt!$"

MatchCall_PositiveBattleText10::
	.string "Coucou, {STR_VAR_2}{PLAYER}… C'est moi, {KUN}.\n"
	.string "Comment va la vie? Mes\p"
	.string "POKéMON sont en super\p"
	.string "forme, ces derniers\n"
	.string "temps. Ils viennent de\p"
	.string "me faire gagner un\n"
	.string "combat. A bientôt, j'espère.$"

MatchCall_PositiveBattleText11::
	.string "{STR_VAR_1}{PLAYER}? Bonjour, c'est {KUN}. Tu\n"
	.string "as fait des combats,\p"
	.string "récemment? Moi, j'en\n"
	.string "ai gagné un\p"
	.string "aujourd'hui! Je suis sur la\n"
	.string "bonne voie! Bon, À bientôt!$"

MatchCall_PositiveBattleText12::
	.string "Bonjour, {STR_VAR_1}{PLAYER}. C'est {KUN}. Tout\n"
	.string "va bien, mon petit? Je\p"
	.string "suis frais comme un\n"
	.string "gardon! Je n'arrête pas\p"
	.string "de gagner des combats,\n"
	.string "tous les jours! Contre\l"
	.string "des jeunes gens, en plus!$"

MatchCall_PositiveBattleText13::
	.string "Bonjour, {STR_VAR_1}{PLAYER}! C'est {KUN} qui\n"
	.string "appelle! J'espère que\p"
	.string "tout va bien. Moi j'ai\n"
	.string "la pêche! J'enchaîne\p"
	.string "les victoires aux\n"
	.string "combats! Et les petits\l"
	.string "jeunes ne me font pas\p"
	.string "peur, tu sais! À bientôt!$"

MatchCall_PositiveBattleText14::
	.string "Bonjour, {STR_VAR_1}{PLAYER}. C'est {KUN}.\n"
	.string "J'ai fait un combat\p"
	.string "il y a peu et mon {STR_VAR_1} a\n"
	.string "été formidable!\p"
	.string "J'aurais aimé que tu\n"
	.string "voies ça, {STR_VAR_2}{PLAYER}. À bientôt!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Salut, {KUN}! C'est {PLAYER}.\n"
	.string "Quoi, tu es près\p"
	.string "de… {STR_VAR_1}, tu dis? Mais\n"
	.string "il faut qu'on fasse\p"
	.string "un combat! Je\n"
	.string "t'attends, à tout de suite!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Salut, {STR_VAR_2}!\n"
	.string "C'est {PLAYER}. {STR_VAR_1}?\p"
	.string "C'est là que\n"
	.string "tu es? On fait\p"
	.string "un combat?\n"
	.string "Bon, je t'attends!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Salut, {STR_VAR_2}! C'est moi,\n"
	.string "{PLAYER}. {STR_VAR_1}, tu dis? C'est là\p"
	.string "que tu te trouves?\n"
	.string "Que le monde est\p"
	.string "petit! On fait un\n"
	.string "combat? Cette fois, je\p"
	.string "ne perdrai pas! Je ne\n"
	.string "bouge pas, je t'attends!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Allô, {STR_VAR_2}{PLAYER}? Ici {KUN}.\n"
	.string "Bonjour! Où tu es?\p"
	.string "{STR_VAR_1}? Ah, oui? Il faut\n"
	.string "absolument qu'on\p"
	.string "fasse un combat,\n"
	.string "alors! Je t'attends!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Salut, {STR_VAR_2}{PLAYER}! {KUN} à\n"
	.string "l'appareil. Ça\l"
	.string "roule? Où\p"
	.string "es-tu? {STR_VAR_1}? Si on\n"
	.string "en profitait\p"
	.string "pour refaire un\n"
	.string "combat? J'espère\p"
	.string "bien que tu vas\n"
	.string "venir! Je t'attends!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Salut, {STR_VAR_2}{PLAYER}. Ici {KUN}. Je\n"
	.string "viens aux nouvelles.\l"
	.string "{STR_VAR_1}, vraiment? On est\p"
	.string "tout près, alors!\n"
	.string "C'est l'occasion ou\p"
	.string "jamais de refaire un\n"
	.string "combat! Je trépigne\p"
	.string "d'impatience. A tout\n"
	.string "de suite, je t'attends!$"

MatchCall_SameRouteBattleRequestText7::
	.string "Heu… {STR_VAR_2}{PLAYER}? Ici {KUN}… {STR_VAR_1}?\n"
	.string "Tu es dans le\p"
	.string "coin, alors!\n"
	.string "Faisons un\p"
	.string "combat! Tu viens?\n"
	.string "Je vais te montrer\p"
	.string "mes POKéMON.\n"
	.string "Dépêche-toi, je t'attends.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Ça va, {STR_VAR_2}{PLAYER}? C'est {KUN}.\n"
	.string "Tu es près de… {STR_VAR_1},\p"
	.string "c'est ça? Ça te\n"
	.string "dirait de faire\p"
	.string "un petit combat\n"
	.string "contre moi?\p"
	.string "Bon, je\n"
	.string "t'attends. A très bientôt!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Salut, {STR_VAR_2}{PLAYER}! C'est {KUN}!\n"
	.string "La forme? {STR_VAR_1}? Pas\p"
	.string "possible! Ne\n"
	.string "ratons pas cette\p"
	.string "occasion. On fait\n"
	.string "un combat? Bon\p"
	.string "Bon, je t'attends!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Coucou, {STR_VAR_2}{PLAYER}… C'est moi,\n"
	.string "{KUN}. Tu es où? Près de…\p"
	.string "{STR_VAR_1}?!? J'y suis! J'ai\n"
	.string "très envie de te\p"
	.string "voir. On fait un\p"
	.string "combat? Je suis prête!\n"
	.string "Ne me fais pas attendre…$"

MatchCall_SameRouteBattleRequestText11::
	.string "{STR_VAR_2}{PLAYER}? Bonjour, c'est {KUN}.\n"
	.string "Où est-ce que tu\p"
	.string "es? {STR_VAR_1}? Il faut\n"
	.string "qu'on se rencontre\p"
	.string "pour un combat,\n"
	.string "qu'en dis-tu?\p"
	.string "D'accord, je ne bouge\n"
	.string "pas. A tout de suite!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Bonjour, {STR_VAR_2}{PLAYER}. C'est {KUN}.\n"
	.string "{STR_VAR_1}. Où es-tu, mon\l"
	.string "petit? {STR_VAR_2}? Je ne\p"
	.string "suis pas loin! Et\n"
	.string "si on faisait un\p"
	.string "combat? C'est\n"
	.string "l'occasion ou\p"
	.string "jamais! Je t'attends,\n"
	.string "mon petit. A bientôt!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Bonjour, {PLAYER}{KUN}! C'est {STR_VAR_1}\n"
	.string "qui appelle! Où te\p"
	.string "trouves-tu? {STR_VAR_2}? Dis\n"
	.string "donc, je suis tout\p"
	.string "près. Tu viens me\n"
	.string "voir pour faire un\p"
	.string "combat? Bien, je\n"
	.string "t'attends. A tout de suite.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Bonjour, {PLAYER}{KUN}. C'est {STR_VAR_1}.\n"
	.string "Où ça? {STR_VAR_2}? Mais\p"
	.string "c'est tout près!\n"
	.string "Tu ne crois pas\p"
	.string "qu'on devrait se\n"
	.string "rencontrer pour un\p"
	.string "combat? D'accord, je\n"
	.string "t'attends. À bientôt!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Salut, {PLAYER}! C'est {STR_VAR_1}. Tu\n"
	.string "sais quoi? J'ai envie de\p"
	.string "faire un combat contre\p"
	.string "toi! Bon, je suis aux\n"
	.string "alentours de {STR_VAR_2}. A bientôt!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Salut, {PLAYER}! C'est {STR_VAR_1}.\n"
	.string "Dis, tu veux bien\p"
	.string "refaire un\n"
	.string "combat contre moi?\p"
	.string "Tu me trouveras\n"
	.string "près de {STR_VAR_2}. À bientôt!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Salut, {PLAYER}! C'est moi,\n"
	.string "{STR_VAR_1}. Mes POKéMON ont\p"
	.string "bien progressé depuis\n"
	.string "la dernière fois. Je\p"
	.string "voudrais bien qu'ils\n"
	.string "se mesurent encore\p"
	.string "aux tiens, {PLAYER}. On\p"
	.string "refait un combat?\n"
	.string "D'accord, je suis près de {STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Allô, {PLAYER}{KUN}? Ici {STR_VAR_1}.\n"
	.string "Bonjour! Ça va,\l"
	.string "toi? Mes POKéMON\p"
	.string "sont bien\n"
	.string "meilleurs, tu sais.\p"
	.string "Tu veux bien qu'on\n"
	.string "refasse un combat?\p"
	.string "D'accord, je\n"
	.string "t'attends aux alentours de {STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Salut, {PLAYER}{KUN}! {STR_VAR_1} à\n"
	.string "l'appareil. Mes POKéMON\p"
	.string "ont bien progressé, je\n"
	.string "suis drôlement fier\p"
	.string "d'eux. Je voudrais\n"
	.string "refaire un combat contre\p"
	.string "toi. Je t'attends du\n"
	.string "côté de {STR_VAR_2}, alors. À bientôt!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Salut, {PLAYER}{KUN}. Ici {STR_VAR_1}. J'espère\n"
	.string "que ça roule pour toi.\l"
	.string "Je me disais que Je\p"
	.string "voudrais bien faire un\n"
	.string "autre combat contre toi.\p"
	.string "Dis donc, si ça te dit, on\n"
	.string "peut se voir près de {STR_VAR_2}.\p"
	.string "Peut-être à tout à l'heure!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "Heu… {PLAYER}{KUN}? Ici {STR_VAR_1}… Alors?\n"
	.string "Tes POKéMON vont\l"
	.string "bien? Les miens sont\p"
	.string "de plus en plus forts!\n"
	.string "Je voudrais que tu les\p"
	.string "voies. Je suis près\n"
	.string "de {STR_VAR_2}. Passe, si tu veux\p"
	.string "combattre. À bientôt.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Ça va, {PLAYER}{KUN}? C'est {STR_VAR_1}.\n"
	.string "J'espère que tout va\p"
	.string "bien pour toi. Mes\n"
	.string "POKéMON sont en super\p"
	.string "forme. Si tu passes dans\n"
	.string "le coin, Je voudrais bien\p"
	.string "qu'on combatte. Je suis\n"
	.string "près de {STR_VAR_2}. A bientôt, j'espère!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Salut, {PLAYER}{KUN}! C'est {STR_VAR_1}!\n"
	.string "Comment vont tes\l"
	.string "POKéMON? Les miens\p"
	.string "progressent à vue\n"
	.string "d'œil, {PLAYER}{KUN}. Je suis près\p"
	.string "de {STR_VAR_2}. Passe faire un\n"
	.string "combat, si tu veux.\p"
	.string "J'espère te voir bientôt!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Coucou, {PLAYER}{KUN}… C'est moi,\n"
	.string "{STR_VAR_1}. Comment vas-tu?\l"
	.string "Mes POKéMON ont fait\p"
	.string "d'énormes progrès.\n"
	.string "Je voudrais beaucoup\p"
	.string "refaire un combat\n"
	.string "contre toi, {PLAYER}{KUN}. Je\p"
	.string "suis près de {STR_VAR_2}. Passe\n"
	.string "me voir à l'occasion.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "{PLAYER}{KUN}? Bonjour, c'est {STR_VAR_1}.\n"
	.string "Mes POKéMON\l"
	.string "débordent de vie.\p"
	.string "Je pense qu'ils ont\n"
	.string "envie de revoir\l"
	.string "tes POKéMON, {PLAYER}{KUN}. Je\p"
	.string "suis vers {STR_VAR_2}. J'espère\n"
	.string "que tu vas passer.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Bonjour, {PLAYER}{KUN}. C'est {STR_VAR_1}. Je\n"
	.string "voulais te dire que\p"
	.string "mes POKéMON sont\n"
	.string "devenus très forts. Je\p"
	.string "voudrais bien qu'on\n"
	.string "refasse un combat tous\p"
	.string "les deux, {PLAYER}{KUN}. On est aux\n"
	.string "alentours de {STR_VAR_2}. A bientôt!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Bonjour, {PLAYER}{KUN}! C'est {STR_VAR_1} qui\n"
	.string "appelle! Comment vont tes\l"
	.string "POKéMON? Mes POKéMON vont\p"
	.string "tellement bien qu'ils\n"
	.string "battraient n'importe qui!\p"
	.string "Je voudrais faire un\n"
	.string "nouveau combat contre toi,\p"
	.string "pour les tester. Si tu\n"
	.string "passes près de {STR_VAR_2}, viens nous voir.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Bonjour, {PLAYER}{KUN}. C'est {STR_VAR_1}.\n"
	.string "J'espère que tu vas\l"
	.string "bien. Oui, mes POKéMON\p"
	.string "ont beaucoup appris\n"
	.string "depuis la dernière fois.\p"
	.string "Tu ne crois pas qu'on\n"
	.string "devrait refaire un combat,\p"
	.string "{PLAYER}{KUN}? On est près de {STR_VAR_2}, en ce\n"
	.string "moment. J'espère que tu\p"
	.string "vas venir nous voir bientôt!$"

MatchCall_PersonalizedText1::
	.string "C'est {STR_VAR_1}, l'amoureux de la\n"
	.string "montagne! Tu as passé du\p"
	.string "temps en montagne depuis la\n"
	.string "dernière fois? J'y suis\p"
	.string "souvent mais je te croise\p"
	.string "rarement… La prochaine fois,\n"
	.string "on pourrait se voir près de {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "C'est {STR_VAR_1}. Bonjour. J'ai\n"
	.string "parlé de toi à un nouveau\p"
	.string "DRESSEUR. J'ai dit que je\n"
	.string "connaissais un bon DRESSEUR\p"
	.string "qui s'occupe de ses\n"
	.string "POKéMON avec grand soin.\p"
	.string "D'ici peu, tout le monde\n"
	.string "t'admirera. Tu vas devenir\p"
	.string "J'espère qu'on se reverra!$"

MatchCall_PersonalizedText3::
	.string "C'est {STR_VAR_1}. Bonjour! Je\p"
	.string "me trouve dans un\n"
	.string "endroit magnifique aux\p"
	.string "senteurs exquises!\n"
	.string "Quelqu'un a dû planter\p"
	.string "des BAIES. À bientôt!$"

MatchCall_PersonalizedText4::
	.string "Bonjour! Trente ans de\n"
	.string "fouilles, {STR_VAR_1} à ton service! On\p"
	.string "dirait que tu as la\n"
	.string "bougeotte, tu es toujours en\p"
	.string "vadrouille. Tu as découvert\n"
	.string "des ruines en chemin? Si tu en\p"
	.string "vois, pense à moi! Je te\n"
	.string "J'ai des ruines à explorer.$"

MatchCall_PersonalizedText5::
	.string "C'est {STR_VAR_1}! Devine ce que je\p"
	.string "fais! J'admire les vagues sur\n"
	.string "la plage! Oh… Les reflets du\p"
	.string "soleil sur l'eau sont\n"
	.string "magnifiques. Ça scintille! Je\l"
	.string "commence à avoir faim. À bientôt!$"

MatchCall_PersonalizedText6::
	.string "Miam, miam… Oh, salut!\n"
	.string "C'est {STR_VAR_1}. J'adore manger\l"
	.string "sur la plage. Mes POKéMON\p"
	.string "et moi allons bien. On est\n"
	.string "gonflés à bloc! Je vais\l"
	.string "faire trempette. À bientôt!$"

MatchCall_PersonalizedText7::
	.string "Salut, c'est {STR_VAR_1}… Cette\p"
	.string "histoire de TOPDRESSEUR\n"
	.string "m'est un peu montée à la\p"
	.string "tête… Tout le monde croit\n"
	.string "que je suis un DRESSEUR\l"
	.string "parfait. Je ne veux pas\p"
	.string "les décevoir. Je suppose\n"
	.string "que c'est le revers de la\p"
	.string "médaille. Il faut que je\n"
	.string "m'entraîne dur… Et avec le\p"
	.string "sourire, en plus! Il n'y a\n"
	.string "vraiment qu'à toi que je\p"
	.string "pouvais dire ça. Merci, ça\n"
	.string "m'a fait du bien de te parler!$"

MatchCall_PersonalizedText8::
	.string "Salut, toi! C'est {STR_VAR_1}! Ça\n"
	.string "va? J'essaie de bien\p"
	.string "m'occuper de mes POKéMON.\n"
	.string "Tu es mon modèle. La\p"
	.string "prochaine fois qu'on se\n"
	.string "battra, je ferai tout pour\p"
	.string "gagner. C'est super d'avoir\n"
	.string "des amis DRESSEURS! A bientôt!$"

MatchCall_PersonalizedText9::
	.string "C'est {STR_VAR_1}… Attention,\n"
	.string "derrière toi… Il y\l"
	.string "avait quelque chose,\p"
	.string "non? La puissance des\n"
	.string "POKéMON qui reposent\p"
	.string "au MONT MEMORIA… Elle\p"
	.string "me parle de toi… Tu\n"
	.string "dois partir\p"
	.string "immédiatement! Surtout, ne\n"
	.string "te retourne pas… À bientôt…$"

MatchCall_PersonalizedText10::
	.string "C'est {STR_VAR_1}. Comment tu vas?\n"
	.string "C'est pratique de pouvoir\p"
	.string "garder le contact comme\n"
	.string "ça! Avant, quand je\p"
	.string "voulais parler avec\n"
	.string "quelqu'un, je devais demander\l"
	.string "à mon père de me déposer en\p"
	.string "voiture… Bon, je te laisse.\n"
	.string "Contente d'avoir parlé avec toi!$"

MatchCall_PersonalizedText11::
	.string "C'est {STR_VAR_1}! J'ai quelque\n"
	.string "chose à te dire. J'aime\p"
	.string "beaucoup le PARC SAFARI,\n"
	.string "mais je m'y perds tout\p"
	.string "le temps! Les herbes sont\n"
	.string "trop hautes! En plus,\p"
	.string "c'est immense! J'avais\n"
	.string "besoin de confier ça à\p"
	.string "quelqu'un! Bon, je retourne\n"
	.string "au PARC SAFARI! À bientôt!$"

MatchCall_PersonalizedText12::
	.string "Bonjour, ici {STR_VAR_1}. Oui, je\n"
	.string "suis riche. C'est bien\p"
	.string "vrai. Je suis encore plus\n"
	.string "riche que la dernière fois.\p"
	.string "Sinon, mes POKéMON vont\n"
	.string "bien. Ils ont beaucoup\p"
	.string "progressé. J'ai l'impression\n"
	.string "que ce monde a été créé\p"
	.string "pour moi! Je sais ce que tu\n"
	.string "penses. Mais c'est vrai! Je\p"
	.string "te prie de m'excuser. Je\n"
	.string "dois me rendre à une réception.$"

MatchCall_PersonalizedText13::
	.string "C'est moi, {STR_VAR_1}… Devine\n"
	.string "ce que je vois…\p"
	.string "Deux {STR_VAR_2} en plein\n"
	.string "combat! Je vais\p"
	.string "essayer d'attraper le\n"
	.string "gagnant… Oui, tiens…\p"
	.string "Bon… Il faut que j'y\n"
	.string "aille. Je te laisse.$"

MatchCall_PersonalizedText14::
	.string "C'est {STR_VAR_1}! Tu sais, j'en ai\p"
	.string "un peu marre de l'EPAVE.\n"
	.string "Mais puisque j'y suis et\p"
	.string "que Je voudrais te battre\n"
	.string "une fois, je vais y\l"
	.string "rester encore un peu. Je\p"
	.string "ne veux pas te forcer,\n"
	.string "mais pourquoi tu ne viens\p"
	.string "pas? Je pense\n"
	.string "qu'aujourd'hui je vais défier\l"
	.string "l'homme d'à côté. J'ai envie\p"
	.string "d'un petit combat. À bientôt!$"

MatchCall_PersonalizedText15::
	.string "C'est {STR_VAR_1}! Le garçon amphibie!\n"
	.string "Tu sais ce que je crois? Que\p"
	.string "c'est en mer qu'on trouve\p"
	.string "les meilleurs DRESSEURS! Tu\n"
	.string "devrais prendre exemple sur\p"
	.string "moi et venir t'entraîner en\n"
	.string "mer… Waouh!!! Une vague\p"
	.string "géante arrive! Je vais la\p"
	.string "surfer! C'est génial de\n"
	.string "Désolé, mais je dois y aller!$"

MatchCall_PersonalizedText16::
	.string "C'est {STR_VAR_1}! J'ai donné des\n"
	.string "cours de karaté à mes\p"
	.string "POKéMON. Ils sont devenus\n"
	.string "meilleurs que moi! Ils\p"
	.string "apprennent vite! Mais\n"
	.string "grâce à eux, je ne perdrai\l"
	.string "plus un seul combat de\p"
	.string "POKéMON! Il faut qu'on en\n"
	.string "refasse un, au fait! Yah!!!$"

MatchCall_PersonalizedText17::
	.string "C'est moi, {STR_VAR_1}. Comment se\n"
	.string "déroule ton voyage?\p"
	.string "Waouh, vraiment? Ça a\n"
	.string "l'air super intéressant!\p"
	.string "Je pourrais bien en\n"
	.string "faire une chanson! … J'ai\p"
	.string "un début de mélodie en\n"
	.string "tête. Il faut que j'aille\p"
	.string "mettre tout ça par\n"
	.string "écrit, sinon je vais oublier!$"

MatchCall_PersonalizedText18::
	.string "C'est {STR_VAR_1}... Écoute\n"
	.string "ma nouvelle chanson.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2} !\n"
	.string "Pourquoi êtes-vous\l"
	.string "cette {STR_VAR_2} ? Pourquoi je\l"
	.string "ne peux pas être toi, {STR_VAR_2}\l"
	.string "? Lala, {STR_VAR_2} et {STR_VAR_1}, {STR_VAR_1} et {STR_VAR_2}...\p"
	.string "Répéter le refrain, s'estomper...$"

MatchCall_PersonalizedText19::
	.string "C'est moi {STR_VAR_1}, le pro du\n"
	.string "camping! La dernière\p"
	.string "fois, je n'ai pas réussi\n"
	.string "à te battre. On ne peut\p"
	.string "pas être bon en tout!\n"
	.string "Mais quand je fais du\p"
	.string "camping, j'aime bien\n"
	.string "faire des combats. Viens\p"
	.string "nous voir à l'occasion! Sur\n"
	.string "ce, je vais camper. Salut!$"

MatchCall_PersonalizedText20::
	.string "C'est moi, {STR_VAR_1}! Pour être\p"
	.string "honnête, Je voudrais bien\n"
	.string "aller randonner ailleurs. Mais\p"
	.string "il y a tellement de jolies\n"
	.string "filles sur le MONT CHIMNEE… Si\p"
	.string "tu connais des montagnes avec\n"
	.string "plein de jolies filles,\p"
	.string "dis-le-moi! Hé, hé, hé! À bientôt!$"

MatchCall_PersonalizedText21::
	.string "… … … … … … …\n"
	.string "… … … … …\l"
	.string "C'est {STR_VAR_1}… … … … …\p"
	.string "… … … … … … … …\n"
	.string "C'est tout\l"
	.string "pour aujourd'hui…$"

MatchCall_PersonalizedText22::
	.string "C'est {STR_VAR_1}. J'avais envie de\n"
	.string "te parler. De jour en\p"
	.string "jour, mon désir de te\n"
	.string "battre grandit. Mais tu\p"
	.string "dois avoir beaucoup de\n"
	.string "rivaux… J'espère avoir\p"
	.string "bientôt la chance d'être\n"
	.string "ton adversaire. À bientôt!$"

MatchCall_PersonalizedText23::
	.string "C'est {STR_VAR_1}. Tu sais,\p"
	.string "quand un bon DRESSEUR\n"
	.string "passe près de moi, je\l"
	.string "le sens. Où es-tu en\p"
	.string "ce moment, {PLAYER}{KUN}? Je crois\n"
	.string "avoir senti ta\p"
	.string "présence… J'espère te\n"
	.string "voir bientôt. À bientôt!$"

MatchCall_PersonalizedText24::
	.string "Bonjour, c'est {STR_VAR_1}. Tu as l'air\n"
	.string "d'aller bien, {PLAYER}{KUN}. J'ai beaucoup\p"
	.string "voyagé, je suis allé un peu\n"
	.string "partout… C'est cette région que\l"
	.string "je préfère. Je compte y rester\p"
	.string "encore un peu. J'espère qu'on se\n"
	.string "reverra avant que je parte. Je\p"
	.string "n'ai pas oublié tes techniques\n"
	.string "impressionnantes. J'espère qu'on\p"
	.string "J'espère une revanche.$"

MatchCall_PersonalizedText25::
	.string "Sniff… C'est… {STR_VAR_1}… Sniff…\n"
	.string "ROXANNE m'a grondé en\p"
	.string "classe aujourd'hui.\n"
	.string "Mais je l'aime bien\p"
	.string "quand même. Elle me\p"
	.string "permet de prendre\n"
	.string "conscience de mes\p"
	.string "erreurs. Bien sûr que je\n"
	.string "retourne à l'ECOLE DE\p"
	.string "DRESSEURS demain! À bientôt!$"

MatchCall_PersonalizedText26::
	.string "C'est {STR_VAR_1}! ROXANNE m'a\p"
	.string "permis de me battre\n"
	.string "contre elle hier. J'ai\p"
	.string "perdu… Faut pas poser ce\n"
	.string "genre de questions! Mais\p"
	.string "j'étais contente qu'elle me\n"
	.string "laisse me mesurer à elle.\p"
	.string "Je l'admire encore plus\n"
	.string "maintenant! Je vais\p"
	.string "travailler encore plus dur!\n"
	.string "D'ailleurs, il faut que j'y aille!$"

MatchCall_PersonalizedText27::
	.string "Bonjour, c'est ANNA! Je\n"
	.string "suis avec ma charmante\p"
	.string "partenaire, EVA. J'adore\n"
	.string "m'occuper d'EVA et de mes\p"
	.string "POKéMON. Ils sont mignons!\n"
	.string "C'est comme s'ils faisaient\p"
	.string "partie de ma famille!\n"
	.string "Salut, EVA! Tu as acheté le\p"
	.string "pain? Quoi? Mais non, je ne\n"
	.string "te traite pas comme une\p"
	.string "esclave, voyons! Tu as\n"
	.string "perdu, alors c'est à toi\p"
	.string "d'acheter le pain, c'est tout!\n"
	.string "Je t'aime trop! Je ne te\p"
	.string "traiterai jamais comme une\n"
	.string "C'est l'heure de notre collation!$"

MatchCall_PersonalizedText28::
	.string "J'adore les POKéMON! C'est {STR_VAR_1} du\n"
	.string "FAN CLUB! Un truc incroyable\p"
	.string "s'est passé! Mes petits\n"
	.string "POKéMON… Oups! Je ne peux pas\p"
	.string "en dire plus, c'est un secret!\n"
	.string "De toute façon, je ne\l"
	.string "trouverais pas les mots. Oh,\p"
	.string "mon petit {STR_VAR_2} me réclame un {POKEBLOCK}! Ce\n"
	.string "n'est pas beau de réclamer!!!\p"
	.string "Mais il est si mignon, celui-là…\p"
	.string "Désolé, le devoir m'appelle! Je\n"
	.string "t'en dirai plus la prochaine fois!$"

MatchCall_PersonalizedText29::
	.string "Oh, oh! C'est {STR_VAR_1}! J'ai\p"
	.string "plein de choses à te\n"
	.string "raconter! Tiens, écoute\p"
	.string "ça! C'est sur mon tout\n"
	.string "petit {STR_VAR_2} chéri. Dès que\p"
	.string "quelqu'un s'approche, il\n"
	.string "saute dans mes bras, le\p"
	.string "pauvre petit bébé! Oh… Si\n"
	.string "ce n'est pas ça le bonheur,\p"
	.string "je me demande ce que c'est…\p"
	.string "Je suis si heureuse! Il\n"
	.string "fallait absolument que je\p"
	.string "parle de ça à quelqu'un. Bon,\n"
	.string "je dois te laisser. À bientôt!$"

MatchCall_PersonalizedText30::
	.string "Je suis… {STR_VAR_1}. Les gens\n"
	.string "m'appellent l'EXPERT. Il y\p"
	.string "a une chose que je sais.\n"
	.string "Sans mes POKéMON, je ne\l"
	.string "serais rien. Sans eux,\p"
	.string "aucun DRESSEUR ne pourrait\n"
	.string "devenir un EXPERT. Oh! Des\p"
	.string "fois je dis des trucs\n"
	.string "profonds, dis donc! Sur ces\p"
	.string "Je te laisserai dans l'esprit!$"

MatchCall_PersonalizedText31::
	.string "C'est {STR_VAR_1}. Je suis contente\n"
	.string "de te parler! Je fais\p"
	.string "trempette dans les sources\n"
	.string "chaudes, le bonheur! J'ai\p"
	.string "combattu contre beaucoup de\n"
	.string "DRESSEURS mais tu restes\l"
	.string "le meilleur. Et je suis\p"
	.string "sûre que tu as encore\n"
	.string "progressé depuis la dernière fois!$"

MatchCall_PersonalizedText32::
	.string "Hé, salut! C'est {STR_VAR_1}! Quoi\n"
	.string "de neuf? C'est peut-être\p"
	.string "une impression, mais quand\n"
	.string "je gagne, je me sens\l"
	.string "mieux dans mes baskets.\p"
	.string "Non, vraiment! Comment\n"
	.string "expliquer… On dirait\l"
	.string "qu'elles sont plus larges…\l"
	.string "Et plus moelleuses, aussi.\p"
	.string "Pendant notre combat, {PLAYER}{KUN}, mes\n"
	.string "baskets étaient trop\p"
	.string "serrées! … … … … … … Quoi, tu\n"
	.string "m'as cru? Hé, hé, hé! Tu\l"
	.string "crois tout ce qu'on te dit, toi!$"

MatchCall_PersonalizedText33::
	.string "Salut, toi! C'est {STR_VAR_1}! Comme\n"
	.string "d'habitude, je m'adonne\p"
	.string "aux plaisirs de la pêche!\n"
	.string "C'est dommage qu'on ne\p"
	.string "puisse pêcher que dans la\n"
	.string "mer et la rivière. Oui,\p"
	.string "dans les lacs aussi. Mais Je\n"
	.string "voudrais pouvoir pêcher\p"
	.string "partout! Oh, je dois te\n"
	.string "laisser! Ha, ha, ha! Ça mord\p"
	.string "sur une autre ligne! Je veux\n"
	.string "dire, j'ai une prise! À bientôt!$"

MatchCall_PersonalizedText34::
	.string "Bonjour, c'est {STR_VAR_1}. Tout\n"
	.string "baigne? Tu sais, quand\p"
	.string "j'étais petit, j'étais\n"
	.string "plutôt du genre\p"
	.string "tranquille. J'aimais\n"
	.string "prendre mon temps, je\p"
	.string "fuyais le stress. Eh bien\n"
	.string "maintenant, je suis un\p"
	.string "TRIATHLETE. Tu ne sais\n"
	.string "jamais ce que la vie te\p"
	.string "réserve. Aujourd'hui, tu\n"
	.string "es un DRESSEUR. Mais que\p"
	.string "seras-tu demain? Tu\n"
	.string "pourrais très bien avoir\p"
	.string "envie d'enseigner? Ou de\n"
	.string "peindre? Penses-y! Bon, à plus.$"

MatchCall_PersonalizedText35::
	.string "C'est {STR_VAR_1}! Je suis à vélo.\n"
	.string "J'adore nager et\p"
	.string "courir, mais le vélo,\n"
	.string "c'est mon dada! A vélo,\p"
	.string "je ne fais qu'un avec le\n"
	.string "vent. Je me sens\p"
	.string "euphorique! C'est comme\n"
	.string "si je volais! Je veux\p"
	.string "réaliser un nouveau record\n"
	.string "sur la PISTE CYCLABLE,\p"
	.string "aujourd'hui! Toi aussi, tu\n"
	.string "devrais essayer! À bientôt!$"

MatchCall_PersonalizedText36::
	.string "Salut, c'est {STR_VAR_1}! Je suis en\n"
	.string "plein triathlon! Mais\p"
	.string "c'est pas ça qui m'empêche\n"
	.string "d'appeler les amis! Tu\p"
	.string "sais, j'adore m'entraîner\n"
	.string "avec les POKéMON! On se\p"
	.string "comprend sans dire un seul\n"
	.string "mot. C'est simple, on ne\p"
	.string "fait qu'un! Ça me transporte\p"
	.string "de joie! Mince… Il faut que\n"
	.string "je raccroche… C'est… pas\l"
	.string "facile… Je m'essouffle… À bientôt…$"

MatchCall_PersonalizedText37::
	.string "Salut, {STR_VAR_1}. Si tu veux\n"
	.string "améliorer ton endurance,\l"
	.string "entraîne-toi en altitude!\p"
	.string "Essaie de gravir une montagne\n"
	.string "en courant. Tu vas vite\p"
	.string "t'essouffler! Justement, je\n"
	.string "A tout à l'heure!$"

MatchCall_PersonalizedText38::
	.string "C'est {STR_VAR_1}. Bonjour! Je\p"
	.string "n'arrête pas de nager,\n"
	.string "mais je ne trouve pas\p"
	.string "ETERNARA. J'ai\p"
	.string "l'impression de tourner\n"
	.string "en rond. Non, non, c'est\l"
	.string "impossible… Bon, à bientôt!$"

MatchCall_PersonalizedText39::
	.string "Salut, {STR_VAR_1}… Blop!\n"
	.string "Bloup, bloup,\p"
	.string "bloup… Blop!\p"
	.string "Désolé, j'ai mis de\p"
	.string "la crème solaire.\p"
	.string "Mon POKéNAV m'a\p"
	.string "glissé des mains et\n"
	.string "il est tombé dans\p"
	.string "l'eau! Le POKéNAV de\n"
	.string "DEVON est solide! En\p"
	.string "tout cas, il est\n"
	.string "étanche! Bon, je vais\p"
	.string "faire bronzette!\n"
	.string "Désolé, je dois te laisser.$"

MatchCall_PersonalizedText40::
	.string "Bonjour, c'est {STR_VAR_1}. Mon épreuve de\p"
	.string "triathlon préférée, c'est la\n"
	.string "nage. Mais j'ai peur d'un truc.\p"
	.string "Je ne risque pas de ressembler à\n"
	.string "un pruneau à force d'être dans\p"
	.string "l'eau? J'aime le triathlon!\n"
	.string "Test d'endurance humaine!$"

MatchCall_PersonalizedText41::
	.string "Salut, {PLAYER}{KUN}. {STR_VAR_1} à\n"
	.string "l'appareil. Comment\p"
	.string "vont tes POKéMON? Mes\p"
	.string "POKéMON DRAGON pètent\n"
	.string "le feu! A la prochaine!$"

MatchCall_PersonalizedText42::
	.string "C'est {STR_VAR_1}. Mon {STR_VAR_2} a\p"
	.string "beaucoup changé\n"
	.string "depuis la dernière\p"
	.string "fois. Tu ne pourras plus\n"
	.string "me battre. Vivement\p"
	.string "qu'on se revoie! À bientôt!$"

MatchCall_PersonalizedText43::
	.string "C'est {STR_VAR_1} à l'appareil. J'ai\p"
	.string "continué mes recherches sur\n"
	.string "l'art de la dissimulation.\p"
	.string "J'ai fait tellement de\n"
	.string "progrès que plus personne\l"
	.string "ne me voit! Je me sens\p"
	.string "terriblement seul… Comme la\n"
	.string "fumée, je me dissipe! À bientôt!$"

MatchCall_PersonalizedText44::
	.string "C'est {STR_VAR_1}. Je n'ai pas arrêté\n"
	.string "de m'entraîner depuis la\p"
	.string "dernière fois. Mon {STR_VAR_2} est\n"
	.string "devenu super fort. Je\p"
	.string "m'entraîne sur la plage. Je\n"
	.string "Tout comme je le pensais.$"

MatchCall_PersonalizedText45::
	.string "Comment ça va? C'est {STR_VAR_1}.\n"
	.string "Ces cendres volcaniques\p"
	.string "n'en finissent pas de\n"
	.string "tomber! Si ça continue,\p"
	.string "on ne verra plus les\n"
	.string "motifs de mon parasol…\p"
	.string "J'espère te voir bientôt!$"

MatchCall_PersonalizedText46::
	.string "Bonjour, c'est {STR_VAR_1}. Tu sais que\p"
	.string "c'est plus facile de faire\n"
	.string "la planche dans la mer que\p"
	.string "dans la piscine? On y\n"
	.string "flotte beaucoup mieux. Mais\p"
	.string "quand tu fais la planche,\n"
	.string "fais attention de ne pas te\l"
	.string "laisser emporter au large.\p"
	.string "Mais au fait, où je suis là???\n"
	.string "Heu… Il faut que je te laisse!$"

MatchCall_PersonalizedText47::
	.string "Bonjour {PLAYER}{KUN}! C'est {STR_VAR_1}. Je\n"
	.string "suis en montagne.\l"
	.string "Mais le sol est plein\p"
	.string "de bosses. Je ne peux\n"
	.string "pas planter ma\p"
	.string "tente… Oh, j'ai une\p"
	.string "super idée! Je vais\n"
	.string "demander à mes POKéMON\p"
	.string "de damer le sol! Je\n"
	.string "vais essayer! À bientôt!$"

MatchCall_PersonalizedText48::
	.string "Bonjour, c'est {STR_VAR_1}! J'élève des\p"
	.string "POKéMON avec AWA! On prend\n"
	.string "ça très au sérieux! Si on y\p"
	.string "met encore plus d'énergie,\n"
	.string "on deviendra les meilleures!$"

MatchCall_PersonalizedText49::
	.string "Ici {STR_VAR_1}! Je suis un MARIN,\p"
	.string "même si je ne suis pas en\n"
	.string "mer en ce moment… Un MARIN\p"
	.string "à terre, c'est comme un\n"
	.string "poisson sans eau! Dès que\p"
	.string "je rejoins la terre ferme,\n"
	.string "je deviens un peu\p"
	.string "nostalgique. Bon, à la prochaine!$"

MatchCall_PersonalizedText50::
	.string "C'est {STR_VAR_1}. Tu as de\n"
	.string "nouveaux POKéMON? Si tu\p"
	.string "en attrapes un nouveau,\n"
	.string "viens me le montrer! Je\p"
	.string "promets de ne pas être\n"
	.string "jaloux. A bientôt, j'espère!$"

MatchCall_PersonalizedText51::
	.string "C'est {STR_VAR_1}. Elèves-tu\p"
	.string "tes POKéMON\n"
	.string "correctement? Là où\p"
	.string "je me trouve, l'air\n"
	.string "est pur. C'est ce\l"
	.string "qu'il y a de mieux pour\p"
	.string "les POKéMON. Si tu veux\n"
	.string "les élever de façon\l"
	.string "optimale, viens sur la {STR_VAR_2}!$"

MatchCall_PersonalizedText52::
	.string "Bonjour, c'est {STR_VAR_1}. J'ai\p"
	.string "donné un {POKEBLOCK} à mon {STR_VAR_2}. Il\n"
	.string "a beaucoup aimé. Les\p"
	.string "POKéMON ont tous leurs\n"
	.string "préférences en\p"
	.string "matière de {POKEBLOCK}S. Je trouve\n"
	.string "ça fascinant. À bientôt.$"

MatchCall_PersonalizedText53::
	.string "C'est {STR_VAR_1}. Grâce aux POKéMON,\p"
	.string "tu peux survivre en pleine\n"
	.string "nature. Je crois que les\p"
	.string "gens devraient coopérer plus\n"
	.string "avec les POKéMON. On a tout\p"
	.string "à y gagner. Les POKéMON,\n"
	.string "c'est l'avenir. Mais tu ne\p"
	.string "fais pas partie des gens à\n"
	.string "convaincre. Tu penses POKéMON!$"

MatchCall_PersonalizedText54::
	.string "Salut, c'est {STR_VAR_1}. Je suis\n"
	.string "toujours prête! Et toi? {PLAYER}{KUN},\p"
	.string "as-tu assez d'objets? Tes\n"
	.string "POKéMON sont-ils en forme?\p"
	.string "Pour éviter les mauvaises\n"
	.string "surprises, il faut être toujours\l"
	.string "prêt! C'est le secret! Je vais\p"
	.string "vérifier mes provisions! La\n"
	.string "Soyez vigilants!$"

MatchCall_PersonalizedText55::
	.string "C'est {STR_VAR_1}! Oui, {STR_VAR_1}! Il y a\n"
	.string "beaucoup de passage sur\p"
	.string "{STR_VAR_2}. Je me bats contre un\n"
	.string "tas de DRESSEURS.\l"
	.string "Aujourd'hui, j'ai gagné\p"
	.string "cinq combats et n'en ai\n"
	.string "perdu que trois! Tu as passé\p"
	.string "une bonne journée? Bon, tu\n"
	.string "me raconteras ça plus tard!$"

MatchCall_PersonalizedText56::
	.string "C'est moi, {STR_VAR_1}. Mes\p"
	.string "POKéMON INSECTE sont\n"
	.string "franchement cool, non?\p"
	.string "Je les ai ramenés à\n"
	.string "l'école pour les\p"
	.string "montrer à une fille. Eh\n"
	.string "ben, elle s'est mise à\p"
	.string "hurler! Trop bête, la\n"
	.string "fille! Moi, je pensais\p"
	.string "qu'elle les aimerait… C'est\n"
	.string "dommage. Sniff… À bientôt!$"

MatchCall_PersonalizedText57::
	.string "Ouf… Bonjour!\p"
	.string "C'est {STR_VAR_1}! Parler…\p"
	.string "tout en\n"
	.string "escaladant… ce\l"
	.string "n'est pas\p"
	.string "facile… Ha! Ha!\n"
	.string "Arg! Ouf… Ça\l"
	.string "grimpe! On parlera…\l"
	.string "une autre fois… Ouf…$"

MatchCall_PersonalizedText58::
	.string "Oh, salut! Je cherche des\p"
	.string "trésors avec RITA! On\n"
	.string "n'est pas sûrs de trouver\p"
	.string "quoi que ce soit, tu\n"
	.string "sais… Le plus important\p"
	.string "pour moi, c'est d'être\n"
	.string "avec RITA. Quoi encore,\p"
	.string "RITA!?! Pourquoi tu fais\n"
	.string "cette tête-là? Mais non,\p"
	.string "je ne t'ignore pas, ma\n"
	.string "puce! Il n'y a que toi dans\p"
	.string "ma vie! Je dois raccrocher, {PLAYER}…$"

MatchCall_PersonalizedText59::
	.string "C'est {STR_VAR_1}! Je suis retourné\p"
	.string "à l'ARÈNE de MYOKARA pour\n"
	.string "m'entraîner. BASTIEN, le\p"
	.string "CHAMPION D'ARÈNE, est\n"
	.string "devenu bien meilleur. Il\p"
	.string "a parlé des vagues\n"
	.string "sauvages… Ou un truc dans\p"
	.string "le genre. Mais il est\n"
	.string "toujours aussi cool. Et il\l"
	.string "plaît toujours autant aux\p"
	.string "filles! Il en a de la\n"
	.string "chance. Tiens… Je me\p"
	.string "demande si son ami ALDO est\n"
	.string "comme lui. C'est sûrement\l"
	.string "aussi le genre à faire\p"
	.string "craquer les filles… Bon, il\n"
	.string "faut que j'arrête. La jalousie\p"
	.string "est un vilain défaut! Bon,\n"
	.string "oublie ce que je viens de dire!$"

MatchCall_PersonalizedText60::
	.string "C'est un plaisir de\n"
	.string "discuter avec un jeune\p"
	.string "DRESSEUR comme toi. Ta\n"
	.string "passion pour les POKéMON\p"
	.string "va durer, c'est évident.\n"
	.string "Tu pourrais peut-être\p"
	.string "devenir notre partenaire?\n"
	.string "Bien sûr, {PLAYER}{KUN}. La compagnie\l"
	.string "de tes fidèles POKéMON\p"
	.string "te suffit amplement. Tu\n"
	.string "sais comment faire durer\p"
	.string "une relation. Ha, ha,\n"
	.string "ha! Ne te décourage jamais!$"

MatchCall_PersonalizedText61::
	.string "Bonjour, c'est {STR_VAR_1}! Nous\n"
	.string "venons de gagner un combat!\p"
	.string "Nous ne gagnons pas souvent,\n"
	.string "mais c'était contre un\p"
	.string "NAGEUR facile. Ma sœur était\p"
	.string "hors d'elle! Elle voulait\n"
	.string "jouer à la fille faible et\p"
	.string "sans défense pour le séduire!\n"
	.string "Qu'on gagne ou qu'on perde,\p"
	.string "elle n'est jamais contente! {PLAYER}{KUN},\n"
	.string "tu ne pourrais pas essayer\p"
	.string "de lui parler? Bon, À bientôt!$"

MatchCall_PersonalizedText62::
	.string "Bonjour, c'est {STR_VAR_1}. Je suis\n"
	.string "parti en mer hier. Je\p"
	.string "pensais y trouver\n"
	.string "quelque épave à\p"
	.string "explorer. Mais la marée\n"
	.string "m'a ramené chez moi sur\p"
	.string "la terre ferme. Je suis\n"
	.string "toujours mauvais au\l"
	.string "combat… Mais je persévère!\p"
	.string "Je serai sûrement meilleur\n"
	.string "quand j'aurai trouvé des\p"
	.string "ruines! C'est tout ce que je\n"
	.string "voulais te dire! À bientôt!$"

MatchCall_PersonalizedText63::
	.string "Ohé, du bateau! C'est moi,\n"
	.string "{STR_VAR_1}! Je suis sur le CHENAL\l"
	.string "108 en ce moment! Enfin,\l"
	.string "comme d'habitude!\p"
	.string "Aujourd'hui, j'ai vu une\n"
	.string "NAGEUSE de rêve! J'ai crié\p"
	.string "pour attirer son attention,\p"
	.string "tu me connais! Elle m'a\p"
	.string "fusillé du regard! C'était les\n"
	.string "nouvelles du CHENAL 108 par {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "C'est {STR_VAR_1}! Je suis très\p"
	.string "occupée, mais je voulais te\n"
	.string "dire que j'avais battu cinq\l"
	.string "DRESSEURS aujourd'hui. Si je\p"
	.string "continue comme ça, je te\n"
	.string "battrai sûrement la prochaine\p"
	.string "fois. Je crois que toi et\n"
	.string "moi sommes de bons adversaires!$"

MatchCall_BattleFrontierStreakText1::
	.string "C'est {STR_VAR_1}. J'ai\n"
	.string "entendu les nouvelles !\p"
	.string "Ils disent que tu as\n"
	.string "été excellent à l'{STR_VAR_2}.\p"
	.string "C'est génial, {STR_VAR_3} gagne tout\n"
	.string "droit ? A tout à l'heure !$"

MatchCall_BattleFrontierStreakText2::
	.string "Bonjour, c'est {STR_VAR_1}. Je\n"
	.string "suis au courant! {STR_VAR_3}\p"
	.string "victoires consécutives!\n"
	.string "Mais où? {STR_VAR_2}! Excellent. Il\p"
	.string "faut que je prenne\n"
	.string "exemple sur toi. À bientôt!$"

MatchCall_BattleFrontierStreakText3::
	.string "Salut, {PLAYER}! C'est moi,\n"
	.string "{STR_VAR_1}. J'ai eu vent de\p"
	.string "tes exploits! Mais\n"
	.string "où? {STR_VAR_2}? Joli! {STR_VAR_3}\p"
	.string "victoires\n"
	.string "consécutives… Quel record!\p"
	.string "Je ferais bien de prendre\n"
	.string "exemple sur toi! À bientôt!$"

MatchCall_BattleFrontierStreakText4::
	.string "Allô, {PLAYER}{KUN}? Ici {STR_VAR_1}.\n"
	.string "Bonjour! Il paraît que\p"
	.string "tu as obtenu {STR_VAR_3}\n"
	.string "victoires consécutives.\l"
	.string "Mais où? {STR_VAR_2}? Bon, il faut\p"
	.string "que je me remette\n"
	.string "sérieusement à l'entraînement!$"

MatchCall_BattleFrontierStreakText5::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C'est{STR_VAR_1} .\p"
	.string "Tu étais à l'.\n{STR_VAR_2}"
	.string "et a gagné{STR_VAR_3} des batailles\l"
	.string "d'affilée ? C'est pas cela !\p"
	.string "Je ferais mieux de travailler\n"
	.string "sur mon POKéMON plus. A bientôt !$"

MatchCall_BattleFrontierStreakText6::
	.string "Bonjour, {PLAYER}{KUN}. {STR_VAR_1},\n"
	.string "comment allez-vous ?\p{STR_VAR_3}"
	.string "Au fait, j'ai entendu dire\n"
	.string "que tu t'étais tiré.\l"
	.string "le {STR_VAR_2}.\p"
	.string "Ça m'inspire de me\n"
	.string "concentrer sur élever mon équipe.$"

MatchCall_BattleFrontierStreakText7::
	.string "Heu… {PLAYER}{KUN}? Ici {STR_VAR_1}… Tu as\n"
	.string "combattu dans la ZONE\p"
	.string "DE COMBAT, non? {STR_VAR_2}? C'est\n"
	.string "vrai que tu as gagné {STR_VAR_3}\p"
	.string "combats à la suite? Je\p"
	.string "viens d'apercevoir un\n"
	.string "POKéMON rare! Je te laisse!$"

MatchCall_BattleFrontierStreakText8::
	.string "Ça va, {PLAYER}{KUN}? C'est {STR_VAR_1}. Ça a\n"
	.string "l'air d'aller pour\l"
	.string "toi. Tu as gagné {STR_VAR_3}\p"
	.string "combats à la suite\n"
	.string "dans la ZONE DE COMBAT.\l"
	.string "{STR_VAR_2}, n'est-ce pas? C'est\p"
	.string "très impressionnant!\n"
	.string "Continue sur cette voie.$"

MatchCall_BattleFrontierStreakText9::
	.string "Salut, {PLAYER}{KUN}! C'est {STR_VAR_1}! On m'a\n"
	.string "parlé de tes {STR_VAR_3} victoires\p"
	.string "à la suite dans la ZONE\n"
	.string "DE COMBAT! {STR_VAR_2}, c'est ça?\p"
	.string "C'est formidable! Bon, je\n"
	.string "ferais bien de t'imiter!$"

MatchCall_BattleFrontierStreakText10::
	.string "Coucou, {PLAYER}{KUN}… C'est moi, {STR_VAR_1}.\n"
	.string "C'est vrai que tu as gagné {STR_VAR_3}\p"
	.string "combats à la suite dans la\n"
	.string "ZONE DE COMBAT? {STR_VAR_2}!?! Je\p"
	.string "vais essayer de suivre ton\n"
	.string "exemple. Je dois m'améliorer.$"

MatchCall_BattleFrontierStreakText11::
	.string "{PLAYER}{KUN}? Bonjour, c'est {STR_VAR_1}.\n"
	.string "On va devoir\p"
	.string "t'appeler sa Majesté\n"
	.string "{STR_VAR_2} bientôt, non? Tu as\p"
	.string "gagné {STR_VAR_3} combats à la\n"
	.string "suite! C'est\p"
	.string "vraiment bien! Je\n"
	.string "devrais essayer, moi aussi!$"

MatchCall_BattleFrontierStreakText12::
	.string "Bonjour, {PLAYER}{KUN}. C'est\n"
	.string "{STR_VAR_1}. Ça va? Tu as\l"
	.string "gagné {STR_VAR_3} combats à\p"
	.string "la suite dans un\n"
	.string "endroit appelé {STR_VAR_2},\l"
	.string "il paraît. C'est\p"
	.string "assez\n"
	.string "impressionnant. À bientôt!$"

MatchCall_BattleFrontierStreakText13::
	.string "Bonjour, {PLAYER}{KUN}! C'est {STR_VAR_1} qui\n"
	.string "appelle! J'espère que\l"
	.string "tout va bien. Il paraît\p"
	.string "que tu as gagné {STR_VAR_3} combats à\n"
	.string "la suite dans un endroit\p"
	.string "du nom de {STR_VAR_2}. Quelle\n"
	.string "énergie! Je t'admire. A bientôt.$"

MatchCall_BattleFrontierStreakText14::
	.string "Bonjour, {PLAYER}{KUN}. C'est {STR_VAR_1}.\n"
	.string "On m'a parlé de toi!\p"
	.string "Tu as gagné {STR_VAR_3}\n"
	.string "combats à la suite\l"
	.string "dans la ZONE DE\p"
	.string "COMBAT! {STR_VAR_2}!?! Tu es un\n"
	.string "modèle pour moi! À bientôt!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Bonjour, c'est {STR_VAR_1}. Je suis\n"
	.string "au courant! Tu as fait des\p"
	.string "tiennes dans la ZONE DE\n"
	.string "COMBAT! {STR_VAR_2}? Magnifique! {STR_VAR_3}\p"
	.string "victoires consécutives,\n"
	.string "A tout à l'heure!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Bonjour, c'est {STR_VAR_1}! J'ai\n"
	.string "entendu parler de toi! Dans\p"
	.string "quel bâtiment de la ZONE DE\n"
	.string "COMBAT as-tu gagné {STR_VAR_3} combats à\p"
	.string "la suite? {STR_VAR_2}! C'est très fort,\n"
	.string "ça! Je devrais prendre exemple!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Salut, {PLAYER}! C'est moi, {STR_VAR_1}.\n"
	.string "Tu as fait des ravages\p"
	.string "dans la ZONE DE COMBAT?\n"
	.string "{STR_VAR_2}? Je ne savais pas. Mais\p"
	.string "je sais que tu as\n"
	.string "obtenu {STR_VAR_3} victoires\p"
	.string "consécutives… Bon, il faut\n"
	.string "que je me reprenne! À bientôt!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Allô, {PLAYER}{KUN}? Ici {STR_VAR_1}.\n"
	.string "Bonjour, ça va? Tu as\p"
	.string "obtenu {STR_VAR_3} victoires\n"
	.string "consécutives dans la\l"
	.string "ZONE DE COMBAT, non? {STR_VAR_2}?\p"
	.string "Je vais de ce pas\n"
	.string "m'entraîner, tiens… À bientôt!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C'est{STR_VAR_1} .\p"
	.string "Tu étais à l'.\n{STR_VAR_2}"
	.string "et a gagné{STR_VAR_3} des batailles\l"
	.string "d'affilée ? C'est pas cela !\p"
	.string "Je dirais que je viens\n"
	.string "avec vous. A bientôt !$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Salut, {PLAYER}{KUN}. Ici {STR_VAR_1}.\n"
	.string "Comment ça va? Il\p"
	.string "paraît que tu as obtenu\n"
	.string "{STR_VAR_3} victoires à la suite\l"
	.string "dans ce bâtiment… {STR_VAR_2}. Je\p"
	.string "ne peux pas en dire\n"
	.string "autant de moi. À bientôt!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "Heu… {PLAYER}{KUN}? Ici {STR_VAR_1}… C'est vrai\n"
	.string "que tu as relevé le\p"
	.string "défi de ce bâtiment,\n"
	.string "là… {STR_VAR_2}? Et que tu as\p"
	.string "gagné {STR_VAR_3} combats à la\p"
	.string "suite? Je viens de voir un\n"
	.string "POKéMON rare! Je te laisse!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Ça va, {PLAYER}{KUN}? C'est {STR_VAR_1}. Ça\n"
	.string "a l'air d'aller pour\l"
	.string "toi. Tu as gagné {STR_VAR_3}\p"
	.string "combats à la suite\n"
	.string "dans la ZONE DE\l"
	.string "COMBAT. Mais où? {STR_VAR_2}!\p"
	.string "C'est très impressionnant!\n"
	.string "Continue sur cette voie.$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Salut, {PLAYER}{KUN}! C'est {STR_VAR_1}! J'ai\n"
	.string "appris que tu avais\p"
	.string "obtenu {STR_VAR_3} victoires\n"
	.string "consécutives au bâtiment {STR_VAR_2}!\p"
	.string "C'est formidable! Bon, je\n"
	.string "ferais bien de t'imiter!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Coucou, {PLAYER}{KUN}… C'est moi, {STR_VAR_1}.\n"
	.string "Dans quel bâtiment de la\p"
	.string "ZONE DE COMBAT as-tu gagné {STR_VAR_3}\n"
	.string "combats à la suite? {STR_VAR_2}? Je\p"
	.string "vais essayer de suivre ton\n"
	.string "exemple. Je dois m'améliorer.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "{PLAYER}{KUN}? Bonjour, c'est {STR_VAR_1}.\n"
	.string "On va devoir\p"
	.string "t'appeler sa Majesté {STR_VAR_2}\n"
	.string "bientôt, non? Tu as\p"
	.string "gagné {STR_VAR_3} combats à la\n"
	.string "suite, non? C'est\p"
	.string "vraiment bien! Je\n"
	.string "devrais essayer, moi aussi!$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Bonjour, {PLAYER}{KUN}. C'est\n"
	.string "{STR_VAR_1}. Ça va? Dis,\l"
	.string "as-tu gagné {STR_VAR_3}\p"
	.string "combats à la suite\n"
	.string "dans un endroit\l"
	.string "appelé {STR_VAR_2}? C'était\p"
	.string "toi! C'est assez\n"
	.string "impressionnant. À bientôt!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Bonjour, {PLAYER}{KUN}! C'est {STR_VAR_1} qui\n"
	.string "appelle! J'espère que\l"
	.string "tout va bien. Aurais-tu\p"
	.string "par hasard gagné {STR_VAR_3} combats\n"
	.string "à la suite dans un endroit\p"
	.string "du nom de {STR_VAR_2}? Quelle\n"
	.string "énergie! Je t'admire. A bientôt.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Bonjour, {PLAYER}{KUN}. C'est {STR_VAR_1}. J'ai\n"
	.string "entendu parler de toi!\l"
	.string "Tu viens de gagner {STR_VAR_3}\p"
	.string "combats à la suite dans\n"
	.string "un endroit appelé {STR_VAR_2},\p"
	.string "n'est-ce pas? Tu es un\n"
	.string "modèle pour moi! À bientôt!$"

MatchCall_BattleDomeText1::
	.string "Bonjour, {PLAYER} ?\n"
	.string "Bonjour, voici {STR_VAR_1} ! J'ai\l"
	.string "entendu les nouvelles !\p"
	.string "Vous êtes devenu le\n"
	.string "champion de L'époque de l'{STR_VAR_2} {STR_VAR_3} ?\p"
	.string "Je dois faire mieux\n"
	.string "! A tout à l'heure !$"

MatchCall_BattleDomeText2::
	.string "Bonjour, c'est {STR_VAR_1}! Je suis\n"
	.string "au courant! Tu as\p"
	.string "remporté {STR_VAR_3} fois le titre du\n"
	.string "bâtiment {STR_VAR_2}! C'est super! Je\p"
	.string "voudrais bien remporter ce\n"
	.string "titre au moins une fois!$"

MatchCall_BattleDomeText3::
	.string "Salut, {PLAYER}! C'est\n"
	.string "moi, {STR_VAR_1}. Comment ça\l"
	.string "va? Il paraît que\p"
	.string "tu as remporté {STR_VAR_3}\n"
	.string "fois le titre du\p"
	.string "bâtiment {STR_VAR_2}! Ne\n"
	.string "t'arrête pas là! À bientôt!$"

MatchCall_BattleDomeText4::
	.string "Allô, {PLAYER}{KUN}? Ici {STR_VAR_1}. Bonjour!\n"
	.string "J'ai entendu dire que tu\p"
	.string "as remporté le titre du\n"
	.string "bâtiment {STR_VAR_2} {STR_VAR_3} fois. Je vois\p"
	.string "que tes efforts portent\n"
	.string "leurs fruits! Je dois persévérer!$"

MatchCall_BattleDomeText5::
	.string "Salut, {PLAYER}{KUN}! {STR_VAR_1} à l'appareil.\n"
	.string "On m'a dit que tu avais\p"
	.string "remporté {STR_VAR_3} fois haut la\n"
	.string "main le titre du\p"
	.string "bâtiment {STR_VAR_2}. Moi aussi, je\n"
	.string "devrais m'y mettre! A bientôt!$"

MatchCall_BattleDomeText6::
	.string "Hé, {PLAYER}{KUN} ? {STR_VAR_1},\n"
	.string "comment allez-vous ?\p"
	.string "Au fait, j'ai entendu\n"
	.string "dire que tu étais devenu\l"
	.string "le champion {STR_VAR_3} temps à l'{STR_VAR_2}.\p"
	.string "Je ferais mieux d'élever mon\n"
	.string "vous tirez plus loin.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}? Ici {STR_VAR_1}. Tu as obtenu\n"
	.string "le titre du bâtiment\p"
	.string "{STR_VAR_2} {STR_VAR_3} fois, n'est-ce\n"
	.string "pas? Pas mal du\p"
	.string "tout. Au fait, as-tu\n"
	.string "attrapé des POKéMON\p"
	.string "rares aujourd'hui?\n"
	.string "Vraiment? Bien, À bientôt.$"

MatchCall_BattleDomeText8::
	.string "Oh, {PLAYER}{KUN}, comment allez-vous\n"
	.string "? C'est {STR_VAR_1} qui parle.\l"
	.string "J'espère que vous allez\l"
	.string "bien. Oh, mais vous l'êtes.\p"
	.string "J'ai entendu dire que vous\n"
	.string "avez gagné les titres d'{STR_VAR_3}. à l'{STR_VAR_2}.\p"
	.string "Je dois élever mon\n"
	.string "POKéMON comme vous. A bientôt.$"

MatchCall_BattleDomeText9::
	.string "Oh, {PLAYER}{KUN},\n"
	.string "bonjour ! C'est {STR_VAR_1} !\p"
	.string "Vous avez pris le\n"
	.string "titre. {STR_VAR_3} à l'époque du {STR_VAR_2} !\p"
	.string "C'est trop cool ! Je ferais\n"
	.string "mieux d'essayer plus fort aussi !$"

MatchCall_BattleDomeText10::
	.string "Oh, {PLAYER}{KUN},\n"
	.string "bonjour. C'est {STR_VAR_1}.\p"
	.string "Tu as gagné des\n"
	.string "temps francs à {STR_VAR_3}. l'{STR_VAR_2} ?\p"
	.string "C'est tout ce qu'il y a à\n"
	.string "Je dois travailler plus dur.$"

MatchCall_BattleDomeText11::
	.string "{PLAYER}{KUN}? Bonjour, c'est {STR_VAR_1}.\n"
	.string "On va devoir\p"
	.string "t'appeler sa Majesté\n"
	.string "{STR_VAR_2} bientôt, non? Tu en\p"
	.string "as remporté le titre\n"
	.string "{STR_VAR_3} fois, non? Je me\p"
	.string "demande si je\n"
	.string "remporterai un titre\p"
	.string "un jour… Mais ça\n"
	.string "m'étonnerait… Bon, À bientôt!$"

MatchCall_BattleDomeText12::
	.string "Bonjour, {PLAYER}{KUN}. C'est\n"
	.string "{STR_VAR_1}. Ça va? Tu as\l"
	.string "gagné {STR_VAR_3} fois le\p"
	.string "titre d'un\n"
	.string "endroit appelé {STR_VAR_2}?\p"
	.string "C'est assez\n"
	.string "impressionnant. À bientôt!$"

MatchCall_BattleDomeText13::
	.string "Bonjour, {PLAYER}{KUN}! C'est {STR_VAR_1} qui\n"
	.string "appelle! J'espère que\l"
	.string "tout va bien. Il\p"
	.string "paraît que tu as obtenu\n"
	.string "{STR_VAR_3} fois le titre du\p"
	.string "bâtiment {STR_VAR_2}? Quelle\n"
	.string "énergie! Je t'admire. A bientôt.$"

MatchCall_BattleDomeText14::
	.string "{PLAYER}{KUN}? Bonjour, c'est {STR_VAR_1}.\n"
	.string "J'ai entendu\l"
	.string "parler de toi! Tu\p"
	.string "as remporté {STR_VAR_3} fois\n"
	.string "le titre du bâtiment\p"
	.string "{STR_VAR_2}! Tu es un modèle\n"
	.string "pour moi! À bientôt!$"

MatchCall_BattlePikeText1::
	.string "Bonjour, {PLAYER}!\n"
	.string "C'est {STR_VAR_1}! Je\l"
	.string "suis au\p"
	.string "courant! Tu as\n"
	.string "traversé {STR_VAR_3} salles\p"
	.string "du {STR_VAR_2}! C'est\n"
	.string "superbe! À bientôt!$"

MatchCall_BattlePikeText2::
	.string "Bonjour, c'est {STR_VAR_1}! J'ai\n"
	.string "entendu parler de toi!\p"
	.string "Il paraît que tu as\n"
	.string "traversé {STR_VAR_3} salles du {STR_VAR_2}.\p"
	.string "Moi, il faut que je\n"
	.string "redouble d'efforts! À bientôt!$"

MatchCall_BattlePikeText3::
	.string "Salut, {PLAYER}! C'est moi,\n"
	.string "{STR_VAR_1}. Comment ça va? Il\l"
	.string "paraît que tu as\p"
	.string "traversé {STR_VAR_3} salles du\n"
	.string "{STR_VAR_2}! Essaie de faire\p"
	.string "encore mieux la\n"
	.string "prochaine fois! À bientôt!$"

MatchCall_BattlePikeText4::
	.string "Allô, {PLAYER}{KUN}? Ici {STR_VAR_1}.\n"
	.string "Bonjour! Alors comme\p"
	.string "ça, tu as traversé {STR_VAR_3}\n"
	.string "salles du {STR_VAR_2}? Je ferais\p"
	.string "bien de m'occuper un\n"
	.string "peu mieux de mes POKéMON!$"

MatchCall_BattlePikeText5::
	.string "Salut, {PLAYER}{KUN}! {STR_VAR_1} à\n"
	.string "l'appareil. Il\p"
	.string "paraît que tu as\n"
	.string "traversé {STR_VAR_3} salles du {STR_VAR_2}!\p"
	.string "Moi aussi, je devrais\n"
	.string "m'y mettre! A bientôt!$"

MatchCall_BattlePikeText6::
	.string "Hé, {PLAYER}{KUN}? Ici {STR_VAR_1}. Comment\n"
	.string "vas-tu? J'ai entendu\p"
	.string "dire que tu avais\n"
	.string "traversé {STR_VAR_3} salles du {STR_VAR_2}.\p"
	.string "Je ferais bien de me\n"
	.string "concentrer sur mes POKéMON.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}? Ici {STR_VAR_1}. Tu as osé\n"
	.string "entrer dans le {STR_VAR_2}?\p"
	.string "Et tu as traversé {STR_VAR_3}\n"
	.string "salles? Pas mal du\p"
	.string "tout. Je viens de\p"
	.string "voir un POKéMON\n"
	.string "rare! Je te laisse!$"

MatchCall_BattlePikeText8::
	.string "Ça va, {PLAYER}{KUN}? C'est {STR_VAR_1}. Ça\n"
	.string "a l'air d'aller pour\l"
	.string "toi. Il paraît que\l"
	.string "tu as traversé {STR_VAR_3}\p"
	.string "salles du {STR_VAR_2}! C'est\n"
	.string "très impressionnant!\p"
	.string "Je vais élever mes\n"
	.string "POKéMON de la même\l"
	.string "façon que toi. À bientôt!$"

MatchCall_BattlePikeText9::
	.string "Salut, {PLAYER}{KUN}! C'est {STR_VAR_1}! Je\n"
	.string "suis au courant! Tu\p"
	.string "as traversé {STR_VAR_3} salles\n"
	.string "du {STR_VAR_2}! C'est\p"
	.string "formidable! Bon, je\n"
	.string "ferais bien de t'imiter!$"

MatchCall_BattlePikeText10::
	.string "Bonjour, {PLAYER}{KUN}. C'est {STR_VAR_1}.\n"
	.string "Tu as réussi à\p"
	.string "traverser {STR_VAR_3} salles du\n"
	.string "{STR_VAR_2}? Je vais essayer de\p"
	.string "suivre ton exemple.\n"
	.string "Je dois m'améliorer.$"

MatchCall_BattlePikeText11::
	.string "{PLAYER}{KUN}? Bonjour, c'est {STR_VAR_1}.\n"
	.string "On va devoir\p"
	.string "t'appeler sa Majesté {STR_VAR_2}\n"
	.string "bientôt, non? Tu as\p"
	.string "traversé quoi? {STR_VAR_3}\n"
	.string "salles? Ce n'est pas\p"
	.string "rien! Je me demande si\n"
	.string "je remporterai un titre\p"
	.string "un jour… Mais ça\n"
	.string "m'étonnerait… Bon, À bientôt!$"

MatchCall_BattlePikeText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}. Ça va?\l"
	.string "Tu as traversé {STR_VAR_3}\p"
	.string "salles d'un\n"
	.string "certain {STR_VAR_2}? C'est\p"
	.string "assez\n"
	.string "impressionnant. À bientôt!$"

MatchCall_BattlePikeText13::
	.string "Bonjour, {PLAYER}{KUN}! C'est {STR_VAR_1} qui\n"
	.string "appelle! J'espère que\l"
	.string "tout va bien. C'est\p"
	.string "vrai ce qu'on dit? Tu\n"
	.string "as traversé {STR_VAR_3} salles\p"
	.string "du {STR_VAR_2}? Quelle énergie!\n"
	.string "Je t'admire. A bientôt.$"

MatchCall_BattlePikeText14::
	.string "Bonjour, {PLAYER}{KUN}. C'est\n"
	.string "{STR_VAR_1}. J'ai entendu\l"
	.string "parler de toi! Tu\p"
	.string "as traversé {STR_VAR_3}\n"
	.string "salles du {STR_VAR_2}, non?\p"
	.string "Tu es un modèle\n"
	.string "pour moi! À bientôt!$"

MatchCall_BattlePyramidText1::
	.string "{PLAYER}? Bonjour, c'est\n"
	.string "{STR_VAR_1}! Je suis au\l"
	.string "courant! Tu as\p"
	.string "accédé à {STR_VAR_3} niveaux\n"
	.string "de la {STR_VAR_2}? C'est\p"
	.string "super, ça! Je\n"
	.string "devrais essayer d'y aller.$"

MatchCall_BattlePyramidText2::
	.string "Bonjour, c'est {STR_VAR_1}! J'ai\n"
	.string "entendu parler de toi! Il\p"
	.string "paraît que tu as accédé\n"
	.string "à {STR_VAR_3} niveaux de la {STR_VAR_2}.\p"
	.string "Fantastique! Je devrais\n"
	.string "m'occuper mieux de mes POKéMON!$"

MatchCall_BattlePyramidText3::
	.string "Salut, {PLAYER}! C'est moi, {STR_VAR_1}.\n"
	.string "Comment vas-tu? J'ai\l"
	.string "entendu dire que tu\p"
	.string "avais monté {STR_VAR_3} niveaux\n"
	.string "de la {STR_VAR_2}! Essaie de\p"
	.string "faire encore mieux la\n"
	.string "prochaine fois! À bientôt!$"

MatchCall_BattlePyramidText4::
	.string "Allô, {PLAYER}{KUN}? Ici {STR_VAR_1}.\n"
	.string "Bonjour! Il paraît\p"
	.string "que tu as exploré {STR_VAR_3}\n"
	.string "niveaux de la {STR_VAR_2}.\p"
	.string "Je devrais en\n"
	.string "prendre de la graine!$"

MatchCall_BattlePyramidText5::
	.string "Salut, {PLAYER}{KUN}! {STR_VAR_1} à\n"
	.string "l'appareil. On m'a\p"
	.string "dit que tu avais\n"
	.string "exploré {STR_VAR_3} niveaux de la\p"
	.string "{STR_VAR_2}. Moi aussi, je devrais\n"
	.string "m'y mettre! A bientôt!$"

MatchCall_BattlePyramidText6::
	.string "{PLAYER}{KUN}? Ici {STR_VAR_1}. Comment ça\n"
	.string "va? Au fait, il\p"
	.string "paraît que tu as accédé\n"
	.string "à {STR_VAR_3} niveaux de la {STR_VAR_2}! Je\p"
	.string "ferais bien de me\n"
	.string "concentrer sur mes POKéMON.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}? Ici {STR_VAR_1}. Tu as\n"
	.string "exploré la {STR_VAR_2} et\p"
	.string "accédé à {STR_VAR_3} des\n"
	.string "niveaux? Impec.\p"
	.string "Est-ce que tu y\n"
	.string "as vu des\p"
	.string "POKéMON rares?\n"
	.string "Non? Bon, À bientôt!$"

MatchCall_BattlePyramidText8::
	.string "Ça va, {PLAYER}{KUN}? C'est {STR_VAR_1}. Ça a\n"
	.string "l'air d'aller pour\l"
	.string "toi. J'ai entendu dire\l"
	.string "que tu avais exploré {STR_VAR_3}\p"
	.string "niveaux de la {STR_VAR_2}. C'est\n"
	.string "très impressionnant!\p"
	.string "Je vais élever mes\n"
	.string "POKéMON de la même\l"
	.string "façon que toi. À bientôt!$"

MatchCall_BattlePyramidText9::
	.string "Salut, {PLAYER}{KUN}! C'est {STR_VAR_1}!\n"
	.string "Tu as conquis {STR_VAR_3}\p"
	.string "niveaux de la {STR_VAR_2}!\n"
	.string "Bravo! C'est\p"
	.string "formidable! Bon, je\n"
	.string "ferais bien de t'imiter!$"

MatchCall_BattlePyramidText10::
	.string "Bonjour, {PLAYER}{KUN}. C'est {STR_VAR_1}.\n"
	.string "C'est vrai ce qu'on\p"
	.string "dit? Tu as exploré {STR_VAR_3}\n"
	.string "niveaux de la {STR_VAR_2}? Je vais\p"
	.string "essayer de suivre ton\n"
	.string "exemple. Je dois m'améliorer.$"

MatchCall_BattlePyramidText11::
	.string "{PLAYER}{KUN}? Bonjour, c'est {STR_VAR_1}. On\n"
	.string "va devoir t'appeler\p"
	.string "sa Majesté {STR_VAR_2} bientôt,\n"
	.string "non? Tu as vraiment\p"
	.string "exploré {STR_VAR_3} niveaux? Ce\n"
	.string "n'est pas rien! Je me\p"
	.string "demande si je\n"
	.string "remporterai un titre\p"
	.string "un jour… Mais ça\n"
	.string "m'étonnerait… Bon, À bientôt!$"

MatchCall_BattlePyramidText12::
	.string "Bonjour, {PLAYER}{KUN}. C'est\n"
	.string "{STR_VAR_1}. Ça va?\l"
	.string "Dis-moi, as-tu\p"
	.string "réellement exploré\n"
	.string "{STR_VAR_3} niveaux de la {STR_VAR_2}?\p"
	.string "C'est assez\n"
	.string "impressionnant. À bientôt!$"

MatchCall_BattlePyramidText13::
	.string "Bonjour, {PLAYER}{KUN}! C'est {STR_VAR_1}\n"
	.string "qui appelle!\l"
	.string "J'espère que tout va\p"
	.string "bien. On dit que tu as\n"
	.string "exploré {STR_VAR_3}{STR_VAR_2} niveaux de\p"
	.string "la {PLAYER}? Quelle énergie!\n"
	.string "Je t'admire. A bientôt.$"

MatchCall_BattlePyramidText14::
	.string "Bonjour, {KUN}{STR_VAR_1}. C'est\n"
	.string "J'ai entendu\l"
	.string "parler de toi! C'est\p"
	.string "bien toi qui as\n"
	.string "exploré {STR_VAR_3} niveaux de\p"
	.string "la {STR_VAR_2}? Tu es un modèle\n"
	.string "pour moi! À bientôt!$"

MatchCall_Text_Mom1::
	.string "MAMAN: D'abord ton père,\n"
	.string "maintenant toi… Mais\p"
	.string "qu'est-ce qui vous attire\p"
	.string "tant chez les POKéMON? Moi?\n"
	.string "J'aime les POKéMON qui peuvent\l"
	.string "m'aider à la maison, c'est tout.$"

MatchCall_Text_Mom2::
	.string "MAMAN: Bonjour, {PLAYER}! Ton père\n"
	.string "passe tout son temps dans\l"
	.string "l'ARÈNE de CLÉMENTI-VILLE. Il\p"
	.string "passe de temps en temps, avale\n"
	.string "tout ce qu'il peut et repart\l"
	.string "immédiatement à l'ARÈNE. Je me\p"
	.string "fais du souci pour lui. Perdre\n"
	.string "contre toi a été un gros choc!$"

MatchCall_Text_Mom3::
	.string "MAMAN: {PLAYER}… Tout va bien à\n"
	.string "la maison, mon chou.\p"
	.string "Use bien les semelles de\n"
	.string "tes CHAUSSURES DE SPORT!$"

MatchCall_Text_Baoba1::
	.string "BAOBA: {PLAYER} ! La ZONE\n"
	.string "SAFARI est presque prête !\p"
	.string "Je t'appellerai à la\n"
	.string "première heure. C'est fini !$"

MatchCall_Text_Baoba2::
	.string "BAOBA: {PLAYER} ! La ZONE\n"
	.string "SAFARI est ouverte !\p"
	.string "N'importe quand !$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Bonjour, {PLAYER}! Je\p"
	.string "suis en train de me\n"
	.string "remettre à niveau. Je ne\p"
	.string "vais pas rouvrir l'ARÈNE\n"
	.string "tout de suite. Mais dès\p"
	.string "que l'ARÈNE sera prête,\n"
	.string "passe faire un combat!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: C'est toi, {PLAYER}?\n"
	.string "Félicitations! J'ai\l"
	.string "entendu parler de toi! Eh\p"
	.string "bien, je ne vais pas\n"
	.string "rouvrir l'ARÈNE tout de\p"
	.string "suite. Mais dès que l'ARÈNE\n"
	.string "sera prête, passe faire un combat!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}! L'ARÈNE\n"
	.string "est prête! J'espère\p"
	.string "que tu vas bientôt\n"
	.string "venir à MEROUVILLE!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: M'être battue\n"
	.string "contre toi dans l'ARÈNE de\l"
	.string "MEROUVILLE me remplit de fierté, {PLAYER}.$"

MatchCall_Text_Brawly1::
	.string "BASTIEN: Salut, {PLAYER}{KUN}! Notre\p"
	.string "combat m'a beaucoup\n"
	.string "appris. Je vais suivre un\p"
	.string "entraînement intensif\n"
	.string "avant de rouvrir l'ARÈNE.\p"
	.string "Mais ça risque de durer\n"
	.string "quelque temps. Quand tout\p"
	.string "sera prêt, j'espère que tu\n"
	.string "passeras refaire un combat.$"

MatchCall_Text_Brawly2::
	.string "BASTIEN: Salut, {PLAYER}{KUN}! Bravo!\n"
	.string "La nouvelle s'est répandue\p"
	.string "comme une traînée de\n"
	.string "poudre! Je vais devoir me\p"
	.string "remettre sérieusement à\n"
	.string "l'entraînement. Ça va\p"
	.string "prendre un peu de temps avant\n"
	.string "que je rouvre l'ARÈNE. Quand\p"
	.string "tout sera prêt, j'espère que\n"
	.string "tu passeras refaire un combat.$"

MatchCall_Text_Brawly3::
	.string "BASTIEN: Salut, {PLAYER}{KUN}! Je\n"
	.string "suis prêt à rouvrir\p"
	.string "l'ARÈNE! Reviens à\n"
	.string "MYOKARA quand tu veux!$"

MatchCall_Text_Brawly4::
	.string "BASTIEN: {PLAYER}{KUN}, je ne me lasserai\n"
	.string "jamais de me battre contre toi!$"

MatchCall_Text_Wattson1::
	.string "VOLTERE: Oh, c'est toi! Après\p"
	.string "notre combat, j'ai repris\n"
	.string "l'entraînement depuis le début.\p"
	.string "J'ai besoin d'encore un petit\n"
	.string "peu de temps avant de rouvrir\p"
	.string "l'ARÈNE. Tu vas devoir attendre\n"
	.string "Ouhahahahaha!$"

MatchCall_Text_Wattson2::
	.string "VOLTERE: Wahahaha! Tu as\p"
	.string "réussi, n'est-ce pas? La\n"
	.string "nouvelle est arrivée jusqu'à\p"
	.string "moi! J'ai encore besoin de\n"
	.string "continuer un peu\p"
	.string "l'entraînement. Je ne vais pas\n"
	.string "rouvrir l'ARÈNE tout de suite.\p"
	.string "Tu vas devoir attendre avant\n"
	.string "de m'affronter encore. Wahahaha!$"

MatchCall_Text_Wattson3::
	.string "VOLTERE: Oh, c'est\n"
	.string "toi! L'ARÈNE est\p"
	.string "prête! Viens à LAVANDIA\n"
	.string "quand tu veux! Waaaaaouh!$"

MatchCall_Text_Wattson4::
	.string "VOLTERE:\p"
	.string "Wahahahaha! Ton énergie\n"
	.string "me fait toujours du bien!$"

MatchCall_Text_Flannery1::
	.string "ADRIANE: {PLAYER}… Après notre\p"
	.string "combat, j'ai réalisé que je\n"
	.string "manquais d'expérience. Mais\p"
	.string "je ne baisse pas les bras\p"
	.string "pour autant! Je vais\n"
	.string "m'entraîner dur avant de\p"
	.string "rouvrir l'ARÈNE. Quand le moment\n"
	.string "sera venu, nous nous battrons, {PLAYER}.$"

MatchCall_Text_Flannery2::
	.string "ADRIANE: Salut, {PLAYER}?\n"
	.string "Félicitations! La\p"
	.string "nouvelle de ta réussite\n"
	.string "m'a fait chaud au cœur!\p"
	.string "L'entraînement se passe à\n"
	.string "merveille. Dès que l'ARÈNE\p"
	.string "sera prête, une marque\n"
	.string "apparaîtra près de mon nom\l"
	.string "dans la liste du MATCH PHONE.$"

MatchCall_Text_Flannery3::
	.string "ADRIANE: Oh, {PLAYER}? L'ARÈNE est\n"
	.string "prête! Viens à VERMILAVA! On a\p"
	.string "des sources chaudes et Je\n"
	.string "dans la source chaude et un défi!$"

MatchCall_Text_Flannery4::
	.string "ADRIANE: {PLAYER}… Je\n"
	.string "vois que tu ne\l"
	.string "cesses de progresser.$"

MatchCall_Text_Winona1::
	.string "ALIZEE: Bonjour, {PLAYER}! Notre\p"
	.string "combat m'a permis de\n"
	.string "comprendre mes points\p"
	.string "faibles! Quand je rouvrirai\n"
	.string "Encore en défaite!$"

MatchCall_Text_Winona2::
	.string "ALIZEE: Bravo, {PLAYER}! Tout le\p"
	.string "monde à CIMETRONELLE sait qui\n"
	.string "est le nouveau MAÎTRE! Mais…\p"
	.string "l'issue de notre prochain\n"
	.string "combat sera différente, crois-moi.$"

MatchCall_Text_Winona3::
	.string "ALIZEE: C'est toi, {PLAYER}? J'ai\n"
	.string "rouvert l'ARÈNE! On\p"
	.string "t'attend tous à CIMETRONELLE!$"

MatchCall_Text_Winona4::
	.string "ALIZEE: {PLAYER}… J'ai perdu,\n"
	.string "mais cette défaite ne va\l"
	.string "pas m'ébranler. Tu peux\p"
	.string "comprendre, car toi\n"
	.string "aussi tu vis pour tes rêves.$"

MatchCall_Text_TateLiza1::
	.string "LEVY: Oh! C'est… TATIA: {PLAYER}!\n"
	.string "LEVY: On a repris\p"
	.string "l'entraînement… TATIA: pour\n"
	.string "rouvrir l'ARÈNE! LEVY: Quand\p"
	.string "l'ARÈNE sera prête… TATIA:\n"
	.string "il y aura un symbole… LEVY:\p"
	.string "près de nos noms dans…\n"
	.string "TATIA: la liste du MATCH PHONE.$"

MatchCall_Text_TateLiza2::
	.string "LEVY: Félicitations, {PLAYER}!\n"
	.string "TATIA: Félicitations, {PLAYER}!\p"
	.string "LEVY: Nous, on s'entraîne…\n"
	.string "TATIA: encore! LEVY: Quand\p"
	.string "l'ARÈNE sera prête… TATIA:\n"
	.string "il y aura un symbole… LEVY:\p"
	.string "près de nos noms dans…\n"
	.string "TATIA: la liste du MATCH PHONE.$"

MatchCall_Text_TateLiza3::
	.string "LEVY: {PLAYER}! TATIA: {PLAYER}!\n"
	.string "LEVY: L'ARÈNE est\p"
	.string "prête! TATIA:\n"
	.string "L'ARÈNE est prête!\p"
	.string "LEVY: Passe nous\n"
	.string "voir… TATIA: à ALGATIA!$"

MatchCall_Text_TateLiza4::
	.string "LEVY: {PLAYER}, notre combat… TATIA: a\n"
	.string "été une expérience unique.\p"
	.string "LEVY: Ce serait bien si on\n"
	.string "LIZA: On pourrait tous se battre!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hum… {PLAYER}{KUN}… C'est\n"
	.string "ça? Notre combat m'a\p"
	.string "rappelé la première\n"
	.string "fois que j'ai vu\l"
	.string "MARC. Peut-être\p"
	.string "arriverez-vous à\n"
	.string "surpasser MARC? Qui sait!?!$"

MatchCall_Text_Juan2::
	.string "JUAN: Dites donc… {PLAYER}{KUN}… Vous\n"
	.string "avez atteint votre objectif!\p"
	.string "Vous voyez, j'ai l'œil pour\n"
	.string "découvrir les nouveaux\p"
	.string "talents… Vous avez réussi à\n"
	.string "atteindre le sommet de la\l"
	.string "de pouvoir et de prestige.$"

MatchCall_Text_Juan3::
	.string "JUAN: Ho, ho… {PLAYER}{KUN}… L'ARÈNE\p"
	.string "d'ATALANOPOLIS a enfin\n"
	.string "rouvert. Si vous voulez\p"
	.string "me voir, vous pouvez\n"
	.string "passer quand vous voulez.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}… Quand je me bats\p"
	.string "contre vous, c'est comme\n"
	.string "si une musique majestueuse\l"
	.string "jouait dans mon cœur… En\p"
	.string "fermant les yeux, je vous\n"
	.string "vois danser gracieusement…$"

MatchCall_Text_Sidney::
	.string "DAMIEN: Salut, {PLAYER}!\p"
	.string "Repasse quand tu veux\n"
	.string "à la LIGUE POKéMON si\l"
	.string "tu veux te battre\p"
	.string "encore contre moi. J'y\n"
	.string "serai! Je t'attends!$"

MatchCall_Text_Phoebe::
	.string "SPECTRA: Salut, {PLAYER}! Tu\p"
	.string "devrais passer nous\n"
	.string "voir, un de ces jours!\p"
	.string "Je voudrais voir à quel\n"
	.string "point ton attachement\l"
	.string "à tes POKéMON a grandi.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Salut, {PLAYER}.\p"
	.string "Jure-moi que tu n'as\n"
	.string "pas pris la grosse tête!\p"
	.string "Si tu as besoin d'une\n"
	.string "petite douche froide,\l"
	.string "passe à la LIGUE POKéMON…$"

MatchCall_Text_Drake::
	.string "ARAGON: Cette voix… C'est\n"
	.string "toi, {PLAYER}? Je sais que\p"
	.string "maintenant il y a la ZONE\n"
	.string "DE COMBAT où les\l"
	.string "DRESSEURS peuvent tester\l"
	.string "leurs aptitudes. Mais si tu\p"
	.string "veux faire de vrais\n"
	.string "combats, on n'a encore rien\l"
	.string "inventé de mieux que la\p"
	.string "LIGUE POKéMON! Tu ne crois pas, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "MARC: Salut, {PLAYER}{KUN}. As-tu\n"
	.string "rencontré PIERRE? Il est…\p"
	.string "Comment dire… Il est\n"
	.string "vraiment doué! Mais il se bat\p"
	.string "très rarement, c'est un\n"
	.string "solitaire. Il préfère chercher\p"
	.string "des pierres rares. Au moment\n"
	.string "où on parle, il est sûrement\p"
	.string "en train de creuser dans une\n"
	.string "caverne ou une montagne. C'est\p"
	.string "quoi une pierre rare, en fait?\n"
	.string "Je ne vois que les METEORITES…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … … … … … … …\n"
	.string "Bip! FLORA: Bonjour, {PLAYER}{KUN}!\p"
	.string "Je suis allée à\p"
	.string "PACIFIVILLE il y a\n"
	.string "quelques jours. J'y ai\p"
	.string "vu un POKéMON géant de\n"
	.string "couleur verte voler dans\p"
	.string "le ciel! Je n'avais\n"
	.string "jamais vu une chose\p"
	.string "pareille… Je me demande\n"
	.string "bien ce que c'était. C'est\p"
	.string "peut-être une découverte!\n"
	.string "… … … … … … … … … … … Clic!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … … … … … …\n"
	.string "… Bip! BRICE:\p"
	.string "Salut, {PLAYER}! Je reviens\n"
	.string "de PACIFIVILLE. J'y\p"
	.string "ai vu un POKéMON\n"
	.string "géant de couleur\p"
	.string "verte voler dans le\n"
	.string "ciel! Je n'avais\p"
	.string "jamais vu un truc\n"
	.string "pareil! J'aurais aimé\p"
	.string "que tu voies ça, {PLAYER}. … …\n"
	.string "… … … … … … … … … Clic!$"

MatchCall_Text_May1::
	.string "FLORA: Bonjour, {PLAYER}{KUN}! M. MARCO a pris\p"
	.string "sa retraite de MARIN, mais de\n"
	.string "temps en temps, je le vois en mer\l"
	.string "avec son PIKO. La mer, c'était\p"
	.string "Il doit toujours aimer la mer.$"

MatchCall_Text_May2::
	.string "FLORA: Bonjour, {PLAYER}{KUN}! Tu sais qu'il y\p"
	.string "a une ARÈNE à CLÉMENTI-VILLE et\n"
	.string "MYOKARA? Ce sont pourtant de\p"
	.string "petites villes. Par contre, il n'y\n"
	.string "en a pas dans la grande ville\p"
	.string "portuaire de POIVRESSEL. Le jour\n"
	.string "Je devrais demander à être LEADER.$"

MatchCall_Text_May3::
	.string "FLORA: Bonjour, {PLAYER}{KUN}! Tu\p"
	.string "te souviens de l'homme\n"
	.string "de la MAISON COUPCOUP\l"
	.string "à MEROUVILLE? Je viens\p"
	.string "d'apprendre qu'il a un\n"
	.string "petit frère qui habite\p"
	.string "à LAVANDIA. Tu veux\p"
	.string "savoir comment il\n"
	.string "s'appelle? … … … … … … … …\p"
	.string "… … … … TYPE ÉCLATE-ROC!$"

MatchCall_Text_May4::
	.string "FLORA: {PLAYER}{KUN}? TUNNEL\p"
	.string "MERAZON… Ils l'ont appelé\n"
	.string "comme ça parce qu'il\l"
	.string "relie MEROUVILLE à VERGAZON.$"

MatchCall_Text_May5::
	.string "FLORA: Comment ça va, {PLAYER}{KUN}?\p"
	.string "Je suis sur la ROUTE\p"
	.string "111. Je vais faire une\n"
	.string "halte chez une dame âgée\p"
	.string "pour me reposer. Elle\n"
	.string "habite au nord du désert.$"

MatchCall_Text_May6::
	.string "FLORA: Bonjour, {PLAYER}{KUN}! Tu connais\p"
	.string "la TOUR MIRAGE qui se trouve\n"
	.string "dans le désert? Elle\p"
	.string "disparaît parfois\n"
	.string "mystérieusement, puis réapparaît\p"
	.string "J'aimerais pouvoir le voir.$"

MatchCall_Text_May7::
	.string "FLORA: Salut, {PLAYER}{KUN}! Je suis\n"
	.string "sur la ROUTE 119. Il y a\p"
	.string "une rivière immense. Et il\n"
	.string "n'arrête pas de pleuvoir. Je\p"
	.string "suis trempée jusqu'aux os!$"

MatchCall_Text_May8::
	.string "FLORA: Bonjour, {PLAYER}{KUN}. Le MONT MEMORIA\p"
	.string "est un mémorial dédié aux\n"
	.string "POKéMON qui nous ont\p"
	.string "malheureusement quittés.\n"
	.string "Ici, les POKéMON SPECTRE abondent!$"

MatchCall_Text_May9::
	.string "FLORA: Bonjour, {PLAYER}{KUN}! Je pensais\p"
	.string "aller aux sources chaudes de\n"
	.string "VERMILAVA. Mais près du\p"
	.string "SENTIER SINUROC, j'ai\n"
	.string "rencontré des gens bizarres. Ils\l"
	.string "L'humeur était moche!$"

MatchCall_Text_May10::
	.string "FLORA: Bonjour, {PLAYER}{KUN}! Tu es au\n"
	.string "courant? Il paraît que le\p"
	.string "CAPT. POUPE a découvert la\n"
	.string "CAVERNE FONDMER lors de\l"
	.string "son expédition sous-marine.$"

MatchCall_Text_May11::
	.string "FLORA: Bonjour, {PLAYER}{KUN}! Tu sais\n"
	.string "quoi? Si tu n'as pas de\p"
	.string "bateau, il y a une capacité\n"
	.string "de POKéMON qui peut te faire\l"
	.string "flotter sur l'eau. Et ce\p"
	.string "n'est pas tout! Il y a même\p"
	.string "une autre capacité qui\n"
	.string "permet d'aller au fond de la mer.$"

MatchCall_Text_May12::
	.string "FLORA: Bonjour, {PLAYER}{KUN}! Tout va\n"
	.string "bien? Tu as dû voir que\p"
	.string "parfois on ne peut pas\n"
	.string "traverser la mer. C'est tout\l"
	.string "simplement bloqué. Il faut\p"
	.string "plonger sous l'eau et suivre\n"
	.string "les sillons. Une fois de\p"
	.string "l'autre côté, il suffit de\n"
	.string "remonter à la surface. Facile!$"

MatchCall_Text_May13::
	.string "FLORA: Bonjour, {PLAYER}{KUN}! Comment\p"
	.string "ça va? Tu remplis bien ton\n"
	.string "POKéDEX? J'ai entendu dire\p"
	.string "qu'il y a des POKéMON très\n"
	.string "anciens par ici. Il y en\l"
	.string "aurait trois! Je voudrais\p"
	.string "bien en voir au moins un…$"

MatchCall_Text_May14::
	.string "FLORA: {PLAYER}{KUN}! Les gens\n"
	.string "parlent de toi! Tu as\p"
	.string "battu le CHAMPION D'ARÈNE\n"
	.string "d'ATALANOPOLIS, c'est\p"
	.string "super! Il ne te reste plus\n"
	.string "beaucoup de chemin à parcourir.$"

MatchCall_Text_May15::
	.string "FLORA: Il n'y a pas un\n"
	.string "seul DRESSEUR à HOENN qui\l"
	.string "n'ait jamais entendu\p"
	.string "parler de toi, {PLAYER}{KUN}! Quand je\n"
	.string "dis aux gens que je te\l"
	.string "connais, {PLAYER}{KUN}, ils sont impressionnés!$"

MatchCall_Text_Brendan1::
	.string "BRICE: Salut, {PLAYER}! M. MARCO a\p"
	.string "pris sa retraite de MARIN,\n"
	.string "mais il part toujours en mer\l"
	.string "avec son PIKO. Ce n'est pas\p"
	.string "parce qu'il est à la\n"
	.string "retraite qu'il va oublier la mer!$"

MatchCall_Text_Brendan2::
	.string "BRICE: Salut, {PLAYER}! Pourquoi\p"
	.string "CLÉMENTI-VILLE et MYOKARA\n"
	.string "ont une ARÈNE? Après tout,\p"
	.string "POIVRESSEL n'en a pas et\n"
	.string "c'est beaucoup plus grand!\p"
	.string "S'il y en avait une, je\n"
	.string "voudrais en être le CHAMPION.$"

MatchCall_Text_Brendan3::
	.string "BRICE: Bonjour, {PLAYER}!\p"
	.string "Tu te souviens de\n"
	.string "la MAISON COUPCOUP\l"
	.string "à MEROUVILLE?\p"
	.string "L'homme qui y vit a\n"
	.string "un petit frère à\p"
	.string "LAVANDIA. Devine\p"
	.string "comment il s'appelle!\n"
	.string "… … … … … … … … … …\p"
	.string "… … TYPE ÉCLATE-ROC!$"

MatchCall_Text_Brendan4::
	.string "BRICE: {PLAYER}? Tu sais que\p"
	.string "le TUNNEL MERAZON\n"
	.string "s'appelle comme ça parce\l"
	.string "qu'il relie MEROUVILLE à\p"
	.string "VERGAZON? Tu le savais?$"

MatchCall_Text_Brendan5::
	.string "BRICE: {PLAYER}, quoi de neuf? Je suis\p"
	.string "sur la ROUTE 111, là. Je vais\p"
	.string "me reposer un peu chez une\n"
	.string "vielle dame au nord du désert.\p"
	.string "Si tu es dans le coin, tu\n"
	.string "pourrais aussi lui rendre visite.$"

MatchCall_Text_Brendan6::
	.string "BRICE: Hé, {PLAYER}! Tu as entendu\p"
	.string "parler de la TOUR MIRAGE\n"
	.string "dans le désert? Il paraît\p"
	.string "qu'on ne peut pas la voir\n"
	.string "tout le temps, comme un\p"
	.string "mirage! Ça, c'est un truc à voir!$"

MatchCall_Text_Brendan7::
	.string "BRICE: Qui c'est? {PLAYER}! Je\n"
	.string "suis sur la ROUTE 119. Il\p"
	.string "y a une grosse rivière et\n"
	.string "il pleut des cordes. Je\p"
	.string "suis complètement trempé!$"

MatchCall_Text_Brendan8::
	.string "BRICE: {PLAYER}! Le MONT MEMORIA\p"
	.string "est dédié aux POKéMON\n"
	.string "qui nous ont quittés. Du\p"
	.string "coup, tous les POKéMON\n"
	.string "de type SPECTRE y vont!$"

MatchCall_Text_Brendan9::
	.string "BRICE: Salut, {PLAYER}. Je suis\p"
	.string "allé aux sources chaudes\n"
	.string "de VERMILAVA aujourd'hui.\p"
	.string "J'ai croisé des gens à\n"
	.string "l'air louche près du SENTIER\p"
	.string "SINUROC. Des sales types… Ça\n"
	.string "devait être la TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRICE: Bonjour, {PLAYER}! Tu es\n"
	.string "au courant? Le CAPT.\p"
	.string "POUPE a découvert la\n"
	.string "CAVERNE FONDMER pendant\l"
	.string "une expédition sous-marine.$"

MatchCall_Text_Brendan11::
	.string "BRICE: Hé! Salut, {PLAYER}! Je vais\n"
	.string "t'apprendre un truc! Il y a\p"
	.string "une capacité de POKéMON qui\n"
	.string "permet d'aller en mer même\l"
	.string "si on n'a pas de bateau!\p"
	.string "Et il y en a aussi une qui\n"
	.string "permet d'aller au fond de\p"
	.string "la mer. Je trouve ça dingue!$"

MatchCall_Text_Brendan12::
	.string "BRICE: Salut, {PLAYER}! Ça va comme tu\n"
	.string "veux? Tu sais que parfois il\p"
	.string "est impossible de franchir la\n"
	.string "mer? Dans ces cas-là, il faut\p"
	.string "plonger et suivre les sillons\n"
	.string "au fond de la mer. Une fois de\p"
	.string "l'autre côté, il suffit de\n"
	.string "revenir à la surface! Enfantin!$"

MatchCall_Text_Brendan13::
	.string "BRICE: Salut, {PLAYER}! Tu vas\p"
	.string "bien? Ça avance ton\n"
	.string "POKéDEX? Il paraît\p"
	.string "qu'il y a des POKéMON\n"
	.string "très anciens dans le\l"
	.string "coin. Trois! Je voudrais\p"
	.string "en attraper au moins un…$"

MatchCall_Text_Brendan14::
	.string "BRICE: {PLAYER}! Hé, je suis\n"
	.string "au courant! Tu as\p"
	.string "battu le CHAMPION\n"
	.string "D'ARÈNE d'ATALANOPOLIS!\p"
	.string "Trop cool! Tu es près du but!$"

MatchCall_Text_Brendan15::
	.string "BRICE: Tous les\n"
	.string "DRESSEURS te connaissent à\l"
	.string "HOENN, {PLAYER}! Les gens ne me\p"
	.string "croient même pas quand je\n"
	.string "leur dis que je suis l'ami\l"
	.string "de {PLAYER}! Ils sont tous jaloux.$"

MatchCall_Text_Wally1::
	.string "TIMMY: Oh, {PLAYER}! Je suis\p"
	.string "en bien meilleure\n"
	.string "forme, maintenant.\p"
	.string "J'espère être bientôt un\n"
	.string "aussi bon DRESSEUR que toi, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "TIMMY: Salut, {PLAYER}! Depuis que\p"
	.string "le TUNNEL MERAZON est\n"
	.string "creusé, SYLVIE est aux anges!$"

MatchCall_Text_Wally3::
	.string "TIMMY: Oh, {PLAYER}! Je suis\p"
	.string "parti de chez mon oncle à\n"
	.string "VERGAZON sans prévenir\p"
	.string "personne. Il doit être\p"
	.string "furieux contre moi… Mais {PLAYER}…\n"
	.string "Toi, tu me comprends, non?$"

MatchCall_Text_Wally4::
	.string "TIMMY: {PLAYER}? C'est moi,\n"
	.string "TIMMY! L'univers des\p"
	.string "DRESSEURS, c'est quelque\p"
	.string "chose! Dès que tu as des\n"
	.string "POKéMON, tout le monde te\p"
	.string "parle! C'est comme si les\n"
	.string "POKéMON rapprochaient les gens!$"

MatchCall_Text_Wally5::
	.string "TIMMY: {PLAYER}? C'est génial!\n"
	.string "Le TARSAL capturé\l"
	.string "ensemble? Il a évolué, {PLAYER}!\p"
	.string "J'ai peut-être du talent…\p"
	.string "Oh, mais je ne devrais\n"
	.string "pas prendre la grosse tête!\p"
	.string "Après tout, c'est le\n"
	.string "POKéMON qu'il faut féliciter!$"

MatchCall_Text_Wally6::
	.string "… … … … … … … … … … …\n"
	.string "… TIMMY est dans un\p"
	.string "endroit non couvert\n"
	.string "par le réseau POKéNAV…$"

MatchCall_Text_Wally7::
	.string "TIMMY: Oh, {PLAYER}! Avant de\p"
	.string "te connaître, je\n"
	.string "passais tout mon temps\p"
	.string "à la maison… Et\n"
	.string "maintenant, je sillonne\p"
	.string "les routes avec mes\n"
	.string "POKéMON! {PLAYER}… Je te dois tant…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Bien le bonjour, {PLAYER}{KUN}!\p"
	.string "Tu sais qu'on trouve des\n"
	.string "POKéMON absolument\p"
	.string "partout? En montagne, dans\n"
	.string "la mer, dans les hautes\p"
	.string "herbes!?! De même, tu peux\n"
	.string "rencontrer des DRESSEURS\p"
	.string "partout. C'est pour ça que je\n"
	.string "cours toujours à droite à gauche!$"

MatchCall_Text_Scott2::
	.string "SCOTT: Je suis sur la\n"
	.string "ROUTE 119. Ça grouille de\p"
	.string "DRESSEURS ici! Le sol est\n"
	.string "recouvert de hautes herbes.\p"
	.string "Je suis en short, l'herbe\n"
	.string "me chatouille les gambettes!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Bonjour, bonjour, {PLAYER}{KUN}!\p"
	.string "As-tu déjà eu l'occasion de\n"
	.string "gravir le MONT MEMORIA?\p"
	.string "C'est un mémorial dédié aux\n"
	.string "POKéMON qui nous ont quittés.\p"
	.string "Les DRESSEURS devraient tous\n"
	.string "y monter au moins une fois.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Bonjour, {PLAYER}{KUN}! J'ai\p"
	.string "entendu parler de ces\n"
	.string "deux bandes qui font du\p"
	.string "grabuge. TEAM MAGMA et\n"
	.string "TEAM AQUA, je crois. Il\p"
	.string "doit y avoir quelques\n"
	.string "bons DRESSEURS parmi eux.\p"
	.string "Mais ce sont des brutes…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Tiens! Bonjour, {PLAYER}{KUN}. Y\p"
	.string "a-t-il de bons DRESSEURS\n"
	.string "au fond de la mer? Je ne\p"
	.string "peux pas vérifier\n"
	.string "moi-même. Je ne sais pas\l"
	.string "Et je n'élève pas POKéMON...$"

MatchCall_Text_Scott6::
	.string "SCOTT: Bonjour, bonjour,\p"
	.string "{PLAYER}{KUN}! Tu sais que si tu as\n"
	.string "tous les BADGES\l"
	.string "D'ARÈNES, tu as le droit\p"
	.string "de défier la LIGUE\n"
	.string "POKéMON? Avec ton talent,\p"
	.string "tu as toutes les chances\n"
	.string "de devenir MAÎTRE. Mais\p"
	.string "tu sais… Il y a un\n"
	.string "endroit encore mieux. Je\p"
	.string "ne veux pas t'en dire plus\n"
	.string "pour l'instant. Mais\p"
	.string "penses-y. Quand la LIGUE\n"
	.string "POKéMON et le PANTHEON DES\l"
	.string "DRESSEURS seront derrière toi!$"

MatchCall_Text_Scott7::
	.string "… … … … … … … … … … …\n"
	.string "… SCOTT est dans un\p"
	.string "endroit non couvert\n"
	.string "par le réseau POKéNAV…$"

MatchCall_Text_Norman1::
	.string "PAPA: A MEROUVILLE, il y\n"
	.string "a un endroit qui\l"
	.string "s'appelle la MAISON\p"
	.string "COUPCOUP. Quel drôle de nom!\n"
	.string "Vas-y, si tu es dans le coin.$"

MatchCall_Text_Norman2::
	.string "PAPA: Hum… Tu fais\n"
	.string "des progrès, {PLAYER}.\l"
	.string "Plus le temps\p"
	.string "passe et plus tu\n"
	.string "t'éloignes de ta\l"
	.string "mère et moi… C'est\p"
	.string "un drôle de sentiment.$"

MatchCall_Text_Norman3::
	.string "PAPA: Je vois… Tu as\n"
	.string "quatre BADGES… Je vais\p"
	.string "devoir tenir ma\n"
	.string "promesse. Nous allons\p"
	.string "nous battre. Viens quand\n"
	.string "tu veux. Je t'attendrai.$"

MatchCall_Text_Norman4::
	.string "PAPA: {PLAYER}! Tu devrais rendre\n"
	.string "visite à ta mère de temps\p"
	.string "en temps. Moi, je reste\n"
	.string "ici. Je m'entraîne dur. La\p"
	.string "voie qui mène à la\n"
	.string "perfection est un chemin sans fin!$"

MatchCall_Text_Norman5::
	.string "PAPA: Bonjour, {PLAYER}! Quoi? Un\p"
	.string "SCEAU MAGMA? Je n'en ai\n"
	.string "jamais entendu parler.\p"
	.string "Mais vu le nom, ça doit\n"
	.string "avoir un rapport avec un volcan!$"

MatchCall_Text_Norman6::
	.string "PAPA: Allez! C'est ça!\p"
	.string "Oh? {PLAYER}! Je suis en\p"
	.string "pleine séance\n"
	.string "d'entraînement avec mes POKéMON!$"

MatchCall_Text_Norman7::
	.string "PAPA: {PLAYER}! Si j'avais su que\p"
	.string "tu deviendrais le MAÎTRE\n"
	.string "de la LIGUE POKéMON…\p"
	.string "Bien! Je dois réagir! Je ne\n"
	.string "vais pas me laisser faire!$"

MatchCall_Text_Norman8::
	.string "PAPA: Hum? {PLAYER}? Tu\n"
	.string "appelles au bon\p"
	.string "moment! Je t'invite à\n"
	.string "venir faire un combat\p"
	.string "contre moi. Je suis dans\n"
	.string "l'ARÈNE de CLÉMENTI-VILLE.$"

MatchCall_Text_Norman9::
	.string "PAPA: Tu m'épates, {PLAYER}.\n"
	.string "Mais jusqu'où iras-tu?$"

MatchCall_Text_Steven1::
	.string "PIERRE: Bonjour, {PLAYER}{KUN}! As-tu\p"
	.string "déjà visité LAVANDIA? Tu\n"
	.string "devrais aller te\p"
	.string "procurer un VELO COURSE\n"
	.string "aux CYCLES RODOLPHE.\p"
	.string "Ensuite, je te conseille\n"
	.string "d'aller explorer la\p"
	.string "GROTTE GRANITE. Tu pourrais\n"
	.string "bien y faire une découverte.$"

MatchCall_Text_Steven2::
	.string "PIERRE: Bonjour, {PLAYER}{KUN}! J'ai\p"
	.string "rencontré beaucoup de\n"
	.string "DRESSEURS dans ma vie. Mais\p"
	.string "toi, tu n'es pas comme les\n"
	.string "autres. Ça saute aux yeux.$"

MatchCall_Text_Steven3::
	.string "PIERRE: Bonjour, {PLAYER}{KUN}! Quand\p"
	.string "tu es sur la route avec\n"
	.string "tes POKéMON, à quoi\p"
	.string "penses-tu? Tu les\n"
	.string "considères comme des\p"
	.string "partenaires solides? Ou plutôt\n"
	.string "comme d'agréables petits\p"
	.string "camarades? Les enjeux de ton\n"
	.string "L'importance de l'aventure change.$"

MatchCall_Text_Steven4::
	.string "PIERRE: Allô? {PLAYER}{KUN}? Je\n"
	.string "suis au CENTRE\p"
	.string "SPATIAL. J'ai des\n"
	.string "ennuis, là. Je suis\p"
	.string "désolé, je ne peux\n"
	.string "pas parler. À bientôt!$"

MatchCall_Text_Steven5::
	.string "PIERRE: Oh! {PLAYER}{KUN}! Ce n'est\n"
	.string "plus le moment de\p"
	.string "discuter. Il n'y À\n"
	.string "bientôt rien à dire. Tu\p"
	.string "dois croire en toi et faire\n"
	.string "ce que tu penses être juste.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "PIERRE ne\n"
	.string "prend pas l'appel…$"

MatchCall_Text_Steven7::
	.string "PIERRE: {PLAYER}{KUN}… Bravo pour\n"
	.string "ton entrée au PANTHEON\p"
	.string "DES DRESSEURS. … … …\n"
	.string "… … … … … … … … …\p"
	.string "J'espère que nos\n"
	.string "chemins se croiseront encore!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. SÉKO: Oh, {PLAYER}{KUN}! J'ai\n"
	.string "entendu parler de toi, tu\p"
	.string "sais! On dirait que ton\n"
	.string "POKéNAV a été équipé du\p"
	.string "MATCH PHONE. Il faudrait que\p"
	.string "j'y sois enregistré! Comme\n"
	.string "ça, je pourrai garder un œil\l"
	.string "sur ton POKéDEX même quand tu\p"
	.string "es en vadrouille. … … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "Vous avez enregistré\n"
	.string "PROF. SÉKO dans le POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. SÉKO: Avec le POKéDEX et\n"
	.string "le POKéNAV,\l"
	.string "étudier les POKéMON, c'est mieux!$"

MatchCall_Text_MrStone1::
	.string "M. ROCHARD: Oh? {PLAYER}{KUN}! Je\p"
	.string "suis content de voir\n"
	.string "que le POKéNAV\p"
	.string "fonctionne! D'autres\n"
	.string "personnes y seront\p"
	.string "enregistrées, alors tu\n"
	.string "auras plein de gens à\p"
	.string "appeler! Ça a l'air de\n"
	.string "te faire plaisir! Hum…\p"
	.string "Comment je sais ça? Mais\n"
	.string "je te vois de la\p"
	.string "fenêtre de mon bureau,\n"
	.string "pardi! Ha, ha, ha! A bientôt!$"

MatchCall_Text_MrStone2::
	.string "M. ROCHARD: Oh? {PLAYER}{KUN}! Dis, tu\p"
	.string "as oublié la course que je\n"
	.string "t'ai demandée de faire? J'ai\p"
	.string "besoin que tu donnes ma\n"
	.string "lettre à PIERRE à MYOKARA…\p"
	.string "et que tu apportes le paquet\n"
	.string "au CAPT. POUPE à POIVRESSEL.\p"
	.string "Tu n'as pas oublié, dis? Je\p"
	.string "te laisse, je suis un\n"
	.string "DIRECTEUR très occupé! À bientôt!$"

MatchCall_Text_MrStone3::
	.string "M. ROCHARD: Oh! {PLAYER}{KUN}! Tu as\p"
	.string "vu PIERRE? Une\n"
	.string "récompense t'attend,\p"
	.string "alors! Quand tu seras de\n"
	.string "passage à MEROUVILLE,\p"
	.string "viens à mon bureau. A bientôt!$"

MatchCall_Text_MrStone4::
	.string "M. ROCHARD: Oh! {PLAYER}{KUN}! Tu\p"
	.string "savais que DEVON creusait\n"
	.string "le TUNNEL MERAZON? Mais on\p"
	.string "a dû arrêter pour\n"
	.string "préserver les POKéMON de\p"
	.string "cette zone. Franchement, si\p"
	.string "ça ne tenait qu'à moi… Si\n"
	.string "on s'arrête à ce genre de\l"
	.string "détails, on ne fait plus rien!$"

MatchCall_Text_MrStone5::
	.string "M. ROCHARD: Bonjour,\p"
	.string "{PLAYER}{KUN}! Quelqu'un de\n"
	.string "CLÉMENTI-VILLE m'a dit\p"
	.string "que NORMAN est ton\n"
	.string "père! Tu as de qui tenir!$"

MatchCall_Text_MrStone6::
	.string "M. ROCHARD:\p"
	.string "Comment? Tu as battu\n"
	.string "ton propre père? Mais\p"
	.string "c'est ahurissant! Tu\p"
	.string "n'es pas n'importe\n"
	.string "qui, toi! Ha, ha, ha!$"

MatchCall_Text_MrStone7::
	.string "Allô? DEVON SARL,\n"
	.string "j'écou… {PLAYER}! Bonjour!\l"
	.string "Malheureusement, le\p"
	.string "DIRECTEUR vient de\n"
	.string "s'absenter. Le\p"
	.string "DIRECTEUR est très\n"
	.string "occupé. Comme toi, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "Hein? Comment?\p"
	.string "GROU… Quoi? DON?\p"
	.string "La ligne est\n"
	.string "mauvaise… Je ne\p"
	.string "t'entends plus… BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "Hein? Comment? La\p"
	.string "CAV… Quoi?\p"
	.string "FONDMER? La ligne\n"
	.string "est mauvaise… Je ne\p"
	.string "t'entends plus… BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "M. ROCHARD: {PLAYER}{KUN}! C'est moi! Je\p"
	.string "sais que tu as réalisé toutes\n"
	.string "sortes de choses, mais je n'ai\l"
	.string "pas le temps de me tenir\p"
	.string "informé! Quoi qu'il en soit,\n"
	.string "continue comme ça, je me fie à\p"
	.string "ton jugement. Et si tu as besoin\n"
	.string "de moi, n'hésite pas à appeler.$"

MatchCall_Text_MrStone11::
	.string "M. ROCHARD: … … … … … …\n"
	.string "C'est toi, {PLAYER}{KUN}? Ta voix a\p"
	.string "pris tant d'assurance\n"
	.string "que je ne n'ai pas pu te\p"
	.string "reconnaître! Passe me\n"
	.string "voir à DEVON, à l'occasion!$"
