@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " si joli !$"

GiddyText_SoDarling::
	.string " si adorable !$"

GiddyText_SoRelaxed::
	.string " si apaisant !$"

GiddyText_SoSunny::
	.string " si lumineux !$"

GiddyText_SoDesirable::
	.string " si attirant !$"

GiddyText_SoExciting::
	.string " si passionnant !$"

GiddyText_SoAmusing::
	.string " si amusant !$"

GiddyText_SoMagical::
	.string " si magique !$"

GiddyText_Is::
	.string " est$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "Tu ne trouves pas ?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "J'ai tellement envie de partir !\n"
	.string "Tu connais un bel endroit ?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "J'ai 120 couleurs de crayons !\n"
	.string "C'est chouette, non ?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Ce serait bien de s'envoler\n"
	.string "sur un nuage de bulles, non ?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Quand on écrit sur le sable,\n"
	.string "la mer efface tout. C'est triste.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "À quoi ressemble le fond marin ?\n"
	.string "J'aimerais tant y aller un jour !$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Le soleil couchant te donne-t-il\n"
	.string "envie de rentrer chez toi ?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Allongé dans l'herbe verte…\n"
	.string "Oh, quel bonheur !$"

GiddyText_SecretBasesAreSoWonderful::
	.string "Les BASES SECRÈTES, c'est génial !\n"
	.string "Tu sens cette excitation ?$"
