MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Cette capacité ne peut être\n"
	.string "apprise qu'une fois. Ça te va ?$"

MoveTutor_Text_SwaggerTeach:
	.string "Hé ! Mon POKéMON est le meilleur !\n"
	.string "Il est plus cool que les autres !\p"
	.string "Je me vantais comme ça, en roulant\n"
	.string "des mécaniques, quand le PRÉSIDENT\l"
	.string "m'a passé un savon.\p"
	.string "Ça m'a rabattu le caquet.\p"
	.string "Si tu veux, j'apprendrai\n"
	.string "VANTARDISE à l'un de tes POKéMON.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Quoi, non ? Tu ne peux pas te\n"
	.string "prendre au jeu ?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "D'accord, quel POKéMON veut\n"
	.string "apprendre VANTARDISE ?$"

MoveTutor_Text_SwaggerTaught:
	.string "Je complimenterai mon POKéMON\n"
	.string "sans me vanter, désormais.$"

MoveTutor_Text_RolloutTeach:
	.string "D'ici, on peut aller très loin\n"
	.string "dans cette direction\l"
	.string "sans jamais tourner ?\p"
	.string "Je pourrais même y aller\n"
	.string "en roulant.\p"
	.string "Tu crois que ton POKéMON voudrait\n"
	.string "rouler lui aussi ?\p"
	.string "Je peux lui apprendre ROULADE,\n"
	.string "si tu veux.$"

MoveTutor_Text_RolloutDeclined:
	.string "Ne sois pas timide.\n"
	.string "Allez, on roule !$"

MoveTutor_Text_RolloutWhichMon:
	.string "Héhé, bien sûr ! Ce serait génial\n"
	.string "si ce POKéMON me ressemblait.$"

MoveTutor_Text_RolloutTaught:
	.string "J'adore rouler dans l'herbe.\n"
	.string "Allez, on roule !$"

MoveTutor_Text_FuryCutterTeach:
	.string "Il existe une capacité qui devient\n"
	.string "plus forte à chaque utilisation.\p"
	.string "Elle est de type INSECTE et c'est\n"
	.string "carrément géniale.\p"
	.string "Elle s'appelle TAILLADE.\n"
	.string "Je l'apprends à un POKéMON ?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "On n'est pas sur la même onde.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Youpi !\n"
	.string "Montre-moi quel POKéMON la veut.$"

MoveTutor_Text_FuryCutterTaught:
	.string "Quel frisson de voir si TAILLADE\n"
	.string "continue de toucher sans arrêt !$"

MoveTutor_MimicTeach:
	.string "Ah, jeune enfant !\p"
	.string "Je suis jeune aussi, mais j'imite\n"
	.string "les manières et la voix des aînés\l"
	.string "de cette ville.\p"
	.string "Qu'en dis-tu, jeune enfant ?\n"
	.string "Accepterais-tu si je te proposais\l"
	.string "d'enseigner la capacité COPIE ?$"

MoveTutor_MimicDeclined:
	.string "Oh, flûte ! Je voulais apprendre\n"
	.string "COPIE à ton POKéMON !$"

MoveTutor_Text_MimicWhichMon:
	.string "Hinhin ! Ainsi soit-il !\n"
	.string "Montre-moi le POKéMON\l"
	.string "à qui tu veux l'apprendre.$"

MoveTutor_Text_MimicTaught:
	.string "COPIE est une capacité complexe.\p"
	.string "Sauras-tu l'exécuter aussi bien\n"
	.string "que moi… ?$"

MoveTutor_Text_MetronomeTeach:
	.string "Je veux tout un tas de choses !\n"
	.string "Mais j'ai dépensé tout mon argent…\p"
	.string "Ce serait chouette d'avoir un sort\n"
	.string "qui fait apparaître de l'argent\l"
	.string "quand on remue un doigt, non ?\p"
	.string "Si tu veux, je peux apprendre\n"
	.string "MÉTRONOME à ton POKéMON.\p"
	.string "L'argent n'apparaîtra pas,\n"
	.string "mais il bougera un doigt. Ça va ?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Bien. Je serai là si tu changes\n"
	.string "d'avis.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "D'accord ! Je vais lui apprendre !\n"
	.string "Tu choisis quel POKéMON ?$"

MoveTutor_Text_MetronomeTaught:
	.string "Quand un POKéMON agite son doigt\n"
	.string "comme un MÉTRONOME, toutes sortes\l"
	.string "de bonnes choses arrivent.\p"
	.string "Ce serait chouette de pouvoir\n"
	.string "le faire nous aussi, non ?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Pff ! Ma femme use de PUISSANCE\n"
	.string "CACHÉE pour rester éveillée.\p"
	.string "Elle devrait dormir comme moi,\n"
	.string "et faire BLABLA DODO.\p"
	.string "Je peux apprendre BLABLA DODO\n"
	.string "à ton POKéMON. Ça t'intéresse ?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Bon, très bien. Toi aussi, tu veux\n"
	.string "veiller avec PUISSANCE CACHÉE…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, un enfant qui sait apprécier !\n"
	.string "À quel POKéMON l'apprendre ?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Je n'ai jamais réussi le tour de\n"
	.string "pièce de ma femme.\p"
	.string "Je serais ravi de le réussir, même\n"
	.string "en faisant BLABLA DODO…$"

MoveTutor_Text_SubstituteTeach:
	.string "Quand je contemple le vaste monde\n"
	.string "depuis ce toit…\p"
	.string "Je me dis que ce serait génial\n"
	.string "s'il existait plusieurs versions\l"
	.string "de moi pour vivre toutes ces vies.\p"
	.string "Bien sûr, c'est impossible.\n"
	.string "Hihi…\p"
	.string "Tiens ! Ça te dirait qu'un POKéMON\n"
	.string "apprenne CLONAGE ?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, non ?\p"
	.string "Tu sais, ça permet à un\n"
	.string "POKéMON de créer une copie de lui.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Hihi…\n"
	.string "À quel POKéMON veux-tu que\l"
	.string "j'apprenne CLONAGE ?$"

MoveTutor_Text_SubstituteTaught:
	.string "Nous, les humains, devons profiter\n"
	.string "au maximum de notre propre vie !\p"
	.string "J'espère que tu le feras aussi !$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Je n'en peux plus !\p"
	.string "C'est complètement désespéré !\p"
	.string "Je suis DRESSEUR de type COMBAT,\n"
	.string "alors je n'arrive pas à gagner\l"
	.string "à l'ARÈNE malgré mes efforts !\p"
	.string "Argh ! Pan ! Pan ! Pan !\n"
	.string "Pan ! Pan ! Pan !\p"
	.string "Quoi ? Ne me regarde pas ainsi !\n"
	.string "Je ne frappe que le sol !\p"
	.string "Ou alors, tu veux que j'apprenne\n"
	.string "DYNAMO-POING à ton POKéMON ?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Zut ! Toi aussi, tu te moques ?\n"
	.string "Pan ! Pan ! Pan !$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Quoi ? Vraiment ? Tu es quelqu'un\n"
	.string "de bien ! Quel POKéMON la veut ?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Je veux te voir gagner à l'ARÈNE\n"
	.string "D'AZURIA avec DYNAMO-POING !$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Soupir…\p"
	.string "Le CHAMPION D'ARÈNE est vraiment\n"
	.string "adorable et admirable.\p"
	.string "Mais cela signifie aussi que j'ai\n"
	.string "beaucoup de rivales.\p"
	.string "Son charme est à double tranchant.\n"
	.string "Il ne m'a même pas remarquée.\p"
	.string "Laisse-moi apprendre à ton POKéMON\n"
	.string "la capacité DAMOCLÈS !$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Même toi, tu me rejettes…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "D'accord, à quel POKéMON dois-je\n"
	.string "apprendre DAMOCLÈS ?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Je ne vivrai plus pour l'amour !\n"
	.string "Je vais devenir forte !$"

MoveTutor_Text_ExplosionTeach:
	.string "Pas question de croupir ici\n"
	.string "paumé toute ma vie.\p"
	.string "Tu verras, j'irai en ville et\n"
	.string "je connaîtrai un succès fou.\p"
	.string "Sérieusement, ma popularité va\n"
	.string "EXPLOSER !\p"
	.string "Tu as tout entendu, alors je veux\n"
	.string "l'apprendre à ton POKéMON !$"

MoveTutor_Text_ExplosionDeclined:
	.string "Argh ! Tu refuses parce que\n"
	.string "je vis à la campagne ?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Bien ! Va pour une EXPLOSION !\n"
	.string "Quel POKéMON veut exploser ?$"

MoveTutor_Text_ExplosionTaught:
	.string "J'enseigne EXPLOSION aux POKéMON\n"
	.string "depuis longtemps, mais mon propre\l"
	.string "succès tarde encore à exploser…\p"
	.string "Peut-être qu'au fond, je préfère\n"
	.string "rester ici…$"

MoveTutor_Text_HeadbuttTeach:
	.string "Ce que je fais ?\p"
	.string "Je leur donne un COUP D'BOULE.\p"
	.string "Tu crois que ton POKéMON voudrait\n"
	.string "le faire lui aussi ?\p"
	.string "Je peux lui apprendre COUP D'BOULE\n"
	.string "si tu veux. C'est amusant !$"
	
MoveTutor_Text_HeadbuttWhichMon:
	.string "Héhé, bien sûr ! Ce serait génial\n"
	.string "si ce POKéMON me ressemblait.$"

MoveTutor_Text_HeadbuttDeclined:
	.string "Ne sois pas timide.\n"
	.string "Allez, on se cogne la tête !$"

MoveTutor_Text_HeadbuttTaught:
	.string "Un COUP D'BOULE secoue les arbres.\n"
	.string "Parfois, un POKéMON endormi tombe.$"
