MoveRelearner_Text_WouldLearnNewMoves:
	.string "Salut, je rappelle les capacités.\n"
	.string "Veux-tu en réapprendre ?$"

MoveRelearner_Text_LevelUpMoves:
	.string "Capacités par niveau$"

MoveRelearner_Text_EggMoves:
	.string "Capacités Œuf$"

MoveRelearner_Text_TMMoves:
	.string "Capacités CT$"

MoveRelearner_Text_TutormoveMoves:
	.string "Capacités du Maître$"

MoveRelearner_Text_SeeYa:
	.string "À bientôt !$"

MoveRelearner_Text_AnythingElse:
	.string "Puis-je faire autre chose ?$"

MoveRelearner_Text_ChoosePkmn:
	.string "Choisis un POKéMON.$"

MoveRelearner_Text_HaveNoPkmn:
	.string "Tu n'as aucun POKéMON.$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "Désolé…\n"
	.string "Un ŒUF ne peut rien apprendre.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "Désolé…\p"
	.string "Je n'ai aucune capacité à\n"
	.string "enseigner à ce POKéMON.$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "capacité par niveau$"

MoveRelearner_Text_EggMoveLWR::
	.string "capacité Œuf$"

MoveRelearner_Text_TMMoveLWR::
	.string "capacité CT$"

MoveRelearner_Text_TutorMoveLWR::
	.string "capacité du Maître$"

MoveRelearner_Text_MoveLWR::
	.string "capacité$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "Quelle {STR_VAR_3} ?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "Merci d'avoir fait appel à moi.\n"
	.string "Reviens quand tu veux !$"
