gOtherText_NewName::
	.string "NOUVEAU NOM$"

gNameChoice_Green::
	.string "GREEN$"

gNameChoice_Red::
	.string "RED$"

gNameChoice_Leaf::
	.string "LEAF$"

gNameChoice_Fire::
	.string "FIRE$"

gNameChoice_Gary::
	.string "GARY$"

gNameChoice_Kaz::
	.string "KAZ$"

gNameChoice_Toru::
	.string "TORU$"

gNameChoice_Ash::
	.string "ASH$"

gNameChoice_Kene::
	.string "KENE$"

gNameChoice_Geki::
	.string "GEKI$"

gNameChoice_Jak::
	.string "JAK$"

gNameChoice_Janne::
	.string "JANNE$"

gNameChoice_Jonn::
	.string "JONN$"

gNameChoice_Kamon::
	.string "KAMON$"

gNameChoice_Karl::
	.string "KARL$"

gNameChoice_Taylor::
	.string "TAYLOR$"

gNameChoice_Oscar::
	.string "OSCAR$"

gNameChoice_Hiro::
	.string "HIRO$"

gNameChoice_Max::
	.string "MAX$"

gNameChoice_Jon::
	.string "JON$"

gNameChoice_Ralph::
	.string "RALPH$"

gNameChoice_Kay::
	.string "KAY$"

gNameChoice_Tosh::
	.string "TOSH$"

gNameChoice_Roak::
	.string "ROAK$"

gNameChoice_Omi::
	.string "OMI$"

gNameChoice_Jodi::
	.string "JODI$"

gNameChoice_Amanda::
	.string "AMANDA$"

gNameChoice_Hillary::
	.string "HILLARY$"

gNameChoice_Makey::
	.string "MAKEY$"

gNameChoice_Michi::
	.string "MICHI$"

gNameChoice_Paula::
	.string "PAULA$"

gNameChoice_June::
	.string "JUNE$"

gNameChoice_Cassie::
	.string "CASSIE$"

gNameChoice_Rey::
	.string "REY$"

gNameChoice_Seda::
	.string "SEDA$"

gNameChoice_Kiko::
	.string "KIKO$"

gNameChoice_Mina::
	.string "MINA$"

gNameChoice_Norie::
	.string "NORIE$"

gNameChoice_Sai::
	.string "SAI$"

gNameChoice_Momo::
	.string "MOMO$"

gNameChoice_Suzi::
	.string "SUZI$"

gControlsGuide_Text_Intro::
	.string "Les boutons vont être présentés\n"
	.string "par ordre d'importance.$"

gControlsGuide_Text_DPad::
	.string "Déplace le personnage principal.\n"
	.string "Sert aussi à choisir différentes\n"
	.string "rubriques.$"

gControlsGuide_Text_AButton::
	.string "Sert à confirmer, examiner, parler\n"
	.string "et faire défiler le texte.$"

gControlsGuide_Text_BButton::
	.string "Sert à quitter, annuler un choix\n"
	.string "ou fermer un mode.$"

gControlsGuide_Text_StartButton::
	.string "Appuie sur ce bouton pour ouvrir\n"
	.string "le MENU.$"

gControlsGuide_Text_SelectButton::
	.string "Sert à déplacer des objets et à\n"
	.string "utiliser un objet enregistré.$"

gControlsGuide_Text_LRButtons::
	.string "Si tu as besoin d'aide pour jouer\n"
	.string "ou effectuer une action, appuie\n"
	.string "sur le Bouton L ou R.$"

gOakSpeech_Text_AskPlayerGender::
	.string "Dis-moi. Es-tu un garçon ?\n"
	.string "Ou bien une fille ?$"

gPikachuIntro_Text_Page1::
	.string "Dans le monde où tu t'apprêtes à\n"
	.string "entrer, tu vas vivre une grande\n"
	.string "aventure dont tu seras le héros.\n"
	.string "\n"
	.string "Parle aux gens et examine tout\n"
	.string "où que tu ailles : villes, routes\n"
	.string "ou grottes. Recueille informations\n"
	.string "et indices de toutes parts.$"

gPikachuIntro_Text_Page2::
	.string "De nouvelles voies vont s'ouvrir\n"
	.string "si tu aides, relèves les défis\n"
	.string "et résous les mystères.\n"
	.string "\n"
	.string "Parfois, on te défiera et des\n"
	.string "créatures sauvages t'attaqueront.\n"
	.string "Sois brave et continue d'avancer.$"

gPikachuIntro_Text_Page3::
	.string "Durant ton aventure, nous espérons\n"
	.string "que tu rencontreras toutes sortes\n"
	.string "de gens et gagneras en maturité.\n"
	.string "C'est notre objectif principal.\n"
	.string "\n"
	.string "Appuie sur le Bouton A et laisse\n"
	.string "ton aventure commencer !$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "Bonjour !\n"
	.string "Ravi de te rencontrer !\p"
	.string "Bienvenue dans l'univers POKéMON !\p"
	.string "Je m'appelle CHEN.\p"
	.string "On me surnomme affectueusement\n"
	.string "le PROFESSEUR POKéMON.\p$"

gOakSpeech_Text_ThisWorld::
	.string "Ce monde…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "…est peuplé aux quatre coins par\n"
	.string "des créatures appelées POKéMON.\p$"

gOakSpeech_Text_IStudyPokemon::
	.string "Certains vivent avec les POKéMON.\n"
	.string "D'autres les font combattre.\p"
	.string "Quant à moi…\p"
	.string "J'étudie les POKéMON par métier.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "Mais d'abord, parle-moi un peu de\n"
	.string "toi.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "Commençons par ton nom.\n"
	.string "Comment t'appelles-tu ?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "Bien…\n"
	.string "Tu t'appelles donc {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
	.string "Voici mon petit-fils.\p"
	.string "Il est ton rival depuis que vous\n"
	.string "êtes bébés.\p"
	.string "…Euh, quel est son nom déjà ?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "Le nom de ton rival, c'est… ?$"

gOakSpeech_Text_ConfirmRivalName::
	.string "…Euh, c'est {RIVAL} ?$"

gOakSpeech_Text_RememberRivalsName::
	.string "C'est ça ! Je m'en souviens !\n"
	.string "Il s'appelle {RIVAL} !\p$"

gOakSpeech_Text_LetsGo::
	.string "{PLAYER} !\p"
	.string "Ta propre légende POKéMON est\n"
	.string "sur le point de commencer !\p"
	.string "Rêves et aventures t'attendent\n"
	.string "avec les POKéMON ! En avant !$"
