gText_Oak_Welcome::
	.string "Bonjour! Désolé pour l'attente!\p"
	.string "Bienvenue dans le monde\n"
	.string "des POKéMON!\p"
	.string "Mon nom est CHEN.\p"
	.string "Mais tout le monde ici\n"
	.string "m'appellent le PROFESSEUR POKéMON.\n"
	.string "POKéMON.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "Voici ce qu'on appellent\n"
	.string "un “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "Ce monde est peuplé de créatures\n"
	.string "connus sous le nom de POKéMON.\p"
	.string "Pour certains, les POKéMON sont\n"
	.string	"des animaux domestiques,\p"
	.string	"pour d'autres, ils sont un\n"
	.string	"moyen de combattre.\p"
	.string "Pour ma part\n"
	.string "l'étude des Pokémon est ma profession.\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "Mais avant tout,\n"
	.string	"parle-moi un peu de toi.$"

gText_Oak_BoyOrGirl::
	.string "Maintenant dis-moi.\n"
	.string	"Es-tu un garçon\n"
	.string	"ou une fille?$"

gText_Oak_WhatChallenge::
	.string "Quel niveau de difficulté\n"
	.string "attends-tu?$"

gText_Oak_ChallengeSelected::
	.string "Cela me semble être le\n"
	.string "bon niveau de difficulté!$" 

gText_Oak_WhatsYourName::
	.string "Comment t'appelles-tu?$"

gText_Oak_SoItsPlayer::
	.string "D'accord!\n"
	.string "Donc tu t'appelles {PLAYER}{KUN}?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{KUN}, est-tu prêt?\p"
	.string "Tu es sur le point de vivre\n"
	.string "une grande aventure!\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "Ta quête des Pokémon est\n"
	.string	"sur le point de commencer!\p"
	.string	"Un tout nouveau monde de rêves,\n"
	.string	"d'aventures\l"
	.string	"et de Pokémon t'attend!\p"
	.string	"Bonne chance!\p"
	.string "$"
