gText_Oak_Welcome::
	.string "Bonjour ! Désolé pour l'attente !\p"
	.string "Bienvenue dans le monde des\n"
	.string "POKéMON!\p"
	.string "Mon nom est CHEN.\p"
	.string "Mais on m'appelle le PROFESSEUR\n"
	.string "POKéMON.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "Voici ce qu'on appelle un\n"
	.string "POKéMON.\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "Ce monde est peuplé de créatures\n"
	.string "appelées POKéMON.\p"
	.string "Humains et POKéMON vivent\n"
	.string "ensemble et s'entraident.\p"
	.string "Certains jouent avec les POKéMON,\n"
	.string "d'autres les font combattre.\p"
	.string "Mais nous sommes encore loin de\n"
	.string "tout savoir sur les POKéMON.\p"
	.string "De nombreux mystères subsistent.\n"
	.string "C'est pourquoi je les étudie\l"
	.string "chaque jour.\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "Et toi, qui es-tu?$"

gText_Oak_BoyOrGirl::
	.string "Es-tu un garçon ?\n"
	.string "Ou bien une fille ?$"

gText_Oak_WhatChallenge::
	.string "Quel niveau de difficulté\n"
	.string "souhaites-tu?$"

gText_Oak_ChallengeSelected::
	.string "Ce niveau de difficulté semble\n"
	.string "te convenir parfaitement !$"

gText_Oak_WhatsYourName::
	.string "Et comment t'appelles-tu?$"

gText_Oak_SoItsPlayer::
	.string "Ah ! Tu t'appelles {PLAYER}{KUN} ?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{KUN}, es-tu prêt ?\p"
	.string "Ta propre aventure est sur le\n"
	.string "point de commencer.\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "Joies et épreuves t'attendent.\p"
	.string "Rêves et aventures t'attendent,\n"
	.string "avec les POKéMON ! En avant !\p"
	.string "À plus tard !\p"
	.string "$"
