gText_ObtainedTheItem::
	.string "Obtention : {STR_VAR_2} !$"

gText_TheBagIsFull::
	.string "Le SAC est plein…$"

gText_PutItemInPocket::
	.string "{PLAYER} range {STR_VAR_2}\n"
	.string "dans la POCHE {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} : {STR_VAR_2} !$"

gText_TooBadBagIsFull::
	.string "Quel dommage !\n"
	.string "Le SAC est plein…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} range {STR_VAR_2}\n"
	.string "dans le SAC.$"

gText_ObtainedTheDecor::
	.string "Obtention : {STR_VAR_2} !$"

gText_NoRoomLeftForAnother::
	.string "Quel dommage ! Plus de place pour\n"
	.string "une autre {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} est transféré\n"
	.string "vers le PC.$"

gText_ObtainedTheItems::
	.string "Reçu : {STR_VAR_1} {STR_VAR_2} !$"

gText_PlayerFoundItems::
	.string "{PLAYER}: {STR_VAR_1} {STR_VAR_2}!$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} range les JETONS dans\n"
	.string "la BOÎTE JETONS.$"

gText_FoundXCoins::
	.string "{PLAYER} trouve\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "{PLAYER} trouve\n"
	.string "{STR_VAR_1} {STR_VAR_2} !$"

gText_CoinCaseIsFull::
	.string "Quel dommage !\n"
	.string "La BOÎTE JETONS est pleine…$"

gText_NothingToPutThemIn::
	.string "Quel dommage !\n"
	.string "Rien ne peut les contenir…$"
