Text_BootUpPC:
	.string "{PLAYER} allume le PC.$"

gText_WhichPCShouldBeAccessed::
	.string "À quel PC veux-tu accéder ?$"

gText_AccessedSomeonesPC::
	.string "Accès au PC de QUELQU'UN.$"

gText_StorageSystemOpened::
	.string "Le Stockage POKéMON est ouvert.$"

gText_AccessedPlayersPC::
	.string "Accès au PC de {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Accès au PC de LANETTE.$"

gText_AccessedBillsPC::
	.string "Accès au PC de BILL.$"
