gText_WouldYouLikeToRestYourPkmn::
	.string "Bonjour et bienvenue au\n"
	.string "CENTRE POKéMON.\p"
	.string "Nous soignons tes POKéMON\n"
	.string "et leur rendons tous leurs PV.\p"
	.string "Veux-tu les faire soigner ?$"

gText_IllTakeYourPkmn::
	.string "D'accord, confie-moi tes POKéMON\n"
	.string "quelques instants.$"

gText_RestoredPkmnToFullHealth::
	.string "Merci d'avoir patienté.\p"
	.string "Tes POKéMON ont retrouvé\n"
	.string "tous leurs PV.$"

gText_WeHopeToSeeYouAgain::
	.string "Au plaisir de te revoir !$"

gText_WelcomeCutShort::
	.string "Bonjour et bienvenue au\n"
	.string "CENTRE POKéMON.\p"
	.string "Nous soignons tes POKéMON\n"
	.string "et leur rendons tous leurs PV.\p"
	.string "Veux-tu les faire…$"

gText_NoticesGoldCard::
	.string "C-cette carte…\n"
	.string "Serait-ce… La CARTE OR ?!\p"
	.string "Oh, cet or est éblouissant !\n"
	.string "Les quatre étoiles scintillent !\p"
	.string "J'ai déjà vu des DRESSEURS avec\n"
	.string "une CARTE ARGENT, {PLAYER}, mais\l"
	.string "tu es le premier DRESSEUR que je\l"
	.string "vois avec une CARTE OR !\p"
	.string "D'accord, {PLAYER}, fais-moi\n"
	.string "l'honneur de soigner tes POKéMON !$"

gText_YouWantTheUsual::
	.string "Ravie de te revoir, {PLAYER} !\n"
	.string "Comme d'habitude, n'est-ce pas ?$"

gText_IllTakeYourPkmn2::
	.string "D'accord, confie-moi tes POKéMON\n"
	.string "quelques instants.$"

gText_ThankYouForWaiting::
	.string "Merci d'avoir patienté.$"

gText_WeHopeToSeeYouAgain2::
	.string "Au plaisir de te revoir !$"

gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge
    .string "Désolée, mais tu joues avec\n"
    .string "le défi CENTRE POKéMON !\p"
    .string "Bonne chance !{PAUSE_UNTIL_PRESS}$"
