gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRCH : Ah, {PLAYER}{KUN} !\p"
	.string "Tu veux savoir où en est\n"
	.string "ton POKéDEX ?$"

gBirchDexRatingText_Cancel::
	.string "Hmm ? Oh, tu n'en as pas attrapé\n"
	.string "assez pour que ça vaille le coup.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmm…\p"
	.string "Tu as donc vu {STR_VAR_1} POKéMON,\n"
	.string "et tu en as attrapé {STR_VAR_2}…$"

gBirchDexRatingText_LessThan10::
	.string "Explore bien les hautes herbes\n"
	.string "et cherche bien les POKéMON.$"

gBirchDexRatingText_LessThan20::
	.string "Tu commences à prendre le coup\n"
	.string "de main. Mais ça va se corser.$"

gBirchDexRatingText_LessThan30::
	.string "Certains POKéMON n'apparaissent\n"
	.string "que dans des zones précises.\l"
	.string "Tu dois persévérer.$"

gBirchDexRatingText_LessThan40::
	.string "Bon, il manque encore du contenu,\n"
	.string "mais ça commence vraiment à\l"
	.string "ressembler à un POKéDEX.$"

gBirchDexRatingText_LessThan50::
	.string "Ça avance plutôt bien.\n"
	.string "Continue tes efforts.$"

gBirchDexRatingText_LessThan60::
	.string "Utilises-tu tes CANNES À PÊCHE ?\n"
	.string "La mer regorge de POKéMON.$"

gBirchDexRatingText_LessThan70::
	.string "En plus de les attraper,\n"
	.string "fais-les aussi évoluer !$"

gBirchDexRatingText_LessThan80::
	.string "Ce POKéDEX promet d'être\n"
	.string "fantastique.\l"
	.string "C'est mon pressentiment.$"

gBirchDexRatingText_LessThan90::
	.string "Tu en as réuni autant…\n"
	.string "Ton talent est remarquable !$"

gBirchDexRatingText_LessThan100::
	.string "As-tu visité le PARC SAFARI ?\p"
	.string "Il paraît que certains POKéMON ne\n"
	.string "peuvent être attrapés que là-bas.$"

gBirchDexRatingText_LessThan110::
	.string "Tu as enfin atteint\n"
	.string "la barre des 100 espèces.\p"
	.string "Ce POKéDEX est impressionnant !$"

gBirchDexRatingText_LessThan120::
	.string "Des POKéMON se cachent peut-être\n"
	.string "derrière des rochers à ÉCLATE-ROC.$"

gBirchDexRatingText_LessThan130::
	.string "Tu devrais avoir d'autres POKéMON\n"
	.string "en faisant des échanges.$"

gBirchDexRatingText_LessThan140::
	.string "Certains POKéMON évolueraient\n"
	.string "quand ils adorent leur\l"
	.string "DRESSEUR.$"

gBirchDexRatingText_LessThan150::
	.string "J'ignorais qu'il existait autant\n"
	.string "d'espèces de POKéMON dans\l"
	.string "la région de HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "Des POKéMON apparaissent parfois\n"
	.string "en masse, lors d'invasions.\p"
	.string "Ne laisse pas passer ce genre\n"
	.string "d'occasion.$"

gBirchDexRatingText_LessThan170::
	.string "Ton POKéDEX donne un excellent\n"
	.string "aperçu des POKéMON de la région\l"
	.string "de HOENN.$"

gBirchDexRatingText_LessThan180::
	.string "Tu as déjà l'étoffe d'un\n"
	.string "PROFESSEUR POKéMON, et même d'un\l"
	.string "très bon !$"

gBirchDexRatingText_LessThan190::
	.string "Avec un POKéDEX aussi complet,\n"
	.string "tu es un véritable expert !$"

gBirchDexRatingText_LessThan200::
	.string "Tu es tout près de terminer\n"
	.string "ce POKéDEX.\l"
	.string "Je le sens au fond de moi !$"

gBirchDexRatingText_DexCompleted::
	.string "Félicitations !\n"
	.string "Ton POKéDEX est complet !$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmm…\n"
	.string "À l'échelle nationale…\p"
	.string "Tu as vu {STR_VAR_1} POKéMON,\n"
	.string "et tu en as attrapé {STR_VAR_2}…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "CHEN : Ravi de te voir !\n"
	.string "Où en est ton POKéDEX ?\p"
	.string "Voyons cela de plus près.$"

PokedexRating_Text_SeenXOwnedY::
	.string "Voici les progrès réalisés\n"
	.string "dans ton POKéDEX :\p"
	.string "{STR_VAR_1} POKéMON vus et\n"
	.string "{STR_VAR_2} POKéMON possédés.\p"
	.string "{FONT_NORMAL}Évaluation du PROF. CHEN :$"

PokedexRating_Text_LessThan10::
	.string "Tu as encore beaucoup à faire.\p"
	.string "Fouille chaque carré d'herbe\n"
	.string "pour y chercher des POKéMON !$"

PokedexRating_Text_LessThan20::
	.string "On dirait que tu es sur\n"
	.string "la bonne voie !\p"
	.string "J'ai confié la CS FLASH à l'un de\n"
	.string "mes assistants. Va la chercher !$"

PokedexRating_Text_LessThan30::
	.string "Ton POKéDEX manque encore un peu\n"
	.string "de contenu !\p"
	.string "Essaie d'attraper d'autres espèces\n"
	.string "de POKéMON !$"

PokedexRating_Text_LessThan40::
	.string "Bien, tes efforts sont évidents !\n"
	.string "Continue ainsi !\p"
	.string "Un de mes assistants garde un\n"
	.string "CHERCH'OBJET. Va le récupérer !$"

PokedexRating_Text_LessThan50::
	.string "Ton POKéDEX avance vraiment\n"
	.string "bien !\p"
	.string "Un de mes assistants garde une\n"
	.string "PIÈCE RUNE. Va la récupérer !$"

PokedexRating_Text_LessThan60::
	.string "Ah, tu as enfin dépassé les 50\n"
	.string "espèces !\p"
	.string "Un de mes assistants garde un\n"
	.string "MULTI EXP. Va le chercher !$"

PokedexRating_Text_LessThan70::
	.string "Hoho ! Ce POKéDEX devient\n"
	.string "tout à fait respectable !$"

PokedexRating_Text_LessThan80::
	.string "Très bien !\p"
	.string "Je pense que tu trouveras plus\n"
	.string "de POKéMON en allant pêcher !$"

PokedexRating_Text_LessThan90::
	.string "Merveilleux ! Laisse-moi deviner…\n"
	.string "Tu aimes collectionner, pas vrai ?$"

PokedexRating_Text_LessThan100::
	.string "Je suis impressionné !\n"
	.string "Cela n'a pas dû être facile !$"

PokedexRating_Text_LessThan110::
	.string "Tu as enfin recensé 100 espèces !\n"
	.string "Ton talent est incroyable !$"

PokedexRating_Text_LessThan120::
	.string "Tu as même des formes évoluées\n"
	.string "de POKéMON ! Super !$"

PokedexRating_Text_LessThan130::
	.string "Excellent ! Fais des échanges avec\n"
	.string "tes amis pour en obtenir plus !$"

PokedexRating_Text_LessThan140::
	.string "Exceptionnel !\n"
	.string "Tu es devenu un vrai expert !$"

PokedexRating_Text_LessThan150::
	.string "Je n'ai plus rien à ajouter !\n"
	.string "Le PROFESSEUR POKéMON, c'est toi !$"

PokedexRating_Text_Complete::
	.string "Ton POKéDEX est enfin complet !\n"
	.string "Félicitations !!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "Et pour ton POKéDEX NATIONAL :\p"
	.string "{STR_VAR_1} POKéMON vus et\n"
	.string "{STR_VAR_2} POKéMON possédés.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "J'ai hâte de te voir remplir\n"
	.string "le POKéDEX NATIONAL !$"

PokedexRating_Text_YouveCompletedDex::
	.string "Enfin…\p"
	.string "Tu as enfin terminé le\n"
	.string "POKéDEX !\p"
	.string "C'est magnifique !\n"
	.string "Quel exploit fantastique !$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr !$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Merci, {PLAYER} !\n"
	.string "Merci du fond du cœur !\l"
	.string "Tu as réalisé mon rêve !$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "CHEN : Ah, bienvenue !\p"
	.string "Dis-moi, où en est ton\n"
	.string "POKéDEX ?\p"
	.string "Wahaha !\p"
	.string "En fait, je le sais déjà, mais\n"
	.string "j'adore quand même le voir !\p"
	.string "Voyons cela…$"

@ HnS (mostly directly copied from HGSS)

gElmDexRatingText_GoFindMrPokemon::
	.string "PROF. ORME : Ah, {PLAYER}{KUN} !\p"
	.string "As-tu trouvé la maison de\n"
	.string "M. POKéMON, sur la ROUTE 30 ?\p"
	.string "Tu ne peux pas la rater !$"

gElmDexRatingText_Robbery::
	.string "PROF. ORME : {PLAYER}{KUN} !\p"
	.string "Reviens vite ! Quelque chose\n"
	.string "de terrible est arrivé !$"

gElmDexRatingText_AreYouCurious::
	.string "PROF. ORME : Ah, {PLAYER}{KUN} !\p"
	.string "Tu veux savoir où en est\n"
	.string "ton POKéDEX ?$"

gElmDexRatingText_AreYouCuriousNational::
	.string "PROF. ORME : Ah, {PLAYER}{KUN} !\p"
	.string "Tu veux savoir où en est ton\n"
	.string "POKéDEX NATIONAL ?$"

gJohtoDexRatingText_LessThan10::
	.string "Cherche dans les hautes herbes !$"

gJohtoDexRatingText_LessThan20::
	.string "Bien. Tu maîtrises désormais\n"
	.string "les POKé BALLS.$"

gJohtoDexRatingText_LessThan35::
	.string "Tu te débrouilles vraiment bien,\n"
	.string "mais la route est encore longue.$"

gJohtoDexRatingText_LessThan50::
	.string "Hmm, tu attrapes des POKéMON à\n"
	.string "un bon rythme !$"

gJohtoDexRatingText_LessThan65::
	.string "Tu fais des efforts, je le vois.\n"
	.string "Ton POKéDEX prend forme.$"

gJohtoDexRatingText_LessThan80::
	.string "Tu les entraînes bien. Tu sais que\n"
	.string "certains POKéMON n'évoluent pas\p"
	.string "en combattant, n'est-ce pas ?$"

gJohtoDexRatingText_LessThan95::
	.string "As-tu une CANNE À PÊCHE ?\n"
	.string "Certains POKéMON ne peuvent être\p"
	.string "trouvés qu'en pêchant !$"

gJohtoDexRatingText_LessThan110::
	.string "Excellent ! Tu sembles doué pour\n"
	.string "les collections !$"

gJohtoDexRatingText_LessThan125::
	.string "Certains POKéMON n'apparaissent\n"
	.string "qu'à certaines heures.$"

gJohtoDexRatingText_LessThan140::
	.string "Ton POKéDEX se remplit vraiment.\n"
	.string "Continue comme ça !$"

gJohtoDexRatingText_LessThan155::
	.string "Je suis impressionné.\n"
	.string "Tu fais évoluer les POKéMON, pas\p"
	.string "que les attraper.$"

gJohtoDexRatingText_LessThan170::
	.string "Si tu apprends à bien utiliser les\n"
	.string "BALLS spéciales créées par FARGAS,\p"
	.string "tu attraperas plus facilement\n"
	.string "les POKéMON !$"

gJohtoDexRatingText_LessThan185::
	.string "Échanger des POKéMON permet aussi\n"
	.string "d'échanger des informations. Tes\p"
	.string "amis peuvent vraiment t'aider !$"

gJohtoDexRatingText_LessThan200::
	.string "Échanges-tu tes POKéMON ?\n"
	.string "C'est difficile d'y arriver seul !$"

gJohtoDexRatingText_LessThan215::
	.string "Ouah ! Tu as atteint les 200 !\n"
	.string "Ton POKéDEX est superbe !$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan230::
	.string "Tu as prouvé ta valeur.\n"
    .string "Il n'y a aucun souci à se faire.\p"
    .string "Continue d'attraper des POKéMON\n"
    .string "comme tu l'as fait jusqu'ici.$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan245::
	.string "Ton POKéDEX est en bonne voie\n"
	.string "pour être rempli.\p"
	.string "Ce POKéDEX peut être vu comme\n"
	.string "le journal de ton aventure.$"

gJohtoDexRatingText_LessThan260::
	.string "Tu as trouvé tant de POKéMON !\n"
	.string "Tu as bien aidé mes recherches !$"

gJohtoDexRatingText_LessThan275::
	.string "Magnifique ! Tu as le potentiel\n"
	.string "pour devenir un jour un grand\p"
	.string "PROFESSEUR POKéMON !$"

gJohtoDexRatingText_LessThanMaxDex::
	.string "Ton POKéDEX est incroyable !\n"
	.string "Tu peux passer professionnel !$"

gJohtoDexRatingText_Complete::
	.string "Ouah !\n"
	.string "Le POKéDEX de JOHTO est complet !\p"
	.string "Grâce à toi, {PLAYER},\n"
	.string "le POKéDEX de JOHTO est complet !\p"
	.string "Ouah…\n"
	.string "Tu as fait un travail incroyable !$"

gNationalDexRatingText_LessThan100::
	.string "Le but est peut-être encore loin,\n"
	.string "mais n'abandonne pas ! Continue !$"

gNationalDexRatingText_LessThan150::
	.string "N'oublie pas : certains POKéMON\n"
	.string "ne sortent qu'à certaines heures !$"

gNationalDexRatingText_LessThan200::
	.string "Si tu brises des rochers,\n"
	.string "des POKéMON cachés pourraient\p"
	.string "en jaillir !$"

gNationalDexRatingText_LessThan250::
	.string "C'est merveilleux que tu aies pu\n"
	.string "réunir autant de POKéMON !\p"
	.string "La route est longue. Continue ton\n"
	.string "excellent travail !$"

gNationalDexRatingText_LessThan300::
	.string "Avec COUP D'BOULE sur un arbre,\n"
	.string "un POKéMON peut tomber !$"

gNationalDexRatingText_LessThan350::
	.string "Beaucoup de POKéMON absents de\n"
	.string "la région de JOHTO se réunissent\p"
	.string "au PARC SAFARI.$"

gNationalDexRatingText_LessThan400::
@	.string "Music on the radio might also\n"
@	.string "entice POKéMON to leap out$"
	.string "Des lieux cachés dans le monde\n"
	.string "abritent des POKéMON rares\p"
	.string "et insolites. Essaie de tous\n"
	.string "les trouver !$"

gNationalDexRatingText_LessThan435::
	.string "Ouah, quel chemin parcouru… !\n"
	.string "Je suis même un peu surpris !$"

gNationalDexRatingText_LessThan465::
	.string "C'est un moment décisif !\n"
	.string "Tu ne dois pas te décourager !$"

gNationalDexRatingText_LessThan475::
	.string "Encore un petit effort !\n"
	.string "J'attends beaucoup de toi !$"

gNationalDexRatingText_LessThanMaxDex::
	.string "De toute ma vie, je n'ai jamais vu\n"
	.string "un DRESSEUR aussi incroyable !$"

gNationalDexRatingText_Complete::
	.string "Excellent ! Voilà un superbe\n"
	.string "POKéDEX NATIONAL !\p"
	.string "Ouah…{PAUSE 10}\p"
	.string "Tu as merveilleusement répondu\n"
	.string "à mes attentes !\p"
	.string "Tu les as dépassées, {PLAYER}.\n"
	.string "Tu es un DRESSEUR incroyable !\p"
	.string "Merci, {PLAYER} !$"
