Questionnaire_Text_FillOut::
	.string "Il y a un questionnaire.\n"
	.string "Veux-tu y répondre ?$"

Questionnaire_Text_ThankYou::
	.string "Merci d'avoir pris le temps de\n"
	.string "répondre à notre questionnaire.\p"
	.string "Tes réponses nous serviront\n"
	.string "à l'avenir.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, bonjour !\n"
	.string "Tu connais ces mots ?\p"
	.string "Alors tu dois connaître le\n"
	.string "CADEAU MYSTÈRE.\p"
	.string "Désormais, tu pourras recevoir\n"
	.string "des CADEAUX MYSTÈRE !$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Après avoir sauvegardé, tu pourras\n"
	.string "accéder au CADEAU MYSTÈRE.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Oh, bonjour !\n"
	.string "Tu connais ces mots ?\p"
	.string "Alors tu dois connaître\n"
	.string "l'ÉVÈNEMENT MYSTÈRE.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Après avoir sauvegardé, tu pourras\n"
	.string "accéder à l'ÉVÈNEMENT MYSTÈRE.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Merci d'utiliser le système\n"
	.string "ÉVÈNEMENT MYSTÈRE.\p"
	.string "Tu dois être {PLAYER}.\n"
	.string "Un ticket t'attend ici.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Il semble utilisable au port de\n"
	.string "NÉNUCRIQUE.\p"
	.string "Pourquoi ne pas essayer pour voir\n"
	.string "ce qui t'attend ?$"
