	.align 2
gText_ConfirmSave::
	.string "Veux-tu sauvegarder la partie ?$"

gText_AlreadySavedFile::
	.string "Une sauvegarde existe déjà.\n"
	.string "Veux-tu l'écraser ?$"

gText_SavingDontTurnOff::
	.string "SAUVEGARDE…\n"
	.string "N'ÉTEINS PAS LA CONSOLE.$"

gText_PlayerSavedGame::
	.string "{PLAYER} sauvegarde la partie.$"

gText_DifferentSaveFile::
	.string "ATTENTION !\p"
	.string "Une autre partie est déjà\n"
	.string "sauvegardée.\p"
	.string "Si tu sauvegardes, toute son\n"
	.string "aventure, ses objets et ses\l"
	.string "POKéMON seront perdus.\p"
	.string "Veux-tu vraiment sauvegarder\n"
	.string "et écraser l'autre partie ?$"

gText_SaveError::
	.string "Erreur de sauvegarde.\p"
	.string "Remplace la mémoire\n"
	.string "de sauvegarde.$"

gText_SavingDontTurnOffPower::
	.string "SAUVEGARDE…\n"
	.string "N'ÉTEINS PAS LA CONSOLE.$"
