SecretBase_Text_Trainer0Intro:
	.string "Tu as déjà créé une BASE SECRÈTE ?\p"
	.string "J'ai cherché partout avant de\n"
	.string "choisir cet endroit.\p"
	.string "Puisque tu es là, que dirais-tu\n"
	.string "d'un combat ?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "D'accord !\n"
	.string "Nous voilà !$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Hein ?\n"
	.string "Oh, tu ne peux pas maintenant…$"

SecretBase_Text_Trainer0Defeated::
	.string "Aaargh ! Tu es trop fort !\n"
	.string "Ma défaite… Garde-la secrète !$"

SecretBase_Text_Trainer0PostBattle:
	.string "Tu aimes ma BASE SECRÈTE ?\n"
	.string "Reviens me voir demain.$"

SecretBase_Text_Trainer0PreChampion:
	.string "Tu as déjà créé une BASE SECRÈTE ?\p"
	.string "J'ai cherché partout avant de\n"
	.string "choisir cet endroit.\p"
	.string "Fais comme chez toi !$"

SecretBase_Text_Trainer5Intro:
	.string "Il existe plein d'endroits où\n"
	.string "installer une BASE SECRÈTE.\p"
	.string "Mais je préfère celui-ci.\n"
	.string "Tu ne le trouves pas sympa ?\p"
	.string "Oh, ça te dirait de combattre ?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "D'accord, c'est parti !$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Oh…\n"
	.string "Pas maintenant ? D'accord.$"

SecretBase_Text_Trainer5Defeated::
	.string "Hmm… Nous avons perdu…\n"
	.string "Mais ne le dis à personne !\l"
	.string "C'est strictement confidentiel !$"

SecretBase_Text_Trainer5PostBattle:
	.string "Si tu repasses dans le coin,\n"
	.string "j'espère que tu viendras me voir.$"

SecretBase_Text_Trainer5PreChampion:
	.string "Il existe plein de lieux où créer\n"
	.string "une BASE SECRÈTE.\p"
	.string "Mais je préfère celui-ci.\n"
	.string "Tu ne le trouves pas sympa ?$"

SecretBase_Text_Trainer1Intro:
	.string "Cet endroit est très prisé.\n"
	.string "Il est toujours occupé.\p"
	.string "Oh ! Tu pensais toi aussi\n"
	.string "t'installer ici ?\p"
	.string "Je te cède cet endroit\n"
	.string "si tu arrives à me battre.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "D'accord !\n"
	.string "Je vais défendre ma BASE SECRÈTE !$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Hein ? Vraiment ?\n"
	.string "Cet endroit ne t'intéresse pas ?$"

SecretBase_Text_Trainer1Defeated::
	.string "Je ne peux plus continuer !\n"
	.string "Je me rends !$"

SecretBase_Text_Trainer1PostBattle:
	.string "Le jour où je déménagerai,\n"
	.string "cet endroit sera à toi !$"

SecretBase_Text_Trainer1PreChampion:
	.string "Cet endroit est très prisé.\n"
	.string "Il est toujours occupé.\p"
	.string "J'ai attendu qu'il se libère.\n"
	.string "Enfin, j'ai pu m'y installer !$"

SecretBase_Text_Trainer6Intro:
	.string "Bienvenue dans mon LABO POKéMON.\p"
	.string "J'y étudie les combats dans le\n"
	.string "grand secret.\p"
	.string "Veux-tu mesurer ma force ?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "Je vais tout donner !$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Oh.\n"
	.string "Une autre fois, alors !$"

SecretBase_Text_Trainer6Defeated::
	.string "Hmm… J'ai encore du chemin.\n"
	.string "Je dois étudier davantage.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Merci d'avoir combattu avec moi.\n"
	.string "Reviens demain, s'il te plaît.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Bienvenue dans mon LABO POKéMON.\p"
	.string "J'y étudie les combats dans le\n"
	.string "grand secret.$"

SecretBase_Text_Trainer2Intro:
	.string "Les grandes demeures sont belles,\n"
	.string "mais je préfère ce lieu.\p"
	.string "J'aime que toutes sortes de gens\n"
	.string "viennent me voir.\p"
	.string "Alors, ça te dirait de combattre ?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "Voilà qui me plaît !$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "Appelle-moi quand tu seras prêt !$"

SecretBase_Text_Trainer2Defeated::
	.string "Ah ! J'ai perdu !\n"
	.string "Mais combattre reste amusant !$"

SecretBase_Text_Trainer2PostBattle:
	.string "Bon, je devrais aller acheter des\n"
	.string "décorations et des meubles.\p"
	.string "Je veux que ma BASE SECRÈTE soit\n"
	.string "un endroit agréable pour tous.$"

SecretBase_Text_Trainer2PreChampion:
	.string "Les grandes demeures sont belles,\n"
	.string "mais je préfère ce lieu.\p"
	.string "J'aime que toutes sortes de gens\n"
	.string "viennent me voir.$"

SecretBase_Text_Trainer7Intro:
	.string "J'adore acheter des décorations\n"
	.string "et des meubles.\p"
	.string "J'aime tout autant élever des\n"
	.string "POKéMON.\p"
	.string "Aurais-tu l'amabilité de combattre\n"
	.string "mes POKéMON ?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Merci.\n"
	.string "Commençons, veux-tu ?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Oh.\n"
	.string "Quelle déception…$"

SecretBase_Text_Trainer7Defeated::
	.string "Je m'incline…$"

SecretBase_Text_Trainer7PostBattle:
	.string "Ce fut très amusant !\n"
	.string "Je vais faire les boutiques.$"

SecretBase_Text_Trainer7PreChampion:
	.string "J'adore acheter des décorations\n"
	.string "et des meubles.\p"
	.string "J'aime tout autant élever des\n"
	.string "POKéMON.$"

SecretBase_Text_Trainer3Intro:
	.string "Certains créent leur BASE SECRÈTE\n"
	.string "dans des endroits bien cachés.\l"
	.string "Ils veulent se cacher ou quoi ?\p"
	.string "Mais puisque tu m'as trouvé, si on\n"
	.string "se battait ?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "Je ne tomberai pas facilement !$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Oh… Serais-tu fatigué d'avoir\n"
	.string "cherché cet endroit ?$"

SecretBase_Text_Trainer3Defeated::
	.string "Je suis tombé…$"

SecretBase_Text_Trainer3PostBattle:
	.string "Où est ta BASE SECRÈTE ?\n"
	.string "Je devrais venir te voir.$"

SecretBase_Text_Trainer3PreChampion:
	.string "Certains créent leur BASE SECRÈTE\n"
	.string "dans des endroits bien cachés.\l"
	.string "Ils veulent se cacher ou quoi ?$"

SecretBase_Text_Trainer8Intro:
	.string "On m'a dit qu'on pouvait obtenir\n"
	.string "des décorations de mille façons.\p"
	.string "Faisons la course : qui aura\n"
	.string "les plus beaux meubles et décos ?\p"
	.string "En attendant, on se bat ?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "C'est ma BASE SECRÈTE.\n"
	.string "Je ne peux pas perdre !$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Je t'affronterai quand tu veux.$"

SecretBase_Text_Trainer8Defeated::
	.string "Hein ?\n"
	.string "Je viens de perdre ?$"

SecretBase_Text_Trainer8PostBattle:
	.string "Pour les décos, je ne perdrai pas.\n"
	.string "Reviens me voir !$"

SecretBase_Text_Trainer8PreChampion:
	.string "On m'a dit qu'on pouvait obtenir\n"
	.string "des décorations de mille façons.\p"
	.string "Faisons la course : qui aura\n"
	.string "les plus beaux meubles et décos ?$"

SecretBase_Text_Trainer4Intro:
	.string "J'ai trouvé un lieu qui me plaît\n"
	.string "et l'ai décoré comme je l'aime.\p"
	.string "J'élève mon POKéMON favori pour\n"
	.string "être plus fort avec lui.\p"
	.string "Voilà ce que je fais.\n"
	.string "Tu veux te battre contre moi ?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Montre-moi de quoi tu es capable !$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Il y a sans doute des jours où tu\n"
	.string "n'as pas envie.$"

SecretBase_Text_Trainer4Defeated::
	.string "Je sais maintenant ce que tu vaux.$"

SecretBase_Text_Trainer4PostBattle:
	.string "Nous pouvons devenir plus forts.\n"
	.string "Continuons nos efforts !$"

SecretBase_Text_Trainer4PreChampion:
	.string "J'ai trouvé un lieu qui me plaît\n"
	.string "et l'ai décoré comme je l'aime.\p"
	.string "J'élève mon POKéMON favori pour\n"
	.string "être plus fort avec lui.\p"
	.string "Chaque journée est magnifique.$"

SecretBase_Text_Trainer9Intro:
	.string "On apprend beaucoup sur le goût\n"
	.string "et le sens esthétique des gens en\l"
	.string "observant leurs décorations et\l"
	.string "la façon dont ils les exposent.\p"
	.string "Que penses-tu de mon goût ?\n"
	.string "Tu en restes sans voix ?\p"
	.string "Tu veux voir mon style au combat ?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "Pas question de me retenir !$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Je montrerai volontiers mon style\n"
	.string "quand tu voudras.$"

SecretBase_Text_Trainer9Defeated::
	.string "Tu as un talent exceptionnel !\n"
	.string "Ta puissance semble sans limites…$"

SecretBase_Text_Trainer9PostBattle:
	.string "Qu'as-tu pensé de mon style ?\n"
	.string "Je vais continuer à le peaufiner !$"

SecretBase_Text_Trainer9PreChampion:
	.string "On apprend beaucoup sur le goût\n"
	.string "et le sens esthétique des gens en\l"
	.string "observant leurs décorations et\l"
	.string "la façon dont ils les exposent.\p"
	.string "Que penses-tu de mon goût ?\n"
	.string "Tu en restes sans voix ?$"
