ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Tu comptes t'aventurer au fond\n"
	.string "de cette grotte ?\p"
	.string "Rapporte-moi du SEL TRÉFONDS et\n"
	.string "des COQUILLESTRÉFONDS !\p"
	.string "Je pourrai te fabriquer un objet\n"
	.string "avec ces ingrédients.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Apporte-moi quatre exemplaires\n"
	.string "de SEL et de COQUILLESTRÉFONDS,\l"
	.string "je ferai un GRELOT COQUE…\p"
	.string "Tu peux trouver ces ingrédients\n"
	.string "tous les jours.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh ! SEL et COQUILLESTRÉFONDS !\n"
	.string "Et en quantité suffisante !\p"
	.string "Veux-tu que je te fabrique\n"
	.string "un GRELOT COQUE avec ?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Très bien ! Je vais te fabriquer\n"
	.string "un GRELOT COQUE sur-le-champ.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Voilà ! C'est terminé !$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Fais-le tenir à un POKéMON.\n"
	.string "Il va l'adorer, c'est certain.\p"
	.string "Le son du GRELOT COQUE…\n"
	.string "Il est tout simplement sublime !\p"
	.string "Tu peux trouver ses composants\n"
	.string "je pourrai donc en refaire.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… Vraiment…\n"
	.string "Je voulais faire un GRELOT COQUE…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "Ton SAC n'a pas assez de place\n"
	.string "pour que je puisse le fabriquer.\p"
	.string "Fais de la place puis reviens\n"
	.string "un GRELOT COQUE.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Il y avait du SEL TRÉFONDS ici.\n"
	.string "Mais il ne reste plus rien.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Il y avait une COQUILLETRÉFONDS.\n"
	.string "Mais il ne reste plus rien.$"
