Route102_Text_CalvinIntro:
	.string "Si tu as un POKéMON avec toi, tu\n"
	.string "es officiellement un DRESSEUR de\l"
	.string "Tu ne peux pas refuser mon défi!$"

Route102_Text_CalvinDefeated:
	.string "Grrrr, j'ai perdu… J'aurais dû\n"
	.string "davantage entraîner mon POKéMON…$"

Route102_Text_CalvinPostBattle:
	.string "Dis, toi. T'aurais pu me le dire\n"
	.string "avant, que tu avais un tel niveau!$"

Route102_Text_CalvinRegister:
	.string "Je me suis beaucoup entraîné\n"
	.string "depuis notre dernière rencontre.\p"
	.string "Je voudrais t'affronter encore,\n"
	.string "tu m'enregistres dans ton POKéNAV?$"

Route102_Text_CalvinRegisterShort:
	.string "Je voudrais t'affronter encore,\n"
	.string "tu m'enregistres dans ton POKéNAV?$"

Route102_Text_CalvinRematchIntro:
	.string "Depuis que j'ai perdu contre toi,\n"
	.string "je n'ai pas cessé de m'entraîner.\l"
	.string "Tu ne peux pas refuser mon défi!$"

Route102_Text_CalvinRematchDefeated:
	.string "Grrrr, j'ai perdu… Mon\n"
	.string "entraînement est-il mauvais?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Si tu t'améliores, je\n"
	.string "m'améliorerai aussi.$"

Route102_Text_AllenIntro:
	.string "Tu viens de devenir DRESSEUR? On\n"
	.string "est tous les deux des débutants!$"

Route102_Text_AllenDefeated:
	.string "Je voulais me mesurer à toi\n"
	.string "car je pensais pouvoir te battre…$"

Route102_Text_AllenPostBattle:
	.string "Je n'ai même pas gagné une seule\n"
	.string "J'aimerais gagner bientôt...$"

Route102_Text_RickIntro:
	.string "Ah, ah! Nos regards se sont\n"
	.string "Je t'emmène avec mon BUG POKéMON!$"

Route102_Text_RickDefeated:
	.string "En bas et en dehors!$"

Route102_Text_RickPostBattle:
	.string "Si tu fixes ton regard sur un\n"
	.string "C'est une règle!$"

Route102_Text_TianaIntro:
	.string "Je vais continuer à gagner pour\n"
	.string "devenir le meilleur DRESSEUR.\p"
	.string "Fais-moi avancer dans ma carrière!$"

Route102_Text_TianaDefeated:
	.string "C'est moi qui lance ta carrière…$"

Route102_Text_TianaPostBattle:
	.string "Pour prendre le chemin de la\n"
	.string "Je dois attraper plus de POKéMON.$"

Route103_Text_DaisyIntro:
	.string "Ne sens-tu pas le\n"
	.string "parfum de la défaite?$"

Route103_Text_DaisyDefeated:
	.string "Notre parfum ne t'a pas distraite…$"

Route103_Text_DaisyPostBattle:
	.string "L'aromathérapie utilise les\n"
	.string "parfums pour apaiser l'esprit.$"

Route103_Text_AmyIntro:
	.string "EVE: Je suis EVE. Et\n"
	.string "voici ma petite sœur,\l"
	.string "AWA. On combat ensemble!$"

Route103_Text_AmyDefeated:
	.string "EVE: Oooh, on a perdu.$"

Route103_Text_AmyPostBattle:
	.string "EVE: Il faut penser à\n"
	.string "plein de choses quand tu te\l"
	.string "bats contre deux DRESSEURS.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "EVE: Oh, tu n'as qu'un seul\n"
	.string "POKéMON avec toi. Tu ne vas\l"
	.string "pas pouvoir nous affronter.$"

Route103_Text_LivIntro:
	.string "AWA: On se bat\n"
	.string "ensemble, comme une équipe.$"

Route103_Text_LivDefeated:
	.string "AWA: Oh, on a perdu, grande sœur…$"

Route103_Text_LivPostBattle:
	.string "AWA: On fonctionne très bien\n"
	.string "ensemble, ma grande sœur et\p"
	.string "moi… Mais on a quand même perdu…$"

Route103_Text_AmyLivRegister:
	.string "AWA: Nous sommes bien meilleures…\n"
	.string "C'est vrai, la prochaine fois!$"

Route103_Text_LivNotEnoughPokemon:
	.string "AWA: Si tu veux te battre contre\n"
	.string "nous, il faut que tu aies deux\l"
	.string "POKéMON! Sinon, ce ne serait pas!$"

Route103_Text_AmyRematchIntro:
	.string "EVE: Je suis EVE. Et\n"
	.string "voici ma petite sœur,\l"
	.string "AWA. On combat ensemble!$"

Route103_Text_AmyRematchDefeated:
	.string "EVE: Ah, bouhou! On n'a\n"
	.string "toujours pas réussi à gagner…$"

Route103_Text_AmyRematchPostBattle:
	.string "EVE: Il faut penser à\n"
	.string "plein de choses quand tu te\l"
	.string "bats contre deux DRESSEURS.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "EVE: Oh, tu n'as qu'un seul\n"
	.string "POKéMON avec toi. Tu ne vas\l"
	.string "pas pouvoir nous affronter.$"

Route103_Text_LivRematchIntro:
	.string "AWA: On se bat\n"
	.string "ensemble, comme une équipe.$"

Route103_Text_LivRematchDefeated:
	.string "AWA: Arrrg, on a\n"
	.string "encore perdu… Grande sœur…$"

Route103_Text_LivRematchPostBattle:
	.string "AWA: On fonctionne très bien\n"
	.string "ensemble, ma grande sœur et moi…\p"
	.string "Mais pourquoi a-t-on encore perdu?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "AWA: Si tu veux te battre contre\n"
	.string "nous, il faut que tu aies deux\l"
	.string "POKéMON! Sinon, ce ne serait pas!$"

Route103_Text_AndrewIntro:
	.string "Arrg! Ma ligne est emmêlée!\n"
	.string "Ça m'énerve et ça me rend\l"
	.string "agressif! Allez! Viens te battre!$"

Route103_Text_AndrewDefeated:
	.string "Ah! Perdu! Je suis\n"
	.string "encore plus énervé maintenant!$"

Route103_Text_AndrewPostBattle:
	.string "Ah, je vais\n"
	.string "devenir fou… Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "Mon POKéMON est tellement\n"
	.string "adorable! Viens, je te le montre!$"

Route103_Text_MiguelDefeated:
	.string "Oh, ça alors!\n"
	.string "Mon POKéMON chéri!$"

Route103_Text_MiguelPostBattle:
	.string "Mon POKéMON chéri est à\n"
	.string "croquer, même quand il est K.O.!$"

Route103_Text_MiguelRegister:
	.string "Il faudra que tu viennes\n"
	.string "pour voir mes adorables POKéMON!$"

Route103_Text_MiguelRematchIntro:
	.string "Salut, toi! Mon adorable POKéMON\n"
	.string "est à croquer. De plus en plus!$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh! Mon\n"
	.string "POKéMON chéri!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Plus je passe de temps avec mon\n"
	.string "POKéMON et plus il est adorable.$"

Route103_Text_PeteIntro:
	.string "Pour une si petite distance…\n"
	.string "Rien de mieux que la nage…$"

Route103_Text_PeteDefeated:
	.string "Bloub!$"

Route103_Text_PetePostBattle:
	.string "Oh, je comprends d'où tu viens\n"
	.string "maintenant. Si j'avais un POKéMON\p"
	.string "en qui je puisse avoir confiance,\n"
	.string "je l'utiliserais aussi avec SURF.$"

Route103_Text_IsabelleIntro:
	.string "Regarde où tu vas! On a\n"
	.string "failli se rentrer dedans!$"

Route103_Text_IsabelleDefeated:
	.string "Méeuh…$"

Route103_Text_IsabellePostBattle:
	.string "Je ne suis pas bonne, je\n"
	.string "Désolé d'avoir failli t'écraser.$"

Route103_Text_RhettIntro:
	.string "On est un peu\n"
	.string "à l'étroit ici.$"

Route103_Text_RhettDefeated:
	.string "Tu te débrouilles\n"
	.string "bien pour ton âge!$"

Route103_Text_RhettPostBattle:
	.string "Tu aimes bien les\n"
	.string "petits endroits comme ça?$"

Route103_Text_MarcosIntro:
	.string "Est-ce que ma guitare t'a attiré?$"

Route103_Text_MarcosDefeated:
	.string "Ma carrière est fichue!$"

Route103_Text_MarcosPostBattle:
	.string "Je jouais de la guitare un peu à\n"
	.string "l'écart et soudain, je me suis\l"
	.string "retrouvé entouré de fans. Hé,\p"
	.string "Je devrais peut-être devenir pro.$"

Route104_Text_GinaIntro:
	.string "GINA: D'accord, on n'a qu'à\n"
	.string "se battre avec nos POKéMON!$"

Route104_Text_GinaDefeat:
	.string "GINA: Ça m'embête de perdre!$"

Route104_Text_GinaPostBattle:
	.string "GINA: On n'a pas le niveau! Il va\n"
	.string "On doit s'entraîner beaucoup plus!$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: Oh? Un seul POKéMON?\n"
	.string "Alors on ne se bat pas contre\p"
	.string "toi. Avec un seul POKéMON, ça\n"
	.string "va pas l'faire. C'est pas cool.$"

Route104_Text_MiaIntro:
	.string "MIA: On est jumelles,\n"
	.string "alors on combat ensemble.$"

Route104_Text_MiaDefeat:
	.string "MIA: On s'est battues ensemble\n"
	.string "et on a perdu toutes les deux…$"

Route104_Text_MiaPostBattle:
	.string "MIA: On va davantage entraîner nos\n"
	.string "et être fort comme toi.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: Tu veux te mesurer à\p"
	.string "nous? On te dira non et non, si\n"
	.string "tu n'as pas deux POKéMON avec\l"
	.string "toi. On est trop fortes pour toi!$"

Route104_Text_IvanIntro:
	.string "Pourquoi en faire un\n"
	.string "secret? Je suis\p"
	.string "l'expert en POKéMON EAU!\n"
	.string "Hum? Tu ne me connais pas?$"

Route104_Text_IvanDefeat:
	.string "Je pensais ne pas être trop\n"
	.string "Dis-le, mais je ne crois pas...$"

Route104_Text_IvanPostBattle:
	.string "J'étais si occupé à pêcher que\n"
	.string "J'ai oublié d'élever mon POKéMON.$"

Route104_Text_BillyIntro:
	.string "C'est trop cool de laisser\n"
	.string "des traces de pas sur le sable!$"

Route104_Text_BillyDefeat:
	.string "Waah! J'ai du sable dans mes\n"
	.string "Ils sont tous gritty!$"

Route104_Text_BillyPostBattle:
	.string "Je veux laisser les traces de\n"
	.string "mes pas partout sur le sable,\l"
	.string "mais elles disparaissent aussitôt…$"

Route104_Text_HaleyIntro:
	.string "Je devrais peut-être…\n"
	.string "Ou peut-être pas… Oui,\p"
	.string "c'est décidé, je me bats!$"

Route104_Text_HaleyDefeat:
	.string "Je n'aurais pas dû me battre…$"

Route104_Text_HaleyPostBattle:
	.string "Si tu dois prendre une décision et\n"
	.string "que tu laisses quelqu'un d'autre\l"
	.string "la prendre à ta place, tu le\l"
	.string "s'il vous plaît.$"

Route104_Text_HaleyRegister1:
	.string "Tu sais te battre, mais est-ce que\n"
	.string "je devrais t'inscrire dans mon\l"
	.string "POKéNAV? Je suis pas trop sûre… Je\p"
	.string "Bien sûr, je vais t'enregistrer!$"

Route104_Text_HaleyRegister2:
	.string "Tu sais te battre, mais est-ce que\n"
	.string "je devrais t'inscrire dans mon\l"
	.string "POKéNAV? Je suis pas trop sûre… Je\p"
	.string "Bien sûr, je vais t'enregistrer!$"

Route104_Text_HaleyRematchIntro:
	.string "Viens te battre!$"

Route104_Text_HaleyRematchDefeat:
	.string "Oooh… Je pensais\n"
	.string "pouvoir gagner…$"

Route104_Text_HaleyPostRematch:
	.string "J'ai fait le choix de me battre,\n"
	.string "je dois accepter la défaite avec\p"
	.string "J'en ai toujours marre de perdre!$"

Route104_Text_WinstonIntro:
	.string "Oh, oui, je relève le\n"
	.string "défi. J'ai beaucoup d'argent.$"

Route104_Text_WinstonDefeat:
	.string "Pourquoi je n'ai pas pu gagner?$"

Route104_Text_WinstonPostBattle:
	.string "S'il y a bien une chose que\n"
	.string "C'est POKéMON...$"

Route104_Text_WinstonRegister1:
	.string "Hmm? Tu as obtenu un\n"
	.string "POKéNAV. Tu veux de\p"
	.string "l'argent pour que je puisse\n"
	.string "t'enregistrer dans mon POKéNAV?$"

Route104_Text_WinstonRegister2:
	.string "Hmm? Tu as obtenu un\n"
	.string "POKéNAV. Tu veux de\p"
	.string "l'argent pour que je puisse\n"
	.string "t'enregistrer dans mon POKéNAV?$"

Route104_Text_WinstonRematchIntro:
	.string "Après ma défaite contre toi, j'ai\n"
	.string "de choses sur POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "J'ai encore perdu? Pourquoi\n"
	.string "je n'ai pas réussi à gagner?$"

Route104_Text_WinstonPostRematch:
	.string "Je suis riche et pourtant, je ne\n"
	.string "semble pas pouvoir gagner avec les\p"
	.string "Les POKéMON restent mystérieux…$"

Route104_Text_CindyIntro:
	.string "Le destin nous a fait nous\n"
	.string "Puis-je vous demander un combat?$"

Route104_Text_CindyDefeat:
	.string "Oh, ça alors!$"

Route104_Text_CindyPostBattle:
	.string "Bonjour est le début d'À\n"
	.string "J'espère qu'on se reverra.$"

Route104_Text_CindyRegister1:
	.string "Salut, contente de te revoir.\p"
	.string "C'est le destin qui nous fait nous\n"
	.string "s'inscrire dans notre POKéNAVS.$"

Route104_Text_CindyRegister2:
	.string "On devrait fêter ces\n"
	.string "retrouvailles!\p"
	.string "Enregistrons nos\n"
	.string "numéros dans nos POKéNAVS.$"

Route104_Text_CindyRematchIntro:
	.string "Salut! Comme on se retrouve!\n"
	.string "Que dirais-tu d'un petit combat?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh, non… J'ai fait du\n"
	.string "mieux que j'pouvais…$"

Route104_Text_CindyPostRematch:
	.string "Bonjour est le début d'À\n"
	.string "J'espère qu'on se reverra.$"

Route104_Text_DarianIntro:
	.string "J'ai attrapé ce POKéMON qui a\p"
	.string "l'air super fort! Il y a un je ne\n"
	.string "Ça a l'air dur, oui!$"

Route104_Text_DarianDefeat:
	.string "Que…$"

Route104_Text_DarianPostBattle:
	.string "Hé, MAGICARPE, on ne peut pas\n"
	.string "à votre nom, n'est-ce pas?$"

Route105_Text_FosterIntro:
	.string "On raconte qu'il y a une\n"
	.string "pierre mystérieuse par ici. Tu\l"
	.string "sais quelque chose là-dessus?$"

Route105_Text_FosterDefeated:
	.string "J'étais si préoccupé par cette\n"
	.string "mon POKéMON est resté faible...$"

Route105_Text_FosterPostBattle:
	.string "Je peux rester des heures à\n"
	.string "à un beau rocher sans s'ennuyer.$"

Route105_Text_LuisIntro:
	.string "Ouf! En te voyant, j'ai eu peur\n"
	.string "que ce soit un enfant en train de\p"
	.string "se noyer. Mais ça a l'air d'aller,\n"
	.string "alors que dirais-tu de te battre?$"

Route105_Text_LuisDefeated:
	.string "Glou… Glou…$"

Route105_Text_LuisPostBattle:
	.string "Si tu es en train de te noyer, il\n"
	.string "agitez un bras vers la plage.$"

Route105_Text_DominikIntro:
	.string "Nager dans la mer d'un bleu\n"
	.string "intense… C'est formidable!$"

Route105_Text_DominikDefeated:
	.string "J'ai perdu…\n"
	.string "Maintenant, je broie du noir…$"

Route105_Text_DominikPostBattle:
	.string "Pourquoi la mer est-elle\p"
	.string "bleue? Je l'ai appris au MUSEE\n"
	.string "de POIVRESSEL, mais j'ai oublié.$"

Route105_Text_BeverlyIntro:
	.string "Mon corps semble plus léger dans\n"
	.string "C'est comme si j'étais plus mince!$"

Route105_Text_BeverlyDefeated:
	.string "Je flotte…$"

Route105_Text_PostBattle:
	.string "Le poids de ton corps n'est\n"
	.string "réduit que d'un dixième dans\p"
	.string "l'eau. Je ferais donc… Hé!\n"
	.string "Je ne te dis pas mon poids!$"

Route105_Text_ImaniIntro:
	.string "Le bleu du ciel…\n"
	.string "L'étendue de la mer…\l"
	.string "C'est tellement paisible…$"

Route105_Text_ImaniDefeated:
	.string "J'ai perdu pendant que je baisais!$"

Route105_Text_ImaniPostBattle:
	.string "Je veux qu'on trouve ça\n"
	.string "Avec Guggle.$"

Route105_Text_AndresIntro:
	.string "Je suis convaincu que la mer\n"
	.string "nous cache de nombreux secrets.$"

Route105_Text_AndresDefeated:
	.string "Oui… Je ne suis pas\n"
	.string "très bon au combat…$"

Route105_Text_AndresPostBattle:
	.string "Il y a sûrement plein de\n"
	.string "secrets à découvrir au fond des\p"
	.string "océans. Je veux tous les trouver!$"

Route105_Text_AndresRegister:
	.string "Heu? Tu veux quand même\n"
	.string "m'enregistrer dans ton POKéNAV?$"

Route105_Text_AndresRematchIntro:
	.string "Je t'ai déjà dit que je n'étais\n"
	.string "Tu es sûr de vouloir faire ça?$"

Route105_Text_AndresRematchDefeated:
	.string "Oui… Je m'en\n"
	.string "doutais un peu…$"

Route105_Text_AndresRematchPostBattle:
	.string "Je ne me bats peut-être pas bien,\n"
	.string "mais personne ne m'arrive à la\p"
	.string "cheville quand il s'agit\n"
	.string "Le monde!$"

Route105_Text_JosueIntro:
	.string "Nager, ça m'a épuisé.\n"
	.string "J'suis pas vraiment habitué.\p"
	.string "Un petit combat pour changer?$"

Route105_Text_JosueDefeated:
	.string "J'ai perdu parce que j'ai lutté.$"

Route105_Text_JosuePostBattle:
	.string "Dans le ciel, je me sens\n"
	.string "plus à l'aise que dans l'eau!$"

Route106_Text_ElliotIntro:
	.string "Que préfères-tu:\n"
	.string "pêcher en mer ou en rivière?$"

Route106_Text_ElliotDefeated:
	.string "Comme à la pêche en mer, j'ai\n"
	.string "perdu de façon spectaculaire!$"

Route106_Text_ElliotPostBattle:
	.string "La pêche, c'est ce qu'il y a de\n"
	.string "mieux, peu importe que ce soit en\l"
	.string "Tu es d'accord avec moi, non?$"

Route106_Text_ElliotRegister:
	.string "C'est cool la pêche, un peu comme\n"
	.string "On peut se revoir?$"

Route106_Text_ElliotRematchIntro:
	.string "En pêchant, j'ai attrapé un paquet\n"
	.string "de POKéMON. Ça va être terrible!$"

Route106_Text_ElliotRematchDefeated:
	.string "J'ai perdu à nouveau!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Gagner ou perdre… De toute\n"
	.string "Tu es d'accord avec moi, non?$"

Route106_Text_NedIntro:
	.string "Que font les gens s'ils ont envie\n"
	.string "d'aller aux toilettes? J'fais quoi\p"
	.string "si j'ai une touche quand je suis\n"
	.string "Je suis dans les toilettes?$"

Route106_Text_NedDefeated:
	.string "J'ai perdu car\n"
	.string "j'essaie de me retenir…$"

Route106_Text_NedPostBattle:
	.string "Oh, non! Je croyais que\n"
	.string "j'allais avoir une grosse prise!$"

Route106_Text_DouglasIntro:
	.string "Ah, ah, ah! Je suis un mauvais\n"
	.string "l'eau que tu peux pas m'attraper!$"

Route106_Text_DouglasDefeated:
	.string "J'abandonne!$"

Route106_Text_DouglasPostBattle:
	.string "Je ne perdrais pas en nageant...$"

Route106_Text_KylaIntro:
	.string "La mer est mon repaire. Même si tu\n"
	.string "Détends-toi car t'es un gamin!$"

Route106_Text_KylaDefeated:
	.string "Est-ce que par hasard, tu\n"
	.string "as trouvé ça trop facile?$"

Route106_Text_KylaPostBattle:
	.string "Se laisser aller au gré des\n"
	.string "Pourquoi n'essaies-tu pas?$"

Route107_Text_DarrinIntro:
	.string "Ouhaaaa… Je me suis\p"
	.string "endormi en me laissant\n"
	.string "porter par les vagues.$"

Route107_Text_DarrinDefeated:
	.string "Ah, ah, j'ai perdu… J'vais\n"
	.string "faire une p'tite sieste…$"

Route107_Text_DarrinPostBattle:
	.string "Flotter et se laisser bercer\n"
	.string "par les vagues, c'est comme\l"
	.string "Un lit confortable en peluche.$"

Route107_Text_TonyIntro:
	.string "La mer est comme ma\n"
	.string "seconde maison. Battons-nous!$"

Route107_Text_TonyDefeated:
	.string "J'ai perdu sur mon\n"
	.string "territoire… Quel choc!$"

Route107_Text_TonyPostBattle:
	.string "Je traverse les mers à la\n"
	.string "nage, le cœur rempli de\p"
	.string "rêves… C'est une chanson! De\n"
	.string "Bref, je nage encore un peu.$"

Route107_Text_TonyRegister:
	.string "J'en suis tout retourné! Comme\n"
	.string "ça, tu te souviendras de moi!$"

Route107_Text_TonyRematchIntro:
	.string "A nager dans cette large et vaste\n"
	.string "Mon POKéMON s'est renforcé!$"

Route107_Text_TonyRematchDefeated:
	.string "Quel choc! Mon POKéMON\p"
	.string "est devenu plus fort,\n"
	.string "mais je suis resté faible…$"

Route107_Text_TonyRematchPostBattle:
	.string "Ce que tu apprends au combat te\n"
	.string "rend plus fort en tant que\l"
	.string "Les vagues m'ont appris ça.$"

Route107_Text_DeniseIntro:
	.string "Tu connais une petite\n"
	.string "ville appelée MYOKARA?$"

Route107_Text_DeniseDefeated:
	.string "Je déteste ça!$"

Route107_Text_DenisePostBattle:
	.string "Un curieux proverbe est en train\n"
	.string "tendance chez DEWFORD HALL.$"

Route107_Text_BethIntro:
	.string "Tu voulais te battre contre\n"
	.string "moi? Oui, c'est OK pour moi!$"

Route107_Text_BethDefeated:
	.string "Je n'étais pas assez bon pour toi.$"

Route107_Text_BethPostBattle:
	.string "Je crois que les choses iront de\n"
	.string "J'y vais aussi!$"

Route107_Text_LisaIntro:
	.string "LISA: Accepte le défi\n"
	.string "d'un frère et d'une sœur!$"

Route107_Text_LisaDefeated:
	.string "LISA: Impressionnant! Tu as\n"
	.string "un niveau bien plus élevé.$"

Route107_Text_LisaPostBattle:
	.string "LISA: As-tu des amis qui\n"
	.string "Tu irais à la plage avec toi?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: Si tu veux nous\n"
	.string "Apportez plus de POKéMON.$"

Route107_Text_RayIntro:
	.string "RAY: Avec ma sœur, on est\n"
	.string "toujours en train de faire des\p"
	.string "combats POKéMON. Je perds\n"
	.string "2 contre 2!$"

Route107_Text_RayDefeated:
	.string "RAY: Waouh, tu as un\n"
	.string "meilleur niveau que nous!$"

Route107_Text_RayPostBattle:
	.string "RAY: C'est ma sœur qui m'a donné\n"
	.string "mon POKéMON. Je l'ai élevé et\l"
	.string "partenaire!$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: Si tu veux nous\n"
	.string "Allez apporter plus de POKéMON!$"

Route107_Text_CamronIntro:
	.string "Je suis en plein triathlon, mais\n"
	.string "Mais je suis loin d'être fatiguée!$"

Route107_Text_CamronDefeated:
	.string "J'en peux plus…$"

Route107_Text_CamronPostBattle:
	.string "Il me reste encore les\n"
	.string "épreuves de vélo et de course\p"
	.string "après ça. Je ne tiendrai jamais…$"

Route108_Text_JeromeIntro:
	.string "Mon rêve est de parcourir les\n"
	.string "sept mers du monde à la nage!$"

Route108_Text_JeromeDefeated:
	.string "C'est pas comme ça que j'vais\n"
	.string "Comme ça...$"

Route108_Text_JeromePostBattle:
	.string "Jouer avec les POKéMON marins,\n"
	.string "les plaisirs de la natation!$"

Route108_Text_MatthewIntro:
	.string "Eho, toi là-bas! Tu\n"
	.string "vas aussi à l'EPAVE?$"

Route108_Text_MatthewDefeated:
	.string "Je me noie!\n"
	.string "Glou… Glou…$"

Route108_Text_MatthewPostBattle:
	.string "Certaines personnes sont même\n"
	.string "Abandonné le vaisseau.$"

Route108_Text_TaraIntro:
	.string "Mon menteur de petit ami m'a dit\n"
	.string "que j'étais très jolie en bikini…$"

Route108_Text_TaraDefeated:
	.string "Oh, bouh!$"

Route108_Text_TaraPostBattle:
	.string "Même si ce n'est pas vrai,\n"
	.string "j'aime bien qu'on me dise que je\l"
	.string "suis jolie… Ah, nous les filles…$"

Route108_Text_MissyIntro:
	.string "J'adore la mer! J'oublie\n"
	.string "tous mes soucis quand je nage.$"

Route108_Text_MissyDefeated:
	.string "Quand je perds un\n"
	.string "combat, ça me stresse!$"

Route108_Text_MissyPostBattle:
	.string "Nager pour évacuer son\n"
	.string "stress! C'est tellement sain!$"

Route108_Text_CoryIntro:
	.string "J'adore les POKéMON de type\n"
	.string "EAU. Les autres aussi d'ailleurs!$"

Route108_Text_CoryDefeated:
	.string "Aaaaah! J'ai\n"
	.string "perdu! Noooon!$"

Route108_Text_CoryPostBattle:
	.string "Crie un coup quand\n"
	.string "ça va pas! Ça soulage!$"

Route108_Text_CoryRegister:
	.string "J'adore les DRESSEURS difficiles!\n"
	.string "Enregistre-moi dans ton POKéNAV!$"

Route108_Text_CoryRematchIntro:
	.string "Combattre sur l'eau, quel pied!$"

Route108_Text_CoryRematchDefeated:
	.string "Aaaaaaaah! J'ai\n"
	.string "encore perdu! Nooooooon!$"

Route108_Text_CoryRematchPostBattle:
	.string "Si tu cherches un\n"
	.string "challenge, essaie de crier en mer!$"

Route108_Text_CarolinaIntro:
	.string "Je suis très fière de mes\n"
	.string "POKéMON. Laisse-moi te montrer!$"

Route108_Text_CarolinaDefeated:
	.string "C'était pas sympa de ta part!$"

Route108_Text_CarolinaPostBattle:
	.string "Comme je suis à la mer, je n'ai\n"
	.string "mettre un maillot rose, frilly...$"

Route109_Text_DavidIntro:
	.string "Hé, hé! Regarde un peu mes\n"
	.string "C'est ce que tu appelles Cut!$"

Route109_Text_DavidDefeated:
	.string "Oh, oh! A côté\n"
	.string "d'la plaque!$"

Route109_Text_DavidPostBattle:
	.string "Hé, hé! Mes abdos bien\p"
	.string "sculptés n'ont rien à voir\n"
	.string "avec les combats de POKéMON!$"

Route109_Text_AliceIntro:
	.string "Tu as une bonne\n"
	.string "protection contre le soleil?$"

Route109_Text_AliceDefeated:
	.string "Ouille, ouille, ouille!$"

Route109_Text_AlicePostBattle:
	.string "Les joues brûlent vite au soleil.$"

Route109_Text_HueyIntro:
	.string "J'ai jeté l'ancre dans tous les\n"
	.string "Mais SLATEPORT est le meilleur.$"

Route109_Text_HueyDefeated:
	.string "Y a pas meilleur que toi!$"

Route109_Text_HueyPostBattle:
	.string "Dans le plus beau port se trouve\n"
	.string "donc le plus fort des DRESSEURS…$"

Route109_Text_EdmondIntro:
	.string "Aaaaaaaaaah… Te\n"
	.string "battre? Contre moi?$"

Route109_Text_EdmondDefeated:
	.string "Aah…\n"
	.string "Oooooooohhhhh… Aaaaaaaaaah…$"

Route109_Text_EdmondPostBattle:
	.string "D'habitude, je suis meilleur que\n"
	.string "ça! Je suis malade comme un chien!\p"
	.string "Je suis un SAILOR, mais...$"

Route109_Text_RickyIntro:
	.string "J'ai si soif… Je pourrais aller\n"
	.string "à la maison Seashore...$"

Route109_Text_RickyDefeated:
	.string "Grrrrrr…$"

Route109_Text_RickyPostBattle:
	.string "Je suis affamé… Ma bouée\n"
	.string "ressemble à un beignet géant…$"

Route109_Text_RickyRegister:
	.string "On se battra encore? Dès\n"
	.string "que je n'aurai plus soif, OK?$"

Route109_Text_RickyRematchIntro:
	.string "Je suis affamé, mais j'ai encore\n"
	.string "Moi pour une bataille!$"

Route109_Text_RickyRematchDefeated:
	.string "J'ai perdu… C'est\n"
	.string "car je suis affamé…$"

Route109_Text_RickyRematchPostBattle:
	.string "Quand on mange sur la\n"
	.string "plage, tout semble meilleur.$"

Route109_Text_LolaIntro:
	.string "Ne trouves-tu pas qu'un\n"
	.string "Une fleur géante?$"

Route109_Text_LolaDefeated:
	.string "Maman!$"

Route109_Text_LolaPostBattle:
	.string "La plage vue du ciel ressemble\n"
	.string "à un grand jardin de fleurs!$"

Route109_Text_LolaRegister:
	.string "Moi? Je suis là\n"
	.string "tous les jours!$"

Route109_Text_LolaRematchIntro:
	.string "Je n'vais pas encore perdre contre\n"
	.string "C'est pour ça que j'ai mon tube!$"

Route109_Text_LolaRematchDefeated:
	.string "Maman!$"

Route109_Text_LolaRematchPostBattle:
	.string "Avec une bouée, la grâce de mes\n"
	.string "La beauté de POKéMON s'élève!$"

Route109_Text_AustinaIntro:
	.string "Je ne peux pas nager sans ma\n"
	.string "Mais je ne perdrai pas à POKéMON!$"

Route109_Text_AustinaDefeated:
	.string "C'est car j'avais une\n"
	.string "bouée que j'ai perdu?$"

Route109_Text_AustinaPostBattle:
	.string "Ma bouée est un accessoire de\n"
	.string "mode. Je ne sors jamais sans elle.$"

Route109_Text_GwenIntro:
	.string "Salut, grand DRESSEUR. Tu\n"
	.string "veux te battre contre moi?$"

Route109_Text_GwenDefeated:
	.string "Oh, quelle puissance!$"

Route109_Text_GwenPostBattle:
	.string "Comment es-tu devenu si fort?$"

Route109_Text_CarterIntro:
	.string "Waaouh! Qu'est-ce\n"
	.string "que tu vas t'prendre!$"

Route109_Text_CarterDefeated:
	.string "J'ai perdu…$"

Route109_Text_CarterPostBattle:
	.string "Je pense que tu es remarquable.\n"
	.string "Non, tu es un grand être!$"

Route109_Text_PaulIntro:
	.string "PAUL: Eh bien, on peut dire que tu\p"
	.string "sais casser l'ambiance. Tu ne\n"
	.string "Un temps précieux ensemble.$"

Route109_Text_PaulDefeated:
	.string "PAUL: Bon, j'abandonne.$"

Route109_Text_PaulPostBattle:
	.string "PAUL: Ne dis à personne\n"
	.string "qu'on est là. C'est juste\l"
	.string "C'est notre monde privé de deux!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: On s'aime profondément.\n"
	.string "C'est pour ça qu'on fait\l"
	.string "combattre nos POKéMON ensemble.$"

Route109_Text_MelIntro:
	.string "MEL: On est follement amoureux.\n"
	.string "Notre amour enflamme tout HOENN!$"

Route109_Text_MelDefeated:
	.string "MEL: On a perdu et c'est ma\n"
	.string "faute! PAUL va me détester!$"

Route109_Text_MelPostBattle:
	.string "MEL: Euh, PAUL, tu m'en veux?\n"
	.string "Ne te fâche pas, je t'en prie.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: On s'aime profondément.\n"
	.string "C'est pour ça qu'on fait\l"
	.string "combattre nos POKéMON ensemble.$"

Route109_Text_ChandlerIntro:
	.string "Tadaaah! Tu vois? Ma\n"
	.string "bouée est toute ronde!$"

Route109_Text_ChandlerDefeated:
	.string "Oh oh! C'est\n"
	.string "trop dommage!$"

Route109_Text_ChandlerPostBattle:
	.string "Et tout ça après que\n"
	.string "je t'ai montré ma bouée…$"

Route109_Text_HaileyIntro:
	.string "Je ne sais pas nager,\n"
	.string "alors je fais juste semblant.$"

Route109_Text_HaileyDefeated:
	.string "C'est bien ce que je\n"
	.string "pensais! Je ne pouvais pas gagner!$"

Route109_Text_HaileyPostBattle:
	.string "Quand je me suis mise à la\n"
	.string "Mon POKéMON deviendra plus dur.$"

Route109_Text_ElijahIntro:
	.string "Pour un macho comme moi, cette\n"
	.string "de POKéMON est le match parfait!$"

Route109_Text_ElijahDefeated:
	.string "Je suis cool même en défaite.$"

Route109_Text_ElijahPostBattle:
	.string "Pour un macho comme moi, un port\n"
	.string "est le lieu idéal! Je pense donc\p"
	.string "aller faire un tour à POIVRESSEL.$"

Route110_Text_JacobIntro:
	.string "Waouh! Regarde ça! Tu ne dois pas\n"
	.string "trop saisir les courses de VELO.$"

Route110_Text_JacobDefeated:
	.string "Waouh! Mes\n"
	.string "freins ont lâché!$"

Route110_Text_JacobPostBattle:
	.string "Des pneus à plat et des\n"
	.string "problèmes de freins peuvent faire\l"
	.string "Inspectez votre BIKE de problèmes!$"

Route110_Text_AnthonyIntro:
	.string "Hé, toi! Tu peux\n"
	.string "aller aussi vite que moi?$"

Route110_Text_AnthonyDefeated:
	.string "Je suis anéanti!$"

Route110_Text_AnthonyPostBattle:
	.string "La vitesse ne suffira pas à me\n"
	.string "Je dois reconsidérer ça...$"

Route110_Text_BenjaminIntro:
	.string "Garde ton calme à pleine vitesse!$"

Route110_Text_BenjaminDefeated:
	.string "Je ne devrais pas m'affoler\n"
	.string "pendant les combats de POKéMON…$"

Route110_Text_BenjaminPostBattle:
	.string "Pas la peine de paniquer ou de\n"
	.string "Du calme, il y a plein de temps.$"

Route110_Text_BenjaminRegister:
	.string "Ce qui compte c'est\n"
	.string "Criez-moi si vous êtes prêt.$"

Route110_Text_BenjaminRematchIntro:
	.string "T'irais pas un peu trop vite?\n"
	.string "T'énerve pas et viens te battre!$"

Route110_Text_BenjaminRematchDefeated:
	.string "J'ai gardé mon calme, mais perdu…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Pas la peine de paniquer ou de\n"
	.string "Du calme, il y a plein de temps.$"

Route110_Text_AbigailIntro:
	.string "Le triathlon est extrêmement\p"
	.string "difficile. Il faut réussir trois\n"
	.string "de natation, de vélo et de course.$"

Route110_Text_AbigailDefeated:
	.string "Les combats de POKéMON sont durs!$"

Route110_Text_AbigailPostBattle:
	.string "Je suis exténuée. Une pause\n"
	.string "Il est important de se reposer.$"

Route110_Text_AbigailRegister:
	.string "Tu sais, je t'aime bien! Ça te dit\n"
	.string "une revanche sur cette piste?$"

Route110_Text_AbigailRematchIntro:
	.string "C'est pratique de livrer\n"
	.string "bataille en faisant du VELO, non?$"

Route110_Text_AbigailRematchDefeated:
	.string "Waouh… Comment peut-on\n"
	.string "avoir autant de talent?$"

Route110_Text_AbigailRematchPostBattle:
	.string "T'essayais de battre un\p"
	.string "record? Désolée si je te retarde!$"

Route110_Text_JasmineIntro:
	.string "Je n'ai pas arrêté de faire du\n"
	.string "vélo. J'ai des cuisses en béton!$"

Route110_Text_JasmineDefeated:
	.string "J'ai peur d'avoir des crampes…$"

Route110_Text_JasminePostBattle:
	.string "Oh, tu as des BADGES D'ARÈNE? Pas\n"
	.string "Pas étonnant que tu sois si forte!$"

Route110_Text_EdwardIntro:
	.string "J'ai deviné tes\n"
	.string "Je ne peux pas perdre!$"

Route110_Text_EdwardDefeated:
	.string "Je n'ai même pas vu ma propre fin!$"

Route110_Text_EdwardPostBattle:
	.string "Je vois ton\p"
	.string "avenir… Hum… Je vois\n"
	.string "une lumière briller…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha! Mes\n"
	.string "prodiges vont t'éblouir!$"

Route110_Text_JaclynDefeated:
	.string "J'ai perdu de façon prodigieuse!$"

Route110_Text_JaclynPostBattle:
	.string "T'as gagné, mais c'était un\n"
	.string "miracle! Oui, un miracle! Ne crois\l"
	.string "tu ne gagneras pas à chaque fois!$"

Route110_Text_EdwinIntro:
	.string "Je pourrais voir tes POKéMON?\n"
	.string "Un seul regard, s'il vous plaît?$"

Route110_Text_EdwinDefeated:
	.string "Je voudrais\n"
	.string "compléter ma collection…$"

Route110_Text_EdwinPostBattle:
	.string "Quand je vois un POKéMON que je ne\n"
	.string "inconnu, ma passion s'enflamme!$"

Route110_Text_EdwinRegister:
	.string "J'adore collectionner\n"
	.string "les numéros de MATCH PHONE…$"

Route110_Text_EdwinRematchIntro:
	.string "Salut, t'as attrapé de nouveaux\p"
	.string "POKéMON? Je pourrais voir tes\n"
	.string "Un seul regard, s'il vous plaît?$"

Route110_Text_EdwinRematchDefeated:
	.string "Tes POKéMON…\n"
	.string "Je t'envie.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, je rêve de\n"
	.string "La mienne!$"

Route110_Text_DaleIntro:
	.string "Hé! Ne te faufile pas\n"
	.string "derrière moi comme ça!$"

Route110_Text_DaleDefeated:
	.string "J'ai\n"
	.string "perdu! Sapristi!$"

Route110_Text_DalePostBattle:
	.string "La pêche repose sur la\n"
	.string "Concentrez-vous sur le flotteur.$"

Route110_Text_IsabelIntro:
	.string "Ahahahaha! Je voudrais aller\n"
	.string "de mon délicieux POKéMON.$"

Route110_Text_IsabelDefeated:
	.string "Oh, non, j'peux pas accepter ça…$"

Route110_Text_IsabelPostBattle:
	.string "que de me battre, je devrais\n"
	.string "montrer mon POKéMON au FAN CLUB.$"

Route110_Text_IsabelRegister:
	.string "Ce n'est pas comme ça que je\n"
	.string "pourrai frimer avec mes\p"
	.string "POKéMON. Je te demanderai ton\n"
	.string "avis aussi souvent que possible!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! Je serais heureuse de\n"
	.string "aussi souvent que tu veux!$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, non, j'peux pas accepter ça…$"

Route110_Text_IsabelRematchPostBattle:
	.string "Les CONCOURS, c'est charmant, je\n"
	.string "ne peux pas m'empêcher de montrer\p"
	.string "Mais j'aime aussi me battre!$"

Route110_Text_TimmyIntro:
	.string "J'ai trouvé des POKéMON\n"
	.string "sympas dans l'herbe aux alentours!$"

Route110_Text_TimmyDefeated:
	.string "Être cool ne suffit pas à gagner.$"

Route110_Text_TimmyPostBattle:
	.string "C'est difficile de combattre avec\n"
	.string "des POKéMON tout juste attrapés.$"

Route110_Text_AlyssaIntro:
	.string "Je suis tombée de la PISTE\p"
	.string "CYCLABLE… Je vais faire passer ma\n"
	.string "Je me bats avec toi!$"

Route110_Text_AlyssaDefeated:
	.string "Oups! Tu as\n"
	.string "réussi à gagner!$"

Route110_Text_AlyssaPostBattle:
	.string "Tomber… Perdre… Tout ça\n"
	.string "est si humiliant pour moi!$"

Route110_Text_JosephIntro:
	.string "OK! C'est parti pour\n"
	.string "un duo électrique!$"

Route110_Text_JosephDefeated:
	.string "T'as le groove toi!$"

Route110_Text_JosephPostBattle:
	.string "C'est pas grave. La défaite a\n"
	.string "fait de moi un homme meilleur!$"

Route110_Text_KalebIntro:
	.string "Rien de plus beau que deux\n"
	.string "POKéMON qui s'entraident!$"

Route110_Text_KalebDefeated:
	.string "N'as-tu donc aucune compassion?$"

Route110_Text_KalebPostBattle:
	.string "Mes POKéMON ont fait de leur\n"
	.string "mieux, je ne leur en veux pas.$"

Route111_Text_DrewIntro:
	.string "Oh, hé! Ces LUNET. SABLE te vont\n"
	.string "bien. Mais je trouve qu'elles me\p"
	.string "vont mieux. Réglons ça au combat!\n"
	.string "Voyons à qui elles vont le mieux!$"

Route111_Text_DrewDefeat:
	.string "Avec les LUNET. SABLE, j'ai\n"
	.string "pas pu voir ce qui s'est passé.$"

Route111_Text_DrewPostBattle:
	.string "Les LUNET. SABLE permettent de\n"
	.string "passer à travers les tempêtes de\l"
	.string "sable. J'en suis très content!$"

Route111_Text_HeidiIntro:
	.string "Je pique-nique dans le désert. Il\p"
	.string "y a souvent des DRESSEURS, je peux\n"
	.string "aussi prendre plaisir au combat!$"

Route111_Text_HeidiDefeat:
	.string "Ohhh! Quelle méchanceté!$"

Route111_Text_HeidiPostBattle:
	.string "Quand tu combats durant une\n"
	.string "tempête de sable, vérifie les PV\p"
	.string "de ton POKéMON. Il peut être mis\n"
	.string "Un œil dessus!$"

Route111_Text_BeauIntro:
	.string "Avec ces LUNET. SABLE, j'ai\n"
	.string "l'impression d'être un super\l"
	.string "Personne ne peut me battre!$"

Route111_Text_BeauDefeat:
	.string "La foi ne suffit pas pour gagner…$"

Route111_Text_BeauPostBattle:
	.string "Un jour, je serai un vrai héros.\n"
	.string "Je vais travailler davantage pour\l"
	.string "et mon POKéMON plus fort.$"

Route111_Text_BeckyIntro:
	.string "Il paraît qu'il y a des fossiles\n"
	.string "Où pourraient-ils être?$"

Route111_Text_BeckyDefeat:
	.string "Je n'ai fait qu'une apparition…$"

Route111_Text_BeckyPostBattle:
	.string "Si on peut trouver des fossiles\n"
	.string "ça devait être une mer avant.$"

Route111_Text_DustyIntro:
	.string "J'ai cherché des ruines\n"
	.string "antiques pendant trente\l"
	.string "ans! Peux-tu me défier?$"

Route111_Text_DustyDefeat:
	.string "Comme je cherchais des ruines, je\n"
	.string "n'ai pas cherché de POKéMON forts.$"

Route111_Text_DustyPostBattle:
	.string "J'ai cherché des ruines\n"
	.string "antiques pendant trente ans!\p"
	.string "Non, attends, quarante ans?\n"
	.string "Ça fait combien maintenant?$"

Route111_Text_DustyRegister:
	.string "Je n'ai pas trop cherché de\n"
	.string "POKéMON vraiment coriaces.\p"
	.string "Mais ça ne m'empêche pas\n"
	.string "de bien aimer les POKéNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "J'ai cherché des ruines\n"
	.string "antiques pendant trente ans!\p"
	.string "Non, attends, quarante ans? De\n"
	.string "toute façon, tu peux me défier?$"

Route111_Text_DustyRematchDefeat:
	.string "Je n'ai trouvé ni\n"
	.string "ruines, ni POKéMON forts…$"

Route111_Text_DustyPostRematch:
	.string "J'ai cherché des ruines\n"
	.string "antiques pendant trente ans!\p"
	.string "Non, attends, ça ferait\n"
	.string "quarante ans en fait? Ça\p"
	.string "pourrait même faire cinquante ans…\n"
	.string "Mince, ça fait combien de temps?$"

Route111_Text_TravisIntro:
	.string "J'ai la pêche! Et mon\n"
	.string "POKéMON a de l'entrain aussi!$"

Route111_Text_TravisDefeat:
	.string "Mon POKéMON a perdu son entrain…$"

Route111_Text_TravisPostBattle:
	.string "Quand je vois un DRESSEUR plein\n"
	.string "Je ne peux m'empêcher de chercher.$"

Route111_Text_IreneIntro:
	.string "Je ne sais pas où tu vas,\n"
	.string "mais tu voudrais bien te battre?$"

Route111_Text_IreneDefeat:
	.string "Oh, t'as une force pas possible!$"

Route111_Text_IrenePostBattle:
	.string "Je me disais que je devrais\n"
	.string "aller au MONT CHIMNEE, mais\l"
	.string "la vue est aussi superbe ici.$"

Route111_Text_DaisukeIntro:
	.string "Pour m'entraîner, je défie\n"
	.string "tous ceux que je rencontre!$"

Route111_Text_DaisukeDefeat:
	.string "Je déclare forfait! J'abandonne!$"

Route111_Text_DaisukePostBattle:
	.string "Tout ce que je peux faire, c'est\n"
	.string "continuer à m'entraîner jusqu'à ce\l"
	.string "comme toi-même.$"

Route111_Text_WiltonIntro:
	.string "Fais-moi voir comme tu\n"
	.string "as endurci tes POKéMON!$"

Route111_Text_WiltonDefeat:
	.string "Je vois, tu les as\n"
	.string "considérablement endurcis.$"

Route111_Text_WiltonPostBattle:
	.string "Les POKéMON et les DRESSEURS\n"
	.string "apprennent beaucoup au combat. Le\p"
	.string "plus important, c'est de ne\n"
	.string "même si tu perds.$"

Route111_Text_WiltonRegister:
	.string "Il y aurait beaucoup à\n"
	.string "dire sur ton style de\p"
	.string "combat. Si tu es d'accord, Je\n"
	.string "voudrais vraiment une revanche.$"

Route111_Text_WiltonRematchIntro:
	.string "On s'entraîne ici pour\n"
	.string "passer au niveau supérieur.\l"
	.string "Reste et entraîne-toi avec nous!$"

Route111_Text_WiltonRematchDefeat:
	.string "Oh, pas si mal!$"

Route111_Text_WiltonPostRematch:
	.string "Si tu as un tel niveau, tu\n"
	.string "devrais viser la LIGUE POKéMON.$"

Route111_Text_BrookeIntro:
	.string "Oh, tes POKéMON ont\n"
	.string "l'air de faire bonne\l"
	.string "figure. Je vais les enrôler.$"

Route111_Text_BrookeDefeat:
	.string "Ils ne paraissent pas seulement\n"
	.string "forts, ils le sont réellement!$"

Route111_Text_BrookePostBattle:
	.string "Je pensais entraîner mes\n"
	.string "POKéMON assidûment, mais il y a\l"
	.string "encore du pain sur la planche.$"

Route111_Text_BrookeRegister:
	.string "Je voudrais tant avoir plus\n"
	.string "d'amis aussi forts que toi.$"

Route111_Text_BrookeRematchIntro:
	.string "Tu peux rendre tes POKéMON\n"
	.string "plus ou moins forts en fonction\l"
	.string "des capacités que tu leur\p"
	.string "apprends. Quelles sortes de\n"
	.string "Tu sais?$"

Route111_Text_BrookeRematchDefeat:
	.string "Tu leur as appris de bons gestes!$"

Route111_Text_BrookePostRematch:
	.string "J'aurais peut-être dû empêcher mes\n"
	.string "POKéMON d'évoluer jusqu'à ce\l"
	.string "J'ai appris à mieux bouger...$"

Route111_Text_CeliaIntro:
	.string "Je n'aurais vraiment pas dû\n"
	.string "venir ici pour un pique-nique!$"

Route111_Text_CeliaDefeat:
	.string "Aïe! Je n'aurais\n"
	.string "vraiment pas dû venir!$"

Route111_Text_CeliaPostBattle:
	.string "Dans une tempête de sable comme\n"
	.string "ça, il est impossible de faire un\l"
	.string "Allez-y.$"

Route111_Text_BryanIntro:
	.string "Es-tu vraiment si redoutable? Je\n"
	.string "vais tenter de percer ce secret!$"

Route111_Text_BryanDefeat:
	.string "Oh, ta force! Elle est\n"
	.string "entourée de mystère!$"

Route111_Text_BryanPostBattle:
	.string "Ce désert regorge de\n"
	.string "mystères enfouis sous le sable!$"

Route111_Text_BrandenIntro:
	.string "Si je gagne, je te\n"
	.string "donnerai un de mes sandwichs!$"

Route111_Text_BrandenDefeat:
	.string "Pff, je pensais qu'un\n"
	.string "sandwich suffirait à te corrompre…$"

Route111_Text_BrandenPostBattle:
	.string "Mon SABELETTE adore\n"
	.string "manger mes sandwichs.$"

Route111_Text_TyronIntro:
	.string "C'est mon POKéMON préféré!$"

Route111_Text_TyronDefeat:
	.string "Attends! Tu as bien\n"
	.string "regardé mon POKéMON?$"

Route111_Text_TyronPostBattle:
	.string "Au début d'un combat, j'adore le\n"
	.string "moment où je présente mes\p"
	.string "POKéMON. Mais je suis sûr que tout\n"
	.string "Ils entrent dans une bataille!$"

Route111_Text_CelinaIntro:
	.string "Montre-moi comment mettre un\n"
	.string "peu de piment dans ma vie!$"

Route111_Text_CelinaDefeat:
	.string "Oh… Non… C'était\n"
	.string "trop épicé pour moi!$"

Route111_Text_CelinaPostBattle:
	.string "Mon cœur bat encore à tout\n"
	.string "Tu es un fabuleux DRESSEUR.$"

Route111_Text_HaydenIntro:
	.string "Quelqu'un d'aussi connu que\n"
	.string "moi ne connaît aucune pitié.$"

Route111_Text_HaydenDefeat:
	.string "Grr…$"

Route111_Text_HaydenPostBattle:
	.string "Mon estomac gargouille! Je devrais\n"
	.string "tenter de griller quelques BAIES…$"

Route111_Text_BiancaIntro:
	.string "Tu viens de LAVANDIA?\n"
	.string "Quelle énergie tu dois avoir!$"

Route111_Text_BiancaDefeat:
	.string "Ooh là là!\n"
	.string "C'était trop pour moi!$"

Route111_Text_BiancaPostBattle:
	.string "Cette route… Tu n'es pas\n"
	.string "encore au bout de tes peines.$"

Route112_Text_BriceIntro:
	.string "Ahahahaha! Et\n"
	.string "si on\l"
	.string "s'affrontait? Toi\l"
	.string "et moi! Ahahahaha!$"

Route112_Text_BriceDefeat:
	.string "J'ai perdu!\n"
	.string "Ahahahaha!$"

Route112_Text_BricePostBattle:
	.string "Ahahahahaha! Quelque chose me\n"
	.string "monte au nez! Ahahahaha-tchoum!$"

Route112_Text_TrentIntro:
	.string "Mes jambes se sont endurcies\n"
	.string "à fouler le sol rocheux des\p"
	.string "montagnes. Elles ne vont pas\n"
	.string "flancher facilement, camarade!$"

Route112_Text_TrentDefeat:
	.string "Mes jambes se sont serrées!$"

Route112_Text_TrentPostBattle:
	.string "Essaie d'escalader\n"
	.string "ces sentiers de\l"
	.string "montagne en portant un\l"
	.string "bon poids sur le dos.\p"
	.string "Ça, camarade, ça te\n"
	.string "fera un bon exercice.$"

Route112_Text_TrentRegister:
	.string "Mes jambes sont pleines de\n"
	.string "crampes. Tu peux m'attraper\l"
	.string "la pommade qui est dans mon\p"
	.string "sac à dos? Non, ça c'est mon\n"
	.string "POKéNAV! OK, je t'enregistre!$"

Route112_Text_TrentRematchIntro:
	.string "J'ai gardé la forme grâce à la\n"
	.string "Puissance, j'ai des piques!$"

Route112_Text_TrentRematchDefeat:
	.string "J'ai eu le pouvoir?$"

Route112_Text_TrentRematchPostBattle:
	.string "J'ai entendu dire qu'il y\n"
	.string "avait des DRESSEURS en haut du\p"
	.string "MONT CHIMNEE. Je compte y\n"
	.string "monter pour leur lancer un défi!$"

Route112_Text_LarryIntro:
	.string "Je suis fort. J'vais\n"
	.string "pas pleurer si je perds.$"

Route112_Text_LarryDefeat:
	.string "Ouuuin!$"

Route112_Text_LarryPostBattle:
	.string "J'pleure pas car\n"
	.string "maman me manque! Sniff…$"

Route112_Text_CarolIntro:
	.string "Quand tu pars faire un\n"
	.string "pique-nique, il faut\l"
	.string "chanter! Viens, chante avec moi!$"

Route112_Text_CarolDefeat:
	.string "Oh, quel talent!$"

Route112_Text_CarolPostBattle:
	.string "Peu importe que tu sois bon ou\n"
	.string "mauvais en chant et en POKéMON. Le\p"
	.string "Si tu t'amuses le plus, tu gagnes!$"

Route112_Text_BryantIntro:
	.string "J'ai attrapé des POKéMON brûlants\n"
	.string "Regardez!$"

Route112_Text_BryantDefeat:
	.string "C'était vraiment chaud!$"

Route112_Text_BryantPostBattle:
	.string "J'aime beaucoup ta façon de\n"
	.string "Il a un certain goût pour ça.$"

Route112_Text_ShaylaIntro:
	.string "Oh, quel DRESSEUR adorable\n"
	.string "tu es! Battons-nous de\l"
	.string "façon courtoise, je t'en prie!$"

Route112_Text_ShaylaDefeat:
	.string "Oh, quelle force! J'en\n"
	.string "suis toute retournée.$"

Route112_Text_ShaylaPostBattle:
	.string "Tu as des choses à faire en ce\n"
	.string "moment? Je pensais qu'on pourrait\l"
	.string "peut-être faire notre match de\l"
	.string "Mais c'est bon si tu es occupé.$"

Route113_Text_JaylenIntro:
	.string "Tu sais pourquoi il fait\n"
	.string "si frais dans les alentours?$"

Route113_Text_JaylenDefeat:
	.string "Arrrg!\n"
	.string "J'suis dégoûté!$"

Route113_Text_JaylenPostBattle:
	.string "Comme les cendres volcaniques\n"
	.string "gênent le soleil, il ne fait pas\p"
	.string "Tant mieux, je déteste la chaleur!$"

Route113_Text_DillonIntro:
	.string "Les éruptions volcaniques\n"
	.string "prouvent que la terre est en vie.$"

Route113_Text_DillonDefeat:
	.string "T'es quelqu'un de fort!$"

Route113_Text_DillonPostBattle:
	.string "Ah! J'peux plus avancer! Les\n"
	.string "cendres m'empêchent de descendre!\p"
	.string "Tu piges? Les cendres et\p"
	.string "Ok, c'était mauvais, désolé...$"

Route113_Text_MadelineIntro:
	.string "Je prends ce parasol pour que mon\n"
	.string "cher CHAMALLOT ne soit pas\l"
	.string "Ma chère NUMEL.$"

Route113_Text_MadelineDefeat:
	.string "Fooouuu… Je\n"
	.string "suis exténuée…$"

Route113_Text_MadelinePostBattle:
	.string "Tu as vraiment du talent! Je\n"
	.string "Je suis impressionné!$"

Route113_Text_MadelineRegister:
	.string "Viens te mettre à l'abri sous mon\n"
	.string "parasol. Je t'ajoute au POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh salut, ça faisait longtemps,\n"
	.string "Puis-je vous inviter au combat?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, génial!$"

Route113_Text_MadelinePostRematch:
	.string "Tu as toujours autant de talent.\n"
	.string "Je suis impressionné!$"

Route113_Text_LaoIntro:
	.string "Je jaillis des cendres!\n"
	.string "Yaha! Je t'mets au défi!$"

Route113_Text_LaoDefeat:
	.string "J'admets la défaite avec dignité!$"

Route113_Text_LaoPostBattle:
	.string "Il me faut parfaire l'art de la\n"
	.string "Je te dis adieu.$"

Route113_Text_LaoRegister:
	.string "Yahah! Admire l'ancienne technique\n"
	.string "technique d'inscription POKéNAV!$"

Route113_Text_LaoRematchIntro:
	.string "Je jaillis des cendres!\n"
	.string "Yaha! Je t'mets au défi!$"

Route113_Text_LaoRematchDefeat:
	.string "J'admets la défaite avec dignité!$"

Route113_Text_LaoPostRematch:
	.string "Mon manque d'expérience au\n"
	.string "combat a déprécié ma dissimulation\p"
	.string "parfaite. Je te fais mes adieux.$"

Route113_Text_LungIntro:
	.string "Merci de m'avoir trouvé! Mais on\n"
	.string "va quand même devoir se battre!$"

Route113_Text_LungDefeat:
	.string "Je vais utiliser mon pouvoir\n"
	.string "de ninja sur toi… Que les\p"
	.string "cendres volcaniques\n"
	.string "C'est déjà fini?$"

Route113_Text_LungPostBattle:
	.string "Tu sais c'que c'est le pire quand\n"
	.string "C'est seul si personne ne vient.$"

Route113_Text_ToriIntro:
	.string "LILA: On ramasse des cendres\n"
	.string "Nous combattons aussi POKéMON.$"

Route113_Text_ToriDefeat:
	.string "LILA: On a perdu… Ça m'énerve,\n"
	.string "pour avoir d'autres cendres.$"

Route113_Text_ToriPostBattle:
	.string "LILA: On a quoi en cendres? Assez\n"
	.string "Assez pour un FLUTE BLANC.$"

Route113_Text_ToriNotEnoughMons:
	.string "LILA: On veut se battre en 2\n"
	.string "Sinon, on perdrait!$"

Route113_Text_TiaIntro:
	.string "NELLY: Toutes les deux, on ramasse\n"
	.string "Nous combattons aussi POKéMON.$"

Route113_Text_TiaDefeat:
	.string "NELLY: On n'a pas gagné… Ça\n"
	.string "Alors j'ai plus de cendres.$"

Route113_Text_TiaPostBattle:
	.string "NELLY: On a tout plein de cendres!\n"
	.string "Je pense assez pour un BLEU BLANC!$"

Route113_Text_TiaNotEnoughMons:
	.string "NELLY: On veut se battre en 2\n"
	.string "contre 2. Sinon, on va perdre!$"

Route113_Text_CobyIntro:
	.string "Pff, avec ces ailes, je\n"
	.string "Allez-vous-en!$"

Route113_Text_CobyDefeat:
	.string "Euh… Quoi?$"

Route113_Text_CobyPostBattle:
	.string "Je ne sais pas vraiment quoi\n"
	.string "dire après une si grosse défaite…$"

Route113_Text_SophieIntro:
	.string "La chaleur qu'il fait ici me fait\n"
	.string "somnoler. Un combat me réveillera.$"

Route113_Text_SophieDefeat:
	.string "Je suis en train de\n"
	.string "rêver, j'en suis sûre…$"

Route113_Text_SophiePostBattle:
	.string "Ça m'énerve de\n"
	.string "perdre! Je préfère\l"
	.string "encore dormir… Zzzz…$"

Route113_Text_LawrenceIntro:
	.string "Tu étais peut-être en\n"
	.string "train de récolter des cendres?$"

Route113_Text_LawrenceDefeat:
	.string "Oups. Tu nous as\n"
	.string "eus proprement!$"

Route113_Text_LawrencePostBattle:
	.string "Je vais me cacher dans la cendre!$"

Route113_Text_WyattIntro:
	.string "T… tu veux… te battre contre moi?\n"
	.string "Même si j'ai pris mon POKéMON?$"

Route113_Text_WyattDefeat:
	.string "Que… Gagner a l'air de te faire\n"
	.string "Même si c'est moi?$"

Route113_Text_WyattPostBattle:
	.string "Oh, alors tu\n"
	.string "veux dire un mot\p"
	.string "au perdant?\n"
	.string "L'humilité, tu connais?$"

Route114_Text_LennyIntro:
	.string "Lalalahihou! … …\p"
	.string "Il faut que tu\p"
	.string "cries\n"
	.string "Lalalahihou! si tu\l"
	.string "veux entendre ton écho!$"

Route114_Text_LennyDefeat:
	.string "Lalalahihou!$"

Route114_Text_LennyPostBattle:
	.string "Quand j'étais môme, je\n"
	.string "croyais que quelqu'un\l"
	.string "m'imitait et répétait Lalalahihou.$"

Route114_Text_LucasIntro:
	.string "Tu ne devrais pas grimper dans\n"
	.string "les montagnes sans préparation!$"

Route114_Text_LucasDefeat:
	.string "La montagne ne pardonne pas…$"

Route114_Text_LucasPostBattle:
	.string "En hiver, le blizzard et les\n"
	.string "avec blizzards et avalanches.$"

Route114_Text_ShaneIntro:
	.string "C'est sympa le camping! On pêche,\n"
	.string "on fait griller des marshmallows\p"
	.string "et on raconte des histoires qui\n"
	.string "Des batailles!$"

Route114_Text_ShaneDefeat:
	.string "Trop dur pour moi!$"

Route114_Text_ShanePostBattle:
	.string "Je trouve ça bien de pouvoir aller\n"
	.string "faire du camping avec mes POKéMON.$"

Route114_Text_NancyIntro:
	.string "J'ai besoin d'exercice après\n"
	.string "un repas. Affrontons-nous!$"

Route114_Text_NancyDefeat:
	.string "Oh, non!$"

Route114_Text_NancyPostBattle:
	.string "Je viens de prendre un délicieux\n"
	.string "repas, alors je m'endors un peu…$"

Route114_Text_SteveIntro:
	.string "Ohohohoh… Tu veux\n"
	.string "affronter mon POKéMON?$"

Route114_Text_SteveDefeat:
	.string "M… Mon POKéMON…$"

Route114_Text_StevePostBattle:
	.string "Un grand corps tout dur,\n"
	.string "d'énormes cornes et de\p"
	.string "puissants crocs… Ohohohoh… Je\n"
	.string "Si j'avais un POKéMON comme ça...$"

Route114_Text_SteveRegister:
	.string "N'oublie pas ce que tu viens de\n"
	.string "me faire! Moi, je n'oublierai pas!$"

Route114_Text_SteveRematchIntro:
	.string "Ohohohoho… Viens te\n"
	.string "battre contre moi…$"

Route114_Text_SteveRematchDefeat:
	.string "J'ai de la chance\n"
	.string "d'avoir pu voir tes POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ohohohoho… Quand je vois\p"
	.string "des POKéMON se battre, j'ai\n"
	.string "des frissons et je tremble…$"

Route114_Text_BernieIntro:
	.string "Avant d'allumer un feu de camp, il\n"
	.string "Assurez-vous d'avoir l'eau utile.$"

Route114_Text_BernieDefeat:
	.string "Merci d'avoir éteint mon feu!$"

Route114_Text_BerniePostBattle:
	.string "En forêt, il faut faire\n"
	.string "très attention au feu sous\p"
	.string "toutes ses formes. Ne\n"
	.string "du feu.$"

Route114_Text_BernieRegister:
	.string "Je meurs d'envie d'avoir une\n"
	.string "Enregistrons-nous!$"

Route114_Text_BernieRematchIntro:
	.string "Tu sais que pour faire un feu de\n"
	.string "pour les feux de camp?$"

Route114_Text_BernieRematchDefeat:
	.string "Je me suis pris une douche\n"
	.string "avant même de m'enflammer.$"

Route114_Text_BerniePostRematch:
	.string "En forêt, il faut faire\n"
	.string "très attention au feu sous\p"
	.string "toutes ses formes. Ne\n"
	.string "sous-estime pas sa puissance.$"

Route114_Text_ClaudeIntro:
	.string "Si on s'affrontait à la pêche,\n"
	.string "tu n'aurais aucune chance contre\l"
	.string "moi. Alors, amène tes POKéMON!$"

Route114_Text_ClaudeDefeat:
	.string "Si on avait pêché, j'aurais gagné…$"

Route114_Text_ClaudePostBattle:
	.string "Je crois que je vais essayer\n"
	.string "de faire une bonne prise au\p"
	.string "SITE METEORE. Il doit y avoir\n"
	.string "quelque chose là-bas. Je le sens!$"

Route114_Text_NolanIntro:
	.string "J'aime pêcher. Mais j'aime bien\n"
	.string "combattre aussi! Si quelqu'un me\p"
	.string "défie, je suis toujours prêt,\n"
	.string "même si je pêche.$"

Route114_Text_NolanDefeat:
	.string "J'aime combattre, mais ça ne\n"
	.string "veut pas dire que je suis bon…$"

Route114_Text_NolanPostBattle:
	.string "Cette fois, je vais y arriver! Je\p"
	.string "me dis toujours ça, j'arrête\n"
	.string "loin de la pêche ou POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA: Eh bien, oui. Je me\n"
	.string "sens d'humeur. Je vais t'en\l"
	.string "apprendre sur les POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA: Quel style de combat!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: Je donnais à IVY\n"
	.string "une leçon sur les POKéMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Hi, hi, hi… Si tu veux\n"
	.string "te battre contre nous, un\l"
	.string "seul POKéMON ne suffira pas!$"

Route114_Text_IvyIntro:
	.string "IVY: Qui t'a appris sur POKéMON?$"

Route114_Text_IvyDefeat:
	.string "IVY: Etonnante façon de se battre!$"

Route114_Text_IvyPostBattle:
	.string "IVY: J'ai commencé à entraîner\n"
	.string "des POKéMON car TYRA, mon cher\l"
	.string "professeur, me l'a enseigné!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: Tu n'as qu'un seul\n"
	.string "POKéMON? Il doit se sentir seul.$"

Route114_Text_KaiIntro:
	.string "J'en ai attrapé un\n"
	.string "gros! Un gros, je te dis!$"

Route114_Text_KaiDefeat:
	.string "Quoi la taille? Le mien a\n"
	.string "perdu à cause de sa taille?$"

Route114_Text_KaiPostBattle:
	.string "OK… Je vais en\n"
	.string "attraper un plus gros!$"

Route114_Text_CharlotteIntro:
	.string "Moi, je n'ai pas\n"
	.string "qu'un joli minois!$"

Route114_Text_CharlotteDefeat:
	.string "C'était pas mignon de ta part!$"

Route114_Text_CharlottePostBattle:
	.string "Je ne veux pas de POKéMON\n"
	.string "qui soient seulement\p"
	.string "mignons. Ils doivent avoir un\n"
	.string "petit je ne sais quoi en plus!$"

Route114_Text_AngelinaIntro:
	.string "As-tu bien fait\n"
	.string "évoluer tes POKéMON?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, je vois…\n"
	.string "C'est bon à savoir!$"

Route114_Text_AngelinaPostBattle:
	.string "Certains POKéMON changent\n"
	.string "Ils évoluent, c'est surprenant!$"

Route115_Text_TimothyIntro:
	.string "Hum… Tu as l'air tout à\n"
	.string "fait capable…\l"
	.string "Laisse-moi te tenir compagnie!$"

Route115_Text_TimothyDefeat:
	.string "Tu as plus de puissance\n"
	.string "que je ne l'avais imaginé!$"

Route115_Text_TimothyPostBattle:
	.string "Rien n'est inné! Tout\n"
	.string "s'acquiert par le\l"
	.string "travail! C'est ce que je crois…$"

Route115_Text_TimothyRegister:
	.string "Hmm… Cette défaite est un\n"
	.string "vieux souvenir pour moi.\p"
	.string "Si tu le permets, Je\n"
	.string "voudrais bien avoir ma revanche!$"

Route115_Text_TimothyRematchIntro:
	.string "Hum… Comme toujours, ton\n"
	.string "agilité parle d'elle-même.\l"
	.string "Viens me tenir compagnie!$"

Route115_Text_TimothyRematchDefeat:
	.string "Plus de force que jamais!$"

Route115_Text_TimothyPostRematch:
	.string "Tout est une question\p"
	.string "d'efforts! J'ai perdu car je\n"
	.string "n'ai pas fait assez d'efforts!$"

Route115_Text_KoichiIntro:
	.string "Toi! Mes\p"
	.string "MACHOC!\p"
	.string "J'exige un combat!$"

Route115_Text_KoichiDefeat:
	.string "Oh là là!$"

Route115_Text_KoichiPostBattle:
	.string "Mon équipe de MACHOC! Tant\p"
	.string "qu'ils chercheront la\n"
	.string "Devenez fort avec eux!$"

Route115_Text_NobIntro:
	.string "Mon plus grand talent, c'est de\n"
	.string "avec mon front!$"

Route115_Text_NobDefeat:
	.string "Aaaaaaaah! J'ai\n"
	.string "la tête en vrac!$"

Route115_Text_NobPostBattle:
	.string "J'ai appris le karaté à mon\p"
	.string "POKéMON. On dirait que ça lui\n"
	.string "Je suis excité par ça.$"

Route115_Text_NobRegister:
	.string "Tu m'impressionnes! Je prendrai ma\n"
	.string "revanche après mon entraînement!$"

Route115_Text_NobRematchIntro:
	.string "Après que tu m'as battu, on s'est\n"
	.string "entraînés dur pour s'améliorer…\l"
	.string "Allez, donne-nous une revanche!$"

Route115_Text_NobRematchDefeat:
	.string "Arrrrg! On a\n"
	.string "encore perdu!$"

Route115_Text_NobPostRematch:
	.string "Mon POKéMON va devenir plus\n"
	.string "Je vais redoubler d'entraînement!$"

Route115_Text_CyndyIntro:
	.string "Cette plage est le camp secret où\n"
	.string "Ne t'en mêle pas!$"

Route115_Text_CyndyDefeat:
	.string "Je ne me suis pas assez entraînée!$"

Route115_Text_CyndyPostBattle:
	.string "Le sable est comme un coussin qui\n"
	.string "amortit les chocs et qui empêche\l"
	.string "L'endroit idéal pour s'entraîner.$"

Route115_Text_CyndyRegister:
	.string "Bien… Tu es libre de venir. En\n"
	.string "retour, je veux te réaffronter.$"

Route115_Text_CyndyRematchIntro:
	.string "OK, que le combat commence!$"

Route115_Text_CyndyRematchDefeat:
	.string "Je peux lutter mais mon POKéMON...$"

Route115_Text_CyndyPostRematch:
	.string "Lorsque je perds, j'en tire\n"
	.string "quand même un certain plaisir. Ça\l"
	.string "doit être que j'aime mes POKéMON.$"

Route115_Text_HectorIntro:
	.string "J'ai un POKéMON rare!\n"
	.string "Tu voudrais le voir?$"

Route115_Text_HectorDefeat:
	.string "Tu… Tu veux mon\n"
	.string "POKéMON, c'est ça?$"

Route115_Text_HectorPostBattle:
	.string "J'ai ce POKéMON rare.\n"
	.string "Je ne le céderai pas.$"

Route115_Text_KyraIntro:
	.string "Je vais me battre en\n"
	.string "courant! Essaie de me rattraper!$"

Route115_Text_KyraDefeat:
	.string "J'ai un point de côté…$"

Route115_Text_KyraPostBattle:
	.string "J'ai fait l'erreur de vouloir me\n"
	.string "battre en courant! Je devrais\p"
	.string "faire une course pour me calmer!$"

Route115_Text_JaidenIntro:
	.string "Prends ça! Attaque\n"
	.string "ninja ultra POKéMON!$"

Route115_Text_JaidenDefeat:
	.string "Ouaaah! Ma stratégie\n"
	.string "n'était pas la bonne!$"

Route115_Text_JaidenPostBattle:
	.string "Mais mes POKéMON\n"
	.string "étaient super géniaux, non?$"

Route115_Text_HeleneIntro:
	.string "Mes POKéMON mériteraient\n"
	.string "d'avoir une ceinture noire!$"

Route115_Text_HeleneDefeat:
	.string "Quelle humiliation!$"

Route115_Text_HelenePostBattle:
	.string "J'ai rarement vu quelqu'un\n"
	.string "d'aussi fort que moi… J'ai\p"
	.string "compris! Tu dois être un\n"
	.string "CHAMPION D'ARÈNE, n'est-ce pas?$"

Route115_Text_AlixIntro:
	.string "Tu oses croiser mon regard?\n"
	.string "Pas d'échappatoire pour toi!$"

Route115_Text_AlixDefeat:
	.string "Gaaah!\n"
	.string "Pas mal!$"

Route115_Text_AlixPostBattle:
	.string "Très bien! Je vais me\n"
	.string "TÉLÉPORTER à la maison!$"

Route115_Text_MarleneIntro:
	.string "Tu déranges ma méditation…\n"
	.string "Je vais te le faire payer!$"

Route115_Text_MarleneDefeat:
	.string "Tu as brisé ma concentration!$"

Route115_Text_MarlenePostBattle:
	.string "Je méditais avec mes POKéMON.\n"
	.string "Mais ce n'est pas l'endroit idéal…$"

Route116_Text_ClarkIntro:
	.string "S'il n'y a pas de tunnel de\n"
	.string "Je vais juste passer par le haut.$"

Route116_Text_ClarkDefeat:
	.string "Pfou… Pfou… Ça\n"
	.string "fatigue de perdre…$"

Route116_Text_ClarkPostBattle:
	.string "C'est pas grave s'il n'y a pas de\n"
	.string "tunnel. Un MONTAGNARD grimpe!$"

Route116_Text_JoeyIntro:
	.string "Mon POKéMON est le\n"
	.string "roi! Regarde un peu!$"

Route116_Text_JoeyDefeat:
	.string "Aïe! Une coupure! Il faut\n"
	.string "que je mette un pansement!$"

Route116_Text_JoeyPostBattle:
	.string "Les pansements prouvent la\n"
	.string "J'en ai une autre!$"

Route116_Text_JoseIntro:
	.string "Mes POKéMON INSECTE sont\n"
	.string "résistants! Battons-nous!$"

Route116_Text_JoseDefeat:
	.string "J'ai perdu! Je\n"
	.string "croyais pouvoir te vaincre!$"

Route116_Text_JosePostBattle:
	.string "Les POKéMON INSECTE évoluent vite.\n"
	.string "ils deviennent vite forts aussi.$"

Route116_Text_JaniceIntro:
	.string "Laisse-moi te montrer comme\n"
	.string "mon adorable POKéMON est fort!$"

Route116_Text_JaniceDefeat:
	.string "Tu es un cran au-dessus de moi...$"

Route116_Text_JanicePostBattle:
	.string "Je trouve que l'idéal pour un\n"
	.string "Le pouvoir, c'est idéal, je crois.$"

Route116_Text_JerryIntro:
	.string "On apprend toutes sortes de\n"
	.string "choses à l'ECOLE DE DRESSEURS. Je\p"
	.string "veux mettre tout ça en pratique!$"

Route116_Text_JerryDefeat:
	.string "Je me suis un peu relâché à\n"
	.string "C'est pour ça que j'ai perdu.$"

Route116_Text_JerryPostBattle:
	.string "Je vais devoir reprendre des\n"
	.string "cours à l'ECOLE DE\l"
	.string "Sinon, ROXANNE sera à la vapeur.$"

Route116_Text_JerryRegister1:
	.string "J'ai appris à l'ECOLE DE DRESSEURS\n"
	.string "que les POKéNAVS peuvent\p"
	.string "enregistrer les DRESSEURS. Je sais\n"
	.string "Alors je peux essayer?$"

Route116_Text_JerryRegister2:
	.string "J'ai appris à l'ECOLE DE DRESSEURS\n"
	.string "que les POKéNAVS peuvent\p"
	.string "enregistrer les DRESSEURS. Je sais\n"
	.string "Alors je peux essayer?$"

Route116_Text_JerryRematchIntro:
	.string "J'ai étudié sérieusement à\n"
	.string "l'ECOLE DE DRESSEURS. Cette\l"
	.string "fois, je ne vais pas perdre.$"

Route116_Text_JerryRematchDefeat:
	.string "Hum? J'ai étudié\n"
	.string "avec assiduité.$"

Route116_Text_JerryPostRematch:
	.string "Je vais devoir reprendre des\n"
	.string "cours à l'ECOLE DE\l"
	.string "Sinon, ROXANNE sera à la vapeur.$"

Route116_Text_KarenIntro:
	.string "J'étudie à l'école et\n"
	.string "Le chemin de la maison aussi!$"

Route116_Text_KarenDefeat:
	.string "Quel choc! J'ai perdu?$"

Route116_Text_KarenPostBattle:
	.string "C'est pas comme ça que je vais\n"
	.string "DRESSEUR comme ROXANNE par ici!$"

Route116_Text_KarenRegister1:
	.string "Oh, waouh! C'est un POKéNAV? J'en\n"
	.string "J'en ai un, s'il vous plaît.$"

Route116_Text_KarenRegister2:
	.string "Oh, waouh! C'est un POKéNAV? J'en\n"
	.string "J'en ai un, s'il vous plaît.$"

Route116_Text_KarenRematchIntro:
	.string "J'ai beaucoup appris depuis la\n"
	.string "Vous devez voir mes réalisations!$"

Route116_Text_KarenRematchDefeat:
	.string "Quel choc!\n"
	.string "J'ai encore perdu?$"

Route116_Text_KarenPostRematch:
	.string "Tu as battu ROXANNE? Je ne vais\n"
	.string "pas pouvoir te battre. Pas encore.$"

Route116_Text_SarahIntro:
	.string "Pour ta gouverne, personne n'a\n"
	.string "jamais pu me vaincre, personne!$"

Route116_Text_SarahDefeat:
	.string "Eh bien, quelle\n"
	.string "expérience troublante…$"

Route116_Text_SarahPostBattle:
	.string "J'ai les moyens de\n"
	.string "m'offrir tout ce que je\p"
	.string "souhaite! Mais pour les\n"
	.string "Ma richesse n'a pas de sens.$"

Route116_Text_DawsonIntro:
	.string "Si tu poses les yeux sur mes\n"
	.string "POKéMON, leur beauté te laissera\l"
	.string "Tu es sans défense!$"

Route116_Text_DawsonDefeat:
	.string "Oh, dis-moi que ça n'est pas vrai!$"

Route116_Text_DawsonPostBattle:
	.string "Oh, non, non, non! Tu as abîmé\n"
	.string "la fourrure de mes POKéMON! Et\l"
	.string "aussi mon brushing! Je n'ai\l"
	.string "plus qu'à appeler mon styliste!$"

Route116_Text_DevanIntro:
	.string "On va te faire du mal!$"

Route116_Text_DevanDefeat:
	.string "Aïe\n"
	.string "aïe aïe!$"

Route116_Text_DevanPostBattle:
	.string "Je devrais essayer d'autres types\n"
	.string "C'est ce que je devrais faire.$"

Route116_Text_JohnsonIntro:
	.string "C'est une voie sans\n"
	.string "issue. Je m'ennuie… On se bat?$"

Route116_Text_JohnsonDefeat:
	.string "C'était sympa même si j'ai perdu.$"

Route116_Text_JohnsonPostBattle:
	.string "Tu voudrais pas rester ici\n"
	.string "pour me tenir compagnie?$"

Route117_Text_IsaacIntro:
	.string "Dis donc, tu pourrais te battre\n"
	.string "contre les POKéMON que j'élève?$"

Route117_Text_IsaacDefeat:
	.string "Tu as très bien élevé les tiens…$"

Route117_Text_IsaacPostBattle:
	.string "Les POKéMON, ce n'est pas qu'une\p"
	.string "question de force. Parfaire la\n"
	.string "particularité d'une personnalité,\l"
	.string "C'est POKéMON.$"

Route117_Text_IsaacRegister:
	.string "Je vais m'entraîner deux\n"
	.string "fois plus. Tu viendras me voir?$"

Route117_Text_IsaacRematchIntro:
	.string "Les POKéMON que j'élève ont l'air\n"
	.string "en forme, exactement comme avant.$"

Route117_Text_IsaacRematchDefeat:
	.string "Tu sais les élever comme il\n"
	.string "faut. Tu tiendrais une PENSION.$"

Route117_Text_IsaacPostRematch:
	.string "Tes POKéMON grandissent bien! Tu\n"
	.string "Vous devriez entrer dans CONTESTS.$"

Route117_Text_LydiaIntro:
	.string "Tu permets que je vérifie si\n"
	.string "tes POKéMON se développent bien?$"

Route117_Text_LydiaDefeat:
	.string "Oui, ils grandissent bien.$"

Route117_Text_LydiaPostBattle:
	.string "Essaie d'élever tes POKéMON en\n"
	.string "attention à leurs caractères.$"

Route117_Text_LydiaRegister:
	.string "Je suis contente d'avoir rencontré\n"
	.string "J'espère vous revoir.$"

Route117_Text_LydiaRematchIntro:
	.string "Tu permets que je revérifie si\n"
	.string "tu as bien élevé tes POKéMON?$"

Route117_Text_LydiaRematchDefeat:
	.string "Ils grandissent admirablement.$"

Route117_Text_LydiaPostRematch:
	.string "Les POKéMON aiment différentes\n"
	.string "sortes de {POKEBLOCK}S selon leur nature.$"

Route117_Text_DylanIntro:
	.string "Je suis en plein milieu d'un\n"
	.string "Peu importe, faisons une bataille!$"

Route117_Text_DylanDefeat:
	.string "Je n'ai plus du tout de force!$"

Route117_Text_DylanPostBattle:
	.string "J'aurais pu te balayer…\p"
	.string "J'aurais peut-être dû ralentir\n"
	.string "le rythme pour tenir sur la durée…$"

Route117_Text_DylanRegister:
	.string "Les POKéMON aussi doivent être\n"
	.string "J'aimerais que tu m'entraînes!$"

Route117_Text_DylanRematchIntro:
	.string "On n'est qu'à la moitié du\n"
	.string "triathlon et je suis claqué, mais\l"
	.string "je suis en tête. Affrontons-nous!$"

Route117_Text_DylanRematchDefeat:
	.string "Je suis encore à bout de forces!$"

Route117_Text_DylanPostRematch:
	.string "Je suis au top à la natation et\n"
	.string "en cyclisme, mais je ne suis pas\l"
	.string "aussi confiant pour les POKéMON.$"

Route117_Text_MariaIntro:
	.string "Je fais du triathlon avec mon\n"
	.string "Donc j'ai confiance en ma vitesse.$"

Route117_Text_MariaDefeat:
	.string "Je crois qu'il me\n"
	.string "faut plus de pratique.$"

Route117_Text_MariaPostBattle:
	.string "L'entraînement n'a de sens\n"
	.string "que s'il est pratiqué\p"
	.string "régulièrement. OK! Je me\n"
	.string "Demain!$"

Route117_Text_MariaRegister:
	.string "Ton entraînement a l'air d'être\n"
	.string "Si tu veux, je te bats plus tard!$"

Route117_Text_MariaRematchIntro:
	.string "Tu continues à\n"
	.string "t'entraîner? Moi, oui!\l"
	.string "Laisse-moi te le prouver!$"

Route117_Text_MariaRematchDefeat:
	.string "Je crois qu'il me\n"
	.string "faut plus de pratique.$"

Route117_Text_MariaPostRematch:
	.string "Demain, je me remets à\n"
	.string "Rebattons-nous un jour!$"

Route117_Text_DerekIntro:
	.string "Hier un SCOUT… et\n"
	.string "maintenant un\p"
	.string "ENTOMOMANIAC! Mais mon amour\n"
	.string "pour les POKéMON reste intact!$"

Route117_Text_DerekDefeat:
	.string "Mon incompétence, elle\n"
	.string "aussi, est toujours intacte…$"

Route117_Text_DerekPostBattle:
	.string "Je n'ai fait que suivre mon cœur,\n"
	.string "et me voilà considéré comme un\p"
	.string "ENTOMOMANIAC. Enfin, étant un\n"
	.string "expert en POKéMON INSECTE, c'est\l"
	.string "Un manoeuvreux.$"

Route117_Text_AnnaIntro:
	.string "ANNA: Je suis avec ma charmante\n"
	.string "Je dois faire le bien!$"

Route117_Text_AnnaDefeat:
	.string "ANNA: Je suis avec ma charmante\n"
	.string "Laisse-moi gagner!$"

Route117_Text_AnnaPostBattle:
	.string "ANNA: Tes POKéMON se\n"
	.string "complètent bien. Je dirais\p"
	.string "que tu es juste derrière nous!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA: On ne peut pas en\n"
	.string "rester là! Tu reviendras, hein?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA: Si tu veux nous\n"
	.string "Apportez deux POKéMON avec vous.$"

Route117_Text_MegIntro:
	.string "EVA: On va s'accrocher avec ma\n"
	.string "partenaire de choc! On t'écrasera!$"

Route117_Text_MegDefeat:
	.string "EVA: Oh, non! ANNA, je\n"
	.string "suis désolée de te décevoir…$"

Route117_Text_MegPostBattle:
	.string "EVA: J'ai déçu ANNA…\n"
	.string "Sans moi, elle aurait gagné!$"

Route117_Text_MegNotEnoughMons:
	.string "EVA: Tu n'as qu'un seul POKéMON?\n"
	.string "on ne va pas pouvoir s'affronter.\p"
	.string "On veut combattre en 2 contre 2.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: Je ne peux pas continuer à\n"
	.string "Mon associé junior, c'est ça?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: Je n'ai pas pris le rythme.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA: Tes POKéMON se\n"
	.string "complètent bien. Je dirais\p"
	.string "que tu es juste derrière nous!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: Si tu veux nous\n"
	.string "Apportez deux POKéMON avec vous.$"

Route117_Text_MegRematchIntro:
	.string "EVA: On va s'accrocher avec ma\n"
	.string "partenaire. Cette fois, on gagne!$"

Route117_Text_MegRematchDefeat:
	.string "EVA: Trop balèze pour nous!$"

Route117_Text_MegPostRematch:
	.string "EVA: On s'est battues avec\n"
	.string "ma partenaire, mais on a\p"
	.string "perdu… C'est décourageant…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "EVA: Tu n'as qu'un seul POKéMON?\n"
	.string "on ne va pas pouvoir s'affronter.\p"
	.string "On veut combattre en 2 contre 2.$"

Route117_Text_MelinaIntro:
	.string "C'est sympa, hein? Se battre\n"
	.string "aux jolies fleurs?$"

Route117_Text_MelinaDefeat:
	.string "Oh, c'était très impressionnant!$"

Route117_Text_MelinaPostBattle:
	.string "Rien de mieux qu'un petit\n"
	.string "jogging en pleine nature.$"

Route117_Text_BrandiIntro:
	.string "Laisse-moi te montrer la\n"
	.string "force cachée des POKéMON PSY!$"

Route117_Text_BrandiDefeat:
	.string "Etonnant!$"

Route117_Text_BrandiPostBattle:
	.string "Les POKéMON PSY sont complexes.\n"
	.string "Tu devrais essayer d'en attraper.$"

Route117_Text_AishaIntro:
	.string "Se concentrer sur la victoire!\n"
	.string "C'est comme ça que je combats!$"

Route117_Text_AishaDefeat:
	.string "Je ne me morfonds jamais en cas de\n"
	.string "défaite… Je retourne m'entraîner!$"

Route117_Text_AishaPostBattle:
	.string "Si tu penses trop à la défaite,\n"
	.string "tu as plus de chances de perdre.$"

Route118_Text_RoseIntro:
	.string "Le parfum des fleurs a un pouvoir\n"
	.string "Il nous purifie le corps et l'âme.$"

Route118_Text_RoseDefeat:
	.string "Oh là là! On dirait\n"
	.string "bien que j'ai perdu.$"

Route118_Text_RosePostBattle:
	.string "Les fleurs, les\n"
	.string "POKéMON… J'aime tout ce\p"
	.string "qui sent bon. Tout ce qui\n"
	.string "pue… C'est pas pour moi!$"

Route118_Text_RoseRegister:
	.string "Sniff… Cette odeur… C'est un\n"
	.string "Nous devons nous enregistrer!$"

Route118_Text_RoseRematchIntro:
	.string "Est-ce ce doux parfum\n"
	.string "qui t'a fait venir ici?$"

Route118_Text_RoseRematchDefeat:
	.string "Le pouvoir du parfum… Ça\n"
	.string "n'a pas changé grand-chose.$"

Route118_Text_RosePostRematch:
	.string "Si tu sais bien utiliser un doux\n"
	.string "POKéMON sera attiré par elle.$"

Route118_Text_PerryIntro:
	.string "Les POKéMON OISEAU qui volent avec\n"
	.string "Le ciel... c'est le meilleur!$"

Route118_Text_PerryDefeat:
	.string "Arrg… Je me\n"
	.string "suis fait écraser…$"

Route118_Text_PerryPostBattle:
	.string "Tu es balèze! Je vais devoir\n"
	.string "perfectionner mon entraînement.$"

Route118_Text_ChesterIntro:
	.string "Prenez votre envol!\n"
	.string "Mes POKéMON OISEAU!$"

Route118_Text_ChesterDefeat:
	.string "Ils ont pris le vol...$"

Route118_Text_ChesterPostBattle:
	.string "S'ils étaient plus forts, ils\n"
	.string "pourraient voler plus librement…$"

Route118_Text_BarnyIntro:
	.string "Je suis PECHEUR, mais aussi\n"
	.string "J'élève le POKéMON que j'ai pris.$"

Route118_Text_BarnyDefeat:
	.string "Je croyais pourtant que je\n"
	.string "m'entraînais correctement…$"

Route118_Text_BarnyPostBattle:
	.string "Je ne pourrai pas gagner si\n"
	.string "j'entraîne mes POKéMON tout en\p"
	.string "J'ai fait les choses en deux?$"

Route118_Text_WadeIntro:
	.string "Pour les PECHEURS, le matériel est\p"
	.string "la clé de tout. Mais l'essentiel\n"
	.string "sont POKéMON et coeur, bien sûr!$"

Route118_Text_WadeDefeat:
	.string "Ai-je été touché en plein cœur?$"

Route118_Text_WadePostBattle:
	.string "Si tu y penses, la pêche c'est\n"
	.string "entre un FISHERMAN et un POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Laisse ma mélodie bercer ton âme!$"

Route118_Text_DaltonDefeat:
	.string "La, lalala…$"

Route118_Text_DaltonPostBattle:
	.string "Une guitare électrique, ça ne fait\n"
	.string "pas toujours un bruit terrible… On\p"
	.string "peut pincer les cordes de façon à\n"
	.string "en tirer cette émouvante mélodie…$"

Route118_Text_DaltonRegister:
	.string "Tu viendras écouter mes\n"
	.string "prochaines compositions?$"

Route118_Text_DaltonRematchIntro:
	.string "La mélodie de mes POKéMON et moi…\n"
	.string "Délivrons-le à votre âme.$"

Route118_Text_DaltonRematchDefeat:
	.string "La, lalala…$"

Route118_Text_DaltonPostRematch:
	.string "Quand je joue, mes émotions\n"
	.string "à travers ma guitare électrique...$"

Route118_Text_DeandreIntro:
	.string "Go, go, go!\n"
	.string "POKéMON 1, 2, et 3!$"

Route118_Text_DeandreDefeat:
	.string "POKéMON 1, 2, et\n"
	.string "3? Est-ce que ça va?$"

Route118_Text_DeandrePostBattle:
	.string "C'est cool d'avoir toute une\n"
	.string "équipe de POKéMON pour se battre!\p"
	.string "Vous pouvez me copier...$"

Route119_Text_BrentIntro:
	.string "On est le CLUB COPIE!\n"
	.string "On COPIE ce que tu fais!$"

Route119_Text_BrentDefeat:
	.string "Oups! On\n"
	.string "a perdu!$"

Route119_Text_BrentPostBattle:
	.string "Qu'y a-t-il de drôle à\p"
	.string "copier les autres?\n"
	.string "Pffffff… Tu ne comprendras jamais…$"

Route119_Text_DonaldIntro:
	.string "Ah, on se rencontre enfin! Mes\n"
	.string "Mes INSECTE t'accompagneront.$"

Route119_Text_DonaldDefeat:
	.string "J'aurais préféré ne pas te voir…$"

Route119_Text_DonaldPostBattle:
	.string "Je voudrais te copier encore un\n"
	.string "Tu peux te dépêcher et bouger?$"

Route119_Text_TaylorIntro:
	.string "Si tu avances, on avance. Si tu\p"
	.string "tournes à droite, on tourne aussi.$"

Route119_Text_TaylorDefeat:
	.string "Mais si tu gagnes, je perds…$"

Route119_Text_TaylorPostBattle:
	.string "Je ne peux pas copier ta\n"
	.string "victoire. C'est tout bonnement\l"
	.string "impossible… Ça me met en pétard…$"

Route119_Text_DougIntro:
	.string "Hé, t'as finalement réussi à\n"
	.string "Ou essayiez vous de m'éviter?$"

Route119_Text_DougDefeat:
	.string "Ouuuuh, c'était un beau combat!$"

Route119_Text_DougPostBattle:
	.string "On est le CLUB COPIE!\n"
	.string "J'espère que ça t'a plu.$"

Route119_Text_GregIntro:
	.string "Tu ne sais pas qui je suis,\p"
	.string "hein? Mais je ne te connais pas\n"
	.string "non plus. Alors on va se battre!$"

Route119_Text_GregDefeat:
	.string "T'es plutôt balèze!$"

Route119_Text_GregPostBattle:
	.string "On copiera chacun de tes\n"
	.string "Continue d'imiter tes mouvements.$"

Route119_Text_KentIntro:
	.string "Le CLUB COPIE a été fondé par des\n"
	.string "personnes aimant COPIER les\p"
	.string "autres. Un regard lance le combat!$"

Route119_Text_KentDefeat:
	.string "J'abandonne!$"

Route119_Text_KentPostBattle:
	.string "Rejoins-tu notre CLUB COPIE?$"

Route119_Text_JacksonIntro:
	.string "Qui sait toujours\n"
	.string "comment faire pour survivre?\p"
	.string "Nous, les POKéMON RANGERS!$"

Route119_Text_JacksonDefeat:
	.string "Je ne connais pas\n"
	.string "Savoir-faire...$"

Route119_Text_JacksonPostBattle:
	.string "Fuir la civilisation et\n"
	.string "éveiller l'instinct sauvage qui\p"
	.string "est en nous! C'est notre devise!$"

Route119_Text_JacksonRegister:
	.string "J'espère qu'on s'affrontera encore\n"
	.string "se moquer de mon manque de savoir.$"

Route119_Text_JacksonRematchIntro:
	.string "Je vais faire renaître mon\n"
	.string "être avec POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "Toujours autant de force!$"

Route119_Text_JacksonPostRematch:
	.string "Crois en tes POKéMON.\n"
	.string "Crois en toi. Le\p"
	.string "reste se fera tout seul.$"

Route119_Text_CatherineIntro:
	.string "Hé, regarde-toi. Pour\p"
	.string "quelqu'un qui part à\n"
	.string "Vous voyagez très léger.$"

Route119_Text_CatherineDefeat:
	.string "Les accidents se produisent\n"
	.string "quand on ne s'y attend pas!$"

Route119_Text_CatherinePostBattle:
	.string "Tu voyages léger, mais\n"
	.string "tu as tout ce qu'il te\p"
	.string "faut. Tu es mentalement\n"
	.string "et physiquement au top.$"

Route119_Text_CatherineRegister:
	.string "Est-ce que tu as un POKéNAV?\n"
	.string "C'est un outil indispensable\p"
	.string "pour un DRESSEUR. Oh, tu en as\n"
	.string "un! Enregistrons-nous alors!$"

Route119_Text_CatherineRematchIntro:
	.string "Comment se passe ton\n"
	.string "voyage avec tes POKéMON?$"

Route119_Text_CatherineRematchDefeat:
	.string "Il me manque quelque chose…$"

Route119_Text_CatherinePostRematch:
	.string "En tant que DRESSEUR, tu as\n"
	.string "confiance en tes POKéMON et eux,\l"
	.string "compte sur toi.$"

Route119_Text_HughIntro:
	.string "Le ciel, si vaste, tient une\p"
	.string "grande promesse! Rien n'est\n"
	.string "aussi intense que de voler!$"

Route119_Text_HughDefeat:
	.string "A terre et hors combat!$"

Route119_Text_HughPostBattle:
	.string "Mon POKéMON OISEAU m'a permis de\n"
	.string "réaliser mon rêve. Je peux voler!$"

Route119_Text_PhilIntro:
	.string "Je vais te montrer mon vrai\n"
	.string "et mon BIRD POKéMON!$"

Route119_Text_PhilDefeat:
	.string "Nous avons manqué de potentiel…$"

Route119_Text_PhilPostBattle:
	.string "Tout petit déjà,\n"
	.string "j'admirais les POKéMON OISEAU…$"

Route119_Text_YasuIntro:
	.string "Me cacher dans l'ombre et vivre\n"
	.string "dans l'obscurité… Tel est mon\p"
	.string "destin. J'émerge pour te défier!$"

Route119_Text_YasuDefeat:
	.string "J'admets la défaite!$"

Route119_Text_YasuPostBattle:
	.string "Les perdants se retirent\n"
	.string "discrètement pour retourner dans\l"
	.string "Ça aussi, c'est le destin...$"

Route119_Text_TakashiIntro:
	.string "Quand on ne se méfie pas, on\n"
	.string "prend le risque de souffrir!$"

Route119_Text_TakashiDefeat:
	.string "Ta force est surprenante!$"

Route119_Text_TakashiPostBattle:
	.string "Mon attaque\n"
	.string "surprise a échoué…$"

Route119_Text_HideoIntro:
	.string "L'arbre cache la forêt!$"

Route119_Text_HideoDefeat:
	.string "Je m'incline à ta supériorité.$"

Route119_Text_HideoPostBattle:
	.string "L'arbre cache la forêt!\n"
	.string "Un POKéMON cache un autre\p"
	.string "POKéMON! Il n'y a pas de\n"
	.string "sens caché derrière ça.$"

Route119_Text_ChrisIntro:
	.string "Tu m'as parlé… Alors tu veux\n"
	.string "m'affronter! Pas de\p"
	.string "problème! Je vais tester le\n"
	.string "Pendant qu'il s'enfuit!$"

Route119_Text_ChrisDefeat:
	.string "Je n'ai pas la moindre idée\n"
	.string "de ce qu'il faut pour gagner.$"

Route119_Text_ChrisPostBattle:
	.string "Monter sur mon POKéMON pour faire\p"
	.string "du SURF… Et ensuite, pêcher sur\p"
	.string "C'est un moment indescriptible!$"

Route119_Text_FabianIntro:
	.string "Je vais exploser mon\n"
	.string "ampli! La victoire est à\l"
	.string "moi! Ça va vibrer, tu vas voir!$"

Route119_Text_FabianDefeat:
	.string "Tu m'as montré qui est le\n"
	.string "boss, je repars avec mes bosses!$"

Route119_Text_FabianPostBattle:
	.string "J'ai débranché mon\n"
	.string "ampli. Laisse-moi\l"
	.string "seul avec ma défaite.$"

Route119_Text_DaytonIntro:
	.string "Hohoho! J'adore me\n"
	.string "battre contre de\l"
	.string "jeunes DRESSEURS!$"

Route119_Text_DaytonDefeat:
	.string "T'es plutôt\n"
	.string "incroyable!$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho! Je\n"
	.string "vais continuer\l"
	.string "de m'entraîner!$"

Route119_Text_RachelIntro:
	.string "Où que je sois et quoi que je\n"
	.string "J'ai toujours mon parasol en main.$"

Route119_Text_RachelDefeat:
	.string "Mais… C'est\n"
	.string "pas juste!$"

Route119_Text_RachelPostBattle:
	.string "Tu me demandes si mon parasol\n"
	.string "n'est pas trop lourd? Ton SAC est\l"
	.string "J'ai jamais fait le tour.$"

Route120_Text_ColinIntro:
	.string "Connais-tu une capacité\n"
	.string "pouvant toucher un POKéMON en vol?$"

Route120_Text_ColinDefeat:
	.string "Tu es au-dessus de moi!$"

Route120_Text_ColinPostBattle:
	.string "La capacité VOL est très\n"
	.string "pratique, tu ne trouves pas?\p"
	.string "Presque aucune capacité ne\n"
	.string "peut atteindre un POKéMON en vol.$"

Route120_Text_RobertIntro:
	.string "Mon POKéMON est\n"
	.string "fort! Et les tiens?$"

Route120_Text_RobertDefeat:
	.string "Tes POKéMON étaient plus forts…$"

Route120_Text_RobertPostBattle:
	.string "Si un POKéMON progresse avec\n"
	.string "Vous pouvez compter sur.$"

Route120_Text_RobertRegister:
	.string "Je suis sûr que tu vas progresser.\n"
	.string "Je t'ajoute à mon POKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "Si un POKéMON progresse avec\n"
	.string "Vous pouvez compter sur.$"

Route120_Text_RobertRematchDefeat:
	.string "Tes POKéMON sont très forts.$"

Route120_Text_RobertPostRematch:
	.string "Mes POKéMON deviennent plus forts.\n"
	.string "Je dois aussi devenir plus fort.$"

Route120_Text_LorenzoIntro:
	.string "Je vais vérifier si tes POKéMON\n"
	.string "sont prêts à prendre le grand air.$"

Route120_Text_LorenzoDefeat:
	.string "Avec des POKéMON aussi forts que\n"
	.string "Aucun danger de besoin de secours!$"

Route120_Text_LorenzoPostBattle:
	.string "Voyager au gré de ses\n"
	.string "envies avec ses POKéMON… C'est\l"
	.string "le privilège d'être DRESSEUR.$"

Route120_Text_JennaIntro:
	.string "Comment te sens-tu? Si tu n'es pas\n"
	.string "en pleine forme, ça peut être\l"
	.string "Dans les situations critiques.$"

Route120_Text_JennaDefeat:
	.string "Je suis en pleine forme, mais...$"

Route120_Text_JennaPostBattle:
	.string "J'ai l'habitude de faire de\n"
	.string "Je cours toujours avec ma POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … … …\n"
	.string "… … … … … Tu\l"
	.string "veux te battre?$"

Route120_Text_JeffreyDefeat:
	.string "Vaincu…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … … … … …\n"
	.string "… … … Je vais\l"
	.string "essayer de faire mieux…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … … …\n"
	.string "… … … … … Tu\l"
	.string "as un POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … … … …\n"
	.string "… … … … Tu veux\l"
	.string "encore te battre?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "J'ai encore perdu…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … … … … … … …\n"
	.string "… Je vais essayer de\l"
	.string "faire mieux… Pour mes\l"
	.string "précieux POKéMON INSECTE…$"

Route120_Text_JenniferIntro:
	.string "Les POKéMON ont de nombreuses\n"
	.string "capacités spéciales. Pour devenir\l"
	.string "DRESSEUR, apprenez-en.$"

Route120_Text_JenniferDefeat:
	.string "Tu réfléchis, évidemment.$"

Route120_Text_JenniferPostBattle:
	.string "Les capacités spéciales des\n"
	.string "changera les styles de combat.$"

Route120_Text_ChipIntro:
	.string "Qui pourrais-tu bien être?\p"
	.string "Peut-être es-tu à la recherche\n"
	.string "des ruines antiques qui, selon\l"
	.string "la légende, pourraient exister?$"

Route120_Text_ChipDefeat:
	.string "Quelle infâme mésaventure…$"

Route120_Text_ChipPostBattle:
	.string "Ce rocher géant… Je voudrais\n"
	.string "croire qu'il renferme des ruines\l"
	.string "Mais je ne vois pas d'entrée.$"

Route120_Text_ClarissaIntro:
	.string "Pourquoi j'ai ce parasol? Je te le\p"
	.string "dirai si tu réussis à me battre.$"

Route120_Text_ClarissaDefeat:
	.string "Un parasol ne permet pas\n"
	.string "d'éviter les attaques de POKéMON…$"

Route120_Text_ClarissaPostBattle:
	.string "Je ne pense pas que la lumière\n"
	.string "intense soit bénéfique à mes\l"
	.string "Je les protège de mon parasol.$"

Route120_Text_AngelicaIntro:
	.string "Mon POKéMON, mon parasol et moi…\p"
	.string "Si l'un d'entre nous manque, la\n"
	.string "l'image de la beauté sera ruinée.$"

Route120_Text_AngelicaDefeat:
	.string "Tu as ruiné ma beauté...$"

Route120_Text_AngelicaPostBattle:
	.string "Un parasol, ça ne\p"
	.string "t'irait pas du tout. Ça\n"
	.string "ne ferait que t'encombrer…$"

Route120_Text_KeigoIntro:
	.string "Je vais adopter les mouvements des\n"
	.string "POKéMON et créer des arts ninja.$"

Route120_Text_KeigoDefeat:
	.string "La création de nouvelles\n"
	.string "techniques ninja n'est qu'un rêve…$"

Route120_Text_KeigoPostBattle:
	.string "J'aurais peut-être dû suivre les\n"
	.string "enseignements d'un maître ninja.$"

Route120_Text_RileyIntro:
	.string "Nous, les ninjas, on se dissimule\n"
	.string "derrière nos capes de camouflage.\l"
	.string "Tu ignorais où j'étais, hein?$"

Route120_Text_RileyDefeat:
	.string "J'ai perdu! Je vais\n"
	.string "devoir dissimuler ma honte!$"

Route120_Text_RileyPostBattle:
	.string "Nos capes de camouflage\n"
	.string "sont toutes faites à la main.$"

Route120_Text_CallieIntro:
	.string "Si tu ne fais pas\n"
	.string "Tu pourrais être blessé!$"

Route120_Text_CallieDefeat:
	.string "Ouch! C'est moi\n"
	.string "qui me suis fait mal!$"

Route120_Text_CalliePostBattle:
	.string "Je me demande… Dois-je faire\n"
	.string "Ils sont mignons comme ils sont.$"

Route120_Text_LeonelIntro:
	.string "Ton équipe de POKéMON…\n"
	.string "Est-ce que tu as d'autres types?$"

Route120_Text_LeonelDefeat:
	.string "J'ai vu votre politique en action!$"

Route120_Text_LeonelPostBattle:
	.string "Rien de mieux que de se\n"
	.string "battre avec ses POKéMON préférés!$"

Route121_Text_VanessaIntro:
	.string "Tu veux jouer avec\n"
	.string "mon adorable POKéMON?$"

Route121_Text_VanessaDefeat:
	.string "C'est pas ce que je voulais dire!$"

Route121_Text_VanessaPostBattle:
	.string "Je vais à un CONCOURS à\p"
	.string "NENUCRIQUE. Mon POKéMON ne devrait\n"
	.string "balayant la CLASSE MASTER.$"

Route121_Text_WalterIntro:
	.string "Avec les POKéMON, j'ai voyagé\n"
	.string "aux quatre coins du monde. Tu\p"
	.string "dois te dire que je suis confiant\n"
	.string "dans mes capacités.$"

Route121_Text_WalterDefeat:
	.string "Ah, bien joué!$"

Route121_Text_WalterPostBattle:
	.string "Je voudrais bien\n"
	.string "refaire le tour du globe!$"

Route121_Text_WalterRegister:
	.string "Les prouesses de tes POKéMON sont\n"
	.string "remarquables. Je note ton POKéNAV.$"

Route121_Text_WalterRematchIntro:
	.string "Avec les POKéMON, j'ai voyagé\n"
	.string "aux quatre coins du monde. Tu\p"
	.string "dois te dire que je suis confiant\n"
	.string "dans mes capacités.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, bien joué!$"

Route121_Text_WalterPostRematch:
	.string "Tes POKéMON et toi… La\p"
	.string "prouesse que vous avez accomplie\n"
	.string "considéré fort, même à l'étranger.$"

Route121_Text_TammyIntro:
	.string "Dans ce monde, il existe des\n"
	.string "la compréhension dans le monde...$"

Route121_Text_TammyDefeat:
	.string "J'ai perdu…$"

Route121_Text_TammyPostBattle:
	.string "MONT MEMORIA… Là,\n"
	.string "un mystérieux\l"
	.string "pouvoir est en action…$"

Route121_Text_KateIntro:
	.string "VIVI: Ensemble, on ne connaît pas\n"
	.string "la peur! Tu verras notre force!$"

Route121_Text_KateDefeat:
	.string "VIVI: Je vais tout balayer\n"
	.string "devant ma petite protégée…$"

Route121_Text_KatePostBattle:
	.string "VIVI: Quand quelqu'un a confiance\n"
	.string "en moi, je me dois de faire\l"
	.string "d'entre eux...$"

Route121_Text_KateNotEnoughMons:
	.string "VIVI: Si tu n'as qu'un seul\n"
	.string "POKéMON, on ne peut pas\p"
	.string "Ce serait de l'intimidation.$"

Route121_Text_JoyIntro:
	.string "BEA: Ensemble, on ne connaît pas\n"
	.string "la peur. Tu verras notre force!$"

Route121_Text_JoyDefeat:
	.string "BEA: Pardonne-moi, VIVI!$"

Route121_Text_JoyPostBattle:
	.string "BEA: Il va falloir qu'on\n"
	.string "Mon partenaire étudiant, encore.$"

Route121_Text_JoyNotEnoughMons:
	.string "BEA: Il te faut au moins deux\n"
	.string "Si tu vas nous défier!$"

Route121_Text_JessicaIntro:
	.string "Stop! Regarde mes\n"
	.string "POKéMON! De vrais trésors!$"

Route121_Text_JessicaDefeat:
	.string "Oh, comment oses-tu! Ne\n"
	.string "prends pas ça au sérieux!$"

Route121_Text_JessicaPostBattle:
	.string "Je vais peut-être aller attraper\n"
	.string "d'autres POKéMON au PARC SAFARI.$"

Route121_Text_JessicaRegister:
	.string "Je ne me suis pas donnée à fond\n"
	.string "Ce ne sera pas la prochaine fois!$"

Route121_Text_JessicaRematchIntro:
	.string "Mes précieux POKéMON\n"
	.string "ont grandi! Regarde!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, comment oses-tu! Tu ne\n"
	.string "vas quand même pas t'énerver!$"

Route121_Text_JessicaPostRematch:
	.string "Je vais peut-être aller attraper\n"
	.string "d'autres POKéMON au PARC SAFARI.$"

Route121_Text_CristinIntro:
	.string "J'ai pour habitude de battre\n"
	.string "cinq DRESSEURS par jour… Et\l"
	.string "devine quoi! Tu es le numéro cinq!$"

Route121_Text_CristinDefeat:
	.string "Non! Tu es\n"
	.string "ignoble!$"

Route121_Text_CristinPostBattle:
	.string "Je ne pensais pas perdre aussi\n"
	.string "Je gagnerai la prochaine fois!$"

Route121_Text_CristinRegister:
	.string "Tu m'as humiliée! Je\n"
	.string "ne t'oublierai pas…\l"
	.string "Fais-moi voir ton POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "J'ai pour nouvelle habitude de\n"
	.string "battre dix DRESSEURS par jour… Et\l"
	.string "devine quoi! Tu es le numéro dix!$"

Route121_Text_CristinRematchDefeat:
	.string "Attends! Ça va pas! Je\n"
	.string "demande une revanche!$"

Route121_Text_CristinPostRematch:
	.string "Tu es le premier adversaire que\n"
	.string "je ne peux pas battre… Sniff… Je\l"
	.string "Je n'arrive pas à y croire...$"

Route121_Text_CaleIntro:
	.string "Tu vois pas que j'ai\n"
	.string "les mains pleines? Et\p"
	.string "malgré ça, tu insistes\n"
	.string "pour qu'on se batte!$"

Route121_Text_CaleDefeat:
	.string "Evidemment que j'ai perdu!\n"
	.string "J'ai les deux mains prises!$"

Route121_Text_CalePostBattle:
	.string "J'ai acheté trop d'articles au\n"
	.string "CENTRE COMMERCIAL de NENUCRIQUE.\p"
	.string "Il est un peu plus loin. Si\n"
	.string "J'aimerais un BAG comme le tien.$"

Route121_Text_MylesIntro:
	.string "Pour moi, rien de mieux que de\n"
	.string "découvrir les POKéMON des autres!$"

Route121_Text_MylesDefeat:
	.string "Super génial!$"

Route121_Text_MylesPostBattle:
	.string "Ils sont super tes POKéMON!\n"
	.string "Comment est-ce que tu les dresses?$"

Route121_Text_PatIntro:
	.string "Je veux que tout le monde voie\n"
	.string "les POKéMON que j'ai dressés!$"

Route121_Text_PatDefeat:
	.string "Waouh!\n"
	.string "Spectaculaire!$"

Route121_Text_PatPostBattle:
	.string "Je dresse chaque POKéMON avec le\n"
	.string "Je ne choisis pas les favoris.$"

Route121_Text_MarcelIntro:
	.string "Mes POKéMON n'ont jamais connu\n"
	.string "la défaite! Encore une victoire\l"
	.string "et je les inscris à un CONCOURS!$"

Route121_Text_MarcelDefeat:
	.string "Hein? Qu'est-ce qui s'est passé?$"

Route121_Text_MarcelPostBattle:
	.string "Je devrais peut-être les entraîner\n"
	.string "avant d'entrer dans un CONTEST.$"

Route123_Text_WendyIntro:
	.string "Tu veux connaître ta force? Je\n"
	.string "vais te faire passer le test!$"

Route123_Text_WendyDefeat:
	.string "Tu as réussi haut la main!$"

Route123_Text_WendyPostBattle:
	.string "Pour l'emporter même sur moi… Il\n"
	.string "faut que ta force soit grandiose!$"

Route123_Text_BraxtonIntro:
	.string "Tu sembles avoir une belle\n"
	.string "collection de BADGES D'ARÈNES.\p"
	.string "Laisse-moi voir si tu es\n"
	.string "Ces BADGES!$"

Route123_Text_BraxtonDefeat:
	.string "Bon, très bien, tu en es digne!$"

Route123_Text_BraxtonPostBattle:
	.string "Tu as prouvé la véritable\n"
	.string "C'est bon!$"

Route123_Text_VioletIntro:
	.string "On dit que les bons moments\n"
	.string "sont riches en agréables parfums.$"

Route123_Text_VioletDefeat:
	.string "Oh… Je sens l'âpre\n"
	.string "odeur de la souffrance…$"

Route123_Text_VioletPostBattle:
	.string "Le jardin du MAÎTRE DES BAIES\n"
	.string "avec des parfums exaltants.$"

Route123_Text_CameronIntro:
	.string "Etre médium est une question de\p"
	.string "volonté. Je me suis promis de ne\n"
	.string "Tout le monde, ça me rend fort!$"

Route123_Text_CameronDefeat:
	.string "Je suis triste…$"

Route123_Text_CameronPostBattle:
	.string "Etre médium requiert de la\n"
	.string "Je pensais ne pas vous perdre...$"

Route123_Text_CameronRegister:
	.string "Je vois… Je vois… Je vois que\n"
	.string "nous allons nous battre encore!\l"
	.string "Mais je ne peux pas voir si je\p"
	.string "vaincrai… Montre-moi ton POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "Je me suis convaincu que je\n"
	.string "Ça me rend fort!$"

Route123_Text_CameronRematchDefeat:
	.string "Je suis triste…$"

Route123_Text_CameronPostRematch:
	.string "Je devrais m'entraîner au MONT\n"
	.string "Je ne te bats jamais comme ça...$"

Route123_Text_JackiIntro:
	.string "Ne te réjouis pas trop si tes\n"
	.string "POKéMON développent des pouvoirs\p"
	.string "psychiques. Il faut que tu les\n"
	.string "les rendre vraiment utiles.$"

Route123_Text_JackiDefeat:
	.string "Ecrasée!$"

Route123_Text_JackiPostBattle:
	.string "On a tous des pouvoirs psychiques.\n"
	.string "On a oublié comment les utiliser.$"

Route123_Text_JackiRegister:
	.string "Je voudrais te\n"
	.string "rencontrer encore. Tu es d'accord?$"

Route123_Text_JackiRematchIntro:
	.string "As-tu éveillé les pouvoirs\n"
	.string "psychiques qui sommeillent en toi?$"

Route123_Text_JackiRematchDefeat:
	.string "Renversant!$"

Route123_Text_JackiPostRematch:
	.string "Le pouvoir que tu as sur tes\n"
	.string "POKéMON… Serait-ce un don psy?$"

Route123_Text_MiuIntro:
	.string "MIU: Salut, DRESSEUR! J'espère que\n"
	.string "POKéMON ne pleurera pas.$"

Route123_Text_MiuDefeat:
	.string "MIU: Ouin, on a perdu.$"

Route123_Text_MiuPostBattle:
	.string "MIU: DRESSEUR, si tes POKéMON sont\n"
	.string "forts, c'est grâce à votre amitié.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: C'est pas marrant de se\n"
	.string "battre si t'as pas deux POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: OK! On va battre\n"
	.string "les POKéMON de ce DRESSEUR!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Ouin, on a perdu.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Pourquoi es-tu si robuste?\n"
	.string "On n'avait jamais perdu avant.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: C'est pas marrant de se\n"
	.string "battre si t'as pas deux POKéMON.$"

Route123_Text_KindraIntro:
	.string "MONT MEMORIA… Ici reposent\n"
	.string "les âmes des POKéMON… Ton\l"
	.string "POKéMON veut-il se reposer?$"

Route123_Text_KindraDefeat:
	.string "Débordant de vitalité…$"

Route123_Text_KindraPostBattle:
	.string "MONT MEMORIA… Ici reposent\n"
	.string "les âmes des POKéMON… Un\p"
	.string "pouvoir apaisant les esprits\n"
	.string "doit se dégager de cet endroit…$"

Route123_Text_FernandoIntro:
	.string "Je vais m'occuper de toi tout\n"
	.string "en jouant mon solo de guitare!$"

Route123_Text_FernandoDefeat:
	.string "Hé, pas si vite! J'ai\n"
	.string "même pas fini l'intro!$"

Route123_Text_FernandoPostBattle:
	.string "T'as le rock dans la peau. Je\n"
	.string "J'aimerais écrire un air sur toi.$"

Route123_Text_FernandoRegister:
	.string "La prochaine fois, écoute\n"
	.string "au moins jusqu'au bout, OK?$"

Route123_Text_FernandoRematchIntro:
	.string "Je sens que cette fois sera\n"
	.string "la bonne! Je vais gagner\l"
	.string "avant même la fin de ma chanson!$"

Route123_Text_FernandoRematchDefeat:
	.string "Attends un peu! Tu veux\n"
	.string "vraiment pas entendre le refrain?$"

Route123_Text_FernandoPostRematch:
	.string "Ma musique était censée te\n"
	.string "par mon air, tu perdrais.$"

Route123_Text_DavisIntro:
	.string "C'est mon formidable POKéMON\n"
	.string "Mon grand frère l'a eu pour moi.$"

Route123_Text_DavisDefeat:
	.string "Waah! Quelle\n"
	.string "méchanceté!$"

Route123_Text_DavisPostBattle:
	.string "Ne dis pas à mon frère que\n"
	.string "j'ai perdu. Ce sera notre secret!$"

Route123_Text_JazmynIntro:
	.string "Ça me donnera confiance en moi\n"
	.string "de battre quelqu'un comme toi!$"

Route123_Text_JazmynDefeat:
	.string "Où est passée ma confiance?$"

Route123_Text_JazmynPostBattle:
	.string "On dit qu'il ne faut pas juger\n"
	.string "les gens sur leur apparence.\p"
	.string "Mais souvent, ils ne mentent pas.$"

Route123_Text_FrederickIntro:
	.string "Salut jeune DRESSEUR! T'as\n"
	.string "un peu de temps à perdre?$"

Route123_Text_FrederickDefeat:
	.string "Un DRESSEUR plein de\n"
	.string "promesses! Voilà pour toi!$"

Route123_Text_FrederickPostBattle:
	.string "Comment? L'argent de la\n"
	.string "victoire ne te suffit pas?$"

Route123_Text_AlbertoIntro:
	.string "Je dois t'avouer que les\n"
	.string "POKéMON OISEAU sont mon\p"
	.string "obsession! Les oiseaux sont\n"
	.string "C'est les meilleurs!$"

Route123_Text_AlbertoDefeat:
	.string "Vaincus, les OISEAU ont du style!$"

Route123_Text_AlbertoPostBattle:
	.string "Je collectionne les plumes que les\n"
	.string "POKéMON OISEAU perdent pendant\p"
	.string "leurs combats. J'ai l'intention\n"
	.string "Plumes BIRD POKéMON.$"

Route123_Text_EdIntro:
	.string "Quand il n'y a pas de DRESSEUR à\n"
	.string "affronter, je laisse mes POKéMON\l"
	.string "Je les surveille.$"

Route123_Text_EdDefeat:
	.string "Plutôt pas mal tes POKéMON…$"

Route123_Text_EdPostBattle:
	.string "Héhé, je vais copier tes\n"
	.string "Je pense qu'ils vont m'améliorer.$"

Route123_Text_JonasIntro:
	.string "J'ai tendu un piège, et un\n"
	.string "DRESSEUR est tombé dedans!$"

Route123_Text_JonasDefeat:
	.string "Si je ne gagne pas, c'est tout de\n"
	.string "pour s'amuser à jouer au ninja?$"

Route123_Text_JonasPostBattle:
	.string "La prochaine fois, je tendrai un\n"
	.string "piège à quelqu'un de moins fort!$"

Route123_Text_KayleyIntro:
	.string "Je viens d'acheter ce parasol.\n"
	.string "Avec ça, je suis bien plus jolie!$"

Route123_Text_KayleyDefeat:
	.string "Tu es au moins cinq fois\n"
	.string "plus redoutable que moi!$"

Route123_Text_KayleyPostBattle:
	.string "Bien utiliser les accessoires\n"
	.string "le secret derrière la mode appel.$"

Route124_Text_SpencerIntro:
	.string "Hé, tu ne retrouves pas ta\p"
	.string "route? Si tu réussis à battre mes\n"
	.string "POKéMON, je te servirai de guide.$"

Route124_Text_SpencerDefeat:
	.string "Ce combat m'a fait perdre le nord!$"

Route124_Text_SpencerPostBattle:
	.string "De nombreuses personnes perdent\p"
	.string "leurs repères en mer. Si c'est ton\n"
	.string "à la carte du POKéNAV.$"

Route124_Text_RolandIntro:
	.string "Hum! Plutôt que de\n"
	.string "nager, tu avances sur le\p"
	.string "dos d'un POKéMON… Je t'envie!$"

Route124_Text_RolandDefeat:
	.string "Oh! Je ne\n"
	.string "peux pas…$"

Route124_Text_RolandPostBattle:
	.string "Je suis en train d'attraper froid…\n"
	.string "Je suis resté trop longtemps dans\p"
	.string "l'eau… Je veux aussi un POKéMON.$"

Route124_Text_JennyIntro:
	.string "Si tu restes là à flotter en mer,\n"
	.string "ça, POKéMON vient jouer.$"

Route124_Text_JennyDefeat:
	.string "Oh, non! J'ai lancé\n"
	.string "le défi et j'ai perdu…$"

Route124_Text_JennyPostBattle:
	.string "En mer, j'ai remarqué que des\n"
	.string "POKéMON attaquent et d'autres\p"
	.string "regardent. Je suppose que chaque\n"
	.string "POKéMON a sa propre personnalité.$"

Route124_Text_JennyRegister:
	.string "C'est peut-être un caprice, mais\n"
	.string "pour m'inscrire à votre POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "Si tu ne fais que flotter en\n"
	.string "mer, les DRESSEURS vont te défier!$"

Route124_Text_JennyRematchDefeat:
	.string "C'est curieux…\n"
	.string "J'ai encore perdu…$"

Route124_Text_JennyPostRematch:
	.string "Ça n'a rien à voir, mais je vais\n"
	.string "visiter la MAISON DES PIEGES.$"

Route124_Text_GraceIntro:
	.string "Je commence à en avoir marre de\n"
	.string "Et une bataille?$"

Route124_Text_GraceDefeat:
	.string "Je ne t'imaginais\n"
	.string "pas aussi robuste!$"

Route124_Text_GracePostBattle:
	.string "Ce sont tous tes efforts qui\n"
	.string "ont dû te donner autant de force.$"

Route124_Text_ChadIntro:
	.string "Pfffff… J'ai plongé dans les\n"
	.string "abîmes de la mer pour me mettre\l"
	.string "à l'abri. J'excelle en sondage!$"

Route124_Text_ChadDefeat:
	.string "Glou, glou,\n"
	.string "glou… Je coule…$"

Route124_Text_ChadPostBattle:
	.string "Je tiens de source sûre qu'il y a\n"
	.string "par ici un endroit où l'on peut\p"
	.string "faire de la PLONGÉE. Je ne résiste\n"
	.string "Encore...$"

Route124_Text_LilaIntro:
	.string "RITA: Soupir… Me voilà en\p"
	.string "mer, mais avec qui je suis?\n"
	.string "Mon petit frère!\p"
	.string "Battons-nous, que je ne\n"
	.string "C'est ça!$"

Route124_Text_LilaDefeat:
	.string "RITA: SAM! C'est de ta faute\n"
	.string "si on a perdu! Ça se paiera!$"

Route124_Text_LilaPostBattle:
	.string "RITA: Soupir… Si seulement\p"
	.string "j'étais avec un charmant petit\n"
	.string "ami et pas avec mon petit frère…$"

Route124_Text_LilaNotEnoughMons:
	.string "RITA: Tu comptes nous affronter?\n"
	.string "Seulement si tu as deux POKéMON.$"

Route124_Text_RoyIntro:
	.string "SAM: Ma sœur est forte aux\p"
	.string "Ne pleure pas quand tu perds!$"

Route124_Text_RoyDefeat:
	.string "SAM: Ouin… Ma grande\n"
	.string "sœur va m'incendier…$"

Route124_Text_RoyPostBattle:
	.string "SAM: Ma grande sœur est\n"
	.string "vraiment flippante quand\p"
	.string "elle s'énerve. C'est pour ça\n"
	.string "qu'elle n'a pas de petit ami.$"

Route124_Text_LilaRoyRegister:
	.string "SAM: Tu te battras encore avec\n"
	.string "Mais calme-toi la prochaine fois.$"

Route124_Text_RoyNotEnoughMons:
	.string "SAM: Tu veux nous affronter?\n"
	.string "Alors ramène d'autres POKéMON.$"

Route124_Text_LilaRematchIntro:
	.string "RITA: J'ai vraiment pas de\p"
	.string "chance… Me voilà en mer, mais avec\n"
	.string "qui je suis? Mon petit frère!\p"
	.string "Salut, ça faisait longtemps. Qu'on\n"
	.string "se batte! Ça me distraira!$"

Route124_Text_LilaRematchDefeat:
	.string "RITA: SAM! C'est de ta\n"
	.string "faute si on a perdu! On va\p"
	.string "faire une séance d'entraînement!$"

Route124_Text_LilaPostRematch:
	.string "RITA: J'ai pas de chance… Avec un\p"
	.string "petit ami, on battrait tout le\n"
	.string "monde avec nos combinaisons!$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "RITA: Tu comptes nous affronter?\n"
	.string "Seulement si tu as deux POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "SAM: Il faut qu'on\n"
	.string "gagne! Je vais tout donner!$"

Route124_Text_RoyRematchDefeat:
	.string "SAM: Ouin… Ma grande\n"
	.string "sœur va encore m'incendier.$"

Route124_Text_RoyPostRematch:
	.string "SAM: Ma grande sœur est\n"
	.string "vraiment flippante quand elle\p"
	.string "s'énerve. Elle va me faire\n"
	.string "dur avec POKéMON plus tard...$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "SAM: Tu veux nous affronter?\n"
	.string "Alors ramène d'autres POKéMON.$"

Route124_Text_DeclanIntro:
	.string "Je me demande bien ce\n"
	.string "que je suis venu faire\p"
	.string "ici. C'est pathétique,\n"
	.string "y'a pas d'autre mot.$"

Route124_Text_DeclanDefeat:
	.string "Je me suis retrouvé\n"
	.string "noyé sous les coups.$"

Route124_Text_DeclanPostBattle:
	.string "Je devrais aller parler un\n"
	.string "peu avec les NAGEUSES du coin.$"

Route124_Text_IsabellaIntro:
	.string "Je ne peux pas perdre contre un\n"
	.string "Surfeur DRESSEUR.$"

Route124_Text_IsabellaDefeat:
	.string "C'est de la sueur que j'ai dans\n"
	.string "Je ne pleure pas!$"

Route124_Text_IsabellaPostBattle:
	.string "On trouve de très jolies\n"
	.string "choses au fond de l'eau par ici!$"

Route125_Text_NolenIntro:
	.string "Je savais que tu arrivais, je me\n"
	.string "suis attardé pour te rencontrer!$"

Route125_Text_NolenDefeat:
	.string "Je me rends!$"

Route125_Text_NolenPostBattle:
	.string "Le son se propage plus vite\n"
	.string "dans l'eau que dans l'air.$"

Route125_Text_StanIntro:
	.string "Hé, toi là-bas! Viens\n"
	.string "voir mon adorable POKéMON!$"

Route125_Text_StanDefeat:
	.string "J'ai carrément pataugé…$"

Route125_Text_StanPostBattle:
	.string "Le charme d'HYPOTREMPE m'a\n"
	.string "Alors j'ai commencé à nager aussi.$"

Route125_Text_TanyaIntro:
	.string "J'en ai marre de nager. Ça te\n"
	.string "dirait un combat contre moi?$"

Route125_Text_TanyaDefeat:
	.string "T'es vraiment trop!$"

Route125_Text_TanyaPostBattle:
	.string "Fffou… C'est\n"
	.string "par où ALGATIA?$"

Route125_Text_SharonIntro:
	.string "Comment! Tu voudrais te battre\n"
	.string "POKéMON DE L'EAU J'ai levé?$"

Route125_Text_SharonDefeat:
	.string "Que…$"

Route125_Text_SharonPostBattle:
	.string "Cette force… Tu ne me déçois pas!\n"
	.string "Je suis étonnée!$"

Route125_Text_ErnestIntro:
	.string "Je suis un MARIN robuste et\n"
	.string "J'ai bravé les mers du monde!$"

Route125_Text_ErnestDefeat:
	.string "Arrrrg! Je n'ai\n"
	.string "pas réussi à gagner!$"

Route125_Text_ErnestPostBattle:
	.string "Dans la GROTTE TREFONDS, la mer\n"
	.string "monte et descend. Il y a environ\p"
	.string "six heures entre la marée haute\n"
	.string "et la marée basse. Tu l'savais?$"

Route125_Text_ErnestRegister:
	.string "Enregistre-moi dans ton POKéNAV\n"
	.string "et je te dirai un truc dingue!$"

Route125_Text_ErnestRematchIntro:
	.string "Il est grand temps que je prenne\n"
	.string "Allez, nous nous battons!$"

Route125_Text_ErnestRematchDefeat:
	.string "Je n'ai pas réussi à\n"
	.string "gagner! Absolument pas!$"

Route125_Text_ErnestRematchPostBattle:
	.string "La GROTTE TREFONDS… Il existe des\p"
	.string "endroits accessibles ou non en\n"
	.string "fonction de la marée. Tout dépend\l"
	.string "si elle est haute ou basse.\p"
	.string "N'oublie pas qu'il y a environ six\n"
	.string "marée haute jusqu'à marée basse.$"

Route125_Text_KimIntro:
	.string "KIM: Un drôle de vieux monsieur\n"
	.string "vit dans la GROTTE TREFONDS. On me\l"
	.string "Tu vas le voir aussi?$"

Route125_Text_KimDefeat:
	.string "KIM: Je pensais qu'on gagnerait.$"

Route125_Text_KimPostBattle:
	.string "KIM: Un drôle de vieux monsieur\n"
	.string "vit dans la GROTTE TREFONDS,\p"
	.string "Allons le voir!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: Non, non et non! Il te faut\n"
	.string "Ou ce n'est pas bon!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, tu peux me\n"
	.string "dire ce qu'on cherche là?$"

Route125_Text_IrisDefeat:
	.string "IRIS: On s'est approchés.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, on va vraiment\n"
	.string "aller dans la GROTTE TREFONDS?\l"
	.string "On va être toutes mouillées.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, on ne pourrait\n"
	.string "jamais combattre à 2 contre 1.$"

Route125_Text_PresleyIntro:
	.string "Tu te demandes ce qu'un\n"
	.string "Tu viens à la mer?$"

Route125_Text_PresleyDefeat:
	.string "OK, je vais te dire\n"
	.string "ce que je fais ici.$"

Route125_Text_PresleyPostBattle:
	.string "J'ai mis un message dans une\n"
	.string "bouteille et je suis venu le\p"
	.string "déposer. J'espère qu'une\n"
	.string "jolie NAGEUSE tombera dessus.$"

Route125_Text_AuronIntro:
	.string "Hé! C'est toi qui\n"
	.string "jettes des ordures à la mer?$"

Route125_Text_AuronDefeat:
	.string "Oh, apparemment ça\n"
	.string "n'était pas toi?$"

Route125_Text_AuronPostBattle:
	.string "J'ai trouvé une affreuse\n"
	.string "bouteille en train de flotter\p"
	.string "dans l'eau. Ça me met hors de moi\n"
	.string "de voir les gens polluer la mer.$"

Route126_Text_BarryIntro:
	.string "La natation fait travailler tout\n"
	.string "Tu seras en forme!$"

Route126_Text_BarryDefeat:
	.string "Je l'admets!\n"
	.string "Tu as gagné!$"

Route126_Text_BarryPostBattle:
	.string "Mate un peu ce physique! C'est\n"
	.string "Fais gaffe à ce physique!$"

Route126_Text_DeanIntro:
	.string "Cette très haute montagne de\n"
	.string "roche blanche, c'est ATALANOPOLIS.$"

Route126_Text_DeanDefeat:
	.string "Tu m'as réglé mon compte?$"

Route126_Text_DeanPostBattle:
	.string "Je n'arrive pas à trouver l'entrée\n"
	.string "d'ATALANOPOLIS. Où peut-elle être?$"

Route126_Text_NikkiIntro:
	.string "Lalalalalala! Je\n"
	.string "suis une sirène!$"

Route126_Text_NikkiDefeat:
	.string "Je m'efface devant toi, comme une\n"
	.string "bulle qui éclate! Bul, bul, bul…$"

Route126_Text_NikkiPostBattle:
	.string "Tu m'as battue… Je veux\n"
	.string "sombrer dans le désespoir…$"

Route126_Text_BrendaIntro:
	.string "Salut, p'tit môme!\n"
	.string "Tu te bats contre moi?$"

Route126_Text_BrendaDefeat:
	.string "Oh, noooon!$"

Route126_Text_BrendaPostBattle:
	.string "J'adore m'ébattre comme ça\n"
	.string "dans la mer avec les POKéMON!$"

Route126_Text_PabloIntro:
	.string "Admire un peu ce corps d'athlète!\n"
	.string "Je suis plus fort qu'un KARATEKA!$"

Route126_Text_PabloDefeat:
	.string "Oups! Pas mal,\n"
	.string "pas mal du tout!$"

Route126_Text_PabloPostBattle:
	.string "Perdre contre toi ne fait que me\n"
	.string "Je m'entraînerai avec POKéMON.$"

Route126_Text_PabloRegister:
	.string "Ouaip, pas mal! Je voudrais\n"
	.string "J'aimerais mieux vous connaître!$"

Route126_Text_PabloRematchIntro:
	.string "Mate un peu ce physique! Je suis\n"
	.string "encore plus musclé qu'un NAGEUR!$"

Route126_Text_PabloRematchDefeat:
	.string "Oups!\n"
	.string "Vraiment trop fort!$"

Route126_Text_PabloPostRematch:
	.string "Tu arrives vraiment à me motiver.\n"
	.string "Je vais m'entraîner encore plus!\l"
	.string "Reviens me voir dès que possible!$"

Route126_Text_LeonardoIntro:
	.string "L'année dernière, je n'étais même\n"
	.string "pas capable de nager la brasse.\p"
	.string "Je suis capable de n'importe quoi.$"

Route126_Text_LeonardoDefeat:
	.string "Je ferais mieux\n"
	.string "d'apprendre le crawl.$"

Route126_Text_LeonardoPostBattle:
	.string "Rien de mieux que\n"
	.string "l'entraînement pour se\p"
	.string "perfectionner. Tu es jeune,\n"
	.string "Essayez toutes sortes de choses!$"

Route126_Text_IsobelIntro:
	.string "Tu ne trouves pas ça affreux\n"
	.string "N'est-ce pas terrible?$"

Route126_Text_IsobelDefeat:
	.string "Gloub gloub.\n"
	.string "J'ai bu la tasse!$"

Route126_Text_IsobelPostBattle:
	.string "J'ai avalé de l'eau!\n"
	.string "C'est salé et amer!$"

Route126_Text_SiennaIntro:
	.string "Je vais y mettre\n"
	.string "tout mon cœur!$"

Route126_Text_SiennaDefeat:
	.string "Tu as montré plus de volonté.$"

Route126_Text_SiennaPostBattle:
	.string "Je suis épuisée… Je vais\n"
	.string "faire la planche pour changer.$"

Route127_Text_CamdenIntro:
	.string "Je le lis sur ton\n"
	.string "visage. Tu veux me défier.$"

Route127_Text_CamdenDefeat:
	.string "Ooooooooooooh…$"

Route127_Text_CamdenPostBattle:
	.string "Un combat bien disputé\n"
	.string "me ravigote et m'apaise.$"

Route127_Text_DonnyIntro:
	.string "As-tu un rival contre\n"
	.string "qui tu détestes perdre?$"

Route127_Text_DonnyDefeat:
	.string "Arrrrg! J'ai\n"
	.string "horreur de perdre!$"

Route127_Text_DonnyPostBattle:
	.string "Si tu as un rival, ne\n"
	.string "ressens-tu pas le devoir\l"
	.string "de toujours faire mieux?$"

Route127_Text_JonahIntro:
	.string "Grâce à la pêche, j'ai atteint un\n"
	.string "état de complète sérénité…\p"
	.string "Permettez-moi de vous montrer...$"

Route127_Text_JonahDefeat:
	.string "Même si j'ai\n"
	.string "perdu, je reste serein…$"

Route127_Text_JonahPostBattle:
	.string "Ce n'est pas grave si je n'attrape\n"
	.string "rien. La ligne reste dans l'eau…$"

Route127_Text_HenryIntro:
	.string "Ne me dis pas qu'un POKéMON en\n"
	.string "Un POKéMON qui s'en va?$"

Route127_Text_HenryDefeat:
	.string "Je n'arrive pas à tenir le rythme!$"

Route127_Text_HenryPostBattle:
	.string "Tes POKéMON ont l'air forts. Si je\n"
	.string "Votre dur POKéMON!$"

Route127_Text_RogerIntro:
	.string "Hé! C'est parti pour un match\n"
	.string "un fan de POKéMON et un poisson!$"

Route127_Text_RogerDefeat:
	.string "Non! Ma ligne est\n"
	.string "emmêlée! La partie est terminée!$"

Route127_Text_RogerPostBattle:
	.string "Ma ligne exécute une danse! Le\n"
	.string "L'enchevêtrement du tango!$"

Route127_Text_AidanIntro:
	.string "Les POKéMON OISEAU ont une bonne\n"
	.string "vue. Ils voient leurs proies.$"

Route127_Text_AidanDefeat:
	.string "Pfooou… J'abandonne!$"

Route127_Text_AidanPostBattle:
	.string "Par ici, il y a beaucoup\n"
	.string "d'endroits où tu peux plonger. Ils\p"
	.string "sont facilement repérables du ciel\n"
	.string "grâce à leur couleur plus foncée.$"

Route127_Text_KojiIntro:
	.string "Marcher pieds nus, c'est ce que je\n"
	.string "Ça va te durcir les semelles!$"

Route127_Text_KojiDefeat:
	.string "Woutch! Je me suis pris\n"
	.string "une écharde dans le pied!$"

Route127_Text_KojiPostBattle:
	.string "C'est sympa de marcher pieds nus.\n"
	.string "Mais tes fringues sont cool aussi.$"

Route127_Text_KojiRegister:
	.string "Voilà ce que je fais à ceux qui me\n"
	.string "J'espère qu'on pourra le refaire.$"

Route127_Text_KojiRematchIntro:
	.string "Je marche pieds nus tous les\n"
	.string "Mes semelles sont durs!$"

Route127_Text_KojiRematchDefeat:
	.string "Ouch! Encore\n"
	.string "une écharde!$"

Route127_Text_KojiPostRematch:
	.string "Tu n'veux pas essayer de marcher\n"
	.string "pieds nus? Prête tes CHAUSSURES…$"

Route127_Text_AthenaIntro:
	.string "Affrontons-nous dans un\n"
	.string "combat calme et méthodique.$"

Route127_Text_AthenaDefeat:
	.string "Tu ne m'as pas donné le temps\n"
	.string "de me battre stratégiquement.$"

Route127_Text_AthenaPostBattle:
	.string "Quand je suis entourée par le ciel\n"
	.string "On dirait que le temps ralentit.$"

Route128_Text_IsaiahIntro:
	.string "Il y a encore un bon bout\n"
	.string "de chemin avant ETERNARA…$"

Route128_Text_IsaiahDefeat:
	.string "J'ai aussi du chemin à\n"
	.string "Dehors, aussi...$"

Route128_Text_IsaiahPostBattle:
	.string "Toute ma vie j'ai connu la\n"
	.string "Mais je n'abandonnerai jamais!$"

Route128_Text_IsaiahRegister:
	.string "Je sais que je n'ai pas le niveau\n"
	.string "pour l'instant. Mais ça changera.\p"
	.string "Enregistre-moi dans ton POKéNAV.$"

Route128_Text_IsaiahRematchIntro:
	.string "Je ne suis pas trop fatigué. Je\n"
	.string "nageant jusqu'à EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Je n'ai jamais connu la victoire…$"

Route128_Text_IsaiahPostRematch:
	.string "Je vais arriver à ETERNARA,\n"
	.string "où je vais finalement gagner…$"

Route128_Text_KatelynIntro:
	.string "Un triathlon est une course\n"
	.string "épuisante composée de trois\p"
	.string "épreuves. Il faut nager, faire du\n"
	.string "de trois événements.$"

Route128_Text_KatelynDefeat:
	.string "Une bataille de POKéMON aussi...$"

Route128_Text_KatelynPostBattle:
	.string "Après, je dois rouler en VELO,\n"
	.string "Je vais jeter la serviette...$"

Route128_Text_KatelynRegister:
	.string "Je suis sûre que je pourrais mieux\n"
	.string "J'aimerais une revanche.$"

Route128_Text_KatelynRematchIntro:
	.string "C'est long un triathlon. Mais je\n"
	.string "suppose que devenir le MAÎTRE\l"
	.string "est aussi un long et épuisant.$"

Route128_Text_KatelynRematchDefeat:
	.string "Un combat de POKéMON, c'est\n"
	.string "et impitoyable...$"

Route128_Text_KatelynPostRematch:
	.string "Tu devrais bien réfléchir aux\n"
	.string "les défis de la ROUTE VICTOIRE.$"

Route128_Text_AlexaIntro:
	.string "Nous avons travaillé si dur pour\n"
	.string "relever le défi de la LIGUE\p"
	.string "On n'a pas les moyens de perdre!$"

Route128_Text_AlexaDefeat:
	.string "Oh! Comment cela\n"
	.string "a-t-il pu se produire?!$"

Route128_Text_AlexaPostBattle:
	.string "Après ce que j'ai fait pour en\n"
	.string "Je ne céderai pas après un revers.$"

Route128_Text_RubenIntro:
	.string "Il n'y a pas plus fort que moi!$"

Route128_Text_RubenDefeat:
	.string "C'est impossible!$"

Route128_Text_RubenPostBattle:
	.string "Il n'y a probablement pas\n"
	.string "plus fort DRESSEUR que toi!$"

Route128_Text_WayneIntro:
	.string "Je veux aller à ETERNARA, j'ai\n"
	.string "attrapé un POKéMON connaissant\l"
	.string "CASCADE pour gravir les chutes.$"

Route128_Text_WayneDefeat:
	.string "J'ai chuté!$"

Route128_Text_WaynePostBattle:
	.string "Ah, ah, très drôle! Mon\p"
	.string "POKéMON connaît CASCADE, mais je\n"
	.string "n'ai pas le BADGE d'ATALANOPOLIS!$"

Route128_Text_HarrisonIntro:
	.string "Tu as l'air plutôt coriace. Je\n"
	.string "me demande si je peux gagner…$"

Route128_Text_HarrisonDefeat:
	.string "Ouch! Ça ne devait\n"
	.string "pas être possible.$"

Route128_Text_HarrisonPostBattle:
	.string "De nombreux DRESSEURS plutôt\n"
	.string "doués se réunissent souvent\p"
	.string "près d'ETERNARA. Tu crois que\n"
	.string "je suis assez fort pour eux?$"

Route128_Text_CarleeIntro:
	.string "Le soleil semble\n"
	.string "briller plus fort par là-bas.$"

Route128_Text_CarleeDefeat:
	.string "J'ai perdu car j'avais\n"
	.string "le soleil dans les yeux.$"

Route128_Text_CarleePostBattle:
	.string "Il va falloir que je rentre. Je\n"
	.string "dois remettre de la crème solaire.$"

Route129_Text_ChaseIntro:
	.string "C'est mon premier triathlon.\n"
	.string "Je suis tout tendu et nerveux!$"

Route129_Text_ChaseDefeat:
	.string "Arrrrg! J'ai\n"
	.string "raté la victoire!$"

Route129_Text_ChasePostBattle:
	.string "Si je suis tendu, je ne vais\n"
	.string "pas pouvoir donner le maximum.$"

Route129_Text_AllisonIntro:
	.string "Je suis en plein milieu d'un\n"
	.string "triathlon, mais oui, battons-nous!$"

Route129_Text_AllisonDefeat:
	.string "J'étais pourtant sûre de gagner!$"

Route129_Text_AllisonPostBattle:
	.string "Tu sais ce qu'il y a de plus\n"
	.string "formidable dans le triathlon?\p"
	.string "C'est de pouvoir tester les\n"
	.string "limites de ta propre force et de\l"
	.string "ton endurance face à Mère Nature!$"

Route129_Text_ReedIntro:
	.string "Hé! Qu'on\n"
	.string "s'y mette!$"

Route129_Text_ReedDefeat:
	.string "Battu… On m'a battu!\n"
	.string "Ça y est, c'est fait!$"

Route129_Text_ReedPostBattle:
	.string "Un perdant n'a rien à attendre. Il\n"
	.string "C'est l'heure pour moi de rentrer.$"

Route129_Text_TishaIntro:
	.string "Y a pas urgence? On n'a qu'à\n"
	.string "s'y mettre tranquillement.$"

Route129_Text_TishaDefeat:
	.string "Oh, ça alors! Je voulais\n"
	.string "me détendre un peu plus…$"

Route129_Text_TishaPostBattle:
	.string "N'as-tu pas horreur de faire\n"
	.string "des erreurs quand tu te\p"
	.string "dépêches? C'est pour cela que\n"
	.string "lentement.$"

Route129_Text_ClarenceIntro:
	.string "Surfer n'est pas aussi facile\n"
	.string "N'est-ce pas?$"

Route129_Text_ClarenceDefeat:
	.string "Gagner, c'est pas facile non plus!$"

Route129_Text_ClarencePostBattle:
	.string "Tu dois sûrement t'intéresser à la\n"
	.string "LIGUE POKéMON! Continue comme ça!$"

Route130_Text_RodneyIntro:
	.string "Quelle surprise! Je ne pensais pas\n"
	.string "tomber sur un DRESSEUR en mer. Je\p"
	.string "crois qu'on devrait s'affronter!$"

Route130_Text_RodneyDefeat:
	.string "Quelle force pour un si jeune âge…$"

Route130_Text_RodneyPostBattle:
	.string "Tu as le regard de quelqu'un qui a\n"
	.string "connu de rudes épreuves et qui a\l"
	.string "et a gagné, ça te va bien!$"

Route130_Text_KatieIntro:
	.string "Dans les eaux bleues et profondes\n"
	.string "de la mer, mon cœur désemparé\l"
	.string "le confort entre les vagues.$"

Route130_Text_KatieDefeat:
	.string "Comme la mer, vaste et bleue,\n"
	.string "le monde des POKéMON couvre\l"
	.string "des profondeurs incroyables.$"

Route130_Text_KatiePostBattle:
	.string "Le rêve de tous les\n"
	.string "enfants du monde, c'est de\l"
	.string "devenir un jour MAÎTRE POKéMON.$"

Route130_Text_SantiagoIntro:
	.string "Flotter au milieu de l'eau\n"
	.string "comme ça… Ça détend vraiment…$"

Route130_Text_SantiagoDefeat:
	.string "J'étais sans doute trop détendu!$"

Route130_Text_SantiagoPostBattle:
	.string "Se battre et nager comme ça… Je\n"
	.string "suis vraiment un homme heureux…$"

Route131_Text_RichardIntro:
	.string "La mer regorge de POKéMON. Tu\n"
	.string "sais, c'est pas facile de nager.$"

Route131_Text_RichardDefeat:
	.string "Les POKéMON élevés par des\n"
	.string "DRESSEURS sont sacrément forts…$"

Route131_Text_RichardPostBattle:
	.string "Pfou… Pfou… Je suis\n"
	.string "lessivé… L'aller est\p"
	.string "facile. C'est le retour qui\n"
	.string "est plus difficile. Va-t-il\p"
	.string "me rester assez d'énergie\n"
	.string "pour faire le trajet retour?$"

Route131_Text_HermanIntro:
	.string "La mer… La mer… La\n"
	.string "mer… La mer à perte de\l"
	.string "vue! Ça me rend dingue!$"

Route131_Text_HermanDefeat:
	.string "Booouh!$"

Route131_Text_HermanPostBattle:
	.string "Je suis las de la mer et pourtant,\p"
	.string "je ne peux m'empêcher de nager. Je\n"
	.string "C'est ce que je suis.$"

Route131_Text_SusieIntro:
	.string "Salut, mon chou. Attends! On\n"
	.string "devrait s'affronter, toi et moi!$"

Route131_Text_SusieDefeat:
	.string "Même si tu n'en as pas\n"
	.string "l'air, tu as une grande force!$"

Route131_Text_SusiePostBattle:
	.string "As-tu vu un type par ici qui\n"
	.string "se plaignait d'être lassé de\p"
	.string "la mer? Tu parles! Il est\n"
	.string "éperdument amoureux de la mer!$"

Route131_Text_KaraIntro:
	.string "Pourquoi les hommes aiment-ils\p"
	.string "Ils m'ignorent tous!$"

Route131_Text_KaraDefeat:
	.string "J'ai perdu pied!$"

Route131_Text_KaraPostBattle:
	.string "C'est peut-être pas mon maillot de\n"
	.string "Ça doit être ma beauté!$"

Route131_Text_ReliIntro:
	.string "LANA: Avec mon frère, on va\n"
	.string "faire équipe pour t'avoir!$"

Route131_Text_ReliDefeat:
	.string "LANA: On n'a pas réussi à\n"
	.string "gagner, même en faisant équipe…$"

Route131_Text_ReliPostBattle:
	.string "LANA: A PACIFIVILLE, les\n"
	.string "habitants sont liés à la mer et\l"
	.string "aux POKéMON comme au premier jour.$"

Route131_Text_ReliNotEnoughMons:
	.string "LANA: Si tu n'as pas deux POKéMON,\n"
	.string "On ne peut pas se battre, alors.$"

Route131_Text_IanIntro:
	.string "IAN: Avec ma sœurette,\n"
	.string "on fait de notre mieux!$"

Route131_Text_IanDefeat:
	.string "IAN: Avec ma sœurette, on a fait\n"
	.string "Mais nous n'avons pas pu gagner...$"

Route131_Text_IanPostBattle:
	.string "IAN: Tu sais que PACIFIVILLE\n"
	.string "est une ville flottante?\p"
	.string "Alors là où il y a la mer, se\n"
	.string "trouve une partie de PACIFIVILLE!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: Si tu as deux\n"
	.string "POKéMON, on te prend à 2 contre 2!$"

Route131_Text_TaliaIntro:
	.string "Si tu arrives à me battre, je te\n"
	.string "donnerai des infos intéressantes!$"

Route131_Text_TaliaDefeat:
	.string "Oh? J'ai\n"
	.string "vraiment perdu?$"

Route131_Text_TaliaPostBattle:
	.string "Il y a un endroit étrange pas loin\n"
	.string "d'ici. On peut y voir une tour\l"
	.string "Pourquoi tu n'irais pas voir?$"

Route131_Text_KevinIntro:
	.string "Il n'y a pas plus calme que\n"
	.string "les gens de PACIFIVILLE. Ils\p"
	.string "ne se mettent jamais en\n"
	.string "colère, un peu comme moi, quoi!$"

Route131_Text_KevinDefeat:
	.string "Oups!$"

Route131_Text_KevinPostBattle:
	.string "Gr… Eh, non!\n"
	.string "Je ne suis\p"
	.string "pas en colère,\n"
	.string "je t'assure!$"

Route132_Text_GilbertIntro:
	.string "Quand j'étais petit, je prenais\n"
	.string "toujours froid mais depuis que\l"
	.string "je nage, je suis en bonne santé.$"

Route132_Text_GilbertDefeat:
	.string "J'ai besoin de plus de pouvoir...$"

Route132_Text_GilbertPostBattle:
	.string "Les DRESSEURS arpentent champs et\n"
	.string "Il faut qu'ils soient en forme.$"

Route132_Text_DanaIntro:
	.string "Je ne nage pas là où le\n"
	.string "courant est trop fort.$"

Route132_Text_DanaDefeat:
	.string "Oh, non, je t'en supplie!$"

Route132_Text_DanaPostBattle:
	.string "Si je me fais balayer, je\n"
	.string "vais perdre tout repère…$"

Route132_Text_RonaldIntro:
	.string "Défaite, victoire… Si tu\n"
	.string "Essaie!$"

Route132_Text_RonaldDefeat:
	.string "Waah! Je sombre\n"
	.string "dans la défaite!$"

Route132_Text_RonaldPostBattle:
	.string "Je ne me bats jamais si je sais\n"
	.string "que c'est gagné d'avance. J'aime\l"
	.string "victoire et défaite!$"

Route132_Text_KiyoIntro:
	.string "Je médite sur les POKéMON 24\n"
	.string "Comment pourrais-tu me battre?$"

Route132_Text_KiyoDefeat:
	.string "J'ai perdu.\n"
	.string "J'admets la défaite.$"

Route132_Text_KiyoPostBattle:
	.string "Arrrg… Tu es fana de\n"
	.string "POKéMON, n'est-ce pas? Tu\p"
	.string "dois observer les POKéMON\n"
	.string "24 heures sur 24, pas vrai?$"

Route132_Text_MakaylaIntro:
	.string "Je suis toujours avec mon mari,\n"
	.string "mais je peux gagner même sans lui!$"

Route132_Text_MakaylaDefeat:
	.string "Je n'étais pas assez bon.$"

Route132_Text_MakaylaPostBattle:
	.string "Le jeune homme plus loin est le\n"
	.string "portrait craché de mon mari quand\p"
	.string "Il me fait rougir!$"

Route132_Text_JonathanIntro:
	.string "Quelqu'un n'arrête pas de me\n"
	.string "C'était toi?$"

Route132_Text_JonathanDefeat:
	.string "Wow! OK,\n"
	.string "j'ai compris!$"

Route132_Text_JonathanPostBattle:
	.string "J'ai la désagréable impression que\n"
	.string "quelqu'un n'arrête pas de me\p"
	.string "Je ne peux pas me concentrer!$"

Route132_Text_PaxtonIntro:
	.string "Où est-ce que ma femme est\n"
	.string "encore passée? Je passe mon\l"
	.string "temps à la chercher partout!$"

Route132_Text_PaxtonDefeat:
	.string "Ah, j'aurais dû attendre\n"
	.string "pour gagner seul après tout.$"

Route132_Text_PaxtonPostBattle:
	.string "Ma femme doit être en train de me\n"
	.string "Je vais la trouver tout de suite.$"

Route132_Text_DarcyIntro:
	.string "J'adore m'entraîner toute seule\n"
	.string "ici. Je déteste toute cette foule!$"

Route132_Text_DarcyDefeat:
	.string "OK, j'arrête de me plaindre\n"
	.string "de voir trop de monde ici!$"

Route132_Text_DarcyPostBattle:
	.string "Je suppose que je dois pouvoir\n"
	.string "vieux et défier l'autre équipe.$"

Route133_Text_FranklinIntro:
	.string "Le courant m'a mené ici.\n"
	.string "Toi aussi? C'est un coup\l"
	.string "du destin. Battons-nous!$"

Route133_Text_FranklinDefeat:
	.string "Quelle force!\n"
	.string "Trop pour moi!$"

Route133_Text_FranklinPostBattle:
	.string "C'est bien ma chance… Un\n"
	.string "DRESSEUR aussi fort que toi qui\l"
	.string "atterrit ici… Je dois être maudit…$"

Route133_Text_DebraIntro:
	.string "J'ai mené une existence de chagrin\n"
	.string "et de misère… J'ai fait naufrage\l"
	.string "et voilà où je me suis retrouvée…$"

Route133_Text_DebraDefeat:
	.string "Encore une autre défaite…$"

Route133_Text_DebraPostBattle:
	.string "Une vie à la dérive…\n"
	.string "Je n'en veux plus!$"

Route133_Text_LindaIntro:
	.string "Bienvenue! Je\n"
	.string "t'attendais!$"

Route133_Text_LindaDefeat:
	.string "Non! Je t'en prie!$"

Route133_Text_LindaPostBattle:
	.string "Un DRESSEUR aussi fort et\n"
	.string "pourtant si jeune… C'est agaçant!$"

Route133_Text_WarrenIntro:
	.string "Comme les autres, je veux gagner.\n"
	.string "Mes POKéMON seront hors du commun.$"

Route133_Text_WarrenDefeat:
	.string "Zut! Je ne suis pas\n"
	.string "encore assez énergique!$"

Route133_Text_WarrenPostBattle:
	.string "C'est plus sympa de faire les\n"
	.string "choses à ma guise que de faire\l"
	.string "comme les autres. C'est évident!$"

Route133_Text_BeckIntro:
	.string "J'ai fait tout le chemin\n"
	.string "jusqu'ici avec mon POKéMON OISEAU.$"

Route133_Text_BeckDefeat:
	.string "Tu… Tu gardes un\n"
	.string "tel sang-froid!$"

Route133_Text_BeckPostBattle:
	.string "Je voudrais retourner à\n"
	.string "Mais j'aime cet endroit aussi.$"

Route133_Text_MollieIntro:
	.string "J'ai dû me battre des centaines de\n"
	.string "fois, mais j'ai arrêté de compter!$"

Route133_Text_MollieDefeat:
	.string "J'ai aussi perdu des centaines de\n"
	.string "mais une perte encore des piqûres.$"

Route133_Text_MolliePostBattle:
	.string "Continue comme ça, et un jour\n"
	.string "tu seras comme mon mari et moi!$"

Route133_Text_ConorIntro:
	.string "Les jeunes n'en font qu'à leur\n"
	.string "Ils sont sans direction.$"

Route133_Text_ConorDefeat:
	.string "Vous avez un sens ferme du but.$"

Route133_Text_ConorPostBattle:
	.string "Ne laisse pas les autres diriger\n"
	.string "ta vie. Poursuis toujours ton but!$"

Route134_Text_JackIntro:
	.string "Même les POKéMON qui savent\n"
	.string "portée par les courants rapides.$"

Route134_Text_JackDefeat:
	.string "Ouuuuuille!$"

Route134_Text_JackPostBattle:
	.string "Je crois que les POKéMON aiment\n"
	.string "courants autour de ces parties.$"

Route134_Text_LaurelIntro:
	.string "Mes LOVDISC veulent un match\n"
	.string "sympa. Tu te joins à nous?$"

Route134_Text_LaurelDefeat:
	.string "Oups!$"

Route134_Text_LaurelPostBattle:
	.string "Il y a un collectionneur qui\n"
	.string "recherche les ÉCAILLES de LOVDISC.$"

Route134_Text_AlexIntro:
	.string "Dacodac! Assez flemmardé!\n"
	.string "Il est temps de combattre!$"

Route134_Text_AlexDefeat:
	.string "Encore carrément naze…$"

Route134_Text_AlexPostBattle:
	.string "Mes POKéMON OISEAU sont vite\n"
	.string "fatigués après un long vol…$"

Route134_Text_HitoshiIntro:
	.string "Tu es DRESSEUR de POKéMON. Les\n"
	.string "mots sont inutiles. Agissons!$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "C'est moi qui te défie et c'est\n"
	.string "J'ai perdu.$"

Route134_Text_AaronIntro:
	.string "Le mauvais temps sur cette zone\n"
	.string "nous rendre plus forts que jamais.$"

Route134_Text_AaronDefeat:
	.string "J'admets la défaite!$"

Route134_Text_AaronPostBattle:
	.string "On va retourner au SITE\n"
	.string "METEORE pour s'entraîner\p"
	.string "davantage. Si ça te dit, tu n'as\n"
	.string "Ça va t'endurcir!$"

Route134_Text_KelvinIntro:
	.string "Notre… notre bateau!\n"
	.string "La marée l'a emmené!$"

Route134_Text_KelvinDefeat:
	.string "Arrête,\n"
	.string "arrête, j'abandonne!$"

Route134_Text_KelvinPostBattle:
	.string "Si on ne peut pas SURFER, comment\n"
	.string "faire pour rentrer chez nous? En\p"
	.string "fait, je sais qu'un POKéMON K.O.\n"
	.string "peut encore SURF, mais c'est mal.$"

Route134_Text_MarleyIntro:
	.string "Est-ce que tes POKéMON peuvent\n"
	.string "Des attaques éclairantes?$"

Route134_Text_MarleyDefeat:
	.string "Je ne savais pas qu'une telle\n"
	.string "Tu nous as complètement vaincus.$"

Route134_Text_MarleyPostBattle:
	.string "Je n'ai pas perdu mon goût pour la\n"
	.string "Je vais essayer plus fort.$"

Route134_Text_ReynaIntro:
	.string "Mes POKéMON ne pourront pas\n"
	.string "être battus si facilement!$"

Route134_Text_ReynaDefeat:
	.string "Tu plaisantes? Comment\n"
	.string "t'as fait pour gagner?$"

Route134_Text_ReynaPostBattle:
	.string "Haha! Tu as gagné, bien! Je vais\n"
	.string "affronter tous les DRESSEURS que\p"
	.string "je croiserai sur le chemin du\n"
	.string "DRESSEURS J'ai rendez-vous!$"

Route134_Text_HudsonIntro:
	.string "Dis, t'aurais pas vu un\n"
	.string "autre MARIN dans l'coin?$"

Route134_Text_HudsonDefeat:
	.string "Wow! C'était quelque chose!$"

Route134_Text_HudsonPostBattle:
	.string "Notre bateau a pris la mer. Mon\p"
	.string "compagnon est quelqu'un de timide,\n"
	.string "je suis un peu inquiet pour lui.$"

VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "La pile n'est pas assez chargée.\p"
	.string "Nombre d'étapes nécessaires pour\n"
	.string "charger complètement la batterie: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "Il n'y a pas de formateurs à\n"
	.string "Qui peut se battre...\p"
	.string "Le VS Seeker a été éteint.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "Les autres Trainers ne\n"
	.string "être prêt pour la bataille.\p"
	.string "Attendons plus tard.{PAUSE_UNTIL_PRESS}$"
