CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.string "C'est une IMPRIMANTE POKéMON !\p"
	.string "Elle peut imprimer ton POKéMON\n"
	.string "au dos de ta CARTE DRESSEUR.\p"
	.string "Ça ne coûte que 50 ¥.\n"
	.string "Veux-tu essayer ?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.string "Tu n'as pas assez d'argent.$"

CeladonCity_GameCorner_Text_ChoosePrintType::
	.string "Choisis le type d'impression.$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.string "Un grand sourire pour la photo !\n"
	.string "Trois… Deux… Un…\p"
	.string "Flash !$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.string "Ton impression POKéMON est prête !\n"
	.string "Regarde ta CARTE DRESSEUR.$"

FourIsland_House2_Text_WishICouldShowOffStickers::
	.string "Hihi…\n"
	.string "J'ai plein d'AUTOCOLLANTS.\l"
	.string "J'aimerais tellement les montrer…$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
	.string "Oh, excellent !\n"
	.string "Tu es au bon endroit !\p"
	.string "Regarde ! Tu les vois ?\n"
	.string "Ce sont mes AUTOCOLLANTS !\l"
	.string "Tu as vu combien j'en ai ?\p"
	.string "Je parie que tu en veux.\n"
	.string "J'en suis sûr !\p"
	.string "Je t'en donne un si tu me racontes\n"
	.string "quelque chose d'incroyable à ton\l"
	.string "sujet.\p"
	.string "De quoi vas-tu te vanter ?$"

FourIsland_House2_Text_BragAboutSomethingForMe::
	.string "Vante-toi donc un peu.\n"
	.string "Je te donnerai un AUTOCOLLANT.$"

FourIsland_House2_Text_BragAboutWhatToday::
	.string "Oh, salut !\n"
	.string "Voilà notre vantard.\p"
	.string "De quoi vas-tu te vanter\n"
	.string "aujourd'hui ?$"

FourIsland_House2_Text_WowHoFLowest::
	.string "Oh, tu es entré au\n"
	.string "HALL OF FAME.\p"
	.string "C'est plutôt bien, ouais !\n"
	.string "Je vais t'en donner un.$"

FourIsland_House2_Text_WowHoFLow::
	.string "Oh, tu es entré souvent au\n"
	.string "HALL OF FAME !\p"
	.string "C'est impressionnant, ouais !\n"
	.string "Je vais t'en donner un.$"

FourIsland_House2_Text_WowHoFHigh::
	.string "Ouah ! Tant d'entrées au\n"
	.string "HALL OF FAME ?\l"
	.string "C'est vraiment incroyable, ouais !\p"
	.string "La LIGUE POKéMON est à toi !\n"
	.string "Je vais t'en donner un.$"

FourIsland_House2_Text_WowHoFHighest::
	.string "Pas possible ! Tu es entré autant\n"
	.string "de fois au HALL OF FAME ?\p"
	.string "Tu dépasses l'incroyable, ouais !\n"
	.string "Là, je dois te donner ceci.$"

FourIsland_House2_Text_HoFStickerApplied::
	.string "L'AUTOCOLLANT HALL OF FAME est\n"
	.string "posé sur la CARTE DRESSEUR.$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
	.string "Hmm…\p"
	.string "Reviens avec un meilleur récit\n"
	.string "la prochaine fois, d'accord ?$"

FourIsland_House2_Text_LivingLegendHoF::
	.string "Oh non, impossible.\p"
	.string "Tu es presque une légende vivante.\n"
	.string "Je n'ai plus d'AUTOCOLLANTS.$"

FourIsland_House2_Text_WowEggsLowest::
	.string "Oh, il existe des ŒUFS POKéMON ?\n"
	.string "Je l'ignorais !\p"
	.string "C'est plutôt bien, ouais !\n"
	.string "Je vais t'en donner un.$"

FourIsland_House2_Text_WowEggsLow::
	.string "Tu as fait éclore autant d'ŒUFS ?\n"
	.string "Tu dois vraiment les aimer !\p"
	.string "C'est impressionnant, ouais !\n"
	.string "Je vais t'en donner un.$"

FourIsland_House2_Text_WowEggsHigh::
	.string "Ouah ! Tu as fait éclore\n"
	.string "un tas d'ŒUFS !\p"
	.string "Tu es une machine à faire éclore !\n"
	.string "Je vais t'en donner un.$"

FourIsland_House2_Text_WowEggsHighest::
	.string "Qu… Tant d'ŒUFS éclos ?\p"
	.string "D'où vient cet amour des ŒUFS ?\n"
	.string "Ça dépasse l'incroyable, ouais !\p"
	.string "Tu es vraiment trop fort.\n"
	.string "Là, je dois te donner ceci.$"

FourIsland_House2_Text_EggStickerApplied::
	.string "L'AUTOCOLLANT ŒUF est posé\n"
	.string "sur la CARTE DRESSEUR.$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
	.string "Hmm…\p"
	.string "Reviens avec un meilleur récit\n"
	.string "la prochaine fois, d'accord ?$"

FourIsland_House2_Text_LivingLegendEggs::
	.string "Oh non, impossible.\p"
	.string "Tu es presque une légende vivante.\n"
	.string "Je n'ai plus d'AUTOCOLLANTS.$"

FourIsland_House2_Text_WowLinkWinsLowest::
	.string "Oh, tu as remporté un\n"
	.string "combat link ?\p"
	.string "Tu es plutôt fort, ouais !\n"
	.string "Je vais t'en donner un.$"

FourIsland_House2_Text_WowLinkWinsLow::
	.string "Tu as souvent battu tes amis\n"
	.string "en combat link, hein ?\p"
	.string "Ta force impressionne, ouais !\n"
	.string "Je vais t'en donner un.$"

FourIsland_House2_Text_WowLinkWinsHigh::
	.string "Ouah ! Tu as battu tes amis\n"
	.string "un nombre effrayant de fois.\p"
	.string "Tu en as perdu des amis ?\n"
	.string "Je vais t'en donner un.$"

FourIsland_House2_Text_WowLinkWinsHighest::
	.string "Qu… C'est dingue !\n"
	.string "Tu as gagné tellement de fois !\p"
	.string "Rien que de penser à ta force,\n"
	.string "j'en tombe à la renverse.\p"
	.string "Tu hantes mes cauchemars !\n"
	.string "Là, je dois te donner ceci.$"

FourIsland_House2_Text_VictoryStickerApplied::
	.string "L'AUTOCOLLANT VICTOIRE est posé\n"
	.string "sur la CARTE DRESSEUR.$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
	.string "Hmm…\p"
	.string "Reviens avec un meilleur récit\n"
	.string "la prochaine fois, d'accord ?$"

FourIsland_House2_Text_LivingLegendLinkWins::
	.string "Oh non, impossible.\p"
	.string "Tu es presque une légende vivante.\n"
	.string "Je n'ai plus d'AUTOCOLLANTS.$"
