Route3_Text_ColtonRematchIntro::
	.string "Hé!\n"
	.string "Je t'ai vu dans VIRIDIAN FOREST!$"

Route3_Text_BenRematchIntro::
	.string "Salut! J'adore les shorts!\n"
	.string "C'est agréable et facile à porter!\p"
	.string "Tu devrais en mettre un aussi!$"

Route3_Text_JaniceRematchIntro::
	.string "Hé!\n"
	.string "Tu n'arrêtes pas de me regarder!$"

Route3_Text_GregRematchIntro::
	.string "Tu es DRESSEUR, pas vrai?\n"
	.string "Alors, au combat!$"

Route3_Text_SallyRematchIntro::
	.string "Ce regard que tu me lances…\n"
	.string "Il m'intrigue tellement!$"

Route3_Text_CalvinRematchIntro::
	.string "Hé! Qu'est-ce qui te prend?\n"
	.string "Toujours pas de short sur toi!$"

Route3_Text_JamesRematchIntro::
	.string "Je t'affronte avec mes POKéMON\n"
	.string "que j'ai commencé à élever.$"

Route3_Text_RobinRematchIntro::
	.string "Hii!\n"
	.string "Tu m'as poussée?$"

Route4_Text_CrissyRematchIntro::
	.string "J'attrape toujours des POKéMON\n"
	.string "champignons au MONT SÉLÉNITE.$"

Route6_Text_RickyRematchIntro::
	.string "Oh! C'est toi, le petit curieux\n"
	.string "qui nous écoutait!$"

Route6_Text_NancyRematchIntro::
	.string "Hé! Je t'ai bien dit que cette\n"
	.string "conversation était privée!\p"
	.string "Tu ne devrais pas nous écouter,\n"
	.string "petit malpoli!$"

Route6_Text_KeigoRematchIntro::
	.string "Je cherche un bon POKéMON qui ne\n"
	.string "soit pas de type INSECTE, mais…$"

Route6_Text_JeffRematchIntro::
	.string "Hein?\n"
	.string "Tu veux remettre ça avec moi?$"

Route6_Text_IsabelleRematchIntro::
	.string "Moi?\n"
	.string "Bon, d'accord. Une seule fois.$"

Route6_Text_ElijahRematchIntro::
	.string "Hé, ça fait longtemps!\n"
	.string "Tu t'es amélioré?$"

Route8_Text_AidanRematchIntro::
	.string "Tu es doué avec les POKéMON, mais\n"
	.string "quelle est ta note en chimie?$"

Route8_Text_StanRematchIntro::
	.string "Parfait!\n"
	.string "On recommence!$"

Route8_Text_GlennRematchIntro::
	.string "Il faut une stratégie pour gagner\n"
	.string "un combat.\p"
	.string "Tu as suivi mon conseil?$"

Route8_Text_PaigeRematchIntro::
	.string "J'ai réuni beaucoup de NIDORAN.\n"
	.string "Je ne veux pas les faire évoluer…$"

Route8_Text_LeslieRematchIntro::
	.string "L'école est sympa, mais je trouve\n"
	.string "aussi les POKéMON amusants.$"

Route8_Text_AndreaRematchIntro::
	.string "MIAOUSS et PERSIAN, trop mignons,\n"
	.string "miaou, miaou, miaou!$"

Route8_Text_MeganRematchIntro::
	.string "On a l'air bêtes à rester plantés\n"
	.string "ici, mais je peux me battre!$"

Route8_Text_RichRematchIntro::
	.string "Je vadrouille et joue sans arrêt!\n"
	.string "J'enchaîne les victoires!$"

Route8_Text_JuliaRematchIntro::
	.string "Quel POKéMON est mignon, rond et\n"
	.string "tout doux?\p"
	.string "Tu le sais déjà, pas vrai?$"

Route8_Text_RicardoRematchIntro::
	.string "Ma bécane déconne toujours, mec.$"

Route8_Text_JarenRematchIntro::
	.string "D'accord, gamin!\n"
	.string "Pas de pitié cette fois!$"

Route8_Text_EliRematchIntro::
	.string "ELI: Notre pouvoir de jumeaux\n"
	.string "est encore plus fort!$"

Route8_Text_AnneRematchIntro::
	.string "ANNE: Notre pouvoir a augmenté!$"

Route9_Text_AliciaRematchIntro::
	.string "On se bat encore?\n"
	.string "Cette fois, tu es à moi!$"

Route9_Text_ChrisRematchIntro::
	.string "Je n'ai pas oublié tes superbes\n"
	.string "POKéMON.$"

Route9_Text_DrewRematchIntro::
	.string "Je traverse ROCK TUNNEL pour aller\n"
	.string "à LAVANVILLE…\p"
	.string "Mais tout le monde m'arrête en\n"
	.string "chemin…$"

Route9_Text_CaitlinRematchIntro::
	.string "Ne me prends pas de haut!\n"
	.string "Cette fois, c'est du sérieux!$"

Route9_Text_JeremyRematchIntro::
	.string "Bwahaha!\n"
	.string "Génial! Je m'ennuyais encore!$"

Route9_Text_BriceRematchIntro::
	.string "Hahaha!\n"
	.string "Toujours aussi coriace!$"

Route9_Text_BrentRematchIntro::
	.string "Je me suis levé tôt chaque jour\n"
	.string "pour entraîner mes POKéMON cocons!$"

Route9_Text_AlanRematchIntro::
	.string "Hahahaha!\n"
	.string "Cette fois, je gagnerai!$"

Route9_Text_ConnerRematchIntro::
	.string "Gagnez, mes super POKéMON INSECTE!$"

Route10_Text_MarkRematchIntro::
	.string "Waouh, tu es revenu?\n"
	.string "Tu serais aussi un POKéMANIAC?\l"
	.string "Tu veux voir ma collection?$"

Route10_Text_ClarkRematchIntro::
	.string "Ha-ha-ha-ha-atchoum!\n"
	.string "Je n'arrête pas d'éternuer!$"

Route10_Text_HermanRematchIntro::
	.string "Salut, gamin!\n"
	.string "Je t'ai montré mes POKéMON?$"

Route10_Text_HeidiRematchIntro::
	.string "Je suis retournée dans une ARÈNE.\p"
	.string "…Mais j'ai perdu, comme toujours.$"

Route10_Text_TrentRematchIntro::
	.string "Ah!\n"
	.string "Cet air montagnard est délicieux!\l"
	.string "C'est trop bon, je ne peux partir!$"

Route10_Text_CarolRematchIntro::
	.string "La tête commence à me tourner.\n"
	.string "J'ai marché trop longtemps…$"

Route11_Text_HugoRematchIntro::
	.string "Victoire, défaite ou égalité!\n"
	.string "Place à notre revanche!$"

Route11_Text_JasperRematchIntro::
	.string "Rien ne vaut la compétition.\n"
	.string "Je ne m'en lasse toujours pas!$"

Route11_Text_EddieRematchIntro::
	.string "Tu connais la règle, hein?\n"
	.string "Allons-y, mais pas de triche!$"

Route11_Text_BraxtonRematchIntro::
	.string "Salut!\p"
	.string "Mais attention!\n"
	.string "Je pose encore des câbles!$"

Route11_Text_DillonRematchIntro::
	.string "Je suis DRESSEUR depuis peu.\n"
	.string "Mais je crois pouvoir gagner.$"

Route11_Text_DirkRematchIntro::
	.string "Fwahaha!\n"
	.string "Je n'ai jamais perdu!\p"
	.string "…Et si c'est arrivé, j'ai tout\n"
	.string "oublié!$"

Route11_Text_DarianRematchIntro::
	.string "Je n'ai encore jamais gagné…\p"
	.string "C'est peut-être mon destin de ne\n"
	.string "jamais y arriver…$"

Route11_Text_YasuRematchIntro::
	.string "Je suis le meilleur de ma classe.\n"
	.string "Je m'entraîne matin et soir!$"

Route11_Text_BernieRematchIntro::
	.string "Attention aux fils sous tension!$"

Route11_Text_DaveRematchIntro::
	.string "J'ai élevé mes POKéMON avec soin.\n"
	.string "Ils devraient être prêts.\l"
	.string "Cette fois, ils devraient gagner.$"

Route12_Text_NedRematchIntro::
	.string "Ouais!\n"
	.string "Ça mord, par ici!\l"
	.string "C-c'est peut-être un gros poisson!$"

Route12_Text_ChipRematchIntro::
	.string "Te voilà enfin.\n"
	.string "La pêche demande de la patience.$"

Route12_Text_JustinRematchIntro::
	.string "Toujours pas de PIERRE LUNE…\n"
	.string "Tu en as trouvé une?$"

Route12_Text_LucaRematchIntro::
	.string "L'électricité a toujours été ma\n"
	.string "spécialité.\p"
	.string "Mais j'ignore tout des POKéMON\n"
	.string "marins.$"

Route12_Text_HankRematchIntro::
	.string "FOU DE PÊCHE contre POKéMON KID!\n"
	.string "Nouveau round, combattez!$"

Route12_Text_ElliotRematchIntro::
	.string "J'adore pêcher, crois-moi.\n"
	.string "Mais j'aimerais plus de travail…\l"
	.string "…Dur de renoncer à la pêche!$"

Route12_Text_AndrewRematchIntro::
	.string "Qu'est-ce qui mord?\p"
	.string "Tu ne le sauras pas sans me\n"
	.string "battre!$"

Route12_Text_JesRematchIntro::
	.string "JES: Je vais gagner aujourd'hui\n"
	.string "et demander GIA en mariage.$"

Route12_Text_GiaRematchIntro::
	.string "GIA: Hé, JES…\n"
	.string "Ça fait longtemps que j'attends.\p"
	.string "Si on gagne, je t'épouserai!$"

Route13_Text_SebastianRematchIntro::
	.string "Mes oiseaux se souviennent de toi!$"

Route13_Text_SusieRematchIntro::
	.string "Je veux être la meilleure\n"
	.string "DRESSEUSE tant que je suis enfant!$"

Route13_Text_ValerieRematchIntro::
	.string "Waouh!\n"
	.string "Tu as encore plus de beaux BADGES!$"

Route13_Text_GwenRematchIntro::
	.string "Mes adorables POKéMON veulent\n"
	.string "faire à nouveau ta connaissance.$"

Route13_Text_AlmaRematchIntro::
	.string "J'ai vidé mes économies pour\n"
	.string "acheter encore du CARBONE.$"

Route13_Text_PerryRematchIntro::
	.string "Je ne perdrai pas cette fois.\n"
	.string "Le vent souffle en ma faveur!$"

Route13_Text_LolaRematchIntro::
	.string "Oh, te revoilà?\p"
	.string "Oui, je vais rejouer avec toi,\n"
	.string "mon chou.$"

Route13_Text_SheilaRematchIntro::
	.string "Tu ne peux pas oublier notre\n"
	.string "combat?$"

Route13_Text_JaredRematchIntro::
	.string "Qu'est-ce que tu regardes?$"

Route13_Text_RobertRematchIntro::
	.string "Je choisis toujours des POKéMON\n"
	.string "oiseaux. Je leur ai tout consacré.$"

Route14_Text_CarterRematchIntro::
	.string "J'ai utilisé des CT pour apprendre\n"
	.string "de bonnes capacités à mes POKéMON.$"

Route14_Text_MitchRematchIntro::
	.string "Mes POKéMON oiseaux devraient être\n"
	.string "prêts au combat cette fois.$"

Route14_Text_BeckRematchIntro::
	.string "Tu donnes des CT à tes POKéMON?\n"
	.string "Les garder ne sert à rien.$"

Route14_Text_MarlonRematchIntro::
	.string "As-tu appris VOL à ton POKéMON\n"
	.string "oiseau?\p"
	.string "Tu pourras t'envoler avec lui dans\n"
	.string "le ciel! Essaie donc.$"

Route14_Text_DonaldRematchIntro::
	.string "La légende des mirages ailés…\n"
	.string "Tu la connais, pas vrai?$"

Route14_Text_BennyRematchIntro::
	.string "Ça ne m'emballe pas, mais bon.\n"
	.string "Allons-y!$"

Route14_Text_LukasRematchIntro::
	.string "Hé!\n"
	.string "Je me souviens de toi!\p"
	.string "Allez, allez.\n"
	.string "C'est parti, parti, parti!$"

Route14_Text_IsaacRematchIntro::
	.string "Encore toi, hein?\n"
	.string "Tais-toi et bats-toi.$"

Route14_Text_GeraldRematchIntro::
	.string "On roule ici pour profiter des\n"
	.string "grands espaces.$"

Route14_Text_MalikRematchIntro::
	.string "Un combat POKéMON, c'est ça?\n"
	.string "Cool! La baston!$"

Route14_Text_KiriRematchIntro::
	.string "KIRI: JAN, j'espère qu'on gagnera.$"

Route14_Text_JanRematchIntro::
	.string "JAN: KIRI, c'est parti!\n"
	.string "Cette fois, gagnons à coup sûr!$"

Route15_Text_KindraRematchIntro::
	.string "Je vais continuer avec les POKéMON\n"
	.string "reçus par échange.$"

Route15_Text_BeckyRematchIntro::
	.string "Tu as l'air gentil, alors je crois\n"
	.string "pouvoir te battre.\p"
	.string "Je vais retenter ma chance!$"

Route15_Text_EdwinRematchIntro::
	.string "Je siffle, les POKéMON oiseaux\n"
	.string "se rassemblent.\p"
	.string "Ils sont vraiment adorables!$"

Route15_Text_ChesterRematchIntro::
	.string "Hum? Mes oiseaux tremblent!\n"
	.string "Attends, tu es ce DRESSEUR…$"

Route15_Text_GraceRematchIntro::
	.string "Oh, quel petit cœur!\n"
	.string "On dirait un adorable POKéMON!\l"
	.string "Je me souviens de toi!$"

Route15_Text_OliviaRematchIntro::
	.string "J'élève mes POKéMON comme gardes\n"
	.string "car je vis seule.\p"
	.string "Ça n'a pas changé.$"

Route15_Text_ErnestRematchIntro::
	.string "Hé, gamin! Viens!\n"
	.string "J'ai pris ça à un pauvre nul!$"

Route15_Text_AlexRematchIntro::
	.string "Donne ton fric quand tu perdras\n"
	.string "contre moi, gamin!$"

Route15_Text_CeliaRematchIntro::
	.string "Qu'est-ce qui est à la mode?\n"
	.string "Les échanges de POKéMON, bien sûr.$"

Route15_Text_YazminRematchIntro::
	.string "Tu veux encore jouer avec mes\n"
	.string "POKéMON?$"

Route15_Text_MyaRematchIntro::
	.string "MYA: Salut, on se croise souvent,\n"
	.string "pas vrai?\p"
	.string "Aide-moi encore à entraîner mon\n"
	.string "petit frère!$"

Route15_Text_RonRematchIntro::
	.string "RON: Ma sœur est devenue plus\n"
	.string "forte…$"

Route16_Text_LaoRematchIntro::
	.string "Qu'est-ce que tu veux?$"

Route16_Text_KojiRematchIntro::
	.string "Belle BICYCLETTE!\n"
	.string "Donne-la-moi, vite!$"

Route16_Text_LukeRematchIntro::
	.string "Viens jouer, petite souris.\n"
	.string "Je prendrai soin de toi!$"

Route16_Text_HideoRematchIntro::
	.string "Hé, attends une seconde!\n"
	.string "Ne m'appelle pas pour t'enfuir!$"

Route16_Text_CamronRematchIntro::
	.string "J'ai faim et je suis en rogne!\n"
	.string "Il me faut un sac de frappe!$"

Route16_Text_RubenRematchIntro::
	.string "Salut!\n"
	.string "On va bien s'amuser!$"

Route16_Text_JedRematchIntro::
	.string "JED: Tu viens voir notre amour\n"
	.string "sans limites?$"

Route16_Text_LeaRematchIntro::
	.string "LEA: Parfois, la force de notre\n"
	.string "amour me fait peur.$"

Route17_Text_RaulRematchIntro::
	.string "Je l'ai dit: affronter des gamins\n"
	.string "ne rend pas riche rapidement.$"

Route17_Text_IsaiahRematchIntro::
	.string "Je suis fier de mon corps, gamin.\n"
	.string "Allez!$"

Route17_Text_VirgilRematchIntro::
	.string "Tu te promènes?$"

Route17_Text_BillyRematchIntro::
	.string "Nous sommes des MOTARDS!\n"
	.string "La route est à nous, mec!$"

Route17_Text_NikolasRematchIntro::
	.string "VOLTORBE va vraiment\n"
	.string "t'électriser aujourd'hui!$"

Route17_Text_ZeekRematchIntro::
	.string "Mon POKéMON a gagné des niveaux,\n"
	.string "mais refuse d'évoluer. Pourquoi?$"

Route17_Text_JamalRematchIntro::
	.string "Aaah! Je dois vraiment m'entraîner\n"
	.string "et perdre toute cette graisse!$"

Route17_Text_CoreyRematchIntro::
	.string "Sois un rebelle!$"

Route17_Text_JaxonRematchIntro::
	.string "Ouais, belle BICYCLETTE!\n"
	.string "Elle se conduit bien?$"

Route17_Text_WilliamRematchIntro::
	.string "Dégage, gamin!\n"
	.string "Je suis crevé!$"

Route18_Text_WiltonRematchIntro::
	.string "J'explore chaque coin d'herbe à la\n"
	.string "recherche de nouveaux POKéMON.\p"
	.string "Mais ce n'est pas toujours facile…$"

Route18_Text_RamiroRematchIntro::
	.string "Kouroukoucou!\n"
	.string "Mon cri d'oiseau s'améliore?$"

Route18_Text_JacobRematchIntro::
	.string "Je t'ai prévenu, c'est mon\n"
	.string "territoire!\p"
	.string "Je ne veux plus te voir ici.$"

Route19_Text_RichardRematchIntro::
	.string "J'ai presque fini de m'échauffer\n"
	.string "avant d'aller nager.$"

Route19_Text_ReeceRematchIntro::
	.string "Attends! Doucement!\n"
	.string "Et si tu faisais un malaise?$"

Route19_Text_MatthewRematchIntro::
	.string "J'adore nager!\n"
	.string "Toi, tu préfères surfer.$"

Route19_Text_DouglasRematchIntro::
	.string "Qu'y a-t-il au-delà de l'horizon?\n"
	.string "Tu l'as vu?$"

Route19_Text_DavidRematchIntro::
	.string "J'ai encore plongé chercher des\n"
	.string "POKéMON, sans succès comme avant.$"

Route19_Text_TonyRematchIntro::
	.string "Je regarde la mer pour oublier les\n"
	.string "mauvaises choses.\p"
	.string "…Comme ma défaite contre toi!$"

Route19_Text_AnyaRematchIntro::
	.string "Tu voyages toujours sur ton\n"
	.string "POKéMON…\p"
	.string "Ça a l'air si reposant.\n"
	.string "Je peux l'avoir si je gagne?$"

Route19_Text_AliceRematchIntro::
	.string "Nager, c'est génial!\n"
	.string "Les coups de soleil, non!$"

Route19_Text_AxleRematchIntro::
	.string "Ces eaux sont dangereuses!\n"
	.string "Tu ne devrais pas revenir!$"

Route19_Text_ConnieRematchIntro::
	.string "J'ai nagé jusqu'ici avec mes amis…\n"
	.string "Je suis fatiguée…\l"
	.string "On doit vraiment se battre encore?$"

Route19_Text_LiaRematchIntro::
	.string "LIA: Tu sais que mon frère vient\n"
	.string "de devenir DRESSEUR, hein?\p"
	.string "Je veux le faire progresser, alors\n"
	.string "j'ai encore besoin de toi.$"

Route19_Text_LucRematchIntro::
	.string "LUC: Ma sœur m'a tout appris\n"
	.string "sur les POKéMON.\p"
	.string "Je me demande si j'ai progressé?$"

Route20_Text_BarryRematchIntro::
	.string "L'eau est peu profonde ici.\n"
	.string "Beaucoup de gens y nagent.$"

Route20_Text_ShirleyRematchIntro::
	.string "Tu es jaloux de mes vacances\n"
	.string "à SEAFOAM?$"

Route20_Text_TiffanyRematchIntro::
	.string "J'adore flotter avec les poissons\n"
	.string "au milieu des vagues.$"

Route20_Text_IreneRematchIntro::
	.string "Toi aussi, tu étais en vacances?$"

Route20_Text_DeanRematchIntro::
	.string "Regarde ces muscles!\p"
	.string "Je suis encore plus baraqué\n"
	.string "qu'avant!$"

Route20_Text_DarrinRematchIntro::
	.string "Pourquoi montes-tu un POKéMON?\n"
	.string "Tu ne sais toujours pas nager?$"

Route20_Text_RogerRematchIntro::
	.string "Mon POKéMON oiseau m'a porté ici.$"

Route20_Text_NoraRematchIntro::
	.string "Mon copain m'a offert de grosses\n"
	.string "perles. Elles ont encore grossi!$"

Route20_Text_MissyRematchIntro::
	.string "J'ai nagé depuis CRAMOIS'ÎLE.\n"
	.string "Comme je l'ai dit, ce fut dur.$"

Route20_Text_MelissaRematchIntro::
	.string "À l'ouest, CRAMOIS'ÎLE abrite un\n"
	.string "LABO POKéMON.\p"
	.string "Mon papa y travaille.$"

Route21_North_Text_RonaldRematchIntro::
	.string "Tu veux savoir si les poissons\n"
	.string "mordent?$"

Route21_North_Text_WadeRematchIntro::
	.string "Encore une pêche miraculeuse!\n"
	.string "Tu veux remettre ça?$"

Route21_North_Text_SpencerRematchIntro::
	.string "La mer purifie le corps et l'âme!$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
	.string "Je suis encore venu nager\n"
	.string "aujourd'hui!$"

Route21_South_Text_JackRematchIntro::
	.string "J'ai attrapé mes POKéMON en mer.\n"
	.string "C'est là que je les entraîne.$"

Route21_South_Text_JeromeRematchIntro::
	.string "Je participe encore à un\n"
	.string "triathlon!$"

Route21_South_Text_RolandRematchIntro::
	.string "Aah!\n"
	.string "Sens le soleil et le vent!$"

Route21_South_Text_ClaudeRematchIntro::
	.string "Hé, ça suffit maintenant.\n"
	.string "Tu fais encore fuir les poissons!$"

Route21_South_Text_NolanRematchIntro::
	.string "Reste jusqu'à ce que ça morde.$"

Route21_North_Text_LilRematchIntro::
	.string "LIL: Hein? Encore un combat?\n"
	.string "IAN, tu ne peux pas y aller seul?$"

Route21_North_Text_IanRematchIntro::
	.string "IAN: Ma sœur est toujours molle.\n"
	.string "Aide-moi à la remettre en forme!$"

Route25_Text_JoeyRematchIntro::
	.string "Ici, je ne perdrai pas!$"

Route25_Text_DanRematchIntro::
	.string "Papa m'a emmené à une super fête\n"
	.string "sur le S.S. ANNE à VERMILION CITY.$"

Route25_Text_FlintRematchIntro::
	.string "Je suis un gars cool.\n"
	.string "J'ai une petite amie!\p"
	.string "Cette fois, je vais lui montrer à\n"
	.string "quel point je suis cool!$"

Route25_Text_KelseyRematchIntro::
	.string "Salut!\n"
	.string "Mon copain est cool!\l"
	.string "Je suis en forme aujourd'hui!$"

Route25_Text_ChadRematchIntro::
	.string "Je le sentais…\n"
	.string "Je savais qu'on se rebattrait!$"

Route25_Text_HaleyRematchIntro::
	.string "Mon amie a plein de jolis POKéMON.\n"
	.string "Je suis si jalouse!$"

Route25_Text_FranklinRematchIntro::
	.string "Entraîné au MONT SÉLÉNITE,\n"
	.string "mais j'ai encore de l'énergie!$"

Route25_Text_NobRematchIntro::
	.string "Un POKéMANIAC vit sur le cap.\n"
	.string "Tu as vu sa collection?$"

Route25_Text_WayneRematchIntro::
	.string "Tu retournes voir BILL?\n"
	.string "D'abord, on se bat!$"

Route24_Text_ShaneRematchIntro::
	.string "J'ai vu ton exploit dans l'herbe!$"

Route24_Text_EthanRematchIntro::
	.string "D'accord!\n"
	.string "Je vais t'écraser!$"

Route24_Text_ReliRematchIntro::
	.string "Tu as toujours l'air si occupé…\n"
	.string "Tu ne te fatigues pas?$"

Route24_Text_TimmyRematchIntro::
	.string "Tu dois vraiment aimer venir au\n"
	.string "NUGGET BRIDGE.$"

Route24_Text_AliRematchIntro::
	.string "Lors de notre combat…\p"
	.string "J'étais deuxième dans la file,\n"
	.string "mais la meilleure, pas vrai?$"

Route24_Text_CaleRematchIntro::
	.string "On appelle cet endroit le NUGGET\n"
	.string "BRIDGE!\p"
	.string "Tu nous as déjà battus, alors tu\n"
	.string "ne peux plus relever le défi…\p"
	.string "…Mais tu peux nous affronter à\n"
	.string "nouveau.$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "Allongée, bercée par les vagues…\n"
	.string "Je ne vois pas le temps passer…$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "Quel temps magnifique!\n"
	.string "Je vais éviter de le gâcher.$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "Mon coup de soleil me fait mal…$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "La montagne de l'oiseau de feu\n"
	.string "projette une ombre immense…$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "J'ai vraiment le sentiment de\n"
	.string "gagner cette fois!$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "Attends! Une seconde!\n"
	.string "J'ai ferré un gros, c'est sûr!$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "Tu vas encore m'aider à\n"
	.string "m'entraîner?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "Nous n'avons encore manqué aucun\n"
	.string "jour d'entraînement!$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "Chaque matin avant de déjeuner,\n"
	.string "je nage autour de cette île…\l"
	.string "Trois fois!$"

OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "Habille-toi pour le combat!\n"
	.string "Oublie cette tenue frivole!$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "Tu sais, tout paraît délicieux\n"
	.string "quand on vit dans la nature.$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "J'ai encore trop mangé. Tu veux\n"
	.string "nous aider à faire de l'exercice?$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "KIA: Mon frère et moi, quelle\n"
	.string "équipe formidable!\p"
	.string "On ne perdra pas cette fois!$"

OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "MIK: Avec KIA, nous n'avons\n"
	.string "peur de rien!\p"
	.string "On va te le prouver cette fois!$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "On se bat encore?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "D'où viens-tu et où\n"
	.string "vas-tu?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "Je veux bientôt nager sans ma\n"
	.string "bouée.$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "Youpi, youpi!\n"
	.string "POKéMON!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "Oh non, je te l'ai déjà dit!\n"
	.string "Laisse-moi tranquille!$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "JOY: On est devenues plus fortes!\n"
	.string "Beaucoup plus fortes!$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "MEG: Tu ne nous battras pas!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "Oh, bonjour!\p"
	.string "Tu élèves tes POKéMON dans un\n"
	.string "bon environnement?$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "De mes mains, je créerai\n"
	.string "ma victoire aujourd'hui.$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "Je dois me répéter?\n"
	.string "J'essaie de peindre.\l"
	.string "Hors de ma vue!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "Je n'ai fait aucun progrès…\n"
	.string "Je ne trouve toujours pas l'angle…$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "Oh, tu m'offres une nouvelle\n"
	.string "occasion de rivaliser avec toi?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "La piscine de mes POKéMON est\n"
	.string "presque terminée.\p"
	.string "Tu dois venir la voir.$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "Je cours bien.\n"
	.string "Je suis encore plus rapide!$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "Eh bien, mon ami!\n"
	.string "Profitons de ce moment ensemble!$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "Je suis l'aîné des BIRD\n"
	.string "BROTHERS. Tu te souviens?\p"
	.string "Oui, j'aime les oiseaux pour\n"
	.string "leur bec!$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "Je suis le cadet des BIRD\n"
	.string "BROTHERS.\p"
	.string "Moi, j'adore les ailes.\n"
	.string "Combattons encore!$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "Je suis le benjamin des BIRD\n"
	.string "BROTHERS.\p"
	.string "J'adore le duvet des oiseaux.\n"
	.string "Je ne pensais pas te revoir!$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "Je n'ai toujours aucune chance.\n"
	.string "Un combat me changera les idées!$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "Haa… Haa…\p"
	.string "J'ai nagé sans m'arrêter depuis\n"
	.string "le port de SIX ISLAND.$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "Tu arrives toujours pendant que\n"
	.string "je nage.$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "AVA: Encore un combat marin\n"
	.string "à deux contre deux!$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "GEB: Ma grande sœur et moi sommes\n"
	.string "bien plus forts qu'avant!$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "…Hein?\p"
	.string "Je vise ma maison, mais TÉLÉPORT\n"
	.string "me ramène toujours ici!$"

SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "Oh, bonjour.\n"
	.string "Une brise agréable souffle encore.$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "Héhéhé, je m'entraîne encore en\n"
	.string "secret.$"

SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "Quoi, tu en as assez des\n"
	.string "NAGEURS comme moi?\p"
	.string "Oh, ne sois pas comme ça!\n"
	.string "Affronte-moi encore.$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "Soupir…\n"
	.string "Mon copain est encore occupé…$"

SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "Allez, dis-moi, où sont les\n"
	.string "montagnes du coin?$"

SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "MIU: Bonjour, les POKéMON!\n"
	.string "Il est temps de rejouer!$"

SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "MIA: Bonjour, les POKéMON!\n"
	.string "Il est temps de se rebattre!$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "Ce monde semble encore receler\n"
	.string "bien des secrets non résolus.$"

SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "Salut, on s'est déjà vus?\n"
	.string "Pourquoi es-tu revenu?$"

SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "On dit que cette île abrite des\n"
	.string "pierres mystérieuses.\p"
	.string "As-tu découvert quelque chose\n"
	.string "notre dernière rencontre?$"

SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "Une revanche si haut dans le ciel!$"

SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "Je connais plutôt bien les terres\n"
	.string "des environs.$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "J'ai senti ton approche.$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "Quelque part sur cette île, des\n"
	.string "POKéMON étranges dorment.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "Kyahaha!\p"
	.string "Revenir ne changera rien.\n"
	.string "Je vais t'expédier sans effort!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "Salut! Tu fais partie de mon\n"
	.string "fan-club, pas vrai?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "Cette île est bien trop vaste…\n"
	.string "La patrouiller est épuisant…$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "Je ne pardonne pas à ceux qui\n"
	.string "maltraitent les POKéMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "EVE: Je vais encore faire équipe\n"
	.string "avec JON pour combattre.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "JON: Avec EVE, j'ai l'impression\n"
	.string "qu'on ne peut jamais perdre.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "Faisons un autre combat.\n"
	.string "Je suis au meilleur de ma forme!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "Avoir les POKéMON les plus forts\n"
	.string "ne suffit pas…\p"
	.string "Ça ne vaut rien si tu ne sais pas\n"
	.string "bien les utiliser!$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "Je protège l'environnement.\n"
	.string "En retour, la nature me protège!$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "À chaque rencontre, tu portes ces\n"
	.string "chaussures élégantes.$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "Tu dois être devenu plus fort.\n"
	.string "Laisse-moi t'affronter!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "J'ai reçu la meilleure éducation\n"
	.string "pour devenir aussi forte.\p"
	.string "Je ne perdrai pas cette fois.\n"
	.string "Certainement pas!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "LEX: Ma chère NYA, ensemble,\n"
	.string "nous gagnerons à coup sûr!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "NYA: Je ne décevrai pas mon mentor\n"
	.string "LEX! Nous allons gagner!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "As-tu découvert quelque chose sur\n"
	.string "cette chambre de pierre?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "On dit qu'un POKéMON mystique dort\n"
	.string "à l'intérieur.$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "Mon professeur continue de\n"
	.string "m'apprendre à peindre.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "Aujourd'hui, outre notre cours,\n"
	.string "nous avons revu la chambre.$"
