LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Bonjour! Vous étiez dans un\n"
	.string "CONCOURS POKéMON, n'est-ce pas?\l"
	.string "Je reconnais votre POKéMON. Je\p"
	.string "suis journaliste. Je réalise\n"
	.string "un reportage sur les CONCOURS\p"
	.string "POKéMON. Je peux me permettre de\n"
	.string "vous poser quelques questions?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Vous voulez bien? Super!\n"
	.string "Merci. Rapidement, comment\p"
	.string "décririez-vous le CONCOURS\n"
	.string "auquel vous avez participé?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Oh, je vois. Quelle\n"
	.string "déclaration incroyable. Cela\p"
	.string "donne un bon aperçu de la\n"
	.string "façon dont s'est déroulé le\p"
	.string "CONCOURS. J'ai une dernière\p"
	.string "question. Lorsque vous\n"
	.string "entendez {STR_VAR_2}, ça vous évoque quoi?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Je vois! C'est comme ça que\p"
	.string "vous percevez le concept de\n"
	.string "{STR_VAR_2}. Merci! Vous m'avez donné\p"
	.string "de bonnes idées. Je vais\n"
	.string "pouvoir réaliser un\p"
	.string "chouette reportage sur les\n"
	.string "CONCOURS POKéMON. Avec un\p"
	.string "peu de chance, ce reportage\n"
	.string "passera même à la télé.\l"
	.string "J'espère que vous y comptez!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Oh, quel dommage… Eh bien, si\p"
	.string "vous entendez parler d'une\n"
	.string "S'il te plaît, partage avec moi.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Je suivrai votre prochain\n"
	.string "CONCOURS POKéMON avec intérêt.$"

gTVBravoTrainerText00::
	.string "C'est l'heure de\n"
	.string "BRAVO DRESSEUR!\p"
	.string "Aujourd'hui, nous allons\n"
	.string "appartenant à {STR_VAR_1}.\p"
	.string "Maintenant, ce POKéMON a\n{STR_VAR_3}"
	.string "un rang dans la{STR_VAR_2} catégorie .$"

gTVBravoTrainerText01::
	.string "Et voici {STR_VAR_2} le\n"
	.string "{STR_VAR_1}! Il est\p"
	.string "surnommé {STR_VAR_2}… {STR_VAR_3}!\p"
	.string "Son surnom\n"
	.string "l'évoque déjà!$"

gTVBravoTrainerText02::
	.string "Quoi qu'il en soit, quand le\n"
	.string "DRESSEUR {STR_VAR_1} a inscrit ce POKéMON\l"
	.string "dans un CONCOURS, nous avons\l"
	.string "pu parler de son partenaire.$"

gTVBravoTrainerText03::
	.string "A propos du CONCOURS, {STR_VAR_1}\n"
	.string "a déclaré avec un\l"
	.string "sourire: {STR_VAR_2}! Le POKéMON de\p"
	.string "{STR_VAR_1} a pris la place numéro {STR_VAR_3}\n"
	.string "du CONCOURS. Cette\p"
	.string "phrase résume bien l'état\n"
	.string "d'esprit de {STR_VAR_1} en ce moment!$"

gTVBravoTrainerText04::
	.string "A propos du CONCOURS, {STR_VAR_1} a\n"
	.string "déclaré avec une pointe\l"
	.string "d'amertume: {STR_VAR_2}. Le POKéMON\p"
	.string "de {STR_VAR_1} a pris la place\n"
	.string "numéro {STR_VAR_3} du CONCOURS. Il me\p"
	.string "semble que la déception de\n"
	.string "{STR_VAR_1} est tout à fait évidente!$"

gTVBravoTrainerText05::
	.string "N'aimeriez-vous pas aussi\n"
	.string "savoir ce que {STR_VAR_1} imagine {STR_VAR_2} être?\p"
	.string "Bien sûr\n"
	.string "qu'on l'a fait!\p"
	.string "La réponse est\n"
	.string "parfaitement condensée: {STR_VAR_3}!\p"
	.string "C'est ce que le\n"
	.string "concept de {STR_VAR_2} représente à {STR_VAR_1}!$"

gTVBravoTrainerText06::
	.string "La dernière démo,\n"
	.string "{STR_VAR_2}, utilisée par {STR_VAR_1}\l"
	.string "était tout à fait {STR_VAR_3}!$"

gTVBravoTrainerText07::
	.string "Bravo, {STR_VAR_1}! Bravo, {STR_VAR_2}! J'espère\n"
	.string "que nous pourrons encore\p"
	.string "voir {STR_VAR_1} gravir les échelons de\n"
	.string "la gloire! Bien, le temps qui\p"
	.string "nous est accordé est\n"
	.string "Jusqu'à la prochaine fois, à plus!$"

gTVBravoTrainerText08::
	.string "Et voici le {STR_VAR_1} du DRESSEUR!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Bonjour! C'est vous qui\n"
	.string "venez de vous battre,\p"
	.string "n'est-ce pas? J'interviewe\n"
	.string "tous les DRESSEURS du coin.\p"
	.string "Vous pouvez me donner vos\n"
	.string "impressions sur le combat?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Vraiment? Vous\n"
	.string "acceptez? Merci! Donc,\l"
	.string "heu… Comment ça s'est\p"
	.string "passé dans la TOUR DE\n"
	.string "COMBAT? En gardez-vous\p"
	.string "une bonne impression? Ou\n"
	.string "une mauvaise impression?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh… Je m'excuse du\n"
	.string "dérangement. J'espère que vous\p"
	.string "accepterez de nous répondre\n"
	.string "lors de votre prochaine visite.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Mais bien sûr! Cette\p"
	.string "incroyable lueur de\n"
	.string "satisfaction dans vos yeux…\p"
	.string "De toute évidence, vous\n"
	.string "avez fait un très beau combat.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, je vois… Oui, les\p"
	.string "combats ne se déroulent\n"
	.string "pas toujours comme prévu.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Une dernière petite\p"
	.string "question? Si vous deviez\n"
	.string "résumer vos impressions sur\l"
	.string "ce combat, que diriez-vous?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Incroyable! Quelle\p"
	.string "déclaration! Bonne chance\n"
	.string "pour vos prochains\p"
	.string "combats. A bientôt, j'espère!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, je vois… Mais être\p"
	.string "du genre silencieux,\n"
	.string "c'est bien aussi, non?\p"
	.string "J'espère avoir encore\n"
	.string "l'occasion de parler avec vous!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "J'ai hâte que vous\n"
	.string "fassiez votre prochain combat!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Ouais! C'est l'heure du\n"
	.string "DRESSEUR SPECIAL! Nous\p"
	.string "allons vous présenter {STR_VAR_1}, qui\n"
	.string "a relevé le défi de la TOUR\p"
	.string "DE COMBAT! Pour ce défi, {STR_VAR_1}\n"
	.string "avait inscrit son malicieux {STR_VAR_2}.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "Ils ont tous les deux établi le\n"
	.string "nouveau record de {STR_VAR_2} victoires\l"
	.string "Bravo, DRESSEUR!$"

BravoTrainerBattleTower_Text_Lost::
	.string "Ils se sont finalement\n"
	.string "inclinés devant {STR_VAR_1} lors du match\l"
	.string "numéro {STR_VAR_1}{STR_VAR_2}. Très bel essai,\p"
	.string "DRESSEUR! Affronter {STR_VAR_1} aussi tôt\n"
	.string "dans la compétition, quelle\p"
	.string "malchance! Nous avons demandé au\n"
	.string "DRESSEUR ses impressions sur {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "Le deux-some a tout\n"
	.string "{STR_VAR_1}gagné{STR_VAR_2} en battant à\l"
	.string "fond . Bravo, DRESSEUR!\p"
	.string "Ça défie la{STR_VAR_1} croyance!\n"
	.string "C'est tout simplement étonnant!\p"
	.string "Nous avons demandé au DRESSEUR des\n"
	.string "au moment de la gloire.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Après une série de victoires,\n"
	.string "la paire a finalement succombé\l"
	.string "à {STR_VAR_1}'s {STR_VAR_2}, leur dernier obstacle.\p"
	.string "Bien essayé, DRESSEUR!\p"
	.string "Vous ne voyez pas\n"
	.string "beaucoup de\l"
	.string "combinaisons célèbres comme {STR_VAR_1} et {STR_VAR_2}.\p"
	.string "On a demandé au DRESSEUR des\n"
	.string "en luttant contre les célébrités.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Voici la déclaration du\n"
	.string "DRESSEUR: Entière satisfaction!\p"
	.string "N'est-ce pas rafraîchissant?\n"
	.string "Bravo, DRESSEUR! N'est-ce pas\p"
	.string "grandiose de pouvoir se battre\n"
	.string "jusqu'à la satisfaction totale?\p"
	.string "J'ai vraiment compris l'état\n"
	.string "du DRESSEUR quand il a déclaré:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Voici la déclaration du DRESSEUR:\n"
	.string "On ne peut pas parler de\p"
	.string "satisfaction… Visiblement, notre\n"
	.string "DRESSEUR était quelque peu abattu.\p"
	.string "Mais il faut dire qu'il est dur de\n"
	.string "sortir du combat pleinement\p"
	.string "satisfait, non? J'ai mieux compris\n"
	.string "l'humeur du DRESSEUR à ces mots:$"

BravoTrainerBattleTower_Text_None1::
	.string "Rien$"

BravoTrainerBattleTower_Text_None2::
	.string "Rien$"

BravoTrainerBattleTower_Text_None3::
	.string "Rien$"

BravoTrainerBattleTower_Text_None4::
	.string "Rien$"

BravoTrainerBattleTower_Text_Response::
	.string "{STR_VAR_1}.$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "{STR_VAR_1}. N'est-ce pas\n"
	.string "formidable? Cela\p"
	.string "exprime parfaitement la\n"
	.string "joie de {STR_VAR_2}, je pense. Ce\p"
	.string "combat contre {STR_VAR_3}, vers la\n"
	.string "fin… {STR_VAR_1}, c'est vraiment\l"
	.string "ce que vous en diriez!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "{STR_VAR_1}. Voilà qui est judicieux,\n"
	.string "n'est-ce pas? Et ce dernier\p"
	.string "combat contre {STR_VAR_3}… Je crois\n"
	.string "que la déclaration {STR_VAR_1} résume\l"
	.string "parfaitement la situation!\p"
	.string "Il me semble que la\n"
	.string "C'est clair, je dirais!$"

BravoTrainerBattleTower_Text_Outro::
	.string "Bravo, {STR_VAR_2}{STR_VAR_1}! Bravo, {STR_VAR_2}! J'espère\n"
	.string "que nous pourrons encore\p"
	.string "voir {STR_VAR_1} gravir les échelons de\n"
	.string "la gloire! Bien, le temps qui\p"
	.string "nous est accordé est\n"
	.string "Jusqu'à la prochaine fois, à plus!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Waouh! Apparemment, vous\p"
	.string "donnez beaucoup d'amour à\n"
	.string "votre {STR_VAR_1}. Ah, d'accord, il\p"
	.string "s'appelle {STR_VAR_2}. Je peux vous\p"
	.string "demander un service? Je suis\p"
	.string "journaliste pour la télé et je\n"
	.string "réalise un sondage sur les\p"
	.string "POKéMON. Pourriez-vous répondre à\n"
	.string "Des questions simples pour moi?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Super! Merci beaucoup! Très\p"
	.string "bien, allons-y. Il me faut des\n"
	.string "réponses concises, d'accord?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "La première fois que vous avez vu\n"
	.string "{STR_VAR_1}, qu'avez-vous ressenti? Comment\p"
	.string "décririez-vous les sentiments\n"
	.string "à l'époque?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Ce {STR_VAR_1} est traité avec amour. Si vous\p"
	.string "le compariez à quelque chose que\n"
	.string "vous aimez, de quoi s'agirait-il?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Cette question est\n"
	.string "aussi valable pour\p"
	.string "votre {STR_VAR_1} adoré.\n"
	.string "Qu'est-ce que vous aimez chez {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Bien sûr, c'est\p"
	.string "logique. La prochaine\n"
	.string "question est un peu plus\p"
	.string "compliquée. La voici: Pour\p"
	.string "vous, que signifie POKéMON?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Je vois! Humm… Très\p"
	.string "bien! Merci de votre\p"
	.string "coopération. Cette\n"
	.string "discussion avec vous a\p"
	.string "été amusante et\n"
	.string "enrichissante. Votre\p"
	.string "interview passera\n"
	.string "peut-être à la télé.\p"
	.string "Regardez-la régulièrement!\n"
	.string "Voilà, c'est tout. À bientôt!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, très bien… Si vous\p"
	.string "changez d'avis et que vous\n"
	.string "à propos de POKéMON, je serai là!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "J'adore ce métier. On peut\n"
	.string "apprendre tant sur les POKéMON.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Salut! Vous semblez très\n"
	.string "proche de votre {STR_VAR_1}. Vous\p"
	.string "savez quoi? Je suis\n"
	.string "journaliste pour la télé. Je\p"
	.string "voyage pour interviewer les\n"
	.string "gens à propos des POKéMON.\p"
	.string "Mais j'y pense, vous voulez\n"
	.string "peut-être me parler de votre {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Super, merci! Bon, eh\p"
	.string "bien, dites-moi ce que\n"
	.string "vous aimez chez votre {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Oh… Voilà des remarques\n"
	.string "intéressantes. Vous êtes\p"
	.string "vraiment très intime avec\n"
	.string "{STR_VAR_1}, n'est-ce pas? J'ai\p"
	.string "l'impression que vos\n"
	.string "déclarations feront un\p"
	.string "chouette sujet pour la\n"
	.string "télé. Je vous promets d'en\l"
	.string "faire une super émission.\p"
	.string "Regardez-nous régulièrement.\n"
	.string "Voilà, c'est tout. À bientôt!$"

gTVFanClubOpinionsText00::
	.string "C'EST NOUS, LE FAN CLUB\p"
	.string "POKéMON! Et nous sommes en\p"
	.string "direct! Dans cette\n"
	.string "émission, nous compilons\l"
	.string "vos opinions et nous les\p"
	.string "diffusons! Super concept\n"
	.string "d'émission, n'est-ce pas?\l"
	.string "Aujourd'hui, nous vous\p"
	.string "présentons un reportage de\n"
	.string "notre journaliste, envoyé\p"
	.string "spécial au FAN CLUB POKéMON.\p"
	.string "Bien, qui est notre fan de\p"
	.string "POKéMON, aujourd'hui? … … …\n"
	.string "… … … … … {STR_VAR_1}! Ecoutons ce que\p"
	.string "{STR_VAR_1} souhaite nous raconter sur\n"
	.string "{STR_VAR_3} le {STR_VAR_2}. Puis, je répandrai\p"
	.string "ces belles paroles sur les\p"
	.string "ondes! Youhou! C'est parti!$"

gTVFanClubOpinionsText01::
	.string "Nous avons demandé à {STR_VAR_1}: La\n"
	.string "première fois que vous avez vu\l"
	.string "votre {STR_VAR_2}, qu'avez-vous ressenti?\p"
	.string "{STR_VAR_3}! Hé! Génial! Quelles paroles\p"
	.string "magnifiques! Pas de doute, ça\p"
	.string "nous remet en mémoire de\n"
	.string "magnifiques souvenirs d'autrefois.$"

gTVFanClubOpinionsText02::
	.string "Nous avons demandé à {STR_VAR_1}:\n"
	.string "Si vous deviez\l"
	.string "comparer votre {STR_VAR_2} à\p"
	.string "quelque chose, ce\p"
	.string "serait… … … … … … … … … {STR_VAR_3}!\p"
	.string "Hé, voilà une idée\p"
	.string "originale! On peut sentir\n"
	.string "l'intensité des sentiments\l"
	.string "de ce DRESSEUR pour son {STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "Continuons… Qu'est-ce\n"
	.string "qui était si attirant\l"
	.string "chez {STR_VAR_2} pour {STR_VAR_1}? … … … …\p"
	.string "… … … … {STR_VAR_3}! Waouh!\p"
	.string "Quelle déclaration\p"
	.string "fracassante! L'amour\p"
	.string "de ce DRESSEUR pour\n"
	.string "son {STR_VAR_2} ne fait aucun doute!$"

gTVFanClubOpinionsText04::
	.string "Hein? Oh, nous avons\n"
	.string "encore du temps. Très\p"
	.string "bien! Voyons donc…\p"
	.string "Nous avons demandé à\n"
	.string "{STR_VAR_1}: Pour vous, que\p"
	.string "signifie POKéMON? … …\p"
	.string "… … … … {STR_VAR_3}! Bravo! Ce\p"
	.string "sont de bien belles\p"
	.string "paroles! {STR_VAR_3}! Ça donne\p"
	.string "envie de le répéter\p"
	.string "encore et encore!\n"
	.string "Bien, après ces belles\p"
	.string "paroles, il est temps\n"
	.string "de se dire À bientôt.\p"
	.string "Et répétons encore\n"
	.string "une fois ces belles\p"
	.string "paroles! Tous ensemble… {STR_VAR_3}!$"

gTVFanClubText00::
	.string "C'EST NOUS, LE FAN CLUB\p"
	.string "POKéMON! Et nous sommes en\p"
	.string "direct! Aujourd'hui, nous\n"
	.string "allons commencer par le\p"
	.string "QUART D'HEURE DES SONDAGES.\n"
	.string "Parmi les histoires de\l"
	.string "POKéMON et de DRESSEURS,\p"
	.string "quel récit va attirer notre\p"
	.string "attention aujourd'hui?\p"
	.string "Voyons voir… Celui-ci! Nous\p"
	.string "allons commencer par cette\n"
	.string "lettre! Il s'agit d'une\p"
	.string "lettre de {STR_VAR_1} à propos de son {STR_VAR_2}.\n"
	.string "Voyons comment notre écrivain\l"
	.string "exprime son amour pour {STR_VAR_2}! Humm…$"

gTVFanClubText01::
	.string "Wouah! Quelle\n"
	.string "lettre incroyable!$"

gTVFanClubText02::
	.string "J'ai adoré, alors c'est encore là!$"

gTVFanClubText03::
	.string "Quand une lettre est belle,\n"
	.string "on peut la relire à volonté!$"

gTVFanClubText04::
	.string "La partie {STR_VAR_3}{STR_VAR_3} met vraiment\n"
	.string "l'accent sur l'impact\p"
	.string "émotionnel! C'est une lettre\n"
	.string "Une profondeur sincère!$"

gTVFanClubText05::
	.string "Surtout la partie {STR_VAR_3}!\p"
	.string "Super utilisation de {STR_VAR_3}!$"

gTVFanClubText06::
	.string "D'ailleurs, ça n'est pas\n"
	.string "important, mais {STR_VAR_3} est super\p"
	.string "chouette. Ces derniers temps,\n"
	.string "dans les conversations récemment.$"

gTVFanClubText07::
	.string "Si je devais noter cette lettre,\n"
	.string "je lui donnerais {STR_VAR_3} points. La\p"
	.string "prochaine fois, j'espère que {STR_VAR_1} nous\n"
	.string "fera une lettre encore meilleure!\p"
	.string "Oh, le temps passe à une vitesse\n"
	.string "folle! Il est temps de se quitter!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh? Vous aimez peut-être les\n"
	.string "POKéMON? J'effectue un\p"
	.string "reportage pour la chaîne de TV.\p"
	.string "Je recueille des histoires\n"
	.string "récentes de POKéMON et de\p"
	.string "DRESSEURS. Si ça ne vous gêne pas,\n"
	.string "Quelque chose à propos de toi?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Je recueille des histoires\n"
	.string "récentes de POKéMON et de\p"
	.string "DRESSEURS. Si ça ne vous gêne pas,\n"
	.string "Quelque chose à propos de toi?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, vous voulez bien?\n"
	.string "Merci beaucoup! Dans ce\p"
	.string "cas, pouvez-vous me raconter\n"
	.string "une histoire intéressante\l"
	.string "en rapport avec des POKéMON?$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Bon, tant pis… Si vous avez\p"
	.string "une histoire intéressante à\n"
	.string "raconter, revenez me voir.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, quelle histoire\p"
	.string "passionnante! Je vais m'arranger\n"
	.string "pour faire passer votre histoire à\p"
	.string "la télévision. Elle sera bientôt\n"
	.string "donc s'il vous plaît attendez-le.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Humm… J'ai une excellente histoire\n"
	.string "pour une émission de télé. Je\p"
	.string "Je ferais mieux de l'écrire vite!$"

gTVRecentHappeningsText00::
	.string "Bonjour, bienvenue à HISTOIRES\p"
	.string "VECUES. La vie quotidienne des\n"
	.string "DRESSEURS DE POKéMON est digne\p"
	.string "des meilleurs contes. Nous\n"
	.string "allons vous présenter certains\p"
	.string "de ces contes de POKéMON.\n"
	.string "Aujourd'hui, nous allons vous\p"
	.string "raconter l'histoire du DRESSEUR {STR_VAR_1}.\n"
	.string "Qu'est-il arrivé à {STR_VAR_1} récemment?\p"
	.string "Voyons...$"

gTVRecentHappeningsText01::
	.string "Une histoire enrichissante,\p"
	.string "n'est-ce pas? Cette histoire vous\n"
	.string "donne une idée des récentes\l"
	.string "aventures de {STR_VAR_1}. On s'y croirait!$"

gTVRecentHappeningsText02::
	.string "{STR_VAR_3}. Cela donne de la\n"
	.string "profondeur à l'histoire.$"

gTVRecentHappeningsText03::
	.string "{STR_VAR_3}. Cela met l'histoire\n"
	.string "en perspective. On en\l"
	.string "sait plus sur le contexte.$"

gTVRecentHappeningsText04::
	.string "{STR_VAR_3}. Cette partie de\n"
	.string "l'histoire est explicite.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} nous a raconté une\n"
	.string "merveilleuse histoire de\p"
	.string "POKéMON. L'histoire de {STR_VAR_1} est\n"
	.string "désormais gravée dans nos esprits\p"
	.string "pour toujours. C'est fini pour\n"
	.string "aujourd'hui. A la prochaine fois.$"

gTVMassOutbreakText00::
	.string "Bonjour à tous! C'est\n"
	.string "l'heure du BULLETIN POKéMON.\p"
	.string "Nous venons d'apprendre\n"
	.string "l'apparition d'un phénomène\p"
	.string "très rare. Des témoignages\n"
	.string "affirment l'arrivée massive\l"
	.string "de {STR_VAR_2} du côté de la {STR_VAR_1}. Les {STR_VAR_2},\p"
	.string "comme vous le savez déjà, sont\n"
	.string "des POKéMON très rares et\l"
	.string "difficiles à trouver. Voici\p"
	.string "donc une chance unique de voir\n"
	.string "ce débarquement en masse de {STR_VAR_2}\l"
	.string "sauvages dans la nature.\p"
	.string "C'est la nouvelle de POKéMON.$"

gTV3CheersForPokeblocksText00::
	.string "ANIMATRICE: C'est\n"
	.string "l'heure de retrouver\p"
	.string "VIVE LES {POKEBLOCK}S!\n"
	.string "Aujourd'hui, nous allons\p"
	.string "tester le {POKEBLOCK} créé avec\n"
	.string "l'aide de {STR_VAR_1}. Sans attendre,\p"
	.string "je vais le faire goûter à\n"
	.string "mon GLOUPTI. … … … … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GULPIN: Gubi, Gubi!\p"
	.string "MC: Et le verdict est très {STR_VAR_1}!\n"
	.string "GULPIN dit qu'il a un goût {STR_VAR_2}!\p"
	.string "Merci beaucoup, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "Le résultat de {STR_VAR_1} laisse à\n"
	.string "désirer. Si ce DRESSEUR\p"
	.string "pouvait mieux mixer,\n"
	.string "le {POKEBLOCK} aurait plus de goût.$"

gTV3CheersForPokeblocksText03::
	.string "GULPIN: Gubi, Gubi!\p"
	.string "MC: C'est trop {STR_VAR_1}.\n"
	.string "GULPIN dit qu'il a un goût {STR_VAR_2}!\p"
	.string "On dirait que les erreurs de {STR_VAR_3}\n"
	.string "nuisent à la qualité du mélange...$"

gTV3CheersForPokeblocksText04::
	.string "Les efforts de {STR_VAR_1}\n"
	.string "n'ont servi à rien.\p"
	.string "Espérons que {STR_VAR_2} fera\n"
	.string "mieux la prochaine fois!$"

gTV3CheersForPokeblocksText05::
	.string "A la prochaine! Et\n"
	.string "n'oubliez pas: VIVE LES {POKEBLOCK}S!$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Salut! Je suis fan de\p"
	.string "{STR_VAR_1}. Je l'adore! Et\n"
	.string "toi, tu penses quoi de {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Je vois, je vois. C'est donc\n"
	.string "ce que tu penses de ce DRESSEUR.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Est-ce que tu as\n"
	.string "tout oublié sur {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Je suis fan de {STR_VAR_1}. Je l'adore!\n"
	.string "Et toi, tu penses quoi de {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Sur 100, tu\n"
	.string "mettrais combien à {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Est-ce que tu as\n"
	.string "tout oublié sur {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Oh, je vois! Mais tu devrais\n"
	.string "rencontrer {STR_VAR_1}. Tu deviendras vite\l"
	.string "fan, je n'en doute pas.$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Je vois, je vois.\p"
	.string "Merci! C'est bon à\n"
	.string "savoir. Je partagerai\p"
	.string "l'info avec d'autres fans de\n"
	.string "{STR_VAR_1} et en discuterai avec eux!$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Il va bientôt y avoir un\n"
	.string "reportage sur {STR_VAR_1} à la télé.\p"
	.string "J'espère que tu pourras le voir!$"

gTVTrainerFanClubSpecialText00::
	.string "DRESSEUR FAN\n"
	.string "{STR_VAR_1}CLUB SPECIAL!\p"
	.string "C'est une présentation spéciale\n"
	.string "pour les fans{STR_VAR_1} de dans tout HOENN!\p"
	.string "Aujourd'hui, nous posons la\n"
	.string "Les gens pensent à {STR_VAR_1}?\p"
	.string "Nous avons posé la question à \n{STR_VAR_2}"
	.string "en tant que représentant DRESSEUR.\p"
	.string "Nous avons demandé, En un\n"
	.string "mot, comment décririez-vous{STR_VAR_1} ?\p"
	.string "La réponse est:{STR_VAR_3} .\p"
	.string "Quelle\n{STR_VAR_2}"
	.string "opinion perspicace!\p"
	.string "{STR_VAR_3}Il a{STR_VAR_1} une si\n"
	.string "belle bague à elle!\p"
	.string "{STR_VAR_2} a{STR_VAR_1} également\n"
	.string "marqué de 0 à 100.$"

gTVTrainerFanClubSpecialText01::
	.string "Le score est de {STR_VAR_3} points!\n"
	.string "C'est un score vraiment très\p"
	.string "important! {STR_VAR_2} doit certainement\n"
	.string "avoir une très haute opinion de {STR_VAR_1}!$"

gTVTrainerFanClubSpecialText02::
	.string "Le score est de {STR_VAR_3}\n"
	.string "points! C'est un bon\p"
	.string "score! {STR_VAR_2} doit considérer {STR_VAR_1}\n"
	.string "comme un véritable adversaire!$"

gTVTrainerFanClubSpecialText03::
	.string "Le score est de {STR_VAR_3} points!\n"
	.string "C'est un score plutôt\p"
	.string "faible! {STR_VAR_2} doit juste\n"
	.string "{STR_VAR_1} pour être un simple acolyte.$"

gTVTrainerFanClubSpecialText04::
	.string "Le score est de {STR_VAR_3}\n"
	.string "point(s)! C'est un score\p"
	.string "ridicule! {STR_VAR_2} doit avoir une\n"
	.string "bien mauvaise impression de {STR_VAR_1}.$"

gTVTrainerFanClubSpecialText05::
	.string "Voilà les amis! Je\p"
	.string "crois que nous venons\n"
	.string "d'apprendre quelque\p"
	.string "chose sur {STR_VAR_1}. Pour finir,\n"
	.string "je vous laisse avec la\p"
	.string "parole du jour de {STR_VAR_2}. {STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "Et maintenant,\n"
	.string "c'est l'heure de...\p"
	.string "Je dis la fortune de votre\n"
	.string "le surnom que tu as donné.\p"
	.string "Le conseil est ce que j'ai à\n"
	.string "des conseils utiles que j'offre.\p"
	.string "Aujourd'hui, je vais\n"
	.string "faire une lecture du\l"
	.string "surnom {STR_VAR_3} du POKéMON de {STR_VAR_1} {STR_VAR_2}.\p"
	.string "Qu'est-ce que c'est?\p"
	.string "Ce\n"
	.string "surnom est...$"

gTVNameRaterText01::
	.string "Un surnom qui laisse deviner de\n"
	.string "nombreux talents, divers et\p"
	.string "variés. Je recommande à ce\n"
	.string "et relever de nombreux défis.$"

gTVNameRaterText02::
	.string "Un surnom qui complète\n"
	.string "parfaitement {STR_VAR_1}, le nom du DRESSEUR.\p"
	.string "Cela suggère qu'ils forment une\n"
	.string "bonne équipe en parfaite harmonie.$"

gTVNameRaterText03::
	.string "Un surnom qui met en avant la\n"
	.string "personnalité unique du POKéMON!\p"
	.string "S'il est élevé correctement, ce\n"
	.string "l'unicité fleurira excessivement!$"

gTVNameRaterText04::
	.string "Un surnom qui montre bien\n"
	.string "l'attention et la compassion de ce\p"
	.string "POKéMON. S'il est élevé\n"
	.string "Venez présenter une vraie chaleur!$"

gTVNameRaterText05::
	.string "Un très joli surnom qui\n"
	.string "suggère un avenir\p"
	.string "prometteur. Je me demande ce que\n"
	.string "l'avenir réserve à ce POKéMON.$"

gTVNameRaterText06::
	.string "Un chouette surnom qui devrait\n"
	.string "garantir une bonne santé à ce\p"
	.string "POKéMON! Ce POKéMON aura une\n"
	.string "robuste pendant longtemps.$"

gTVNameRaterText07::
	.string "Un chouette surnom qui donnera\n"
	.string "beaucoup d'énergie à ce POKéMON!\p"
	.string "Tout porte à croire que ce POKéMON\n"
	.string "un acteur fort dans les batailles.$"

gTVNameRaterText08::
	.string "Un surnom plaisant qui rend ce\n"
	.string "POKéMON très charmant! Aucun\p"
	.string "doute possible, ce POKéMON aura\n"
	.string "du succès pendant les CONCOURS.$"

gTVNameRaterText09::
	.string "La racine du surnom {STR_VAR_1}\n"
	.string "s'appuie sur la lettre {STR_VAR_3}. Cette\p"
	.string "lettre est soutenue par la\n"
	.string "première lettre, {STR_VAR_2}, qui confère\l"
	.string "une forte présence au surnom.$"

gTVNameRaterText10::
	.string "Le surnom {STR_VAR_1} est très\n"
	.string "harmonieux et très agréable.\p"
	.string "La présence des lettres {STR_VAR_2} et {STR_VAR_3}\n"
	.string "est particulièrement bienvenue!$"

gTVNameRaterText11::
	.string "Le surnom {STR_VAR_1} révèle une\n"
	.string "magnificence et une fluidité\p"
	.string "certaines. Le passage de la\n"
	.string "de {STR_VAR_2} à {STR_VAR_3} est superbe.$"

gTVNameRaterText12::
	.string "Etudions d'autres exemples de\n"
	.string "surnoms, si vous le voulez bien!$"

gTVNameRaterText13::
	.string "Par exemple, prenons une partie\n"
	.string "du nom du DRESSEUR {STR_VAR_1}, ce qui\l"
	.string "pourrait donner un super surnom: {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "{STR_VAR_2}{STR_VAR_3} pourrait aussi être\n"
	.string "une bonne idée de surnom.$"

gTVNameRaterText15::
	.string "Le nom de l'espèce du\n"
	.string "POKéMON, {STR_VAR_2}, pourrait servir\l"
	.string "de point de départ au surnom {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} serait aussi un\n"
	.string "surnom efficace.$"

gTVNameRaterText17::
	.string "En revanche, il faut éviter\n"
	.string "d'utiliser le nom d'espèce d'un\p"
	.string "autre POKéMON. Par exemple, il ne\n"
	.string "faut pas prendre le nom {STR_VAR_2} pour\l"
	.string "C'est inacceptable.$"

gTVNameRaterText18::
	.string "Mais il faut bien admettre que {STR_VAR_1}\n"
	.string "est un bon surnom. Espérons\p"
	.string "que ce DRESSEUR continuera à\n"
	.string "traiter {STR_VAR_3}{STR_VAR_1}{STR_VAR_1} avec amour. Voilà!\p"
	.string "C'est fini pour aujourd'hui. Ne\n"
	.string "Puissions-nous nous revoir.$"

gTVPokemonAnglerText00::
	.string "PECHE AU {STR_VAR_2} PRESENTATEUR:\p"
	.string "Salut! Aujourd'hui, nous\n"
	.string "apprenons à pêcher le {STR_VAR_2}.\p"
	.string "Vous, le PRO DE LA PECHE,\n"
	.string "quel conseil donneriez-vous\p"
	.string "pour la pêche au {STR_VAR_2}? PRO DE LA\n"
	.string "PECHE: Hein? La pêche au {STR_VAR_2}? Eh\l"
	.string "bien, tout d'abord, soyez\p"
	.string "patients. C'est la base de\n"
	.string "tout. Vous voyez {STR_VAR_1}, là-bas? Ce\p"
	.string "DRESSEUR est un bon exemple.\n"
	.string "Il a déjà laissé filer {STR_VAR_3}\p"
	.string "POKéMON. Et pourtant, {STR_VAR_1}\n"
	.string "attend, sans abandonner. C'est\p"
	.string "ainsi qu'on attrape des {STR_VAR_2}.\p"
	.string "PRESENTATEUR: Je vois… Oh! {STR_VAR_1} a\n"
	.string "finalement attrapé un {STR_VAR_2}\p"
	.string "récalcitrant! Le DRESSEUR est\n"
	.string "sur le point de pleurer de\p"
	.string "joie! Quand je vois ce genre de\n"
	.string "regard, ça me donne envie de\p"
	.string "pêcher! Téléspectateurs,\n"
	.string "pourquoi ne pas vous mettre à la\p"
	.string "pêche au {STR_VAR_2}? En attendant notre\n"
	.string "Bonne pêche à vous tous!$"

gTVPokemonAnglerText01::
	.string "PECHE AU {STR_VAR_2} PRESENTATEUR:\p"
	.string "Salut! Aujourd'hui, nous\n"
	.string "apprenons à pêcher le {STR_VAR_2}. Vous,\p"
	.string "le PRO DE LA PECHE, quel\n"
	.string "conseil donneriez-vous pour la\p"
	.string "pêche au {STR_VAR_2}? PRO DE LA PECHE:\n"
	.string "Hein? La pêche au {STR_VAR_2}? Eh bien,\l"
	.string "tout d'abord, tenez votre\p"
	.string "CANNE énergiquement! Vous\n"
	.string "voyez {STR_VAR_1}, là-bas? Vous voyez\p"
	.string "comment il tient sa CANNE? Ce\n"
	.string "DRESSEUR vient d'en attraper {STR_VAR_3}\p"
	.string "de suite. PRESENTATEUR: C'est\n"
	.string "incroyable! C'est une véritable\p"
	.string "razzia… Quand je vois une telle\n"
	.string "technique, ça me donne envie de\p"
	.string "pêcher! Téléspectateurs,\n"
	.string "pourquoi ne pas vous mettre à la\p"
	.string "pêche au {STR_VAR_2}? En attendant notre\n"
	.string "Bonne pêche à vous tous!$"

gTVPokemonTodayFailedText00::
	.string "Bonjour!\p"
	.string "C'est l'heure de POKéMON!\p"
	.string "BIG SIS: Est-ce que tout le monde\n"
	.string "est pêcheur et perky aujourd'hui?\p"
	.string "Aujourd'hui, nous allons\n"
	.string "regarder le POKéMON de {STR_VAR_1} {STR_VAR_2}!\p"
	.string "BIG BRO: C'est\n"
	.string "ce qu'on va faire!$"

gTVPokemonTodayFailedText01::
	.string "Oh! Puisqu'on parle de\n"
	.string "{STR_VAR_1}… FRANGINE, j'ai vu ce\p"
	.string "DRESSEUR de mes\n"
	.string "propres yeux!\p"
	.string "FRANGINE: Oh, vraiment?\p"
	.string "FRANGIN: Oui, j'étais\n"
	.string "en voyage à {STR_VAR_2}. Et je suis\p"
	.string "tombé sur {STR_VAR_1}, qui\n"
	.string "essayait d'attraper le\l"
	.string "POKéMON {STR_VAR_3}, mais malheureusement…$"

gTVPokemonTodayFailedText02::
	.string "Le POKéMON a réussi à\p"
	.string "s'échapper! Finalement, le\n"
	.string "DRESSEUR a gaspillé {STR_VAR_2} POKé\p"
	.string "BALLS! Il fallait voir la\n"
	.string "déception dans les yeux de {STR_VAR_1} au\l"
	.string "moment où le POKéMON s'est enfui!$"

gTVPokemonTodayFailedText03::
	.string "{STR_VAR_1} a fait une gaffe et le\n"
	.string "POKéMON s'est retrouvé\p"
	.string "K.O.! Finalement, le\n"
	.string "DRESSEUR a gaspillé {STR_VAR_2} POKé\p"
	.string "BALLS! Il fallait voir le\n"
	.string "désarroi dans les yeux de {STR_VAR_1} au\l"
	.string "quand le POKéMON s'est évanoui!$"

gTVPokemonTodayFailedText04::
	.string "FRANGINE: Hé! Ce\n"
	.string "n'est pas très\p"
	.string "sympa! Il ne faut\n"
	.string "pas se moquer du\p"
	.string "malheur des autres!\n"
	.string "Pauvre {STR_VAR_1}. Quel dommage!\p"
	.string "FRANGIN: C'est vrai!\n"
	.string "Désolé de m'être moqué.$"

gTVPokemonTodayFailedText05::
	.string "FRANGINE: Hi hi\p"
	.string "hi… FRANGIN:\n"
	.string "Hé! Tu viens de\p"
	.string "rire! FRANGINE:\p"
	.string "Hein?! Je n'ai\n"
	.string "pas rigolé!\p"
	.string "Honnêtement!\n"
	.string "Pauvre {STR_VAR_1}. Quel\p"
	.string "dommage! FRANGIN: …$"

gTVPokemonTodayFailedText06::
	.string "FRANGINE: Finies les\n"
	.string "bêtises! Voyons donc le\p"
	.string "POKéMON du jour… Quoi?\n"
	.string "Notre temps est déjà écoulé?\p"
	.string "Oh non! Nous n'avons eu le\n"
	.string "temps de présenter aucun\p"
	.string "POKéMON! FRANGIN: A la\p"
	.string "prochaine! FRANGINE: Hé, ne\n"
	.string "terminez pas l'émission sans moi!$"

gTVPokemonTodaySuccessfulText00::
	.string "Bonjour!\p"
	.string "C'est l'heure de POKéMON!\p"
	.string "BIG SIS: Est-ce que tout le monde\n"
	.string "est pêcheur et perky aujourd'hui?\p"
	.string "Aujourd'hui, nous allons\n"
	.string "regarder le POKéMON de {STR_VAR_1} {STR_VAR_2}!\p"
	.string "BIG BRO: C'est\n"
	.string "ce qu'on va faire!$"

gTVPokemonTodaySuccessfulText01::
	.string "BIG SIS: {STR_VAR_1} a\n"
	.string "donné le surnom {STR_VAR_3} au {STR_VAR_2}!\p"
	.string "On dirait que {STR_VAR_3} est en train de\n"
	.string "recevoir de bons soins affectueux!$"

gTVPokemonTodaySuccessfulText02::
	.string "FRANGIN: Ce DRESSEUR a dû\n"
	.string "lancer {STR_VAR_3} BALL(S) pour\p"
	.string "l'attraper! Hé, tu te rends\n"
	.string "pour l'attraper!$"

gTVPokemonTodaySuccessfulText03::
	.string "FRANGINE: S'il était si\n"
	.string "facile à attraper, c'est que\l"
	.string "le destin a voulu réunir {STR_VAR_2}{STR_VAR_1} et {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText04::
	.string "FRANGINE: Ouah! C'est génial!\p"
	.string "Mais comme on dit, un POKéMON\n"
	.string "difficile à attraper est assuré\l"
	.string "d'obtenir l'amour de son DRESSEUR!$"

gTVPokemonTodaySuccessfulText05::
	.string "BIG SIS: {STR_VAR_1}'s {STR_VAR_2} est un POKéMON\n"
	.string "mémorable parce qu'il a fallu un\l"
	.string "MASTER BALL précieux à attraper!\p"
	.string "BIG BRO: C'est génial!\p"
	.string "BIG SIS: {STR_VAR_1} doit bien\n"
	.string "avoir voulu que {STR_VAR_2}, pour sûr!$"

gTVPokemonTodaySuccessfulText06::
	.string "BIG BRO: Puis donner\n"
	.string "le surnom {STR_VAR_3} à ce {STR_VAR_2}...\p"
	.string "Tu as bien une bonne\n"
	.string "idée du sens du DRESSEUR {STR_VAR_1}.\p"
	.string "BIG SIS: J'appuie cette notion!$"

gTVPokemonTodaySuccessfulText07::
	.string "Moi en revanche, j'aurais\n"
	.string "donné ce surnom à un {STR_VAR_3}!\p"
	.string "FRANGIN: Hé! Mais ça pourrait\n"
	.string "être le début d'une nouvelle mode!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} le {STR_VAR_1}! Ça sonne bien,\n"
	.string "non? Les lettres, la\p"
	.string "prononciation, tout\n"
	.string "colle parfaitement\l"
	.string "au POKéMON {STR_VAR_1}!\p"
	.string "FRANGIN: Oui, c'est vrai!$"

gTVPokemonTodaySuccessfulText09::
	.string "A ma connaissance,\n"
	.string "aucun DRESSEUR n'a\l"
	.string "jamais donné le surnom {STR_VAR_2} à\p"
	.string "un {STR_VAR_1}! FRANGIN: Cela prouve\n"
	.string "le bon goût de ce\l"
	.string "DRESSEUR en matière de surnoms!$"

gTVPokemonTodaySuccessfulText10::
	.string "La prochaine fois que\n"
	.string "j'attrape un POKéMON, je\p"
	.string "l'appelle {STR_VAR_2}. FRANGIN: Vraiment?\n"
	.string "Moi aussi! Je l'appellerai {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText11::
	.string "FRANGINE: Oh, non! L'heure\n"
	.string "tourne! Bon, les amis, c'est\p"
	.string "fini pour aujourd'hui. À bientôt\n"
	.string "et à bientôt! FRANGIN: N'oubliez\p"
	.string "pas, votre POKéMON pourrait être\n"
	.string "le sujet de la prochaine émission!$"

SmartShopper_Text_Intro::
	.string "Bonjour à tous! C'est\p"
	.string "l'heure du POKéACHAT.\p"
	.string "JOURNALISTE: Comment vont nos\p"
	.string "téléspectateurs?\n"
	.string "Aujourd'hui, nous visitons une\p"
	.string "boutique à {STR_VAR_2}. Voyons donc ce que\n"
	.string "nos vendeuses ont à nous proposer!$"

SmartShopper_Text_ClerkNormal::
	.string "Interrogeons cette vendeuse\n"
	.string "pour savoir quelle est la\p"
	.string "tendance. Bonjour, comment\p"
	.string "vont les affaires? VENDEUSE:\p"
	.string "Oh, très très bien. En ce\n"
	.string "moment, l'objet {STR_VAR_2} se vend\p"
	.string "beaucoup. Par exemple, Récemment,\n"
	.string "un DRESSEUR appelé {STR_VAR_1} en a acheté {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "INTERVIEWER: Le DRESSEUR a\n"
	.string "acheté {STR_VAR_3} {STR_VAR_2}S? C'est un trail!\p"
	.string "{STR_VAR_1} a dû être en réserve\n"
	.string "pour un long voyage vers\l"
	.string "des endroits lointains.\p"
	.string "Pour voyager, {STR_VAR_2}S\n"
	.string "sont si importants!$"

SmartShopper_Text_RandomComment2::
	.string "INTERVIEWER: En parlant\n"
	.string "de l'article {STR_VAR_2}, je viens\l"
	.string "d'en acheter {STR_VAR_3} récemment.\p"
	.string "Après tout, {STR_VAR_2} est un bon article!$"

SmartShopper_Text_RandomComment3::
	.string "JOURNALISTE: Combien de fois\n"
	.string "l'objet {STR_VAR_2}?! {STR_VAR_3}?! Je n'aurais\p"
	.string "jamais cru que quelqu'un en\n"
	.string "achèterait autant. Bon sang,\p"
	.string "je ne peux pas me permettre\n"
	.string "d'en acheter autant que ça, moi…$"

SmartShopper_Text_RandomComment4::
	.string "JOURNALISTE: Une fois, j'ai\n"
	.string "acheté un lot complet de\p"
	.string "l'objet {STR_VAR_2}. Mais finalement, il\n"
	.string "y en avait trop. J'ai fini\p"
	.string "par le regretter… Depuis, je\n"
	.string "n'achète que ce qui est\p"
	.string "strictement nécessaire… Heu…\p"
	.string "Inutile de parler de moi!$"

SmartShopper_Text_SecondItem::
	.string "CLERK: {STR_VAR_1} a également acheté le\n"
	.string "produit {STR_VAR_2} en vrac, en prenant {STR_VAR_3}.\p"
	.string "INTERVIEWER: Oh, c'est\n"
	.string "{STR_VAR_2} est un très bon article, aussi.$"

SmartShopper_Text_ThirdItem::
	.string "VENDEUSE: Et le DRESSEUR a aussi\n"
	.string "acheté {STR_VAR_3} exemplaires de l'objet {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "VENDEUSE: En plus, c'était\n"
	.string "pendant les soldes. Malin, non?$"

SmartShopper_Text_OutroNormal::
	.string "JOURNALISTE: Hum… {STR_VAR_1} semble\n"
	.string "aimer faire des économies!\p"
	.string "Le total des achats de {STR_VAR_1} s'est\p"
	.string "finalement élevé à… {STR_VAR_2}¥?! Une\n"
	.string "sacrée somme! Oh! Mince!\p"
	.string "Notre temps est écoulé!\n"
	.string "A tout à l'heure!$"

SmartShopper_Text_IsVIP::
	.string "VENDEUSE: {STR_VAR_1} fait partie de ma\n"
	.string "clientèle privilégiée, c'est sûr.$"

SmartShopper_Text_ClerkMax::
	.string "Interrogons le greffier\n"
	.string "pour obtenir le bas bas.\p"
	.string "Salut, comment vont vos affaires?\p"
	.string "CLERK: On fait des\n"
	.string "affaires incroyables.\p"
	.string "Récemment, un DRESSEUR nommé {STR_VAR_1}\n"
	.string "a acheté le produit {STR_VAR_2} en vrac.\p"
	.string "Le DRESSEUR a presque\n"
	.string "éliminé tout notre stock de {STR_VAR_2}S.\p"
	.string "Je n'ai jamais rêvé qu'un\n"
	.string "client n'aurait jamais besoin de\l"
	.string "autant de {STR_VAR_2}S. C'est juste inouï!\p"
	.string "INTERVIEWER: Donc ça\n"
	.string "serait comme 100 ou 200 vendus?\p"
	.string "CLERK: Oh, non, bien plus que ça!\p"
	.string "INTERVIEWER: Oh, mon Dieu! {STR_VAR_1}\n"
	.string "doit être un shopper spécial!\p"
	.string "CLERK: {STR_VAR_1} est un client\n"
	.string "VIP, sans doute à ce sujet.$"

SmartShopper_Text_OutroMax::
	.string "JOURNALISTE: Hum… C'est\n"
	.string "vraiment étonnant. Pourquoi\p"
	.string "un DRESSEUR a-t-il besoin\n"
	.string "d'en acheter autant? … …\p"
	.string "Le mystère demeure, mais\p"
	.string "nous n'avons\n"
	.string "malheureusement plus de temps.\l"
	.string "Rendez-vous à la prochaine\p"
	.string "{STR_VAR_1} est certainement une énigme...$"

gTVWorldOfMastersText00::
	.string "CULTURE POKéMON Bonjour, chers\p"
	.string "téléspectateurs. Vous avez\p"
	.string "peut-être déjà entendu parler\n"
	.string "d'un DRESSEUR appelé {STR_VAR_1}. {STR_VAR_1} est\p"
	.string "célèbre dans l'art d'attraper\n"
	.string "des POKéMON. La quête de\p"
	.string "POKéMON de {STR_VAR_1} dépend\n"
	.string "essentiellement de ses longues\p"
	.string "recherches effectuées à pied. Lors\n"
	.string "d'un jour mémorable, ce DRESSEUR a\p"
	.string "effectué {STR_VAR_2} pas. Le nombre total de\n"
	.string "POKéMON pris ce jour-là: {STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Cet exploit remarquable n'a été\n"
	.string "possible que grâce à la formidable\l"
	.string "entente entre le DRESSEUR et son {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "Le DRESSEUR a attrapé son\n"
	.string "dernier {STR_VAR_3} près de {STR_VAR_2}. Ce POKéMON\p"
	.string "a la particularité d'être un\n"
	.string "véritable détenteur de records.\p"
	.string "Nous espérons que ça donnera\n"
	.string "envie aux DRESSEURS\p"
	.string "expérimentés de faire mieux. C'est\n"
	.string "Alignez-vous la prochaine fois.$"

gTVTodaysRivalTrainerText00::
	.string "LE RIVAL DU JOUR! Bonjour,\p"
	.string "chers DRESSEURS de POKéMON!\n"
	.string "Comment allez-vous,\p"
	.string "aujourd'hui? Comme chaque jour,\n"
	.string "Nous examinerons un de nos rivaux!$"

gTVTodaysRivalTrainerText07::
	.string "Le rival du jour est\n"
	.string "{STR_VAR_1}. Où est notre rival?\p"
	.string "{STR_VAR_3}! {STR_VAR_1} a enregistré {STR_VAR_2}\n"
	.string "POKéMON dans son POKéDEX.$"

gTVTodaysRivalTrainerText08::
	.string "Le rival du jour est {STR_VAR_1}.\n"
	.string "Notre rival est dans une\p"
	.string "BASE SECRETE! {STR_VAR_1} a enregistré\n"
	.string "{STR_VAR_2} POKéMON dans son POKéDEX.$"

gTVTodaysRivalTrainerText09::
	.string "Le rival du jour est\p"
	.string "{STR_VAR_1}. {STR_VAR_1} a enregistré {STR_VAR_2}\n"
	.string "POKéMON dans son POKéDEX.$"

gTVTodaysRivalTrainerText10::
	.string "Le rival du jour est\n"
	.string "{STR_VAR_1}. Notre rival se\p"
	.string "trouve sur le ferry.\n"
	.string "{STR_VAR_1} a enregistré {STR_VAR_2}$"

	.string "POKéMON dans son POKéDEX.$"

gTVTodaysRivalTrainerText01::
	.string "Combien de BADGES a notre\n"
	.string "rival? Eh bien, il en a {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Mais notre rival\n"
	.string "n'a aucun BADGE!$"

gTVTodaysRivalTrainerText03::
	.string "Notre rival n'a aucun\n"
	.string "symbole de la ZONE DE COMBAT.$"

gTVTodaysRivalTrainerText04::
	.string "Voyons combien de\n"
	.string "symboles de la ZONE DE\p"
	.string "COMBAT notre rival a-t-il.\n"
	.string "Symboles or: {STR_VAR_1}! Symboles argent: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Notre rival a obtenu {STR_VAR_1} POINT(s)\n"
	.string "DE COMBAT à la ZONE DE COMBAT.$"

gTVTodaysRivalTrainerText06::
	.string "Alors? Feriez-vous le\n"
	.string "poids face à {STR_VAR_1}? L'aventure\p"
	.string "continue! Très chers\p"
	.string "DRESSEURS! Il faut toujours\p"
	.string "aller de l'avant et surtout\n"
	.string "aller au devant de ses rivaux!$"

TrendWatcher_Text_Intro::
	.string "CHAÎNE IN DE MYOKARA!\p"
	.string "ANIMATEUR: Quoi d'neuf chez\n"
	.string "vous? Nous vous tenons au\l"
	.string "courant des dernières modes\p"
	.string "à MYOKARA. Avec nous\n"
	.string "aujourd'hui, un vieux loup\l"
	.string "de mer. Il en sait un paquet\p"
	.string "sur MYOKARA! Vieil homme: Je\p"
	.string "suis content d'être ici.\p"
	.string "ANIMATEUR: Allons, pas de\n"
	.string "blabla, pas de chichi entre\p"
	.string "nous! Droit au but! Qu'est-ce\p"
	.string "qui est à la mode à MYOKARA,\n"
	.string "en ce moment? Vieil homme: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "ANIMATEUR: {STR_VAR_1} {STR_VAR_2}? Vieil homme:\p"
	.string "Non. {STR_VAR_1} {STR_VAR_2} n'a jamais été très à\n"
	.string "la mode. Je peux en parler,\p"
	.string "si vous le souhaitez.\p"
	.string "ANIMATEUR: Heu… Non merci! On\n"
	.string "Ce qui est en ce moment...$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Vieil homme: {STR_VAR_1} {STR_VAR_2} était ce\n"
	.string "que {STR_VAR_3} de LITTLEROOT m'a\l"
	.string "appris comme étant à la mode...$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Vieil homme: {STR_VAR_1} {STR_VAR_2} était ce\n"
	.string "que {STR_VAR_3} de LITTLEROOT m'a\l"
	.string "appris comme étant à la mode...$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Mais ça n'a pas marché.\p"
	.string "Festival {STR_VAR_1} {STR_VAR_2}! Concours {STR_VAR_1} {STR_VAR_2}!\p"
	.string "J'ai essayé d'en parler\p"
	.string "autour de moi, mais…\n"
	.string "Peut-être que c'est {STR_VAR_1}\p"
	.string "qui n'a pas plu…\n"
	.string "ANIMATEUR: C'est bien\p"
	.string "joli, tout ça… Mais\n"
	.string "d'entendre ce qu'il y a dans...$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Vieil homme: {STR_VAR_3}! Y\n"
	.string "a-t-il quelque\l"
	.string "chose au-dessus de {STR_VAR_1} {STR_VAR_2}?$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Vieil homme: {STR_VAR_3}! Y\n"
	.string "a-t-il quelque\l"
	.string "chose au-dessus de {STR_VAR_1} {STR_VAR_2}?$"

TrendWatcher_Text_Outro::
	.string "ANIMATEUR: Hum… Heu,\n"
	.string "c'était l'info du jour! {STR_VAR_1}\p"
	.string "{STR_VAR_2}… Eh bien… Ce n'est pas à\n"
	.string "la mode à MYOKARA! C'est\p"
	.string "fini pour aujourd'hui. À\p"
	.string "bientôt! Vieil homme: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "CHASSE AU TRESOR A HOENN!\p"
	.string "Salut, vous… De nouveaux objets\n"
	.string "secrets ont-il été trouvés?\p"
	.string "Nous sommes avides de\n"
	.string "témoignages sur les trésors qui\p"
	.string "nous entourent! Nous avons reçu\n"
	.string "Il est dit: {STR_VAR_1} découvert!$"

gTVHoennTreasureInvestigatorsText01::
	.string "Oh! Je ferais bien de lire\n"
	.string "cette lettre jusqu'au\p"
	.string "bout! Chers CHASSEURS,\n"
	.string "j'espère que vous vous\p"
	.string "portez bien. Récemment,\n"
	.string "j'ai vu {STR_VAR_2} dans les environs\p"
	.string "de {STR_VAR_3}. Ce DRESSEUR a trouvé\n"
	.string "l'objet {STR_VAR_1}. Comme je l'envie!\p"
	.string "Eh bien, nous nous\p"
	.string "réjouissons pour {STR_VAR_2}! Chers\n"
	.string "téléspectateurs, à vos\p"
	.string "CHERCH'OBJETS! Et pensez à nous\n"
	.string "si vous tombez sur la perle rare!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Oh! Je ferais bien de lire\n"
	.string "cette lettre jusqu'au bout!\p"
	.string "Chers CHASSEURS, j'espère\n"
	.string "que vous vous portez bien.\p"
	.string "Récemment, j'ai vu {STR_VAR_2} sur un\p"
	.string "ferry. Ce DRESSEUR a trouvé\n"
	.string "l'objet {STR_VAR_1}. Comme je l'envie!\p"
	.string "Eh bien, nous nous\p"
	.string "réjouissons pour {STR_VAR_2}! Chers\n"
	.string "téléspectateurs, à vos\p"
	.string "CHERCH'OBJETS! Et pensez à nous\n"
	.string "si vous tombez sur la perle rare!$"

gTVFindThatGamerText00::
	.string "LE JOUEUR DU JOUR! Bien\p"
	.string "le bonjour, amis joueurs!\n"
	.string "Tout se passe bien avec\p"
	.string "la {STR_VAR_2}? Comme d'habitude,\n"
	.string "nous vous présentons un\l"
	.string "DRESSEUR qui est venu\p"
	.string "tenter sa chance au CASINO!\n"
	.string "Notre joueur du jour est… {STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} a joué le match {STR_VAR_2} et a\n"
	.string "gagné un rare {STR_VAR_3} COINS.\p"
	.string "Quand {STR_VAR_1} vient, nous devons nous\n"
	.string "assurer d'avoir assez de COINS.\p"
	.string "C'est ce que les commis de GAME\n"
	.string "Mutter quand le joueur est en jeu!\p"
	.string "Si vous rencontrez {STR_VAR_1}\n"
	.string "au CASINO devant une\l"
	.string "{STR_VAR_2}, ne l'imitez pas!\p"
	.string "Nous étions en direct du CASINO.\n"
	.string "La tension est à son comble, ici!\p"
	.string "Ce sera tout pour aujourd'hui!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} a joué le match {STR_VAR_2}\n"
	.string "et a perdu {STR_VAR_3} COINS.\p"
	.string "Quand {STR_VAR_1} vient, nos ventes\n"
	.string "de COIN semblent augmenter.\p"
	.string "C'est ce que disent les commis de\n"
	.string "Dis quand notre joueur est en jeu!$"

gTVFindThatGamerText03::
	.string "Si vous rencontrez {STR_VAR_1} au\n"
	.string "CASINO devant une {STR_VAR_2}, ne\l"
	.string "l'imitez pas! Nous étions en\p"
	.string "direct du CASINO. La\n"
	.string "tension est à son comble, ici!\p"
	.string "Ce sera tout pour aujourd'hui!$"

gTVBreakingNewsText00::
	.string "CHAÎNE DES SCOOPS!$"

gTVBreakingNewsText01::
	.string "Un {STR_VAR_2} rare attrapé\n"
	.string "par {STR_VAR_1}! Nous sommes\p"
	.string "en direct à\n"
	.string "proximité de {STR_VAR_3}! {STR_VAR_1} a\p"
	.string "réussi à capturer\n"
	.string "un {STR_VAR_2} rare ici même!$"

gTVBreakingNewsText02::
	.string "Quand {STR_VAR_1} a rencontré le\n"
	.string "{STR_VAR_2} rare, le POKéMON {STR_VAR_3} a\l"
	.string "été envoyé au combat.$"

gTVBreakingNewsText03::
	.string "Le DRESSEUR a naturellement eu\n"
	.string "recours aux POKé BALLS. Il en\p"
	.string "a lancé {STR_VAR_1}. C'est avec une {STR_VAR_2} que\n"
	.string "le POKéMON rare a été attrapé.$"

gTVBreakingNewsText04::
	.string "Dans cet instant, {STR_VAR_2}\n"
	.string "résonna avec les\l"
	.string "Une joie triomphante.\p"
	.string "Je dois dire que je suis un peu\n"
	.string "{STR_VAR_1} J'aimerais rugir aussi.\p"
	.string "...C'est la fin du flux en\n"
	.string "direct de la scène heureuse!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} a failli attraper\n"
	.string "un {STR_VAR_1}{STR_VAR_2} rare! Nous\p"
	.string "sommes en direct à\n"
	.string "proximité de {STR_VAR_3}!\p"
	.string "C'est ici que {STR_VAR_1} a\n"
	.string "failli attraper un {STR_VAR_2} rare!$"

gTVBreakingNewsText06::
	.string "Quand {STR_VAR_1} a rencontré le\n"
	.string "{STR_VAR_2} rare, le POKéMON {STR_VAR_3} a\l"
	.string "été envoyé au combat.$"

gTVBreakingNewsText07::
	.string "Le DRESSEUR a fait le {STR_VAR_2}\n"
	.string "utiliser le mouvement {STR_VAR_1}.\p"
	.string "Sans signification, le DRESSEUR a\n"
	.string "fait évanouir le rare POKéMON...$"

gTVBreakingNewsText12::
	.string "{STR_VAR_1} a paniqué à la vue\n"
	.string "du {STR_VAR_2} rare. Le\p"
	.string "DRESSEUR a ordonné\n"
	.string "au {STR_VAR_3} d'attaquer. Le\p"
	.string "POKéMON rare s'est\n"
	.string "malheureusement évanoui…$"

gTVBreakingNewsText08::
	.string "Dans cet instant, {STR_VAR_2} a\n"
	.string "fait écho aux cris\l"
	.string "de frustration de {STR_VAR_1}...$"

gTVBreakingNewsText09::
	.string "Cependant, {STR_VAR_1} semblait\n"
	.string "manquer de POKé BALLS.\p"
	.string "Le DRESSEUR a dû rompre\n"
	.string "la bataille avec la rare {STR_VAR_2}.\p"
	.string "Dans cet instant, {STR_VAR_3} a\n"
	.string "fait écho aux cris\l"
	.string "de frustration de {STR_VAR_1}...$"

gTVBreakingNewsText10::
	.string "Cependant, le {STR_VAR_2} s'est\n"
	.string "enfui sans avertissement.\p"
	.string "Dans cet instant, {STR_VAR_3} a\n"
	.string "fait écho aux cris\l"
	.string "de frustration de {STR_VAR_1}...$"

gTVBreakingNewsText11::
	.string "Je dois dire que c'est\n"
	.string "triste pour {STR_VAR_1}. J'ai envie\p"
	.string "de hurler aussi! Voilà, je\n"
	.string "vous dis à très bientôt!$"

gTVSecretBaseVisitText00::
	.string "Salut les amis! C'est le\n"
	.string "moment d'effectuer une\l"
	.string "petite VISITE DE BASE\p"
	.string "SECRETE. Aujourd'hui,\n"
	.string "nous allons découvrir la\p"
	.string "BASE SECRETE de {STR_VAR_1}. A quoi\n"
	.string "ressemble la BASE SECRETE\p"
	.string "de {STR_VAR_1}? Nous allons voir ça\n"
	.string "tout de suite! … … … … … …$"

gTVSecretBaseVisitText01::
	.string "Oh! Remarquable!\n"
	.string "Merveilleux!\p"
	.string "{STR_VAR_2}… Ceci est\n"
	.string "pour le\l"
	.string "moins surprenant!$"

gTVSecretBaseVisitText02::
	.string "Oh!\n"
	.string "Il n'y a pas un\p"
	.string "seul élément de\n"
	.string "décoration! C'est\p"
	.string "un très bon\n"
	.string "exemple de\p"
	.string "minimalisme! C'est\n"
	.string "très simple, mais ça\p"
	.string "en jette! Chapeau, {STR_VAR_1}.\n"
	.string "Je te reconnais bien là!$"

gTVSecretBaseVisitText03::
	.string "Oh! Je vois! C'est\n"
	.string "très clair! Les\p"
	.string "{STR_VAR_2}… A cet endroit…\n"
	.string "Le message est fort!$"

gTVSecretBaseVisitText04::
	.string "Oh! Je vois!\n"
	.string "C'est très clair!\p"
	.string "décorations ne se\n"
	.string "bousculent pas! Le\p"
	.string "message n'en est que plus fort!$"

gTVSecretBaseVisitText05::
	.string "Waouh! {STR_VAR_2}, {STR_VAR_3}… Ça se\p"
	.string "marie à\n"
	.string "merveille! On ne\p"
	.string "pouvait pas rêver\n"
	.string "de meilleur choix!$"

gTVSecretBaseVisitText06::
	.string "Waouh! {STR_VAR_2}… Cet élément\p"
	.string "de décoration est\n"
	.string "très bien placé! Sa\p"
	.string "présence remplit\n"
	.string "toute la BASE SECRETE!$"

gTVSecretBaseVisitText07::
	.string "Waouh! Il n'y a\p"
	.string "absolument rien ici. Cet\p"
	.string "espace vide donne un\n"
	.string "certain cachet à la BASE SECRETE.$"

gTVSecretBaseVisitText08::
	.string "Oh! Voici {STR_VAR_1}!\n"
	.string "Testons un\l"
	.string "peu ce\p"
	.string "DRESSEUR! … … …\n"
	.string "… … … … … … … … …$"

gTVSecretBaseVisitText09::
	.string "Oh… {STR_VAR_1} a gagné, je\n"
	.string "m'incline. Les\p"
	.string "POKéMON de ce\n"
	.string "DRESSEUR ont aussi\p"
	.string "mérité le titre de\n"
	.string "MAÎTRE. Ils reflètent\p"
	.string "la résistance de {STR_VAR_1} en\n"
	.string "tant que DRESSEUR. Le {STR_VAR_2}\p"
	.string "connaissait même {STR_VAR_3}… Ça\n"
	.string "nous en dit long sur\p"
	.string "{STR_VAR_1}. Quelle belle leçon!$"

gTVSecretBaseVisitText10::
	.string "Aïe… {STR_VAR_1} a gagné, je\n"
	.string "m'incline. Les\p"
	.string "POKéMON de ce\n"
	.string "DRESSEUR sont\p"
	.string "incroyablement\n"
	.string "forts! Ils reflètent\p"
	.string "la ténacité de {STR_VAR_1} en\n"
	.string "tant que DRESSEUR. Le {STR_VAR_2}\p"
	.string "connaissait même {STR_VAR_3}… Ça\n"
	.string "nous en dit long sur\p"
	.string "{STR_VAR_1}. Quelle belle leçon!$"

gTVSecretBaseVisitText11::
	.string "Waouh! {STR_VAR_1} a gagné,\n"
	.string "je m'incline. Les\p"
	.string "POKéMON de ce\n"
	.string "DRESSEUR sont très\p"
	.string "équilibrés. Ils\n"
	.string "reflètent le\p"
	.string "sérieux de {STR_VAR_1} en tant\n"
	.string "que DRESSEUR. Le {STR_VAR_2}\p"
	.string "connaissait même {STR_VAR_3}… Ça\n"
	.string "nous en dit long sur\p"
	.string "{STR_VAR_1}. Quelle belle leçon!$"

gTVSecretBaseVisitText12::
	.string "Bien, bien! {STR_VAR_1} a\n"
	.string "gagné, je\p"
	.string "m'incline. Les\n"
	.string "POKéMON de ce\p"
	.string "DRESSEUR sont très\n"
	.string "prometteurs. Ils\p"
	.string "reflètent les espoirs\n"
	.string "et les rêves de {STR_VAR_1}. Le {STR_VAR_2}\p"
	.string "connaissait même {STR_VAR_3}… Ça\n"
	.string "nous en dit long sur\p"
	.string "{STR_VAR_1}. Quelle belle leçon!$"

gTVSecretBaseVisitText13::
	.string "Cette BASE SECRETE était\n"
	.string "vraiment superbe, les\p"
	.string "amis! Si vous avez\n"
	.string "l'occasion, visitez la BASE\p"
	.string "SECRETE de {STR_VAR_1}. Bon, à la prochaine!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Quel suspense!\n"
	.string "Quelle tension! Voici\p"
	.string "le FLASH SPECIAL de\n"
	.string "la LOTERIE POKéMON!\p"
	.string "Bonjour à tous, en\n"
	.string "direct de la LOTERIE\l"
	.string "POKéMON, au\l"
	.string "rez-de-chaussée du\p"
	.string "CENTRE COMMERCIAL\n"
	.string "NENUCRIQUE! Comme\p"
	.string "d'habitude, nous avons\n"
	.string "un heureux DRESSEUR!\p"
	.string "Ce DRESSEUR s'appelle…\n"
	.string "{STR_VAR_1}! {STR_VAR_1} a gagné le {STR_VAR_2}, {STR_VAR_3}!\p"
	.string "Félicitations, {STR_VAR_1}! Chers\n"
	.string "téléspectateurs, à\p"
	.string "vous de jouer\n"
	.string "maintenant! Nous vous\p"
	.string "attendons avec\n"
	.string "impatience au CENTRE\p"
	.string "COMMERCIAL NENUCRIQUE! Nous\n"
	.string "étions en direct du CENTRE\l"
	.string "COMMERCIAL NENUCRIQUE pour\l"
	.string "vous, résidents de HOENN!$"

gTVThePokemonBattleSeminarText00::
	.string "LE SÉMINAIRE POKÉMON BATTLE!\p"
	.string "Nous examinons les batailles pour\n"
	.string "voir les leçons des autres.\p"
	.string "L'étude de cas d'aujourd'hui\n"
	.string "porte sur la bataille de {STR_VAR_1}.\p"
	.string "{STR_VAR_1} {STR_VAR_2} luttait\n"
	.string "contre une {STR_VAR_3}...$"

gTVThePokemonBattleSeminarText01::
	.string "Il a utilisé {STR_VAR_3}\n"
	.string "contre le {STR_VAR_2}…\p"
	.string "Hum… {STR_VAR_1}! Ça ne\n"
	.string "va pas du tout!$"

gTVThePokemonBattleSeminarText02::
	.string "Notez que le {STR_VAR_1} de ce\n"
	.string "DRESSEUR connaissait aussi$"

gTVThePokemonBattleSeminarText03::
	.string "{STR_VAR_1}, {STR_VAR_2}\n"
	.string "et {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "{STR_VAR_1}\n"
	.string "et {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Quelle capacité ce\n"
	.string "DRESSEUR aurait-il dû\p"
	.string "utiliser? … … … … … … {STR_VAR_1},\n"
	.string "voyons! {STR_VAR_1} aurait été\p"
	.string "bien plus efficace que\n"
	.string "{STR_VAR_2}! Chers\p"
	.string "téléspectateurs, j'espère\n"
	.string "que l'erreur de ce DRESSEUR\p"
	.string "vous servira! A la prochaine!$"

gTVTrainerFanClubText00::
	.string "Bon, tous ensemble! LE\n"
	.string "FAN CLUB DES DRESSEURS!\p"
	.string "ANIMATEUR: Alors, ça\n"
	.string "groove chez vous?\l"
	.string "Aujourd'hui, nous avons\p"
	.string "réuni tous les DRESSEURS\p"
	.string "fans de {STR_VAR_1}! FANS:\p"
	.string "Ouais!!!!!!! FANS: {STR_VAR_1}!\n"
	.string "ANIMATEUR: Tous ensemble!\p"
	.string "Est-ce que vous aimez {STR_VAR_1}?\p"
	.string "FANS: On aime {STR_VAR_1}! ANIMATEUR:\n"
	.string "Qu'est-ce qui vous plaît chez {STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "FANS: Ce DRESSEUR a un\n"
	.string "super lancer de POKé BALLS!$"

gTVTrainerFanClubText02::
	.string "FANS: On adore sa façon de courir!$"

gTVTrainerFanClubText03::
	.string "FANS: Ce DRESSEUR sait se montrer\n"
	.string "fort quand les choses se corsent!$"

gTVTrainerFanClubText04::
	.string "FANS: Ce DRESSEUR en\n"
	.string "connaît un rayon sur les POKéMON!$"

gTVTrainerFanClubText05::
	.string "FANS: Ce DRESSEUR est d'une\n"
	.string "Tous les POKéMON!$"

gTVTrainerFanClubText06::
	.string "FANS: Ce DRESSEUR a une\n"
	.string "super technique à VELO!$"

gTVTrainerFanClubText07::
	.string "FANS: Sa façon\n"
	.string "d'acheter des objets!$"

gTVTrainerFanClubText08::
	.string "FANS: Les surnoms que ce\n"
	.string "DRESSEUR donne aux POKéMON!$"

gTVTrainerFanClubText09::
	.string "FANS: Le goût avec lequel ce\n"
	.string "DRESSEUR a décoré sa BASE SECRETE!$"

gTVTrainerFanClubText10::
	.string "FANS: Ce DRESSEUR utilise\n"
	.string "les CT avec un tel aplomb!$"

gTVTrainerFanClubText11::
	.string "ANIMATEUR: Comme\n"
	.string "vous avez vu, {STR_VAR_1}\p"
	.string "en jette! Les\n"
	.string "FANS de {STR_VAR_1} ont un\p"
	.string "slogan!\n"
	.string "ANIMATEUR: Quand\p"
	.string "je dis {STR_VAR_1}, vous\p"
	.string "dites… FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}! FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "ANIMATEUR:\n"
	.string "Exactement! Si\p"
	.string "quelqu'un dit {STR_VAR_1}…\n"
	.string "Il faut répondre {STR_VAR_2}\p"
	.string "{STR_VAR_3}! Je dois avouer\n"
	.string "que ça sonne\l"
	.string "bien! Je\p"
	.string "comprends les\n"
	.string "FANS de {STR_VAR_1}! Toi, en\p"
	.string "face de ta télé,\n"
	.string "avec nous! Tous\p"
	.string "ensemble!\p"
	.string "ANIMATEUR: Quand je\p"
	.string "dis {STR_VAR_1}, vous dites…\p"
	.string "FANS: {STR_VAR_2}! FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}! FANS: {STR_VAR_3}!\n"
	.string "ANIMATEUR: Je\l"
	.string "remercie tous les\p"
	.string "FANS de {STR_VAR_1}! Quelle\n"
	.string "ambiance ici!\p"
	.string "ANIMATEUR: Quand je dis {STR_VAR_1},\p"
	.string "vous dites… FANS: {STR_VAR_2}! FANS: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "Porchémon\n"
	.string "à Ribbons!\p"
	.string "Bonjour, mes chers spectateurs!\p"
	.string "Je sais que tu seras d'accord,\n"
	.string "un POKéMON à RUBANS est divin!\p"
	.string "Aujourd'hui, je veux partager\n"
	.string "avec vous un joli POKéMON que j'ai\l"
	.string "repéré en déambulation en ville.\p"
	.string "La jolie POKéMON\n"
	.string "d'aujourd'hui est celle de {STR_VAR_1} {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "Le nombre de RUBANS\n"
	.string "que {STR_VAR_2} portait était de\p"
	.string "{STR_VAR_3}. Ça montre à quel\n"
	.string "point {STR_VAR_1} adore ses POKéMON.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2}{STR_VAR_3} porte le nombre\n"
	.string "incroyable de {STR_VAR_1} RUBANS! Ça\p"
	.string "nous en dit long sur\n"
	.string "l'engagement envers le POKéMON!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} porte le nombre\n"
	.string "incroyable de {STR_VAR_3} RUBANS! Ça\p"
	.string "nous montre bien que {STR_VAR_1} se\n"
	.string "consacre totalement à ses POKéMON!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Regardons de plus\n"
	.string "près les RUBANS de {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "Le RUBAN CHAMPION est\n"
	.string "particulièrement\p"
	.string "seyant. {STR_VAR_2} l'a reçu à son\n"
	.string "entrée au PANTHEON DES\p"
	.string "DRESSEURS. Il témoigne\n"
	.string "du courage de {STR_VAR_2}. {STR_VAR_2} avec\p"
	.string "le RUBAN CHAMPION! Il\n"
	.string "lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "Le RUBAN SANG-FROID est\n"
	.string "particulièrement seyant.\p"
	.string "{STR_VAR_2} l'a obtenu en\n"
	.string "remportant un CONCOURS DE\p"
	.string "SANG-FROID. Il témoigne\n"
	.string "du sang-froid de {STR_VAR_2}. {STR_VAR_2} avec\p"
	.string "le RUBAN SANG-FROID! Il\n"
	.string "lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "Le RUBAN BEAUTE est\n"
	.string "particulièrement\p"
	.string "seyant. {STR_VAR_2} l'a obtenu en\n"
	.string "remportant un CONCOURS\p"
	.string "DE BEAUTE. Il rend\n"
	.string "hommage à la beauté de {STR_VAR_2}. {STR_VAR_2}\p"
	.string "avec le RUBAN BEAUTE! Il\n"
	.string "lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "Le RUBAN GRACE est\n"
	.string "particulièrement\p"
	.string "seyant. {STR_VAR_2} l'a obtenu en\n"
	.string "remportant un CONCOURS\p"
	.string "DE GRACE. Il témoigne\n"
	.string "de la grâce de {STR_VAR_2}. {STR_VAR_2} avec\p"
	.string "le RUBAN GRACE! Il lui\n"
	.string "va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "Le RUBAN INTELLIGENCE est\n"
	.string "particulièrement seyant. {STR_VAR_2}\p"
	.string "l'a obtenu en remportant\n"
	.string "un CONCOURS\p"
	.string "D'INTELLIGENCE. Il témoigne\n"
	.string "de l'intelligence de {STR_VAR_2}. {STR_VAR_2} avec\p"
	.string "le RUBAN INTELLI- GENCE! Il\n"
	.string "lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "Le RUBAN ROBUSTESSE est\n"
	.string "particulièrement seyant.\p"
	.string "{STR_VAR_2} l'a obtenu en\n"
	.string "remportant un CONCOURS DE\p"
	.string "ROBUSTESSE. Il témoigne de\n"
	.string "la robustesse de {STR_VAR_2}. {STR_VAR_2} avec\p"
	.string "le RUBAN ROBUSTESSE! Il\n"
	.string "lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "Le RUBAN GAGNANT est\n"
	.string "particulièrement\p"
	.string "seyant. {STR_VAR_2} l'a obtenu pour\n"
	.string "ses exploits à la TOUR\p"
	.string "DE COMBAT. Il témoigne\n"
	.string "de la puissance de {STR_VAR_2}. {STR_VAR_2}\p"
	.string "avec le RUBAN GAGNANT! Il\n"
	.string "lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "Le RUBAN VICTOIRE est\n"
	.string "particulièrement seyant. {STR_VAR_2}\p"
	.string "l'a obtenu pour ses\n"
	.string "exploits à la TOUR DE\p"
	.string "COMBAT. Il témoigne de la\n"
	.string "puissance incroyable de {STR_VAR_2}. {STR_VAR_2}\p"
	.string "avec le RUBAN VICTOIRE! Il\n"
	.string "lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "Le RUBAN ARTISTE est\n"
	.string "particulièrement\p"
	.string "seyant. {STR_VAR_2} l'a obtenu en\n"
	.string "servant de modèle à un\p"
	.string "artiste. Il témoigne\n"
	.string "du charme de {STR_VAR_2}. {STR_VAR_2} avec le\p"
	.string "RUBAN ARTISTE! Il lui\n"
	.string "va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Le RUBAN EFFORT est\n"
	.string "particulièrement seyant.\p"
	.string "{STR_VAR_2} l'a obtenu pour avoir\n"
	.string "été un travailleur\p"
	.string "dévoué. Il témoigne de la\n"
	.string "détermination de {STR_VAR_2}. {STR_VAR_2} avec\p"
	.string "le RUBAN travailleur! Il\n"
	.string "lui va vraiment très bien!$"

TVSpotTheCuties_Text_Outro::
	.string "Oh… Les RUBANS et les\p"
	.string "POKéMON… Ils vont si\n"
	.string "bien ensemble! Je vais\p"
	.string "défaillir, je préfère\n"
	.string "vous dire À bientôt!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Bonjour à tous! C'est l'heure\n"
	.string "du BULLETIN POKéMON. Nous avons\p"
	.string "des informations étonnantes en\n"
	.string "provenance de la ZONE DE COMBAT.$"

gTVPokemonNewsBattleFrontierText01::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires\l"
	.string "consécutives au défi de la\l"
	.string "SALLE DE COMBAT SOLO de la\p"
	.string "TOUR DE COMBAT. Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires\l"
	.string "consécutives au défi de la\l"
	.string "SALLE DE COMBAT DUO de la\p"
	.string "TOUR DE COMBAT. Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires\l"
	.string "consécutives au défi de la\l"
	.string "SALLE DE COMBAT MULTI de la\p"
	.string "TOUR DE COMBAT. Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires\l"
	.string "consécutives au défi de la\l"
	.string "SALLE DE COMBAT MULTI LINK de\p"
	.string "la TOUR DE COMBAT. Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "Le DRESSEUR {STR_VAR_1} a établi\n"
	.string "un record au TOURNOI\l"
	.string "DE COMBAT SOLO du\l"
	.string "DOME DE COMBAT en\p"
	.string "gagnant {STR_VAR_2} fois. Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "Le DRESSEUR {STR_VAR_1} a établi\n"
	.string "un record au TOURNOI\l"
	.string "DE COMBAT DUO du DOME\l"
	.string "DE COMBAT en gagnant\p"
	.string "{STR_VAR_2} fois. Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires\l"
	.string "consécutives au défi du\l"
	.string "COMBAT ÉCHANGE SOLO de\p"
	.string "l'USINE DE COMBAT. Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires\l"
	.string "consécutives au défi du\l"
	.string "COMBAT ÉCHANGE DUO de\p"
	.string "l'USINE DE COMBAT. Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\n"
	.string "record! Il a terminé {STR_VAR_2}\l"
	.string "salles lors du défi du\l"
	.string "COMBAT HASARD du REPTILE\p"
	.string "DE COMBAT. Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "Le DRESSEUR {STR_VAR_1} a établi\n"
	.string "un record de {STR_VAR_2}\l"
	.string "victoires consécutives\l"
	.string "au TOURNOI K.O. du DOJO\p"
	.string "DE COMBAT. Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires\l"
	.string "consécutives au défi du\l"
	.string "HALL DE COMBAT SOLO du\p"
	.string "PALACE DE COMBAT. Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires\l"
	.string "consécutives au défi du\l"
	.string "HALL DE COMBAT DUO du\p"
	.string "PALACE DE COMBAT. Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\n"
	.string "record! Il a terminé {STR_VAR_2}\l"
	.string "niveaux lors du défi du\l"
	.string "COMBAT QUETE de la\p"
	.string "PYRAMIDE DE COMBAT. Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "Ainsi qu'aux trois\n"
	.string "POKéMON: {STR_VAR_1}, {STR_VAR_2}, et {STR_VAR_3}!\p"
	.string "Félicitations pour cet\n"
	.string "exploit époustouflant!!$"

gTVPokemonNewsBattleFrontierText15::
	.string "Ainsi qu'aux deux\n"
	.string "POKéMON: {STR_VAR_1}, et {STR_VAR_2}!\p"
	.string "Félicitations pour cet\n"
	.string "exploit époustouflant!!$"

gTVPokemonNewsBattleFrontierText16::
	.string "Et aux\p"
	.string "quatre\p"
	.string "POKéMON: {STR_VAR_1}! {STR_VAR_2}! {STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "Et {STR_VAR_1}!\p"
	.string "Félicitations pour cet\n"
	.string "exploit époustouflant!!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Nous attendons avec impatience de\n"
	.string "connaître les prochains exploits\l"
	.string "de {STR_VAR_1} et de ses fidèles POKéMON!\p"
	.string "C'est la nouvelle de POKéMON NEWS!$"

gTVWhatsNo1InHoennTodayText00::
	.string "QUOI DE NEUF DANS HOENN?\n"
	.string "C'est reparti pour une\p"
	.string "émission de folie! Salut les\n"
	.string "amis, ça roule pour vous?\p"
	.string "Penchons-nous sur le\n"
	.string "DRESSEUR qui a fait parler de\p"
	.string "lui aujourd'hui! Le DRESSEUR\n"
	.string "nº 1 du jour n'est autre que {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "Dans la même journée, {STR_VAR_1} a\n"
	.string "joué {STR_VAR_2} fois aux MACHINES A\p"
	.string "SOUS du CASINO. Des témoins\n"
	.string "auraient entendu {STR_VAR_1} murmurer:\l"
	.string "Pour moi, les rouleaux ne\l"
	.string "N'est-ce pas intéressant?$"

gTVWhatsNo1InHoennTodayText02::
	.string "Dans la même journée, {STR_VAR_1} a\n"
	.string "joué {STR_VAR_2} fois à la ROULETTE\l"
	.string "du CASINO. En plein jeu,\p"
	.string "on a entendu {STR_VAR_1} crier: Que\n"
	.string "la bille décide! Le\p"
	.string "visage du DRESSEUR affichait\n"
	.string "une concentration extrême.$"

gTVWhatsNo1InHoennTodayText03::
	.string "Dans la même journée, {STR_VAR_1} a battu\n"
	.string "des POKéMON sauvages {STR_VAR_2} fois! Les\p"
	.string "POKéMON de {STR_VAR_1} semblent être\n"
	.string "devenus beaucoup plus forts. Ils\p"
	.string "aiment se battre, peu importe\n"
	.string "Quoi qu'il en soit!$"

gTVWhatsNo1InHoennTodayText04::
	.string "Dans la même journée,\n"
	.string "{STR_VAR_1} a utilisé le MIXEUR {STR_VAR_2}\p"
	.string "fois! A la fin, {STR_VAR_1}\n"
	.string "avait la tête qui\p"
	.string "tournait. Le DRESSEUR\n"
	.string "titubait comme un SPINDA!$"

gTVWhatsNo1InHoennTodayText05::
	.string "Dans la même journée, {STR_VAR_1} a\n"
	.string "planté {STR_VAR_2} BAIES! Du coup,\p"
	.string "les vêtements de {STR_VAR_1}\n"
	.string "étaient couverts de\p"
	.string "terre. Là où ce DRESSEUR a\n"
	.string "semé, de nombreuses fleurs\p"
	.string "ont fleuri. On dit que les\n"
	.string "fleurs apaisent les gens.$"

gTVWhatsNo1InHoennTodayText06::
	.string "Dans la même journée, {STR_VAR_1}\n"
	.string "a cueilli {STR_VAR_2} BAIES! Le\p"
	.string "SAC de {STR_VAR_1} était tellement\n"
	.string "plein que ce DRESSEUR\l"
	.string "avait du mal à marcher!$"

gTVWhatsNo1InHoennTodayText07::
	.string "Dans la même journée, {STR_VAR_1} a\n"
	.string "obtenu {STR_VAR_2} POINTS DE COMBAT! {STR_VAR_1} a\p"
	.string "eu du mal à décider contre\n"
	.string "quoi échanger ses POINTS DE\l"
	.string "COMBAT. Il a longuement\l"
	.string "hésité entre un objet sympa et\p"
	.string "une décoration chic. Trop de\n"
	.string "choix s'offraient à ce DRESSEUR.$"

gTVWhatsNo1InHoennTodayText08::
	.string "N'est-ce pas\p"
	.string "incroyable? {STR_VAR_1}! Le\n"
	.string "DRESSEUR nº 1!\p"
	.string "Prenez exemple sur {STR_VAR_1}!\n"
	.string "Devenez le nº 1 du jour!$"

TVSecretBaseSecrets_Text_Intro::
	.string "SECRETS DE BASES SECRETES!\p"
	.string "Si les murs pouvaient\n"
	.string "parler, que nous diraient\p"
	.string "ceux des BASES SECRETES?\n"
	.string "Aujourd'hui, nous allons\p"
	.string "observer la BASE SECRETE de {STR_VAR_1}.\n"
	.string "Oh? On dirait que {STR_VAR_2} vient\p"
	.string "d'arriver. Observons\p"
	.string "Que fera {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Que va faire {STR_VAR_2} maintenant?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "Et maintenant, que va faire {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Finalement, {STR_VAR_2} a fait {STR_VAR_3}\n"
	.string "pas dans la BASE\l"
	.string "SECRETE de {STR_VAR_1} avant de partir.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hum… La BASE\p"
	.string "SECRETE de {STR_VAR_1} ne\n"
	.string "semble pas intéresser {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} a l'air de beaucoup\n"
	.string "aimer la BASE SECRETE de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} semble se trouver\n"
	.string "très à l'aise dans\l"
	.string "la BASE SECRETE de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_Outro::
	.string "J'espère que nous vous aurons\n"
	.string "donné envie d'aller faire un tour\p"
	.string "dans la BASE SECRETE de {STR_VAR_1}! A\n"
	.string "SECRET BASE! Merci d'être venus!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "Notre visiteur est\p"
	.string "immobile! Une vraie\p"
	.string "statue! La BASE SECRETE de\n"
	.string "{STR_VAR_1} serait-elle soporifique?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "Notre visiteur est\p"
	.string "immobile! Une vraie statue!\p"
	.string "Serait-ce un accès de fatigue?\n"
	.string "Ou le signe d'un ennui profond?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "Notre visiteur s'assoit\n"
	.string "sur une chaise! Cette\p"
	.string "BASE SECRETE a l'air\p"
	.string "confortable! Cette chaise\n"
	.string "semble lui plaire énormément!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "Notre visiteur s'en prend à\p"
	.string "un ballon! Oh, non! Le\n"
	.string "ballon a éclaté, chers\p"
	.string "téléspectateurs! Le bruit\n"
	.string "le bruit soudain!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "Notre visiteur est dans\p"
	.string "une TENTE! Notre visiteur\p"
	.string "se promène! Notre visiteur\p"
	.string "gambade! La taille de\n"
	.string "cette TENTE a dû le surprendre!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "Notre visiteur observe\n"
	.string "observe une plante!\p"
	.string "Notre visiteur semble\n"
	.string "avoir un goût très sûr.$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "Notre visiteur\n"
	.string "un BOUCLIER OR!\p"
	.string "L'émerveillement se lit dans\n"
	.string "les yeux de notre visiteur!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "Notre visiteur observe un\n"
	.string "BOUCLIER ARGENT! Notre\p"
	.string "visiteur en prend plein les yeux!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "Notre visiteur\n"
	.string "observe un ORNEMENT\p"
	.string "VERRE! Oh, non!\p"
	.string "Notre visiteur le\p"
	.string "touche! Il va être\n"
	.string "couvert de traces de doigts…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "Notre visiteur regarde la\p"
	.string "télévision! Cela le captive!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "Notre visiteur a vu une BOULE\p"
	.string "DE BOUE! Cela semble lui plaire!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "...Oh?\p"
	.string "Le visiteur est en train de\n"
	.string "BAG et rôder dedans!\p"
	.string "Le visiteur en\n"
	.string "a sorti un {STR_VAR_2}!\p"
	.string "Regardez le sourire du\n"
	.string "visiteur tout en tenant le {STR_VAR_2}!\p"
	.string "C'est comme une pub à la télé!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "Le visiteur prend un coussin et...$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "le frappe?!? Notre visiteur semble\p"
	.string "Le visiteur est-il stressé?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "le sert bien fort dans ses\p"
	.string "bras! Notre visiteur a\n"
	.string "visiblement besoin d'affection!$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "Notre visiteur est\n"
	.string "en pleine discussion\p"
	.string "avec {STR_VAR_1}! On dirait\n"
	.string "qu'un combat se\p"
	.string "prépare! Et… C'est\p"
	.string "notre visiteur qui\n"
	.string "remporte le combat!\p"
	.string "Notre visiteur entame\n"
	.string "une danse de la victoire!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "Notre visiteur est en\n"
	.string "pleine discussion avec\p"
	.string "{STR_VAR_1}! On dirait qu'un\n"
	.string "combat se prépare! Et…\p"
	.string "C'est {STR_VAR_1} qui l'emporte!\p"
	.string "Notre pauvre visiteur a\n"
	.string "perdu! Notre visiteur a\p"
	.string "l'air de s'en vouloir!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "Notre visiteur est\n"
	.string "en pleine\p"
	.string "discussion avec {STR_VAR_1}! On\n"
	.string "dirait qu'un combat\p"
	.string "se prépare! Et… Non,\p"
	.string "notre visiteur\p"
	.string "refuse de se battre!\p"
	.string "Il n'y aura pas de\n"
	.string "combat! {STR_VAR_1} ne lui a pas plu?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "Notre visiteur a les yeux\n"
	.string "rivés sur un poster! Ce\p"
	.string "poster est-il au goût de\n"
	.string "notre visiteur? Mais… Le\p"
	.string "regard de notre visiteur\n"
	.string "est pour le moins troublant.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "Notre visiteur a marché sur un\p"
	.string "TAPIS NOTE! Tiens… Notre\n"
	.string "visiteur a joué un air entraînant!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "Notre visiteur est\n"
	.string "en pleine discussion\p"
	.string "avec {STR_VAR_1}! On dirait\n"
	.string "qu'un combat se\p"
	.string "prépare! Et…\p"
	.string "Egalité! Un combat\n"
	.string "pour rien. On peut lire\p"
	.string "la déception sur le\n"
	.string "visage des deux DRESSEURS!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "Notre visiteur a marché\n"
	.string "sur un TAPIS TOURNANT!\p"
	.string "On dirait que sa tête\p"
	.string "tourne! Notre visiteur\n"
	.string "ne marche plus très droit!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "Notre visiteur\n"
	.string "s'approche d'une\p"
	.string "DECO DE SABLE!\p"
	.string "Oh! L'objet\n"
	.string "s'effrite! Il s'est\p"
	.string "cassé! Notre\n"
	.string "visiteur a l'air penaud!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "Notre visiteur passe\n"
	.string "son doigt sur le bureau!\p"
	.string "La poussière semble\n"
	.string "l'agacer! Eh bien, notre\p"
	.string "visiteur semble être\n"
	.string "très attaché à la propreté!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "Notre visiteur regarde une BRIQUE!\p"
	.string "Peut-être est-ce l'objet sur la\n"
	.string "l'objet sur le BRICK.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Notre visiteur marche sur\n"
	.string "une PLANCHE SOLIDE. Notre\p"
	.string "visiteur regarde en bas!\p"
	.string "Notre visiteur ne semble\n"
	.string "pas être très téméraire!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "Notre visiteur contemple\n"
	.string "une BARRIERE! Notre\p"
	.string "visiteur serait-il en train\n"
	.string "de manigancer quelque chose?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "Notre visiteur est\n"
	.string "sur un TAPIS\p"
	.string "BRILLANT! Notre visiteur\n"
	.string "semble prendre la pose!\p"
	.string "Notre visiteur se\n"
	.string "prendrait-il pour une star?$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "Notre visiteur\n"
	.string "regarde un PNEU! Notre\p"
	.string "visiteur penserait-il à\n"
	.string "s'acheter une voiture?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "Notre visiteur se trouve\p"
	.string "sur une ESTRADE! Notre\n"
	.string "visiteur regarde la BASE\p"
	.string "SECRETE de {STR_VAR_1} d'en haut!\p"
	.string "Et… Notre visiteur se\n"
	.string "met à hurler! Incroyable!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "Notre visiteur a foncé tête la\n"
	.string "première dans une PORTE CASSABLE!\p"
	.string "Le visiteur se moque de rien!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "Notre visiteur parle à une\p"
	.string "C'est un peu flippant...$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "Notre visiteur\n"
	.string "monte sur un\p"
	.string "TOBOGGAN! Et…\p"
	.string "glisse jusqu'en bas!\p"
	.string "On dirait que notre\n"
	.string "visiteur s'amuse bien!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "Notre visiteur\n"
	.string "monte sur un\p"
	.string "TOBOGGAN! Et…\p"
	.string "Apparemment, il préfère\n"
	.string "redescendre! Notre\p"
	.string "visiteur aurait-il le vertige?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "Notre visiteur se trouve\n"
	.string "sur un TAPIS SAUTEUR!\p"
	.string "Notre visiteur saute! Et\p"
	.string "saute encore! Belle\p"
	.string "réception au sol! Notre\p"
	.string "visiteur s'applaudit! Une\n"
	.string "jolie performance en solo!$"

gTVSafariFanClubText00::
	.string "FAN CLUB SAFARI!\p"
	.string "JOURNALISTE: Alors, les\n"
	.string "amis! En train de lancer\p"
	.string "des SAFARI BALLS? Comme\n"
	.string "vous vous en doutez, je\p"
	.string "suis au PARC SAFARI!\n"
	.string "Discutons un peu avec le GUIDE\p"
	.string "SAFARI! Comment se\n"
	.string "Des formateurs qui regardent?$"

gTVSafariFanClubText01::
	.string "GUIDE: Ils ont tous\n"
	.string "l'air d'y mettre du leur\p"
	.string "et de s'appliquer. {STR_VAR_1}\p"
	.string "réussit particulièrement\n"
	.string "bien. {STR_VAR_1} a attrapé {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "Ce DRESSEUR sait utiliser les\n"
	.string "{POKEBLOCK}S. Je crois qu'il en a utilisé {STR_VAR_2}.$"

gTVSafariFanClubText03::
	.string "Ce DRESSEUR n'a pas\n"
	.string "utilisé un seul {POKEBLOCK}!\p"
	.string "Du travail de pro.$"

gTVSafariFanClubText04::
	.string "JOURNALISTE: Vraiment? On\p"
	.string "dirait que notre {STR_VAR_1} excelle\n"
	.string "au SAFARI! GUIDE: J'espère\p"
	.string "que ce DRESSEUR va revenir\n"
	.string "nous montrer sa technique.$"

gTVSafariFanClubText05::
	.string "GUIDE: Ils ne semblent pas\n"
	.string "avoir beaucoup de succès. {STR_VAR_1}\p"
	.string "s'est particulièrement\p"
	.string "mal débrouillé. Ce\n"
	.string "DRESSEUR n'a attrapé que {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06::
	.string "GUIDE: Ils ne semblent pas\n"
	.string "avoir beaucoup de succès. {STR_VAR_1}\p"
	.string "s'est particulièrement mal\p"
	.string "débrouillé. Ce DRESSEUR\n"
	.string "n'a attrapé aucun POKéMON.$"

gTVSafariFanClubText07::
	.string "Ce DRESSEUR utilise des {POKEBLOCK}S.\n"
	.string "Je crois qu'il en a utilisé\p"
	.string "{STR_VAR_2}. Je voudrais bien que ce\n"
	.string "DRESSEUR s'améliore un peu.$"

gTVSafariFanClubText08::
	.string "Je pense que ce DRESSEUR aurait\n"
	.string "eu plus de chance en utilisant\l"
	.string "des {POKEBLOCK}S, chose qu'il n'a pas faite.$"

gTVSafariFanClubText09::
	.string "JOURNALISTE: Vraiment? On\p"
	.string "dirait que le SAFARI et {STR_VAR_1},\n"
	.string "ça fait deux! GUIDE:\p"
	.string "J'espère que ce DRESSEUR\n"
	.string "Encore et encore pour s'en sortir.$"

gTVSafariFanClubText10::
	.string "JOURNALISTE: Bien sûr! Il\n"
	.string "ne faut pas baisser les\p"
	.string "bras! Téléspectateurs,\n"
	.string "venez au PARC SAFARI vous\p"
	.string "aussi! A la prochaine, ciao!$"

ContestLiveUpdates_Text_Intro::
	.string "INFOS CONCOURS POKéMON\p"
	.string "ANIMATRICE: Merci de\p"
	.string "nous retrouver! Nous\n"
	.string "sommes en direct depuis\p"
	.string "le nouveau site {STR_VAR_1}. Le hall\n"
	.string "est rempli du public qui\p"
	.string "ne souhaite pas partir.\p"
	.string "Spectateur: {STR_VAR_2}! Spectateur:\p"
	.string "{STR_VAR_3}! ANIMATRICE: Comme vous\n"
	.string "venez de l'apprendre, le\l"
	.string "CONCOURS a été remporté\p"
	.string "par le {STR_VAR_2} de {STR_VAR_3}. Spectateur:\n"
	.string "{STR_VAR_2}! Tu es le meilleur!\p"
	.string "Spectateur: {STR_VAR_3}! Bien joué!\n"
	.string "ANIMATRICE: Ecoutons voir\p"
	.string "ce que les fans ont à dire\n"
	.string "à propos de ce CONCOURS.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Spectateur: {STR_VAR_2} était en tête aux\n"
	.string "jugements préliminaire et\p"
	.string "Ça {STR_VAR_2} va continuer à gagner!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Spectateur: Le {STR_VAR_2} n'a pas bien fait\n"
	.string "dans le jugement primaire, mais il\l"
	.string "Nettoyé dans le second jugement!\p"
	.string "C'était un retour\n"
	.string "miraculeux pour ça {STR_VAR_2}. Yippee!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Spectateur: {STR_VAR_2} est\n"
	.string "resté constant\l"
	.string "durant les deux\p"
	.string "jugements. {STR_VAR_3} et {STR_VAR_2}\n"
	.string "forment une sacrée paire!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Spectateur: Du point de vue {STR_VAR_1}, ce {STR_VAR_2}\n"
	.string "a été exceptionnel. Mais\p"
	.string "j'espère qu'il arrivera à nous\n"
	.string "Mais la prochaine fois.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Spectateur: Quand le {STR_VAR_2} a\n"
	.string "commencé à se montrer nerveux, je\l"
	.string "n'ai pas pu m'empêcher de crier\p"
	.string "pour l'encourager. Je n'ai qu'un\n"
	.string "mot à dire à ce {STR_VAR_2}: félicitations!$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Spectateur: Ce {STR_VAR_2} a\n"
	.string "réussi à m'enflammer!\p"
	.string "{STR_VAR_2}, tu as été formidable!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Spectateur: Ce combo de {STR_VAR_2}\n"
	.string "était à couper le\p"
	.string "souffle! J'en tremble encore!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Spectateur: La démonstration du {STR_VAR_2}\n"
	.string "gagnant a fait vibrer mon cœur!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}! Tu as fait preuve d'un\n"
	.string "sang-froid incroyable!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}! C'était de\n"
	.string "toute beauté!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}! C'était\n"
	.string "super gracieux!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}! Tu as fait\n"
	.string "preuve d'intelligence!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}! Tu as su\n"
	.string "montrer ta robustesse!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Spectateur: La démonstration du {STR_VAR_2}\n"
	.string "L'appel a encore mon cœur qui bat!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}! Tu incarnes\n"
	.string "le sang-froid!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}! Tu\n"
	.string "incarnes la beauté!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}! Tu\n"
	.string "incarnes la grâce!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}! Comment fais-tu pour\n"
	.string "être aussi intelligent?$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}! Quelle\n"
	.string "robustesse!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Spectateur: Je n'ai pas\n"
	.string "réussi à quitter {STR_VAR_2} du regard,\l"
	.string "même après sa démonstration. Ce {STR_VAR_2}\p"
	.string "arrive vraiment à me captiver!$"

ContestLiveUpdates_Text_GotStartled::
	.string "Spectateur: J'étais au bord\n"
	.string "des larmes quand {STR_VAR_2} s'est fait\l"
	.string "surprendre par la\p"
	.string "démonstration d'un autre POKéMON.\n"
	.string "Mais tu as su tenir, {STR_VAR_2}! Bien joué!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Spectateur:\n"
	.string "Oh... C'est{STR_VAR_2} de{STR_VAR_3} !\l"
	.string "{STR_VAR_2}de ! {STR_VAR_3} de !\l"
	.string "{STR_VAR_2}Comment{STR_VAR_3} pourrait-il\l"
	.string "être si merveilleux?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "MC: Cet endroit est\n"
	.string "plein de fans de {STR_VAR_1}!\p"
	.string "Je dois également\n"
	.string "mentionner qu'un autre\l"
	.string "POKéMON, {STR_VAR_2}'s {STR_VAR_3}, m'a attiré l'œil.\p"
	.string "{STR_VAR_2} est {STR_VAR_3}...$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "A cause de sa nervosité, il n'a\n"
	.string "pas pu réussir une seule\p"
	.string "démonstration durant le jugement\n"
	.string "{STR_VAR_1} faire même un appel.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Il est arrivé bon dernier\n"
	.string "aux deux jugements.\p"
	.string "J'espère que {STR_VAR_1} va se\n"
	.string "rattraper avec {STR_VAR_2} pour se faire\l"
	.string "pardonner cette dernière place!$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Il n'a pas réussi à profiter de\n"
	.string "l'ambiance dans le public pour\l"
	.string "faire une démonstration\p"
	.string "appropriée. Nous espérons que {STR_VAR_1}\n"
	.string "apprendra à saisir leur humeur\l"
	.string "la prochaine fois.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Bien qu'étant en tête à la fin du\n"
	.string "jugement préliminaire, il n'a pas\l"
	.string "réussi à en tirer avantage pendant\p"
	.string "le jugement secondaire. Quelle\n"
	.string "humiliation, tout ça pour rien! {STR_VAR_1}\p"
	.string "doit être en train de réfléchir à\n"
	.string "faire des appels plus efficaces.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Le public ne s'est jamais\n"
	.string "véritablement enflammé pour ses\p"
	.string "démonstrations pendant le jugement\n"
	.string "secondaire. Nous espérons qu'il\l"
	.string "ses appels au public plus.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Il a perdu à {STR_VAR_1}'s {STR_VAR_2}\n"
	.string "seulement par une petite marge.\p"
	.string "Il doit être déchirant de se\n"
	.string "si près de la victoire à l'échec.\p"
	.string "Je ne serais pas surpris si\n"
	.string "{STR_VAR_3} pleurait sur ce résultat.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Il a déçu le JUGE en répétant\n"
	.string "encore et encore les mêmes\p"
	.string "démonstrations. C'est une erreur\n"
	.string "impardonnable dans un CONCOURS, et\p"
	.string "ce POKéMON en fait les frais. {STR_VAR_1}\n"
	.string "Désolé de vous avoir montré ça.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} a vraiment fait de son\n"
	.string "mieux, mais… Ça n'a servi à\p"
	.string "rien, il est arrivé dernier. {STR_VAR_1}\p"
	.string "devrait réfléchir à cette\n"
	.string "et d'utiliser les connaissances.$"

ContestLiveUpdates_Text_Outro::
	.string "J'aimerais terminer ce programme\n"
	.string "les adieux habituels aux gagnants.\p"
	.string "Cette fois,\n"
	.string "c'est {STR_VAR_1} et le {STR_VAR_2}!\p"
	.string "MC: Tout le\n"
	.string "monde est prêt?\p"
	.string "Auditoire: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "Félicitations! Vous êtes\l"
	.string "le gagnant du CONTEST!$"

gTVPokemonBattleUpdateText00::
	.string "INFOS COMBATS POKéMON Nous\p"
	.string "vous donnons les derniers\n"
	.string "résultats des combats de POKéMON!$"

gTVPokemonBattleUpdateText01::
	.string "Les DRESSEURS {STR_VAR_1} et {STR_VAR_2}\n"
	.string "étaient face à face\l"
	.string "dans un COMBAT {STR_VAR_3}. Ce\p"
	.string "match s'est terminé\n"
	.string "sur une victoire de {STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "Dans la bataille, {STR_VAR_1}'s\n"
	.string "{STR_VAR_2} était une force\l"
	.string "formidable utilisant {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "{STR_VAR_1}'s {STR_VAR_2} avait un faible\n"
	.string "montrant que bien mal.$"

gTVPokemonBattleUpdateText04::
	.string "Bravo pour votre victoire,\n"
	.string "{STR_VAR_1}! Quant à vous, {STR_VAR_2}, nous\p"
	.string "espérons que vous ferez\n"
	.string "mieux la prochaine fois!\p"
	.string "Ainsi se termine cette\n"
	.string "émission d'INFOS COMBATS POKéMON!$"

gTVPokemonBattleUpdateText05::
	.string "Les équipes des DRESSEURS {STR_VAR_1} et {STR_VAR_2}\n"
	.string "se sont affrontées en COMBAT\p"
	.string "MULTI. Ce match s'est terminé\n"
	.string "sur une victoire de l'équipe de {STR_VAR_1}!$"

gTVPokemonBattleUpdateText06::
	.string "Dans le combat, le {STR_VAR_2} de\n"
	.string "l'équipe de {STR_VAR_1} a très\l"
	.string "efficacement utilisé {STR_VAR_3}!$"

gTVPokemonBattleUpdateText07::
	.string "Le {STR_VAR_3} n'a pas su montrer son\n"
	.string "vrai niveau face à l'équipe de\p"
	.string "{STR_VAR_2}. Félicitations sur la\n"
	.string "victoire de votre équipe, {STR_VAR_1}!\p"
	.string "Quand à vous {STR_VAR_2}, nous espérons que\n"
	.string "votre équipe fera mieux la\p"
	.string "prochaine fois! Ainsi se termine\n"
	.string "MISE À JOUR DU BATTLE DE POKÉMON!$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "INES: Oh! Nous venons de\n"
	.string "repérer un DRESSEUR qui a\p"
	.string "l'air costaud! OK, caméra,\n"
	.string "action! Allons l'interviewer.$"

GabbyAndTy_Text_GabbyIntro:
	.string "INES: Oh! Tu es {PLAYER}! Bonjour! Tu te\n"
	.string "souviens de nous? Nous sommes\p"
	.string "devenus bien plus forts. On peut\n"
	.string "te montrer? Caméra, ça tourne!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "INES: Je ne me suis pas trompée!\n"
	.string "J'ai trouvé un DRESSEUR étonnant!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "INES: Incroyable! Génial! Qui\n"
	.string "es-tu?! Je savais qu'on était\p"
	.string "sur un bon coup quand on est\n"
	.string "tombés sur toi! Oh,\p"
	.string "laisse-moi t'expliquer. Nous\n"
	.string "voyageons un peu partout pour\l"
	.string "interviewer des DRESSEURS.\p"
	.string "Pourrais-tu nous accorder un peu\n"
	.string "de ton temps pour une interview?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "INES: {STR_VAR_1}! Tu te souviens?\p"
	.string "C'est ta conclusion après\n"
	.string "ton dernier combat. Je\p"
	.string "n'oublie jamais ce genre de truc!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "La dernière fois qu'on s'est\n"
	.string "battus, tu nous as écrasés avant\p"
	.string "qu'on ait eu le temps de dire\n"
	.string "Veux-tu être interrogé à nouveau?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "La dernière fois qu'on s'est\n"
	.string "battus, tu nous as jeté une POKé\p"
	.string "BALL, non? Nous étions si choqués.\n"
	.string "Nous en avons parlé à tout le\p"
	.string "monde. Tout le monde!, qu'en\n"
	.string "Veux-tu être interrogé à nouveau?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "La dernière fois qu'on s'est\n"
	.string "battus, tu as utilisé tes objets\p"
	.string "avec brio. Alors, qu'en penses-tu?\n"
	.string "Tu veux qu'on t'interviewe encore?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "La dernière fois qu'on s'est\n"
	.string "battus, on a réussi à éviter\p"
	.string "l'humiliation. Alors, qu'en\n"
	.string "Veux-tu être interrogé à nouveau?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Alors, qu'en penses-tu? Tu\n"
	.string "veux qu'on t'interviewe encore?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Tu veux bien? Merci mille\n"
	.string "fois! Bien, je voudrais\p"
	.string "que tu décrives ta\n"
	.string "perception de notre combat.\l"
	.string "Sois précis et concis. Allez!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "INES: Mmm, mouais! C'est\n"
	.string "une excellente conclusion!\p"
	.string "J'ai l'impression qu'on va\n"
	.string "faire un tabac avec cette\p"
	.string "émission de télé. Ils vont\n"
	.string "sûrement la diffuser, alors\p"
	.string "regarde-nous souvent à la\n"
	.string "télé! Bon, allez! A bientôt!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "INES: Oh… Tant pis, mais\p"
	.string "n'abandonne pas! Nous allons\n"
	.string "continuer à suivre ton parcours!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "INES: Nous allons\n"
	.string "continuer à suivre ton parcours!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "INES: Y a-t-il un vrai DRESSEUR,\n"
	.string "ici, avec beaucoup de POKéMON?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "INES: Ouah, tu es un sacré\p"
	.string "personnage! Tu as gagné en\n"
	.string "puissance depuis notre dernier\p"
	.string "combat. Et pas qu'un peu! Nous\n"
	.string "avions raison quand nous avons dit\p"
	.string "que tu étais un DRESSEUR balèze.\n"
	.string "Alors, qu'en penses-tu? Tu veux\l"
	.string "Cette fois?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "INES: Ça, c'était du\n"
	.string "combat! Tu as pu tout filmer?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "GUY: Hé, mate un peu,\n"
	.string "là! Ce DRESSEUR a l'air\l"
	.string "d'être balèze! On tourne!$"

GabbyAndTy_Text_TyIntro:
	.string "GUY: Hé, mate un peu,\n"
	.string "là! Je me souviens de\p"
	.string "toi! Je vais filmer ce\n"
	.string "combat avec ma caméra!$"

GabbyAndTy_Text_TyPostBattle:
	.string "GUY: Tu as ça dans le sang! J'ai\n"
	.string "J'ai des premières images ici!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "GUY: Quoi? Tu n'as qu'un\n"
	.string "POKéMON? Et c'est tout? Si tu\p"
	.string "avais plus de POKéMON, ça me\n"
	.string "ferait une super vidéo, mais bon…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "GUY: Ouais, on a repéré un super\n"
	.string "DRESSEUR. C'est un super scoop!$"

GabbyAndTy_Text_TyDefeat:
	.string "GUY: Ouais, j'ai tout.\n"
	.string "C'est dans la boîte!$"

gTVInSearchOfTrainersText00::
	.string "EN QUETE DE DRESSEURS… INES:\p"
	.string "Bonjour! Aujourd'hui, je suis\n"
	.string "du côté de la {STR_VAR_1}. Nous sommes sur\p"
	.string "le terrain pour essayer de\n"
	.string "repérer les talents qui\p"
	.string "montent. Aujourd'hui, nous\n"
	.string "braquons notre objectif sur le\p"
	.string "DRESSEUR {PLAYER}. Quelque chose à propos\n"
	.string "C'est ce qui nous a attirés.$"

gTVInSearchOfTrainersText01::
	.string "Nous nous étions déjà battus\n"
	.string "contre {PLAYER}, mais nous pouvons vous\l"
	.string "jurer que sa technique s'est\p"
	.string "améliorée. Je savais que nous\n"
	.string "Quand on a vu ce DRESSEUR!$"

gTVInSearchOfTrainersText02::
	.string "La meilleure façon de déterminer\n"
	.string "la force d'un DRESSEUR est de…\p"
	.string "Heu, enfin, la façon la plus\n"
	.string "rapide est de se battre. C'est\p"
	.string "comme ça que nous avons commencé\p"
	.string "notre enquête! … … Nous nous\n"
	.string "sommes donc battus contre {PLAYER}. Au\p"
	.string "cours de cette performance\n"
	.string "éprouvante, nous avons été\p"
	.string "aplatis, écrasés et terriblement\p"
	.string "humiliés! {PLAYER} est d'une force\n"
	.string "a combattu notre DRESSEUR vedette.$"

gTVInSearchOfTrainersText03::
	.string "L'enchaînement de {STR_VAR_1} et de\n"
	.string "{STR_VAR_3} était divin! La vue de\p"
	.string "{STR_VAR_1} et de {STR_VAR_3} se soutenant\n"
	.string "mutuellement en plein\l"
	.string "milieu du combat… Ce\p"
	.string "sont des images qui font\p"
	.string "chaud au cœur! Le\n"
	.string "DRESSEUR a utilisé {STR_VAR_2} pour\p"
	.string "clore le combat. L'attaque {STR_VAR_2}\n"
	.string "montre l'amitié entre {STR_VAR_1} et {STR_VAR_3}!$"

gTVInSearchOfTrainersText04::
	.string "… Après notre rencontre,\n"
	.string "j'ai perdu toute confiance\p"
	.string "en moi. Nous avons été\n"
	.string "battus avant même de\l"
	.string "pouvoir frapper. Ohhh… Sniff…\p"
	.string "En tout cas, les combats de {PLAYER}\n"
	.string "sont des spectacles à ne pas\p"
	.string "manquer. J'encourage les\n"
	.string "DRESSEURS confiants à défier {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Juste une précision. Il ne\n"
	.string "faut jamais jeter de POKé\l"
	.string "BALL pendant un combat de\p"
	.string "DRESSEURS! {PLAYER} a de toute\n"
	.string "évidence une grande force,\p"
	.string "mais ne respecte pas les\p"
	.string "règles. Un message pour notre\n"
	.string "Le DRESSEUR!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} adore anticiper les actions\n"
	.string "de l'adversaire. Le timing de\p"
	.string "l'utilisation des objets était\n"
	.string "tout simplement remarquable!$"

gTVInSearchOfTrainersText07::
	.string "Honnêtement, j'ai vraiment fait\n"
	.string "de mon mieux. Même si nous avons\p"
	.string "perdu, le combat a été\n"
	.string "particulièrement tendu. Mais si tu\p"
	.string "as du mal à me battre, c'est que\n"
	.string "vous avez un moyen de le faire, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Après notre combat, nous\n"
	.string "avons demandé à {PLAYER} un bref\p"
	.string "résumé. Le DRESSEUR a\p"
	.string "répondu: {PLAYER}{STR_VAR_1}. Les POKéMON de {PLAYER}\n"
	.string "étaient {STR_VAR_2} et {STR_VAR_3}… Et {STR_VAR_1}… Mmm! Voilà\l"
	.string "qui est profond! Il y a un\p"
	.string "sens caché derrière ça! Ce\n"
	.string "n'est pas étonnant. C'est\p"
	.string "toujours intéressant d'écouter\n"
	.string "un bon DRESSEUR. Voilà, c'est\p"
	.string "tout pour aujourd'hui! Ne\n"
	.string "ratez pas la prochaine émission!$"

ContestLadyShow_Text_Intro::
	.string "INFOS CONCOURS POKéMON\p"
	.string "ANIMATRICE: Désolée\n"
	.string "d'interrompre vos programmes,\p"
	.string "et merci de nous retrouver!\n"
	.string "Nous sommes en direct pour vous\l"
	.string "montrer le résultat d'un\p"
	.string "CONCOURS catégorie {STR_VAR_1} qui vient de\p"
	.string "se terminer! Spectateurs: ?!!!\n"
	.string "ANIMATRICE: Oh, on dirait bien\p"
	.string "que les participants du CONCOURS\n"
	.string "se dirigent par ici! Je vais\p"
	.string "tenter de les interviewer en\n"
	.string "C'est pas vrai!$"

ContestLadyShow_Text_Won::
	.string "ANIMATRICE: Excusez-moi! Merci de\n"
	.string "répondre à nos questions en\p"
	.string "Félicitations pour votre victoire!\p"
	.string "Quel a été le facteur clé de\n"
	.string "la victoire d'aujourd'hui?\p"
	.string "BEAUTY: Nous avons fait de notre\n"
	.string "mieux aujourd'hui, mon {STR_VAR_2} et moi!\p"
	.string "Mais je suis sûr que nous\n"
	.string "n'aurions pas réussi si ce n'était\l"
	.string "reçu jusqu'au CONTEST!\p"
	.string "MC: Avez-vous quelqu'un de\n"
	.string "spécial avec qui vous\l"
	.string "aimeriez partager votre joie?\p"
	.string "BEAUTY: Hé, dehors!\p"
	.string "{STR_VAR_3}\n"
	.string "Tu\l"
	.string "regardes?$"

ContestLadyShow_Text_Lost::
	.string "ANIMATRICE: Excusez-moi! Merci de\n"
	.string "répondre à nos questions en\p"
	.string "direct! Vous devez être déçue par\n"
	.string "la tournure des évènements.\p"
	.string "Avez-vous des commentaires? CANON:\n"
	.string "Ça me brise le cœur… Nous nous\p"
	.string "sommes pourtant donnés à fond, mon\n"
	.string "{STR_VAR_2} et moi! Mais j'ai l'impression\p"
	.string "d'avoir trahi tous ceux qui nous\n"
	.string "ont supportés. ANIMATRICE: Je ne\p"
	.string "devrais pas le dire, mais il\n"
	.string "manquait quelque chose à votre\l"
	.string "POKéMON. CANON: {STR_VAR_3}, je suis désolée…\p"
	.string "Je ferai mieux la prochaine fois…\n"
	.string "Je le jure… Sniff… sniff…\p"
	.string "Spectateurs: Vous avez vu? La\p"
	.string "pauvre fille! ANIMATRICE: Oh… oh…\n"
	.string "Merci d'être venu!$"

ContestLadyShow_Text_LostBadly::
	.string "ANMATRICE: Excusez-moi! Merci\n"
	.string "de répondre à nos questions en\p"
	.string "direct! Comment s'est passé ce\p"
	.string "CONCOURS pour vous? CANON: Tout\n"
	.string "s'est mal passé… Pour une raison\l"
	.string "qui m'échappe, mon {STR_VAR_2} n'a pas\p"
	.string "réussi à attirer l'attention du\n"
	.string "public. ANIMATRICE: Je ne\p"
	.string "devrais pas le dire, mais il\n"
	.string "manquait quelque chose à votre\p"
	.string "POKéMON. CANON: … … … … … …\n"
	.string "…Sniff… Ouin!! Spectateurs: Vous\p"
	.string "avez vu? La pauvre fille!\p"
	.string "ANIMATRICE: Oh… oh… Hum… C'est\n"
	.string "Merci d'être venu!$"
