FuchsiaCity_House1_hns_MapScripts::
	.byte 0

FuchsiaCity_House1_EventScript_BillsOlderSister::
	msgbox FuchsiaCity_House1_Text_BillsOlderSister, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_Youngster::
	msgbox FuchsiaCity_House1_Text_Youngster, MSGBOX_NPC
	end

FuchsiaCity_House1_Text_BillsOlderSister:
	.string "Mon pépé est chez mon frère LEO,\n"
	.string "au CAP AZURIA.$"

FuchsiaCity_House1_Text_Youngster:
	.string "J'ai vu des POKéMON bizarres et\n"
	.string "lents sur la PISTE CYCLABLE.$"

