BattleFrontier_Lounge4_hns_MapScripts::
	.byte 0

BattleFrontier_Lounge4_EventScript_Woman_hns::
	msgbox BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Cook_hns::
	msgbox BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Man_hns::
	msgbox BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring_hns:
	.string "Je me demande s'ils diffuseront\n"
	.string "des interviews de DRESSEURS\l"
	.string "coriaces aujourd'hui.$"

BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere_hns:
	.string "Si j'ouvrais un restaurant ici,\n"
	.string "ça marcherait à coup sûr.$"

BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles_hns:
	.string "Ouf…\p"
	.string "J'ai besoin de souffler après\n"
	.string "des combats aussi intenses…\p"
	.string "Mais même là, je ne cesse jamais\n"
	.string "de peaufiner stratégies et\l"
	.string "combos.$"

