BattleFrontier_Lounge8_hns_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man_hns::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman_hns::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy_hns::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds_hns:
	.string "Ce qu'il faut à un DRESSEUR…\p"
	.string "Du savoir…\n"
	.string "De la stratégie…\l"
	.string "De la chance…\l"
	.string "Du cran…\l"
	.string "Du caractère…\l"
	.string "Du courage…\l"
	.string "Et du talent…\p"
	.string "Eh bien, j'ai tout ce qu'il\n"
	.string "faut! Je serai imbattable dans\l"
	.string "chaque bâtiment!\p"
	.string "Hein? Des POKéMON?\n"
	.string "C'est quoi, ça?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains_hns:
	.string "Tu connais les CERVEAUX DE LA\n"
	.string "ZONE?\p"
	.string "C'est comme ça que SCOTT appelle\n"
	.string "les sept DRESSEURS d'exception\l"
	.string "qui tiennent les sept bâtiments\l"
	.string "de la ZONE DE COMBAT.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling_hns:
	.string "À la TOUR DE COMBAT, une grande\n"
	.string "m'a dit que j'avais beaucoup de\l"
	.string "talent pour le combat!\p"
	.string "Moi, je préfère les CONCOURS\n"
	.string "POKéMON!\p"
	.string "Mais je suis nulle en CONCOURS!\p"
	.string "Avoir du talent et aimer une\n"
	.string "chose, ce n'est pas pareil.$"

