Akala_House_hns_MapScripts::
	.byte 0


Alola_Akala_House_OldWoman::
	lock
	faceplayer
	msgbox Alola_Akala_House_OldWoman_Text_0, MSGBOX_AUTOCLOSE
	release
	end


Alola_Akala_House_OldWoman_Text_0:
	.string "Je répète chaque jour à mon mari\n"
	.string "de ne pas nourrir les NATU, mais\l"
	.string "il n'écoute jamais!\p"
	.string "Un jour il en ramènera un à la\n"
	.string "maison, j'en suis sûre!$"
