VermilionCity_House2_hns_MapScripts::
	.byte 0

VermilionCity_House2_EventScript_PokefanF::
	msgbox VermilionCity_House2_Text_PokefanF, MSGBOX_NPC
	end

VermilionCity_House2_EventScript_Youngster::
	msgbox VermilionCity_House2_Text_Youngster, MSGBOX_NPC
	end

VermilionCity_House2_Text_PokefanF:
	.string "Tu connais le TRAIN MAGNÉTIQUE?\p"
	.string "C'est une ligne qui va jusqu'à\n"
	.string "DOUBLONVILLE, à JOHTO.$"

VermilionCity_House2_Text_Youngster:
	.string "Je veux aller à SAFRANIA voir le\n"
	.string "TRAIN MAGNÉTIQUE.$"
